/*
 Copyright 2022 Glance Networks, Inc.
*/
var GLANCE_LOGGER=!0,GlanceLogger={sanitize:function(a){return a.replace(/[\r\n]/g," ").replace("<","&lt;")},_log:function(a,...b){!window.console||!window.console[a]||window.GLANCE_COBROWSE&&window.GLANCE_COBROWSE.disableLogging||(b=b.map(c=>{if("object"===typeof c)try{c=JSON.stringify(c)}catch(d){console.error(d),c="unable to convert object to string"}return"string"===typeof c?GlanceLogger.sanitize(c):c}),window.console[a](...b))},log:function(...a){GlanceLogger._log("log",...a)},error:function(...a){GlanceLogger._log("error",
...a)}},LOG_DIFFS=!1,LOG_DIFFDET=!1,LOG_DRAW=!1,LOG_PRES=!0,LOG_CBSTATE=!1,LOG_IFRAME=!1,LOG_SCROLL=!1,LOG_EVENTS=!1,LOG_LOADER=!1,LOG_UI=!1,LOG_FOCUS=!1,LOG_XDOM=!0,LOG_C3P=!1,LOG_PDF=!1,LOG_STYLES=!1,LOG_GEST=!1,LOG_MSG=!1,LOG_RES=!0,LOG_RC=!1,LOG_SD=!1,LOG_VID=!0,LOG_MASK=!1,LOG_DOC=!1,LOG_XLS=!1,LOG_SS=!1,debuglog=GLANCE_LOGGER?function(...a){GlanceLogger.log("DEBUG:",...a)}:function(){},diffslog=GLANCE_LOGGER&&LOG_DIFFS?function(...a){GlanceLogger.log("DIFFS:",...a)}:function(){},diffdetlog=
GLANCE_LOGGER&&LOG_DIFFDET?function(...a){GlanceLogger.log("DIFFDET:",...a)}:function(){},drawlog=GLANCE_LOGGER&&LOG_DRAW?function(...a){GlanceLogger.log("DRAW:",...a)}:function(){},preslog=LOG_PRES?function(...a){GlanceLogger.log("PRES:",...a)}:function(){},cbstatelog=GLANCE_LOGGER&&LOG_CBSTATE?function(...a){GlanceLogger.log("CBSTATE:",...a)}:function(){},iframelog=GLANCE_LOGGER&&LOG_IFRAME?function(...a){GlanceLogger.log("IFRAME:",...a)}:function(){},scrolllog=GLANCE_LOGGER&&LOG_SCROLL?function(...a){GlanceLogger.log("SCROLL:",
...a)}:function(){},eventslog=GLANCE_LOGGER&&LOG_EVENTS?function(...a){GlanceLogger.log("EVENTS:",...a)}:function(){},loaderlog=GLANCE_LOGGER&&LOG_LOADER?function(...a){GlanceLogger.log("LOADER:",...a)}:function(){},uilog=GLANCE_LOGGER&&LOG_UI?function(...a){GlanceLogger.log("UI:",...a)}:function(){},focuslog=GLANCE_LOGGER&&LOG_FOCUS?function(...a){GlanceLogger.log("FOCUS:",...a)}:function(){},xdomlog=LOG_XDOM?function(...a){GlanceLogger.log("XDOM:",...a)}:function(){},c3plog=GLANCE_LOGGER&&LOG_C3P?
function(...a){GlanceLogger.log("C3P:",...a)}:function(){},pdflog=GLANCE_LOGGER&&LOG_PDF?function(...a){GlanceLogger.log("PDF:",...a)}:function(){},stylelog=GLANCE_LOGGER&&LOG_STYLES?function(...a){GlanceLogger.log("STYLES:",...a)}:function(){},gestlog=GLANCE_LOGGER&&LOG_GEST?function(...a){GlanceLogger.log("GEST:",...a)}:function(){},msglog=GLANCE_LOGGER&&LOG_MSG?function(...a){GlanceLogger.log("MSG:",...a)}:function(){},reslog=GLANCE_LOGGER&&LOG_RES?function(...a){GlanceLogger.log("RES:",...a)}:
function(){},rclog=GLANCE_LOGGER&&LOG_RC?function(...a){GlanceLogger.log("RC:",...a)}:function(){},sdlog=GLANCE_LOGGER&&LOG_SD?function(...a){GlanceLogger.log("SD:",...a)}:function(){},vidlog=LOG_VID?function(...a){GlanceLogger.log("VID:",...a)}:function(){},masklog=GLANCE_LOGGER&&LOG_MASK?function(...a){GlanceLogger.log("MASK:",...a)}:function(){},doclog=GLANCE_LOGGER&&LOG_DOC?function(...a){GlanceLogger.log("DOC:",...a)}:function(){},sslog=GLANCE_LOGGER&&LOG_SS?function(...a){GlanceLogger.log("SS:",
...a)}:function(){},assert=GLANCE_LOGGER?function(a){if(!a)if(window.console&&window.console.error)GlanceLogger.error("ASSERT");else throw Error("ASSERT");}:function(){};function consolelog(...a){GlanceLogger.log("GLANCE:",...a)}function errorlog(...a){GlanceLogger.error("GLANCE:",...a)};/*
 Copyright (c) 2022 Glance Networks, Inc.
*/
var GLANCE=GLANCE||{};GLANCE.Lib=GLANCE.Lib||{};GLANCE.VERSION="6.3.1.0";GLANCE.PATCH="";window.GLANCE=window.GLANCE||{};window.GLANCE.VERSION=GLANCE.VERSION;window.GLANCE.PATCH=GLANCE.PATCH;window.GLANCE.Lib=window.GLANCE.Lib||{};GLANCE.Lib.KEYTYPE={RANDOM:"GLANCE_KEYTYPE_RANDOM"};GLANCE.Lib.KEYTYPE={RANDOM:"GLANCE_KEYTYPE_RANDOM"};
GLANCE.Lib.MESSAGES={GLANCE_INVOKE_MSG:"glance_invoke",GLANCE_SCREENSHARE:"glance_screenshare",GLANCE_SCREENSHAREPREVIEW:"glance_screensharepreview",GLANCE_VISITOR_SCREENSHAREPREVIEW:"glance_visitor_screensharepreview",GLANCE_AGENTVIDEO:"glance_agentvideo",GLANCE_VIDEOPREVIEW:"glance_videopreview"};GLANCE.Lib.Const={GID:"data-gid",GCID:"data-gcid",SDID:"data-sdid"};GLANCE.Lib.scriptId=function(a){return("glance_"+a).toLowerCase()};
GLANCE.Lib.CallFlags={None:0,Reconnect:1,Reverse:2,Declined:4,Rcrequested:8,Closing:16,Beta:32,MultipleGuestsOk:64,Anonymous:128,Showback:256,GuestNameRequired:512,GuestEmailRequired:1024,GuestPhoneRequired:2048,GuestNameHidden:4096,GuestEmailHidden:8192,GuestPhoneHidden:16384,GuestInfo:32256,Encrypt:32768,ForceAjax:65536,Persist:131072,PresenceStart:262144,StagingSession:524288,HDAgentVideoEnabled:2097152};
GLANCE.Lib.IntVersion=function(){var a=GLANCE.VERSION.split(".");return 1E6*parseInt(a[0])+1E3*parseInt(a[1])+parseInt(a[2])}();GLANCE.Lib.VideoJoinURL=function(a,b){b=b||"clip";return`https://${URL.toString().includes("[native code]")?(new URL(a)).hostname:GLANCE.Lib.GElement.nativeInstance("URL",a).hostname}/viv/VideoPlayer.html?offer=${a}&scaling=${b}&noendpage=1&guestid={guestid}&conntype={role}`};
GLANCE.Lib.Browser=function(){var a=navigator.userAgent.toLowerCase(),b=navigator.platform.toLowerCase(),c=a.match(/(edge)[\s\/:]([\w\d\.]+)?/)||a.match(/(opera|ie|firefox|chrome|crios|version)[\s\/:]([\w\d\.]+)?.*?(safari|version[\s\/:]([\w\d\.]+)|$)/)||a.match(/(rv):([\w\d\.]+)/)||[null,"unknown",0];"crios"===c[1]?c[1]="chrome":"rv"===c[1]&&(c[1]="ie");a={extend:Function.prototype.extend,name:"version"==c[1]?c[3]:c[1],version:"ie"==c[1]&&document.documentMode||parseFloat("opera"==c[1]&&c[4]?c[4]:
c[2]),Platform:{name:a.match(/ip(?:ad|od|hone)/)||b.match(/mac/)&&"undefined"!==typeof navigator.standalone?"ios":(a.match(/(?:webos|android)/)||b.match(/mac|win|linux/)||["other"])[0]},Features:{xpath:!!document.evaluate,air:!!window.runtime,query:!!document.querySelector,json:!!window.JSON},Plugins:{},isMobileDevice:function(){return"ios"==this.Platform.name||"android"==this.Platform.name}};document.documentMode&&window.XDomainRequest?(a.name="ie",a.version=document.documentMode):window.navigator&&
navigator.appVersion&&-1!=navigator.appVersion.indexOf("MSIE 7.")&&(a.name="ie",a.version="7");a[a.name]=!0;a[a.name+parseInt(a.version,10)]=!0;a.Platform[a.Platform.name]=!0;return a}();GLANCE.Lib.getIframe=function(a,b){b=b||document;return GLANCE.Lib.GElement.nativeMethod(b,"querySelector","iframe[frameid='"+a+"']")};GLANCE.Lib.equal=function(a,b){return GLANCE.Lib.JSONStringify(a)===GLANCE.Lib.JSONStringify(b)};
GLANCE.Lib.random=function(a){for(a=String(Math.round(Math.random()*Math.pow(10,a)));4>a.length;)a="0"+a;return a};GLANCE.Lib.getCryptoToken=function(a){a=new Uint32Array(Math.ceil(a/32));window.crypto.getRandomValues(a);let b="";a.forEach(c=>{b+=c.toString(36)});return b};GLANCE.Lib.getProperties=function(a,b){var c={},d=new RegExp(b),e;for(e in a)e.match(d)&&(c[e.substr(b.length)]=a[e]);return c};GLANCE.Lib.pointDistance=function(a,b){return Math.max(Math.abs(a.x-b.x),Math.abs(a.y-b.y))};
GLANCE.Lib.Url={};GLANCE.Lib.Url.isAbsolute=function(a){return 0<=a.indexOf("//")||0===a.indexOf("/")};GLANCE.Lib.ExtendableTimer=function(){};GLANCE.Lib.ExtendableTimer.prototype.set=function(a,b){GLANCE.Lib.GElement.nativeMethod(window,"clearTimeout",this.timer);var c=this;this.timer=GLANCE.Lib.GElement.nativeMethod(window,"setTimeout",function(){delete c.timer;b&&b()},a)};GLANCE.Lib.ExtendableTimer.prototype.isSet=function(){return void 0!==this.timer};
GLANCE.Lib.ExtendableTimer.prototype.clear=function(){GLANCE.Lib.GElement.nativeMethod(window,"clearTimeout",this.timer);delete this.timer};void 0===GLANCE.Lib.JSONStringify&&(GLANCE.Lib.JSONStringify=function(a){return GLANCE.Lib.GElement.USE_CLEANCONTEXT&&GLANCE.Lib.GElement.CleanContext?GLANCE.Lib.GElement.CleanContext.window.JSON.stringify(a):JSON.stringify(a)});
GLANCE.Lib._enhanceSocket=function(a){a.onmessage=function(b){b=JSON.parse(b.data);if(a.onreceiveobj)a.onreceiveobj(b)};a.sendobj=function(b){b=GLANCE.Lib.JSONStringify(b);a.send(b)};a.getcode=function(b){return b&&b.code||0};a.getreason=function(b){return b&&b.reason||""};return a};GLANCE.Lib.GWebSocket=function(a){a=new WebSocket(a);GLANCE.Lib._enhanceSocket(a);return a};
GLANCE.Lib.GSockJS=function(a,b){var c={};if(GLANCE.Lib.useIFrameProxy)var d=new GLANCE.Lib.GSockJSProxy(a);else GLANCE.Lib.Browser.ie9&&"http:"===window.location.protocol&&(c.protocols_whitelist=["iframe-eventsource","iframe-htmlfile"]),d=new SockJS(a,"",c);d.hbskipped=0;d.checkheartbeat=function(){d.cancelheartbeatcheck();b&&d.transport&&!d.transport.match(/^iframe-/)&&(d.hbinterval=GLANCE.Lib.GElement.nativeMethod(window,"setInterval",function(){d.hbskipped++;if(d.onheartbeatskipped)d.onheartbeatskipped({hbskipped:d.hbskipped})},
b))};d.cancelheartbeatcheck=function(){d.hbinterval&&GLANCE.Lib.GElement.nativeMethod(window,"clearInterval",d.hbinterval)};GLANCE.Lib._enhanceSocket(d);d.onclose=function(e){d.cancelheartbeatcheck();if(d.on_close)d.on_close(e)};d.onheartbeat=function(){d.hbskipped=0;d.checkheartbeat();if(d.on_heartbeat)d.on_heartbeat()};return d};GLANCE.Lib.RequestProxy={loaded:!1};
GLANCE.Lib.RequestProxy.init=function(a){GLANCE.Lib.RequestProxy.server=a;if(!document.getElementById("glance_request_proxy")){var b=document.createElement("iframe");b.id="glance_request_proxy";b.width="0px";b.height="0px";b.style.border="none";b.src="https://"+a+"/RequestProxy.htm?1";b.onload=function(){GLANCE.Lib.RequestProxy.loaded=!0};document.body.appendChild(b)}GLANCE.Lib.RequestProxy.proxyframe=document.getElementById("glance_request_proxy").contentWindow};
GLANCE.Lib.RequestProxy.postMessage=function(a,b){var c=GLANCE.Lib.RequestProxy;c.loaded?c.proxyframe.postMessage(a,b||"https://"+GLANCE.Lib.RequestProxy.server):GLANCE.Lib.GElement.nativeMethod(window,"setTimeout",function(){c.postMessage(a,b)},100)};
GLANCE.Lib.GSockJSProxy=function(a){this.readyState=SockJS.CONNECTING;this.sockid=Math.round(1E6*Math.random());GLANCE.Lib.GSockJSProxy.sockets=GLANCE.Lib.GSockJSProxy.sockets||{};GLANCE.Lib.GSockJSProxy.sockets[this.sockid]=this;GLANCE.Lib.RequestProxy.postMessage({from:"GSockJSProxy",sockid:this.sockid,cmd:"open",url:a})};GLANCE.Lib.GSockJSProxy.init=function(a){GLANCE.Lib.RequestProxy.init(a);GLANCE.Lib.Window.addEventListener("message",GLANCE.Lib.GSockJSProxy.handleMessage,!1)};
var _protect_gsjsproxyresp={to:0,event:0};
GLANCE.Lib.GSockJSProxy.handleMessage=function(a){if(GLANCE.Lib.getDomain(a.origin)===GLANCE.Lib.getDomain(GLANCE.Lib.RequestProxy.server)&&"undefined"!=typeof a.data.to&&"GSockJSProxy"==a.data.to){var b=GLANCE.Lib.GSockJSProxy.sockets[a.data.sockid];if(b)switch(a.data.event.type){case "open":b.readyState=SockJS.OPEN;if(b.onopen)b.onopen(a.data.event);break;case "heartbeat":b.onheartbeat();break;case "message":b.onmessage(a.data.event);break;case "close":b.readyState=SockJS.CLOSED;b.onclose(a.data.event);
break;default:GLANCE.Lib.log("UNKNOWN GLANCE SOCKJS PROXY MESSAGE: "+JSON.stringify(a.data))}}};GLANCE.Lib.GSockJSProxy.prototype.send=function(a){GLANCE.Lib.RequestProxy.postMessage({from:"GSockJSProxy",sockid:this.sockid,cmd:"send",data:a})};GLANCE.Lib.GSockJSProxy.prototype.close=function(a,b){this.readyState=SockJS.CLOSING;GLANCE.Lib.RequestProxy.postMessage({from:"GSockJSProxy",sockid:this.sockid,cmd:"close"})};GLANCE.Lib.nextGID=1;
GLANCE.Lib.compressObj=function(a){if(void 0===a||null===a)return a;a=GLANCE.Lib.JSONStringify(a);return{_c:GLANCE.Lib.compressToBase64(a)}};GLANCE.Lib.compressToBase64=function(a){a=(new TextEncoder).encode(a);var b=(new window.GLANCE.Lib.Zlib.RawDeflate(a)).compress();a="";b=new Uint8Array(b);for(var c=b.byteLength,d=0;d<c;d++)a+=String.fromCharCode(b[d]);return window.btoa(a)};
GLANCE.Lib.decompressObj=function(a){if(null===a||a instanceof String&&0===a.length)return null;if(void 0===a._c)return a;a=GLANCE.Lib.decompressFromBase64(a._c);return JSON.parse(a)};GLANCE.Lib.decompressFromBase64=function(a){a=window.atob(a);for(var b=a.length,c=new Uint8Array(b),d=0;d<b;d++)c[d]=a.charCodeAt(d);a=(new window.GLANCE.Lib.Zlib.RawInflate(c.buffer)).decompress();return(new TextDecoder).decode(a)};
GLANCE.Lib.pad=function(a,b,c){return(a.length>=c?"":Array(1+c-a.length>>>0).join(b))+a};GLANCE.Lib.hash=function(a){var b=0,c;if(0==a.length)return b;for(c=0;c<a.length;c++){var d=a.charCodeAt(c);b=(b<<5)-b+d;b&=b}return Math.abs(b)};GLANCE.Lib.Params={};GLANCE.Lib.Params.copy=function(a,b,c){if(void 0!==a)return c=c||Object.keys(a),c.forEach(function(d){void 0!==a[d]&&(b[d]=a[d])}),b};
GLANCE.Lib.invokeFunction=function(a){var b=a.func.split(".");if(2>b.length)GLANCE.Lib.errlog("ERR_BADINVOKE:",a.func);else if("GLANCE"===b[0]||"GLANCE_COBROWSE"===b[0]&&"Custom"===b[1]){for(var c=window[b[0]],d=1;d<b.length;d++)if(c=c[b[d]],!c){GLANCE.Lib.errlog("ERR_UNDEFINVOKE:"+b[d]);return}a.args=a.args||{};a.args.remote=!0;c(a.args)}else GLANCE.Lib.errlog("ERR_BADINVOKE:"+b[0])};
GLANCE.Lib.UTCNow=function(){function a(c,d){for(c=c.toString();c.length<d;)c="0"+c;return c}var b=new Date;return b.getUTCFullYear()+"/"+(b.getUTCMonth()+1)+"/"+b.getUTCDate()+" "+a(b.getUTCHours(),2)+":"+a(b.getUTCMinutes(),2)+":"+a(b.getUTCSeconds(),2)};GLANCE.Lib.Timer=function(){this.t=0};GLANCE.Lib.Timer.prototype.elapsed=function(){return(new Date).getTime()-this.t};GLANCE.Lib.Timer.prototype.set=function(){this.t=(new Date).getTime()};GLANCE.Lib.Window={};
GLANCE.Lib.Window.addEventListener=function(a,b,c){GLANCE.Lib.GElement.nativeMethod(window,"addEventListener",a,b,c)};GLANCE.Lib.Window.removeEventListener=function(a,b){GLANCE.Lib.GElement.nativeMethod(window,"removeEventListener",a,b)};GLANCE.Lib.Window.postWindowMessage=function(a,b,c,d){var e={};e[b]=c;a.postMessage(e,void 0!==d?d:"*")};
GLANCE.Lib.Window.onWindowMessage=function(a,b,c){var d=function(e){if("string"===typeof e.data)try{var g=JSON.parse(e.data)}catch(k){return!1}else g=e.data;void 0!==g[a]&&(c&&!GLANCE.Lib.isAllowedOrigin(e.origin,c)?GLANCE.Lib.errlog("UNTRUSTED_ORIGIN:"+e.origin+" "+JSON.stringify(g)):b(e.source,g[a]))};GLANCE.Lib.GElement.nativeMethod(window,"addEventListener","message",d);return d};GLANCE.Lib.Window.POPUP_WINDOW="location=no,menubar=0,titlebar=0,status=0,toolbar=0";
GLANCE.Lib.Window.onPageHide=function(a){GLANCE.Lib.Window.addEventListener(void 0!==window.onpagehide?"pagehide":"unload",a)};GLANCE.Lib.Window.onPageShow=function(a){void 0!==window.onpageshow&&GLANCE.Lib.Window.addEventListener("pageshow",a)};GLANCE.Lib.Window.DOMEvents="DOMAttrModified DOMAttributeNameChanged DOMCharacterDataModified DOMElementNameChanged DOMNodeInserted DOMNodeInsertedIntoDocument DOMNodeRemoved DOMNodeRemovedFromDocument DOMSubtreeModified".split(" ");
GLANCE.Lib.Window.listenForDOMChanges=function(a){var b=!MutationObserver.toString().includes("native code")&&GLANCE.Lib.GElement.USE_CLEANCONTEXT?GLANCE.Lib.GElement.CleanContext:window;GLANCE.Lib.Window.mutationObserver=new b.MutationObserver(a);GLANCE.Lib.Window.mutationObserver.observe(document,{childList:!0,characterData:!0,attributes:!0,subtree:!0})};GLANCE.Lib.Window.stopListenForDOMChanges=function(){GLANCE.Lib.Window.mutationObserver&&GLANCE.Lib.Window.mutationObserver.disconnect();delete GLANCE.Lib.Window.mutationObserver};
GLANCE.Lib.cleanObj=function(a){function b(d){for(var e in d)if("object"===typeof d[e]){b(d[e]);a:{var g=void 0;var k=d[e];if(k instanceof Array||k instanceof String)g=!1;else{for(g in k)if(k.hasOwnProperty(g)){g=!1;break a}g=!0}}g&&delete d[e]}}function c(d){if(!(d instanceof Array||d instanceof String))for(var e in d)void 0===d[e]?delete d[e]:"object"===typeof d[e]&&c(d[e])}c(a);b(a)};GLANCE.Lib.compareObjects=function(a,b){return JSON.stringify(a)===JSON.stringify(b)};
GLANCE.Lib.compareVersions=function(a,b){a=String(a).split(".");var c=String(b).split(".");a.push([0,0,0,0]);c.push([0,0,0,0]);for(b=0;4>b;b++){isNaN(a[b])&&(a[b]=0);isNaN(c[b])&&(c[b]=0);if(Number(a[b])<Number(c[b]))return-1;if(Number(a[b])>Number(c[b]))return 1}return 0};GLANCE.Lib.AppendUrlParams=function(a,b){var c=a.indexOf("#");return 0>c?a+(-1===a.indexOf("?")?"?":"&")+b:GLANCE.Lib.AppendUrlParams(a.substring(0,c),b)+a.substring(c)};GLANCE.Lib.XMLDoc=function(a){this.ownerDoc=a.ownerDocument};
GLANCE.Lib.XMLDoc.prototype.getElementText=function(a){return(a=this.ownerDoc.querySelector(a))?a.textContent:null};
GLANCE.Lib.JSONFetch=async function(a,b){return new Promise(async(c,d)=>{b.headers={"Content-Type":"application/json"};"object"===typeof b.body&&(b.body=JSON.stringify(b.body));let e;try{e=await fetch(a,b)}catch(k){GLANCE.Lib.errlog(`JSON request to ${a} failed: ${k.message}`);d("connection");return}if(e.ok){try{var g=await e.json()}catch(k){GLANCE.Lib.errlog(`JSON request to ${a} reponse parse failed`,k),d("error")}c(g)}else GLANCE.Lib.errlog(`JSON request to ${a} failed status: ${e.status}`),c=
await e.text(),GLANCE.Lib.errlog(c),d(401===e.status||403===e.status?"authorization":"error")})};GLANCE.Lib.Request=function(a){GLANCE.Lib.useIFrameProxy?this.ifproxy=new GLANCE.Lib.Request.IFrameProxyRequest(a):this.xmlhttp=this.getXmlHttp();this.response=null;this.type=a};GLANCE.Lib.Request.prototype.setAuthorizer=function(a){this.authorizer=a};GLANCE.Lib.Request.prototype.setAuthorizationToken=function(a){this.authorizationToken=a};GLANCE.Lib.Request.prototype.getXmlHttp=function(){return new window.XMLHttpRequest};
GLANCE.Lib.Request.prototype.abort=function(){this.ifproxy?this.ifproxy.abort():this.xmlhttp.abort()};
GLANCE.Lib.Request.prototype.onreadystatechange=function(){if(4==this.xmlhttp.readyState){GLANCE.Lib.GElement.nativeMethod(window,"clearTimeout",this.requesttimeout);delete this.requesttimeout;var a="error";if(0==this.xmlhttp.status)GLANCE.Lib.log(this.method+" to "+this.url+" failed: network"),this.onfailure(!0,"connection",this.xmlhttp.status);else if(200!==this.xmlhttp.status){GLANCE.Lib.errlog(this.method+" to "+this.url+" failed with status: "+this.xmlhttp.status);"text"===this.xmlhttp.responseType&&
null!==this.xmlhttp.responseText&&GLANCE.Lib.log(this.xmlhttp.responseText);if(401===this.xmlhttp.status||403===this.xmlhttp.status)a="authorization",this.authorizer&&this.authorizer.clearToken();this.onfailure(!1,a,this.xmlhttp.status)}else{if(""!==this.xmlhttp.response){if("XML"===this.accept)this.response=this.xmlhttp.responseXML&&this.xmlhttp.responseXML.documentElement,null===this.response&&GLANCE.Lib.errlog("Invalid XML response: "+this.xmlhttp.responseText);else if(this.IE11BinaryWorkaround){for(var b=
new Uint8Array(this.xmlhttp.responseText.length),c=0;c<this.xmlhttp.responseText.length;c++)b[c]=this.xmlhttp.responseText.charCodeAt(c)&255;this.response=new Blob([b],{type:this.xmlhttp.getResponseHeader("Content-Type")})}else if("blob"===this.xmlhttp.responseType)this.response=this.xmlhttp.response;else if(this.xmlhttp.responseXML)this.response=this.parsejson(this.xmlhttp.responseXML.childNodes[0].childNodes[0].nodeValue);else if("HTML"===this.accept||"TEXT"===this.accept)this.response=this.xmlhttp.responseText;
else if(this.response=this.parsejson(this.xmlhttp.responseText),null===this.response){GLANCE.Lib.log(this.method+" to "+this.url+" failed - can't parse response "+this.xmlhttp.responseText);this.onfailure(!1,a);return}if(void 0!==this.response.err&&void 0!==this.response.msg){GLANCE.Lib.log(this.method+" to "+this.url+" failed with error:"+this.response.err+" "+this.response.msg);this.onfailure(!1,a);return}}this.onsuccess(this.response)}}};
GLANCE.Lib.Request.prototype.parsejson=function(a){var b=null;try{b=JSON.parse(a)}catch(c){return GLANCE.Lib.log("JSON parse failed with error: "+c.toString()+" parsing: "+a),null}return b};GLANCE.Lib.Request.prototype.getResponseHeader=function(a){return this.xmlhttp.getResponseHeader(a)};
GLANCE.Lib.Request.prototype.setAccept=function(a){this.accept=a;"XML"===a?this.acceptheader="text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8":"JSON"===a?this.acceptheader="application/json, text/javascript, */*; q=0.01":"HTML"===a?this.acceptheader="text/html":"TEXT"===a?this.acceptheader="text/*":"IMAGE"===a?this.acceptheader="image/*":"BINARY"===a&&(this.acceptheader="*/*");if("IMAGE"===a||"BINARY"===a)this.xmlhttp.responseType="blob"};
GLANCE.Lib.Request.appendQueryStringParams=function(a,b){return a+"?"+Object.keys(b).map(function(c){return c+"="+b[c]}).join("&")};GLANCE.Lib.Request.prototype.get=function(a,b,c,d,e){this.method="GET";this.post(a,null,b,c,d,e)};GLANCE.Lib.Request.formUrlEncode=function(a){var b=[],c;for(c in a)a.hasOwnProperty(c)&&b.push(encodeURIComponent(c)+"="+encodeURIComponent(a[c]));return b.join("&")};
GLANCE.Lib.Request.prototype.post=function(a,b,c,d,e,g){this.url=a;this.onsuccess=void 0!==e?e:function(){};this.onfailure=void 0!==g?g:function(){};this.method=this.method||"POST";if(this.ifproxy)this.ifproxy.post(a,b,c,d,e,g);else{e=this.contenttype||("JSON"===this.type?"application/json; charset=utf-8":"application/x-www-form-urlencoded; charset=utf-8");if("string"===typeof b)var k=b;else b instanceof Blob?(e=b.type,k=b):b&&(k="JSON"===this.type?GLANCE.Lib.JSONStringify(b):"data="+GLANCE.Lib.JSONStringify(b));
var n=this;GLANCE.Lib.Browser.safari&&this.safaritimeout&&(this.requesttimeout=GLANCE.Lib.GElement.nativeMethod(window,"setTimeout",function(){GLANCE.Lib.log(this.method+" to "+this.url+" failed - timedout (Safari)");this.onfailure(!1,"timedout")}.bind(this),this.safaritimeout));this.xmlhttp.onreadystatechange=function(){n.onreadystatechange()};try{this.xmlhttp.open(this.method,a,c),void 0!==this.acceptheader&&this.xmlhttp.setRequestHeader("Accept",this.acceptheader),void 0!==this.xmlhttp.setRequestHeader&&
"GET"!==this.method&&this.xmlhttp.setRequestHeader("Content-type",e),this.authorizer&&this.authorizer.gettoken()?this.xmlhttp.setRequestHeader("Authorization","Bearer "+this.authorizer.gettoken()):this.authorizationToken&&this.xmlhttp.setRequestHeader("Authorization","Bearer "+this.authorizationToken),this.xmlhttp.withCredentials=d,this.xmlhttp.send(k)}catch(m){GLANCE.Lib.log(this.method+" to "+a+" failed with: "+m.toString()),this.onfailure(!1,m.toString())}}};
GLANCE.Lib.Request.IFrameProxyRequest=function(a){this.type=a;GLANCE.Lib.Request.IFrameProxyRequest.currentRequest=this};GLANCE.Lib.Request.IFrameProxyRequest.init=function(a){GLANCE.Lib.RequestProxy.init(a);GLANCE.Lib.Window.addEventListener("message",GLANCE.Lib.Request.IFrameProxyRequest.handleMessage,!1)};
GLANCE.Lib.Request.IFrameProxyRequest.prototype.post=function(a,b,c,d,e,g){this.onsuccess=e;this.onfailure=g;GLANCE.Lib.RequestProxy.postMessage({from:"IFrameProxyRequest",type:this.type,url:a,obj:b,async:c,withcred:d})};GLANCE.Lib.Request.IFrameProxyRequest.prototype.abort=function(){GLANCE.Lib.Request.IFrameProxyRequest.postMessage({from:"IFrameProxyRequest",abort:!0})};var _protect_ifproxyresp={to:0,success:0,response:0};
GLANCE.Lib.Request.IFrameProxyRequest.handleMessage=function(a){if(GLANCE.Lib.getDomain(a.origin)===GLANCE.Lib.getDomain(GLANCE.Lib.RequestProxy.server)&&"undefined"!=typeof a.data.to&&"IFrameProxyRequest"==a.data.to)if(a.data.success)GLANCE.Lib.Request.IFrameProxyRequest.currentRequest.onsuccess(a.data.response);else GLANCE.Lib.Request.IFrameProxyRequest.currentRequest.onfailure()};GLANCE.Lib.Cookie=function(a,b){this.name=a;this.domain=b||(new GLANCE.Lib.Page(window)).getDomain()};
GLANCE.Lib.Cookie.prototype.setObj=function(a,b){var c=new Date;c.setUTCHours(c.getUTCHours()+8);document.cookie=this.name+"="+escape(GLANCE.Lib.JSONStringify(a))+"; expires="+c.toGMTString()+"; domain="+this.domain+"; path=/"+(b||a.secure?";secure":"")};GLANCE.Lib.Cookie.prototype.getObj=function(){var a=this.get();return a?JSON.parse(a):null};
GLANCE.Lib.Cookie.prototype.get=function(){return this.exists()?unescape(document.cookie.replace(new RegExp("(?:^|.*;\\s*)"+escape(this.name).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=\\s*((?:[^;](?!;))*[^;]?).*"),"$1")):null};GLANCE.Lib.Cookie.prototype.del=function(){var a=new Date;a.setDate(a.getDate()-1);document.cookie=escape(this.name)+"=; expires="+a.toGMTString()+"; domain="+this.domain+"; path=/"};
GLANCE.Lib.Cookie.prototype.exists=function(){return(new RegExp("(?:^|;\\s*)"+escape(this.name).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=")).test(document.cookie)};GLANCE.Lib.lsCookie=function(a){this.name=a};GLANCE.Lib.lsCookie.prototype.setObj=function(a){var b=new Date;b.setUTCHours(b.getUTCHours()+8);localStorage.setItem(this.name,GLANCE.Lib.JSONStringify(a));localStorage.setItem(this.name+"_exp",b.toGMTString())};
GLANCE.Lib.lsCookie.prototype.getObj=function(){if(!this.exists())return null;var a=localStorage.getItem(this.name);return JSON.parse(a)};GLANCE.Lib.lsCookie.prototype.setExp=function(a){"string"===typeof a&&(a=parseInt(a));var b=new Date;b.setUTCMinutes(b.getUTCMinutes()+a);localStorage.setItem(this.name+"_exp",b.toGMTString())};GLANCE.Lib.lsCookie.prototype.get=function(){return this.exists()?localStorage.getItem(this.name):null};
GLANCE.Lib.lsCookie.prototype.del=function(){localStorage.removeItem(this.name);localStorage.removeItem(this.name+"_exp")};GLANCE.Lib.lsCookie.prototype.exists=function(){var a=localStorage.getItem(this.name+"_exp");if(!a)return!1;a=new Date(a);return a<new Date?(this.del(),!1):!0};GLANCE.Lib.DualCookie=function(a,b){this.cookies=[new GLANCE.Lib.Cookie(a,b),new GLANCE.Lib.lsCookie(a)]};GLANCE.Lib.DualCookie.prototype.setObj=function(a,b){this.cookies[0].setObj(a,b);this.cookies[1].setObj(a,b)};
GLANCE.Lib.DualCookie.prototype.getObj=function(){return this.cookies[0].getObj()||this.cookies[1].getObj()};GLANCE.Lib.DualCookie.prototype.get=function(){return this.cookies[0].get()||this.cookies[1].get()};GLANCE.Lib.DualCookie.prototype.del=function(){this.cookies[0].del();this.cookies[1].del()};GLANCE.Lib.DualCookie.prototype.exists=function(){return this.cookies[0].exists()||this.cookies[1].exists()};
GLANCE.Lib.formatDocEvent=function(a){var b={};["url","name","visitorselected","agentselected"].forEach(c=>{a.hasOwnProperty(c)&&(b[c]=a[c])});return b};GLANCE.Lib.parseSize=function(a,b,c){b={w:b,h:c};a&&((c=a.match(/(\d+)x(\d+)/))&&3===c.length||GLANCE.Lib.log("ERR_INVALIDDIMS:"+a),b.w=c[1],b.h=c[2]);return b};GLANCE.Lib.Event=function(a){this.event=a||window.event;this.client={x:this.event.clientX,y:this.event.clientY}};GLANCE.Lib.toEvent=function(a){return new GLANCE.Lib.Event(a)};
GLANCE.Lib.Event.fireHTMLEvent=function(a,b){if("undefined"!==typeof CustomEvent)try{var c=new CustomEvent(b)}catch(d){}c||(c=document.createEvent("HTMLEvents"),c.initEvent(b,!0,!0));a.dispatchEvent(c)};GLANCE.Lib.Event.fireKeyboardEvent=function(a,b){b=new KeyboardEvent("keydown",{bubbles:!0,cancelable:!0,key:String.fromCharCode(b.code),"char":String.fromCharCode(b.code),shiftKey:!1});a.dispatchEvent(b)};
GLANCE.Lib.cssEscape=function(a){function b(d,e,g){d=48+parseInt(d);return"\\"+GLANCE.Lib.pad(d.toString(16),"0",6)}function c(d,e,g){return"\\"+d}if(a)return a=a.trim().replace(/[^\w\d-_]/g,c),/^\d/.test(a)&&(a=a.replace(/^\d/,b)),/^-/.test(a)&&(a=a.replace(/^-/,c)),a};
GLANCE.Lib.Page=function(a){this.doc=a.document;this.wnd=a;this.mouse={x:-1,y:-1};this.browser=GLANCE.Lib.Browser;var b=[["hidden","visibilitychange"],["mozHidden","mozvisibilitychange"],["webkitHidden","webkitvisibilitychange"],["msHidden","msvisibilitychange"],["oHidden","ovisibilitychange"]];for(a=0;a<b.length;a++)if(b[a][0]in document){this.HIDDENATTR=b[a][0];this.VISCHANGEEVT=b[a][1];break}};
GLANCE.Lib.hostFromUrl=function(a){var b=a;a=a.split("?");1<a.length&&(b=a[0]);b=(new RegExp(/(?:.*?:\/\/){0,1}([^\/:]+)/)).exec(b);return null===b||2>b.length||0>b[1].indexOf(".")?null:b[1]};
GLANCE.Lib.getDomain=function(a){var b=new RegExp(/^(?:[a-z]{1,5}:\/\/|)([^:\?\/]*)/),c=a.match(/^\d+\.\d+.\d+.\d+$/);b=b.exec(a);if(c)return a;if(null===b||2!==b.length)return"about:"!==a&&GLANCE.Lib.log("ERR_DOMAINPARSE: "+a),null;c=b[1].split(".");return 1===c.length?(GLANCE.Lib.log("ERR_DOMAINPARSE: "+a),null):2===c.length?c.join("."):3===c.length?c.slice(1).join("."):4>=c[c.length-2].length?c.slice(c.length-3).join("."):c.slice(c.length-2).join(".")};
GLANCE.Lib.isAllowedOrigin=function(a,b){var c=!1;a=GLANCE.Lib.hostFromUrl(a);if(null===a||!b)return!1;b.forEach(function(d,e){"object"===typeof d&&(d=d.domain);if(a.match(new RegExp("\\."+d+"$","i"))||a===d)c={index:e,domain:d}});return c};GLANCE.Lib.Page.prototype.getStylesheet=function(a){for(var b=this.doc.styleSheets,c=0;c<b.length;c++)if(b[c].ownerNode&&b[c].ownerNode.getAttribute(GLANCE.Lib.Const.GID)===a.getAttribute(GLANCE.Lib.Const.GID))return b[c];return null};
GLANCE.Lib.Page.prototype.getURL=function(){return window.location.href.replace(/\?.*/g,"")};GLANCE.Lib.Page.prototype.getProto=function(){for(var a=this.wnd.location.protocol,b=this.wnd;("about:"===a||"javascript:"===a)&&b.parent!==b;)a=b.parent.location.protocol,b=b.parent;return a.replace(/:/g,"")};GLANCE.Lib.Page.prototype.isSrclessIframe=function(){return this.wnd.parent!==this.wnd&&""===this.wnd.location.hostname};
GLANCE.Lib.Page.prototype.getDomain=function(){for(var a=this.wnd.location.hostname,b=this.wnd;""===a&&b.parent!==b;)a=b.parent.location.hostname,b=b.parent;return GLANCE.Lib.getDomain(a)};GLANCE.Lib.Page.prototype.inList=function(a){for(var b=window.location.href.toLowerCase(),c=0;c<a.length;c++)if(0<=b.indexOf(a[c].toLowerCase()))return!0;return!1};
GLANCE.Lib.stringToBlob=function(a,b){for(var c=new ArrayBuffer(a.length),d=new Uint8Array(c),e=0,g=a.length;e<g;e++)d[e]=a.charCodeAt(e);return new Blob([c],{type:b})};GLANCE.Lib.trapFocusInIframe=function(){["first","last"].forEach(function(a){let b=document.querySelector("."+a+"control");b&&(b.addEventListener("keydown",function(c){("Tab"===c.key&&"last"===a&&!c.shiftKey||"first"===a&&c.shiftKey)&&c.preventDefault()}),"first"===a&&b.focus())})};
GLANCE.Lib.getScrollables=function(a){function b(d){if(d=GLANCE.Lib.GElement.nativeGetProperty("children",d))for(var e=0;e<d.length;e++)GLANCE.Lib.toElem(d[e]).isScrollable()&&c.push(d[e]),b(d[e])}var c=[];b(a);return c};GLANCE.Lib.Page.prototype.getElementsByTagName=function(a){return GLANCE.Lib.GElement.nativeMethod(this.doc,"getElementsByTagName",a)};
GLANCE.Lib.Page.prototype.isLinkToOtherDomain=function(a){for(var b,c=this.getDomain();a&&!GLANCE.Lib.toElem(a).isBody();){if(a instanceof DocumentFragment){a=null;break}if("a"===a.tagName.toLowerCase())break;a=a.parentNode}if(!a||"a"!==a.tagName.toLowerCase())return!1;b=a.href;b=b.baseVal||b;var d=b.indexOf("//");if(0>d)return!1;0===d&&(b="http:"+b);return a.hasAttribute("download")||b.startsWith("blob:")?!1:GLANCE.Lib.getDomain(b)!==c};
GLANCE.Lib.Page.prototype.getUrlParam=function(a){a=(new RegExp("[\\?&]"+a+"=([^&#]*)")).exec(this.wnd.location.href);return null==a?"":a[1]};GLANCE.Lib.Page.prototype.addScriptAsync=async function(a){return new Promise((b,c)=>{var d=this.doc.createElement("script");d.onload=b;d.onerror=c;for(const e in a)d.setAttribute(e,a[e]);d.setAttribute("charset","UTF-8");this.doc.head.appendChild(d)})};
GLANCE.Lib.Page.prototype.addScript=function(a,b,c){var d=this.doc.createElement("script");b&&d.addEventListener("load",b);c&&d.addEventListener("error",c);d.setAttribute("type","text/javascript");d.setAttribute("charset","UTF-8");for(b=0;b<a.length;b++)d.setAttribute(a[b][0],a[b][1]);this.doc.head.appendChild(d);return d};GLANCE.Lib.Page.prototype.VSCROLL=1;GLANCE.Lib.Page.prototype.HSCROLL=2;
GLANCE.Lib.Page.prototype.getScrollVisible=function(a){var b=this.getDimensions(),c=this.getDocDimensions(),d=GLANCE.Lib.Page.getComputedStyle(this.doc.body);if(null===d)return!1;var e=a===this.VSCROLL?d.overflowY:d.overflowX;return(a===this.VSCROLL?c.y:c.x)>(a===this.VSCROLL?b.y:b.x)&&("visible"===d.overflow||"visible"===e||"auto"===d.overflow||"auto"===e||"scroll"===e)};GLANCE.Lib.Page.prototype.getElement=function(a){return GLANCE.Lib.GElement.nativeMethod(this.doc,"getElementById",a)};
GLANCE.Lib.Page.prototype.trackMouse=function(){var a=this;this.onMouseMove=function(b){b=new GLANCE.Lib.Event(b);a.mouse.x=b.client.x||-1;a.mouse.y=b.client.y||-1;return!0};this.onMouseOut=function(b){new GLANCE.Lib.Event(b);a.mouse.x=-1;a.mouse.y=-1;return!0};this.addEventListener("mousemove",this.onMouseMove);this.addEventListener("mouseout",this.onMouseOut)};
GLANCE.Lib.Page.prototype.stopTrackMouse=function(){this.doc.removeEventListener("mousemove",this.onMouseMove);this.doc.removeEventListener("mouseout",this.onMouseOut)};GLANCE.Lib.Page.prototype.trackMouseClick=function(){var a=this;this.clearMouseClick();this.onMouseClick=function(b){b=new GLANCE.Lib.Event(b);a.click.x=b.client.x||0;a.click.y=b.client.y||0;a.click.ts=Date.now();return!0};this.addEventListener("click",this.onMouseClick)};
GLANCE.Lib.Page.prototype.stopTrackMouseClick=function(){this.doc.removeEventListener("click",this.onMouseClick)};GLANCE.Lib.Page.prototype.getMouse=function(){return this.getElemRelativeCoords(this.mouse)};GLANCE.Lib.Page.prototype.clearMouse=function(){this.mouse={x:-1,y:-1}};GLANCE.Lib.Page.prototype.getMouseClick=function(){var a=this.click;this.click={x:-1,y:-1};return this.getElemRelativeCoords(a)};GLANCE.Lib.Page.prototype.clearMouseClick=function(){this.click={x:-1,y:-1}};
GLANCE.Lib.Page.prototype.isHidden=function(){return void 0===this.HIDDENATTR?!1:this.doc[this.HIDDENATTR]};GLANCE.Lib.Page.prototype.onVisibilityChange=function(a){this.doc.addEventListener(this.VISCHANGEEVT,a)};
GLANCE.Lib.Page.prototype.getNonFixedElemNear=function(a,b){function c(k){if(!k||"body"===k.tagName.toLowerCase())return!1;let n=GLANCE.Lib.Page.getComputedStyle(k).position;return"fixed"===n||"sticky"===n?!0:c(GLANCE.Lib.GElement.nativeGetProperty("parentElement",k))}var d,e=0,g={};for(GLANCE.Lib.Params.copy(a,g);(d=this.getElemAt(g))&&c(d);)if(scrolllog("skipping fixed elem "+d.tagName+"  class="+d.getAttribute("class")+" data-gid="+d.getAttribute(GLANCE.Lib.Const.GID)+" at "+JSON.stringify(g)),
g[b]+=50,10<e++)return scrolllog("getNonFixedElemNear not finding a non fixed element, returning body"),document.body;scrolllog("getNonFixedElemNear found non-fixed elem "+d.tagName+"  class="+d.getAttribute("class")+" data-gid="+d.getAttribute(GLANCE.Lib.Const.GID)+" at "+JSON.stringify(g));return d||document.body};GLANCE.Lib.Page.prototype.getElemAt=function(a){a=document.elementsFromPoint(a.x,a.y).filter(b=>"glance_overlay"!==b.id)[0];a||(a=document.body);3==a.nodeType&&(a=a.parentNode);return a};
GLANCE.Lib.Page.coordsOutside=function(a){a=a.client||a;return 0>a.x||0>a.y};
GLANCE.Lib.Page.prototype.getElemRelativeCoords=function(a,b,c){if(a&&(0>a.x||0>a.y))return{client:{x:Math.round(a.x),y:Math.round(a.y)}};a=a||this.pageToClientCoords(b);b=b||this.clientToPageCoords(a);c=GLANCE.Lib.toElem(c?this.getNonFixedElemNear(a,c):this.getElemAt(a));if(c.matches("#glance_session_widget *")||c.matches("#glance_screensharepreview"))c=GLANCE.Lib.toElem(document.getElementById("glance_session_widget"));var d=c.getCoords();return{client:{x:Math.round(a.x),y:Math.round(a.y)},relative:{x:Math.round(b.x-
d.x),y:Math.round(b.y-d.y),element:c.getPath()}}};GLANCE.Lib.Page.prototype.getElemRelativeOffset=function(a,b){if(0===b)return{offset:0};var c=this.getScrollCoords(a,b);c=this.getElemRelativeCoords(void 0,c,a).relative;return{offset:b,relative:{element:c.element,offset:c[a]}}};GLANCE.Lib.Page.prototype.relativeOffsetToPage=function(a,b,c){if(!b)return c;var d={element:b.element};d[a]=b.offset;d["x"===a?"y":"x"]=0;return(b=this.relativeCoordsToPage(d))?b[a]:c};
GLANCE.Lib.Page.prototype.relativeCoordsToClient=function(a,b){return(a=this.relativeCoordsToPage(a))?this.pageToClientCoords(a):b};GLANCE.Lib.Page.prototype.relativeCoordsToPage=function(a,b){var c=a?GLANCE.Lib.toElem(this.doc.documentElement).getUniqueElement(a.element,!1):null;if(null===c)return GLANCE.Lib.log("Element not found for relative coords"),b;b=GLANCE.Lib.toElem(c).getCoords();return{x:b.x+a.x,y:b.y+a.y}};
GLANCE.Lib.Page.prototype.toAbsoluteUrls=function(a,b){var c,d=this;return a.replace(RegExp("url\\s*\\(['\"]?(\\s*(?!.*//.*).+?)['\"]?\\)","g"),function(e,g){"/"!==g.charAt(0)&&(c=d.getPath())&&(g=c+g);return"url("+b+d.wnd.location.host+g+")"})};GLANCE.Lib.Page.prototype.head=function(){return void 0!==this.doc.head?this.doc.head:this.getElementsByTagName("head")[0]};GLANCE.Lib.Page.prototype.cloneBody=function(){return GLANCE.Lib.toElem(this.doc.body).deepClone()};
GLANCE.Lib.Page.prototype.cloneHead=function(){return this.doc.head.cloneNode(!0)};GLANCE.Lib.Page.prototype.addLoadListener=function(a){this.wnd.addEventListener&&(document.readyState.match(/complete/)?a():(this.wnd.addEventListener("load",a),this.doc.addEventListener("DOMContentLoaded",a,!1)))};GLANCE.Lib.Page.prototype.getDocContainer=function(){return this.doc.compatMode&&"CSS1Compat"!==this.doc.compatMode?this.doc.body:this.doc.documentElement};
GLANCE.Lib.Page.prototype.getDimensions=function(){if(void 0!==window.orientation)return{x:window.innerWidth,y:window.innerHeight};var a=this.getDocContainer();return{x:a.clientWidth,y:a.clientHeight}};GLANCE.Lib.Page.prototype.getDocDimensions=function(){if(this.doc.width)return{x:this.doc.width,y:this.doc.height};var a=this.getDocContainer();return{x:a.scrollWidth,y:a.scrollHeight}};
GLANCE.Lib.Page.prototype.getScrollInfo=function(){for(var a=this.getDimensions(),b=this.getDocDimensions(),c=["x","y"],d,e,g,k,n={},m=0;m<c.length;m++)d=c[m],e=Math.round(Math.pow(a[d],2)/b[d]),g=a[d]-4,k=0,b[d]>a[d]&&(k=(g-e)/(b[d]-a[d])),k=Math.round(1E4*k)/1E4,n[d]={tabsz:e,ratio:k};return n};
GLANCE.Lib.Page.prototype.getScroll=function(){if(void 0!==window.pageXOffset)return{x:Math.round(this.wnd.pageXOffset),y:Math.round(this.wnd.pageYOffset)};if(void 0!==document.documentElement.scrollTop)return{x:this.doc.documentElement.scrollLeft,y:this.doc.documentElement.scrollTop};if(void 0!==document.body.scrollLeft)return{x:this.doc.body.scrollLeft,y:this.doc.body.scrollTop};throw Error("Can't get page scroll");};
GLANCE.Lib.Page.prototype.getScrollCoords=function(a,b){var c=this.getDimensions(),d=this.getScroll();return{x:"x"===a?b:c.x/2+d.x,y:"y"===a?b:c.y/2+d.y}};GLANCE.Lib.Page.prototype.pageToClientCoords=function(a){var b=this.getScroll();return{x:a.x-b.x,y:a.y-b.y}};GLANCE.Lib.Page.prototype.clientToPageCoords=function(a){var b=this.getScroll();return{x:a.x+b.x,y:a.y+b.y}};
GLANCE.Lib.Page.prototype.scrollTo=function(a,b,c){var d=this.getScroll();d[a]=b;a={left:d.x,top:d.y,behavior:c?"smooth":"auto"};GLANCE.Lib.Browser.ie11||GLANCE.Lib.Browser.edge?window.scrollTo(d.x,d.y):window.scrollTo(a);scrolllog("scrolled the page to:",d,"new scroll position:",this.getScroll())};GLANCE.Lib.Page.prototype.getPath=function(){var a=this.origPath(),b=a.match(/(((.*?)\/)*)([^\/]+)/);return 0>a.indexOf(".")?a:b?b[1]:null};
GLANCE.Lib.Page.prototype.getBasePath=function(){let a=new URL(document.baseURI),b=a.pathname.split("/");0<b.slice(-1).indexOf(".")&&(b=b.slice(0,-1));return a.origin+b.join("/")};GLANCE.Lib.Page.prototype.origPath=function(){return window.GLANCE.Cobrowse.Loader._origpath};GLANCE.Lib.Page.prototype.pathChanged=function(){return window===window.parent&&window.location.pathname!==this.origPath()};GLANCE.Lib.Page.getComputedStyle=function(a,b){return window.getComputedStyle(a,b)};
GLANCE.Lib.Page.prototype.addEventListener=function(a,b,c){GLANCE.Lib.GElement.nativeMethod(this.doc,"addEventListener",a,b,c)};GLANCE.Lib.Page.prototype.removeEventListener=function(a,b,c){GLANCE.Lib.GElement.nativeMethod(this.doc,"removeEventListener",a,b,c)};GLANCE.Lib.errlog=function(a){GlanceLogger.error(a)};GLANCE.Lib.log=function(a){GlanceLogger.log(a)};
GLANCE.Lib.moo={extendElement:function(a){a.playAnimation=function(b,c){window.clearTimeout(a.timeout);a.removeClass(b);window.requestAnimationFrame(function(d){window.requestAnimationFrame(function(e){a.addClass(b);a.timeout=window.setTimeout(()=>{a.removeClass("remoteclick")},c)})})}}};GLANCE.Lib.GElement=function(a){this.element=a};GLANCE.Lib.toElem=function(a){return new GLANCE.Lib.GElement(a)};
GLANCE.Lib.GElement.prototype.show=function(a){void 0===a&&(a=!0);this.element.className.match(new RegExp(a?"glance_show":"glance_hide","g"))||(this.replaceClass(a?"glance_hide":"glance_show",a?"glance_show":"glance_hide"),this.addClass(a?"glance_show":"glance_hide"))};GLANCE.Lib.GElement.prototype.dummyOuterHTML=function(){var a=this.element.id?' id="'+this.element.id+'"':"";return"<meta "+GLANCE.Lib.Const.GID+'="'+this.element.getAttribute(GLANCE.Lib.Const.GID)+'"'+a+"></meta>"};
GLANCE.Lib.GElement.prototype.addClass=function(a){"string"===typeof this.element.className&&this.element.className.match(new RegExp("\\b"+a+"\\b","g"))||(this.element.className+=" "+a)};GLANCE.Lib.GElement.prototype.removeClass=function(a){this.element.className=this.element.className.replace(new RegExp("\\s+"+a,"g"),"")};GLANCE.Lib.GElement.prototype.replaceClass=function(a,b){this.element.className=this.element.className.replace(new RegExp(a,"g"),b)};
GLANCE.Lib.GElement.prototype.addEventListener=function(a,b,c){GLANCE.Lib.GElement.nativeMethod(this.element,"addEventListener",b,c)};GLANCE.Lib.GElement.prototype.removeEventListener=function(a,b,c){GLANCE.Lib.GElement.nativeMethod(this.element,"removeEventListener",b,c)};GLANCE.Lib.GElement.prototype.isTextInput=function(){return this.element.tagName.match(/^textarea$/i)||this.element.type.match(/^(text|datetime|email|password|tel|url|number)$/i)};
GLANCE.Lib.GElement.prototype.isButtonInput=function(){return this.element.tagName.match(/^input$/i)&&this.element.type.match(/^(radio|checkbox|button)$/i)};GLANCE.Lib.GElement.prototype.hasNativeShadowRoot=function(){return this.element.attachShadow==Element.prototype.attachShadow&&GLANCE.Lib.GElement.nativeGetProperty("shadowRoot",this.element)};
GLANCE.Lib.GElement.prototype.hasGIDlessDescendants=function(){for(var a=GLANCE.Lib.GElement.nativeMethod(this.element,"querySelectorAll","*"),b=0;b<a.length;b++)if(!a[b].getAttribute(GLANCE.Lib.Const.GID))return!0;return!1};
GLANCE.Lib.GElement.prototype.simulateMouseEvent=function(a,b){"click"===a&&this.element.tagName.match(/input|textarea/i)&&(this.element.focus(),this.isTextInput()&&"number"!==this.element.type&&(this.element.selectionStart=this.element.selectionEnd));if("click"===a&&void 0!==this.element.click)this.element.click();else{void 0===b&&(b={view:window,bubbles:!0,cancelable:!0});try{var c=new MouseEvent(a,b)}catch(d){c=this.element.ownerDocument.createEvent("MouseEvents"),c.initMouseEvent(a,!0,!0,this.element.ownerDocument.defaultView,
1,0,0,0,0,!1,!1,!1,!1,1,null)}this.element.dispatchEvent(c)}};
GLANCE.Lib.GElement.nativeGetProperty=function(a,b){if(!GLANCE.Lib.GElement.USE_CLEANCONTEXT||1!==b.nodeType)return b[a];var c=GLANCE.Lib.GElement.USE_CLEANCONTEXT?GLANCE.Lib.GElement.CleanContext:window;if(GLANCE.Lib.GElement.USE_CLEANCONTEXT)try{var d=c.document.createElement(b.nodeName)}catch(g){d=c.document.createElement("div")}else d=b;d=c.Object.getPrototypeOf(d);if(!d)return b[a];if("contentWindow"===a)return c.Object.getOwnPropertyDescriptor(d,a).get.call(b);for(var e;!(e=c.Object.getOwnPropertyDescriptor(d,
a))||0>e.get.toString().indexOf("[native code]");)if(d=c.Object.getPrototypeOf(d),!d)return b[a];return e.get.call(b)};
GLANCE.Lib.GElement.nativeMethod=function(a,b,...c){return GLANCE.Lib.GElement.USE_CLEANCONTEXT&&GLANCE.Lib.GElement.CleanContext&&a.nodeType?"#document"===a.nodeName?GLANCE.Lib.GElement.CleanContext.document[b].apply(a,c):"#document-fragment"===a.nodeName?GLANCE.Lib.GElement.CleanContext.DocumentFragment.prototype[b].apply(a,c):GLANCE.Lib.GElement.CleanContext.document.body[b].apply(a,c):GLANCE.Lib.GElement.USE_CLEANCONTEXT&&GLANCE.Lib.GElement.CleanContext&&"[object Window]"===a.toString()?GLANCE.Lib.GElement.CleanContext.window[b].apply(a,
c):a[b].apply(a,c)};
GLANCE.Lib.GElement.getNativeMethod=function(a,b){return GLANCE.Lib.GElement.USE_CLEANCONTEXT&&GLANCE.Lib.GElement.CleanContext&&GLANCE.Lib.GElement.CleanContext.document[a]?"#document"===b.nodeName?GLANCE.Lib.GElement.CleanContext.document[a]:"#document-fragment"===b.nodeName?GLANCE.Lib.GElement.CleanContext.DocumentFragment.prototype[a]:GLANCE.Lib.GElement.CleanContext.document.body[a]:GLANCE.Lib.GElement.USE_CLEANCONTEXT&&GLANCE.Lib.GElement.CleanContext&&"[object Window]"===b.toString()?GLANCE.Lib.GElement.CleanContext.window[a]:
b[a]};GLANCE.Lib.GElement.nativeInstance=function(a,...b){a=GLANCE.Lib.GElement.CleanContext.window[a];return new (Function.bind.apply(a,[a,...b]))};
GLANCE.Lib.GElement.prototype.deepClone=function(){try{if(GLANCE.Lib.GElement.USE_CLEANCONTEXT)if(GLANCE.Lib.GElement.CleanContext.clone)var a=GLANCE.Lib.GElement.CleanContext.clone(this.element);else diffslog("clean context clone not loaded  cloning "+this.element.gid+" iframe:"+window.parent!==window),a=GLANCE.Lib.GElement.nativeMethod(this.element,"cloneNode",!0);else a=this.element.cloneNode(!0);return a}catch(b){GLANCE.Lib.log("deepClone failed for "+this.element.tagName+" error:"+b.message)}return this.element.cloneNode(!0)};
GLANCE.Lib.GElement.prototype.isDescendantOf=function(a){return a.contains?GLANCE.Lib.Browser.ie11&&this.element.nodeType===Node.TEXT_NODE?this.element.parentNode===a||GLANCE.Lib.GElement.nativeMethod(a,"contains",this.element.parentNode):GLANCE.Lib.GElement.nativeMethod(a,"contains",this.element):!1};GLANCE.Lib.GElement.prototype.remove=function(){this.element.parentNode&&this.element.parentNode.removeChild(this.element)};
GLANCE.Lib.GElement.prototype.isScrollable=function(){if(!this.element)return!1;var a=window.getComputedStyle(this.element);return null===a?!1:(a.overflowX+a.overflowY).match(/scroll|auto/)};GLANCE.Lib.GElement.prototype.replaces=function(a){this.element.parent.replaceChild(this.element,a)};GLANCE.Lib.GElement.prototype.empty=function(){for(;this.element.hasChildNodes();)this.element.removeChild(this.element.childNodes[0])};
GLANCE.Lib.GElement.prototype.getDimensions=function(){if(this.element.getBoundingClientRect){var a=this.element.getBoundingClientRect();return{width:Math.round(a.right-a.left),height:Math.round(a.bottom-a.top)}}return{width:this.element.offsetWidth,height:this.element.offsetHeight}};GLANCE.Lib.GElement.prototype.setDimensions=function(a,b){this.element.style.width=a+"px";this.element.style.height=b+"px"};GLANCE.Lib.GElement.prototype.isBody=function(){return/^(?:body|html)$/i.test(this.element.tagName)};
GLANCE.Lib.GElement.prototype.isHead=function(){return/^(?:head)$/i.test(this.element.tagName)};GLANCE.Lib.GElement.prototype.isHeadOrHeadChild=function(){return this.isHead()||this.isDescendantOf(document.head)};GLANCE.Lib.GElement.prototype.getScrolls=function(){for(var a=this.element.parentNode,b={x:0,y:0};a&&!GLANCE.Lib.toElem(a).isBody();)b.x+=a.scrollLeft,b.y+=a.scrollTop,a=a.parentNode;return b};
GLANCE.Lib.GElement.prototype.getCoords=function(a){if(this.element.tagName.match(/html/i))return{x:0,y:0};var b=this.element.getBoundingClientRect(),c=document.documentElement,d=(new GLANCE.Lib.Page(window)).getScroll();if(a=!a)a=GLANCE.Lib.Page.getComputedStyle(this.element),a="fixed"===(a?a.getPropertyValue("position"):"");return{x:parseInt(b.left)+(a?0:d.x)-c.clientLeft,y:parseInt(b.top)+(a?0:d.y)-c.clientTop}};
GLANCE.Lib.GElement.prototype.setCoords=function(a,b){this.element.style.left=a+"px";this.element.style.top=b+"px"};GLANCE.Lib.GElement.prototype.positionAtZero=function(){if("static"!==GLANCE.Lib.Page.getComputedStyle(document.body).position){let a=GLANCE.Lib.toElem(document.body).getCoords(!0);this.setCoords(-a.x,-a.y)}else this.setCoords(0,0)};
GLANCE.Lib.GElement.prototype.containsElemCoords=function(a){var b=a.getCoords();a=a.getDimensions();var c=this.getCoords(),d=this.getDimensions();return!(b.x+a.width>c.x+d.width||b.x<c.x||b.y+a.height>c.y+d.height||b.y<c.y)};
GLANCE.Lib.GElement.prototype.pointInScrollbar=function(a){if(!this.isScrollable())return!1;var b=this.element.getBoundingClientRect();return a.y>b.top&&a.y<b.bottom&&a.x>b.left+this.element.clientWidth&&a.x<b.right||a.x>b.left&&a.x<b.right&&a.y>b.top+this.element.clientHeight&&a.y<b.bottom};
GLANCE.Lib.GElement.prototype.moveTo=function(a,b){function c(){10>k++?(e+=n,g+=m,d.setCoords(Math.floor(e),Math.floor(g)),d.movetimer=GLANCE.Lib.GElement.nativeMethod(window,"setTimeout",c,20)):d.setCoords(a,b)}void 0!==this.movetimer&&GLANCE.Lib.GElement.nativeMethod(window,"clearTimeout",this.movetimer);var d=this,e=parseInt(this.element.style.left),g=parseInt(this.element.style.top);isNaN(e)&&(e=-999);isNaN(g)&&(g=-999);var k=0,n=(a-e)/10,m=(b-g)/10;0===n&&0===m||c()};
GLANCE.Lib.GElement.prototype.cancelFade=function(){null!=this.fadeStartTimer&&GLANCE.Lib.GElement.nativeMethod(window,"clearTimeout",this.fadeStartTimer);this.fadeStartTimer=null;this.fadeInterval&&GLANCE.Lib.GElement.nativeMethod(window,"clearInterval",this.fadeInterval);this.fadeInterval=null};GLANCE.Lib.GElement.prototype.setOpacity=function(a){this.opacity=a;this.element.style.opacity=this.opacity/100;this.element.style.filter="alpha(opacity = "+this.opacity+")"};
GLANCE.Lib.GElement.prototype.fade=function(a,b,c){var d=this,e=new Date;null!==this.fadeInterval&&this.cancelFade();this.fadeInterval=GLANCE.Lib.GElement.nativeMethod(window,"setInterval",function(){var g=new Date-e;g>=a?(d.setOpacity(0),d.cancelFade(),c&&c()):d.setOpacity(Math.max(0,b(g/a)))},50)};
GLANCE.Lib.GElement.prototype.getSelectorRelativeToParent=function(){var a,b=1,c=this.tagNameLCase();for(a=this.element.previousElementSibling;null!=a;a=a.previousElementSibling)a.tagName.toLowerCase()===c&&b++;return GLANCE.Lib.cssEscape(c)+":nth-of-type("+b+")"};GLANCE.Lib.GElement.prototype.tagNameLCase=function(){return this.element==document?"document":this.element.tagName.toLowerCase()};
GLANCE.Lib.GElement.prototype.cssid=function(){var a=this.element.getAttribute("id");return a?"#"+GLANCE.Lib.cssEscape(a):void 0};GLANCE.Lib.GElement.prototype.isSelectiveEditable=function(){return!this.element.matches(".glance_masked")&&(this.element.matches(".glance_controllable")||this.element.matches(".glance_controllable *"))};
GLANCE.Lib.GElement.prototype.getPath=function(){for(var a=[],b=this,c;b.element&&b.element.tagName;){if(b.isBody()||b.isHead()){a.unshift(b.tagNameLCase());break}var d=GLANCE.Lib.GElement.nativeGetProperty("parentNode",b.element);if(null===d)return null;c=b.cssid();if(b.element.getAttribute(GLANCE.Lib.Const.GID)){a.unshift("["+GLANCE.Lib.Const.GID+'="'+b.element.getAttribute(GLANCE.Lib.Const.GID)+'"]');break}else if(c&&1===GLANCE.Lib.toElem(d).getElements(c).length){if(a.unshift(c),1===GLANCE.Lib.toElem(document.documentElement).getElements(c).length)break}else a.unshift(b.getSelectorRelativeToParent());
b=GLANCE.Lib.toElem(d)}return a.join(">")};GLANCE.Lib.GElement.matchesShim=Element.prototype.matches||Element.prototype.matchesSelector||Element.prototype.msMatchesSelector;GLANCE.Lib.GElement.prototype.matches=function(a){return GLANCE.Lib.GElement.matchesShim.call(this.element,a)};GLANCE.Lib.GElement.prototype.matchesAny=function(a){return 0<a.length&&this.matches(a.join(","))};
GLANCE.Lib.GElement.prototype.getElements=function(a){return GLANCE.Lib.GElement.nativeMethod(this.element,"querySelectorAll",a)};GLANCE.Lib.GElement.prototype.getShadowDOMElementPath=function(a){if(!a)return null;a=a.replace(/'/g,'"');return(a=a.match(new RegExp("\\["+GLANCE.Lib.Const.GID+'="(.*-.*)"\\]')))&&2===a.length?a[1]:null};
GLANCE.Lib.GElement.prototype.findElementInShadowDOM=function(a){function b(d,e,g){if(null===d)return sdlog("No shadow root at level "+g+"for selector "+a),null;var k="["+GLANCE.Lib.Const.GID+"='"+e.slice(0,g+1).join("-")+"']";d=GLANCE.Lib.GElement.nativeMethod(d,"querySelector",k);return d?g===e.length-1?d:b(d.shadowRoot,e,g+1):(sdlog("sdid "+k+" not found"),null)}var c=this.getShadowDOMElementPath(a);if(!c)return null;c=c.split("-");return b(this.element.ownerDocument,c,0)};
GLANCE.Lib.GElement.prototype.getUniqueElement=function(a,b){function c(e){if(b)throw Error(e);GLANCE.Lib.log(e);return null}if(this.element===document.documentElement&&"html"===a)return this.element;void 0===b&&(b=!0);var d=GLANCE.Lib.GElement.nativeMethod(this.element,"querySelectorAll",a);return 1===d.length?d[0]:1<d.length?c("Nonunique selector: "+a):(d=this.findElementInShadowDOM(a))?d:c("Element not found: "+a)};
GLANCE.Lib.GElement.prototype.getInputValue=function(a){var b=GLANCE.Lib.GElement.nativeGetProperty("type",this.element)||"";a={tag:GLANCE.Lib.GElement.nativeGetProperty("tagName",this.element),type:b,path:this.getPath(),id:GLANCE.Lib.GElement.nativeGetProperty("id",this.element),name:GLANCE.Lib.GElement.nativeGetProperty("name",this.element),sel:GLANCE.Lib.GElement.nativeGetProperty("selectedIndex",this.element),value:a||GLANCE.Lib.GElement.nativeGetProperty("value",this.element)};"string"===typeof a.value&&
(a.value=a.value.replace(/<\/script>/gi,"<\\/script>"));b.match(/^(radio|checkbox)$/i)&&(a.checked=this.element.checked);return a};GLANCE.Lib.GElement.prototype.setInputValue=function(a){switch(a.type.toLowerCase()){case "checkbox":case "radio":this.element.checked=a.checked;break;case "select-one":this.element.selectedIndex=a.sel;break;case "file":break;default:"string"===typeof a.value&&(this.element.value=a.value.replace("<\\/script>","\x3c/script>"))}};
GLANCE.Lib.MessageHandlers=function(){this.handlers={}};GLANCE.Lib.MessageHandlers.prototype.addHandler=function(a,b){this.handlers["^"+a+"$"]=b};GLANCE.Lib.MessageHandlers.prototype.dispatch=function(a){var b=this,c=a.messageName;delete a.messageName;Object.keys(this.handlers).forEach(function(d){if((new RegExp(d)).test(c))b.handlers[d](c,a)})};GLANCE.Lib.EventListeners=function(){this.listeners=this._listeners={}};
GLANCE.Lib.EventListeners.prototype.merge=function(a){a=a.listeners;for(var b in a)this._listeners[b]=(this._listeners[b]||[]).concat(a[b])};GLANCE.Lib.EventListeners.prototype.add=function(a,b){this._listeners[a]=this._listeners[a]||[];this._listeners[a].push(b)};GLANCE.Lib.EventListeners.prototype.remove=function(a,b){a=this._listeners[a];void 0!==a&&(b=a.indexOf(b),0<=b&&a.splice(b,1))};GLANCE.Lib.EventListeners.prototype.removeAll=function(a){this._listeners[a]=[]};
GLANCE.Lib.EventListeners.prototype.fire=function(a,b){eventslog("fire "+a+" "+(b?JSON.stringify(b):""));var c=this._listeners[a],d=!0;if(void 0===c)return!0;for(a=0;a<c.length;a++)c[a](b)||(d=!1);return d};
GLANCE.Lib.CssRuleString=function(a){function b(k){return k.replace(/[\\]:/g,":").replace(":","\\:")}var c=new RegExp(/\[([^\[\]]*)\]/g);try{var d="",e="",g=a.cssRules||a.rules;for(a=0;a<g.length;a++)e=g[a].cssText,e=e.replace(c,b),d+=e+" ";return d}catch(k){return GLANCE.Lib.log("Exception getting csstext for stylesheet:"+k.toString()),""}};
GLANCE.Lib.DomDiff=function(){this.differences=[];this.htmlfilter=function(){return!0};this.renderedhtmlfilter=function(a){return a};this.attrfilter=function(a,b){return a.getAttribute(b)};this.contentfilter=function(){return!0};this.nogids=[]};GLANCE.Lib.DomDiff.prototype.setNoGids=function(a){this.nogids=a};
GLANCE.Lib.DomDiff.prototype.removeGIDs=function(a){delete a.gid;if(1===a.nodeType&&(a.removeAttribute(GLANCE.Lib.Const.GID),a.removeAttribute(GLANCE.Lib.Const.SDID),a.removeAttribute(GLANCE.Lib.Const.GCID),GLANCE.Lib.GElement.nativeGetProperty("children",a))){for(var b=0;b<GLANCE.Lib.GElement.nativeGetProperty("children",a).length;b++)this.removeGIDs(GLANCE.Lib.GElement.nativeGetProperty("children",a)[b]);if(GLANCE.Lib.toElem(a).hasNativeShadowRoot())for(a=GLANCE.Lib.GElement.nativeGetProperty("children",
a.shadowRoot),b=0;b<a.length;b++)this.removeGIDs(a[b])}};
GLANCE.Lib.DomDiff.prototype._assignGIDs=function(a,b){b=b||"";if(1===a.nodeType){if(this.gidless)for(var c=0;c<this.gidless.length;c++)if(a==this.gidless[c]||GLANCE.Lib.toElem(a).isDescendantOf(this.gidless[c])){this.removeGIDs(a);return}a.gid||(c=b?[b,GLANCE.Lib.nextGID].join("-"):GLANCE.Lib.nextGID,a.gid=c,a.setAttribute(GLANCE.Lib.Const.GID,c),"CANVAS"===a.tagName&&a.setAttribute(GLANCE.Lib.Const.GCID,c),GLANCE.Lib.toElem(a).hasNativeShadowRoot()&&a.setAttribute(GLANCE.Lib.Const.SDID,c),GLANCE.Lib.nextGID++);
c=GLANCE.Lib.GElement.nativeGetProperty("children",a);!c&&GLANCE.Lib.Browser.ie11&&(c=GLANCE.Lib.GElement.nativeGetProperty("childNodes",a));if(c)for(var d=0;d<c.length;d++)this._assignGIDs(c[d],b);if(GLANCE.Lib.toElem(a).hasNativeShadowRoot())for(c=GLANCE.Lib.getChildrenOrShadowChildren(a),d=0;d<c.length;d++)this._assignGIDs(c[d],a.gid)}};
GLANCE.Lib.DomDiff.prototype.assignGIDs=function(a,b){diffdetlog("assignGIDs next GID:",GLANCE.Lib.nextGID,"current GID:",a.getAttribute(GLANCE.Lib.Const.GID),this.getPath(a));this.gidless=0<this.nogids.length?GLANCE.Lib.GElement.nativeMethod(document,"querySelectorAll",this.nogids.join(",")):[];this._assignGIDs(a,b);delete this.gidless};GLANCE.Lib.DomDiff.prototype.log=function(a,b){};
GLANCE.Lib.DomDiff.prototype.getPath=function(a){var b=GLANCE.Lib.toElem(a).getPath();return null===b?null:a._idchanged&&!/^(head|body)$/i.test(a.tagName)?"["+GLANCE.Lib.Const.GID+'="'+a.getAttribute(GLANCE.Lib.Const.GID)+'"]':b};GLANCE.Lib.DomDiff.prototype.diff=function(a,b){this._diff(a,b);a=this.differences;this.differences=[];return a};
GLANCE.Lib.DomDiff.prototype.createDiffForDisabledChange=function(a,b){b=this.getPath(a);this.differences.push({diff:a.disabled?"SETATTR":"REMATTR",path:b,attr:"disabled",value:""});diffslog("ATTR diff: "+GLANCE.Lib.JSONStringify(this.differences[this.differences.length-1]));return this._returnMyDiffs()};
GLANCE.Lib.DomDiff.prototype.createDiffsForStyleChange=function(a,b,c){a.getAttribute("style")===b.getAttribute("style")||a.getAttribute("glance_cobrowse_suppress")||this._addAttrDiffFromMutation(a,"style");a=GLANCE.Lib.GElement.nativeGetProperty("children",a);b=GLANCE.Lib.GElement.nativeGetProperty("children",b);for(var d=0;a&&d<a.length;d++)if(d<b.length&&a[d].getAttribute(GLANCE.Lib.Const.GID)===b[d].getAttribute(GLANCE.Lib.Const.GID))this.createDiffsForStyleChange(a[d],b[d],!0);else for(var e=
0;e<b.length;e++)if(b[e].getAttribute(GLANCE.Lib.Const.GID)===a[d].getAttribute(GLANCE.Lib.Const.GID)){this.createDiffsForStyleChange(a[d],b[e],!0);break}if(void 0===c)return this._returnMyDiffs()};GLANCE.Lib.DomDiff.prototype._diff=function(a,b){this._diffElemAttrs(a,b);if(!this._diffChildList(a,b)&&!this._diffNodeList(a,b)){a=GLANCE.Lib.GElement.nativeGetProperty("children",a);var c=GLANCE.Lib.GElement.nativeGetProperty("children",b);for(b=0;void 0!==a&&b<a.length;b++)this._diff(a[b],c[b])}};
GLANCE.Lib.DomDiff.prototype.mergeDiffs=function(a,b){var c,d;for(c=0;c<a.length;c++){var e=!1;switch(a[c].diff){case "CONTENT":for(d=0;d<b.length;d++)if(b[d].path===a[c].path&&b[d].node===a[c].node){b[d].data=a[c].data;e=!0;break}break;case "ATTR":for(d=0;d<b.length;d++)if(b[d].path===a[c].path){b[d].data=a[c].data;e=!0;break}break;case "SETATTR":case "REMATTR":for(d=0;d<b.length;d++)if(("SETATTR"===b[d].diff||"REMATTR"===b[d].diff)&&b[d].path===a[c].path&&b[d].attr===a[c].attr){b[d]=a[c];e=!0;break}break;
case "REPLACE":for(d=0;d<b.length;d++)if(b[d].path===a[c].path&&"REPLACE"===b[d].diff){b[d].data=a[c].data;e=!0;break}}e||b.push(a[c])}};
GLANCE.Lib.DomDiff.prototype._diffElemAttrs=function(a,b){var c,d=a.attributes,e=b.attributes;a.id!==b.id&&(b._idchanged=!0);for(c=0;c<d.length;c++)d.item(c).nodeName!==GLANCE.Lib.Const.GID&&b.getAttribute(d.item(c).nodeName)!=d.item(c).nodeValue&&this._addAttrDiffFromMutation(b,d.item(c).nodeName);for(c=0;c<e.length;c++)e.item(c).nodeName===GLANCE.Lib.Const.GID||a.getAttribute(e.item(c).nodeName)||this._addAttrDiffFromMutation(b,e.item(c).nodeName)};
GLANCE.Lib.DomDiff.prototype._diffNodeList=function(a,b){var c=GLANCE.Lib.GElement.nativeGetProperty("children",a);var d=GLANCE.Lib.GElement.nativeGetProperty("children",b);if(c&&d&&0===c.length&&0===d.length)return a.textContent!==b.textContent&&this._addContentDiff(b),!0;d=GLANCE.Lib.GElement.nativeGetProperty("childNodes",a);let e=GLANCE.Lib.GElement.nativeGetProperty("childNodes",b);if(d.length!==e.length)return this._addHTMLDiff(b),!0;for(var g=0;g<d.length;g++)if(a=d[g],c=e[g],a.nodeType!==
c.nodeType||a.nodeValue!==c.nodeValue)return this._addHTMLDiff(b),!0};GLANCE.Lib.DomDiff.prototype._diffChildList=function(a,b){let c=GLANCE.Lib.GElement.nativeGetProperty("children",a),d=GLANCE.Lib.GElement.nativeGetProperty("children",b);if(void 0===c||void 0===d)return void 0===c!==(void 0===d);if(c.length!=d.length)return this._addHTMLDiff(b);for(a=0;a<c.length;a++)if(c[a].tagName!==d[a].tagName)return this._addHTMLDiff(b);return!1};
GLANCE.Lib.DomDiff.prototype._addAttrDiff=function(a){var b,c={};for(b=0;b<a.attributes.length;b++)this.attrfilter(a,a.attributes[b].name)&&(c[a.attributes[b].name]=a.attributes[b].value);diffslog("ATTR diff: "+this.getPath(a)+" "+GLANCE.Lib.JSONStringify(c),a);this.differences.push({diff:"ATTR",path:this.getPath(a),data:c})};
GLANCE.Lib.DomDiff.prototype.createMediaDiffs=function(){if(void 0!==window.matchMedia)for(var a=GLANCE.Lib.GElement.nativeMethod(document.head,"getElementsByTagName","link"),b=0;b<a.length;b++)this.differences.push({diff:"SETATTR",path:this.getPath(a[b]),attr:"media",value:""===a[b].media||window.matchMedia(a[b].media).matches?"all":"none"});return this._returnMyDiffs()};GLANCE.Lib.DomDiff.prototype.createHTMLAttrDiff=function(){this._addAttrDiff(document.documentElement);return this._returnMyDiffs()};
GLANCE.Lib.DomDiff.prototype._addAttrDiffFromMutation=function(a,b){var c=this.getPath(a);if(null===c)diffslog("Ignoring attr diff for ",b,"=",a.getAttribute(b)+" of elem ",a," not in DOM");else{var d=this.attrfilter(a,b);!1===d?diffslog("Ignoring attr diff for ",b,"=",a.getAttribute(b)+" of elem ",a," filtered out"):(this.differences.push({diff:d||""===d?"SETATTR":"REMATTR",path:c,attr:b,value:d}),diffslog("ATTR diff: "+c+" "+b+" "+d,a))}};
GLANCE.Lib.DomDiff.prototype.addContentDiff=function(a,b){var c=this.getPath(a);null!==c&&(this.differences.push({diff:"CONTENT",path:c,data:b}),diffslog("CONTENT diff: "+c,a))};GLANCE.Lib.DomDiff.prototype._addContentDiff=function(a){this.contentfilter(a)&&(diffslog("CONTENT diff: "+this.getPath(a)),this.addContentDiff(a,a.textContent))};
GLANCE.Lib.getChildNodesOrShadowChildNodes=function(a){return GLANCE.Lib.toElem(a).hasNativeShadowRoot()?GLANCE.Lib.GElement.nativeGetProperty("childNodes",GLANCE.Lib.GElement.nativeGetProperty("shadowRoot",a)):GLANCE.Lib.GElement.nativeGetProperty("childNodes",a)};
GLANCE.Lib.getChildrenOrShadowChildren=function(a){return GLANCE.Lib.toElem(a).hasNativeShadowRoot()?GLANCE.Lib.GElement.nativeGetProperty("children",GLANCE.Lib.GElement.nativeGetProperty("shadowRoot",a)):GLANCE.Lib.GElement.nativeGetProperty("children",a)};
GLANCE.Lib.DomDiff.prototype._addContentDiffFromMutation=function(a){var b,c=a.parentNode;for(b=0;b<GLANCE.Lib.GElement.nativeGetProperty("childNodes",c).length;b++)if(GLANCE.Lib.GElement.nativeGetProperty("childNodes",c)[b]===a){var d=b;break}void 0===d?GLANCE.Lib.log("Node not found in _addContentDiffFromMutation"):this.contentfilter(c)&&(ShadowRoot&&c instanceof ShadowRoot&&(c=c.host),this.differences.push({diff:"CONTENT",path:this.getPath(c),data:a.textContent,node:d}),diffslog("CONTENT diff: "+
this.getPath(c),a.textContent,d,"out of",GLANCE.Lib.GElement.nativeGetProperty("childNodes",c).length))};GLANCE.Lib.DomDiff.prototype._addHTMLDiff=function(a){diffslog("HTML diff: "+this.getPath(a));this.htmlfilter(a);this.differences.push({diff:"HTML",path:this.getPath(a),data:this.renderedhtmlfilter(a.innerHTML)});return!0};
GLANCE.Lib.DomDiff.prototype._getOuterHTML=function(a){var b=GLANCE.Lib.GElement.nativeGetProperty("outerHTML",a);b||(b=document.createElement("div"),b.appendChild(a),b=b.innerHTML);return this.renderedhtmlfilter(b)};GLANCE.Lib.DomDiff.prototype._getElemHtml=function(a){var b=GLANCE.Lib.toElem(a).deepClone();if(this.htmlfilter(a,b))return this._getOuterHTML(b);diffslog("Ignoring filtered element of type: "+a.tagName);return GLANCE.Lib.toElem(b).dummyOuterHTML()};
GLANCE.Lib.DomDiff.prototype._addChildOrderDiff=function(a){var b=this.getPath(a);if(b&&this.contentfilter(a)){diffslog("CHILDORDER diff: "+b,a);a=GLANCE.Lib.GElement.nativeGetProperty("childNodes",a);for(var c=[],d=0;d<a.length;d++)switch(a[d].nodeType){case 1:c.push({gid:a[d].getAttribute(GLANCE.Lib.Const.GID)});break;case 3:c.push({text:a[d].textContent});break;case 8:c.push({comment:a[d].data})}this.differences.push({diff:"CHILDORDER",path:b,data:c})}};
GLANCE.Lib.DomDiff.prototype._addReplaceNodeDiff=function(a){var b=this.getPath(a);if(b&&(1!==a.nodeType||!a.tagName.match(/textarea/i))){diffslog("REPLACE diff: "+b,"gid:",a.getAttribute(GLANCE.Lib.Const.GID),a);a.getAttribute(GLANCE.Lib.Const.GID)||diffslog("No gid for replace node diff on "+this.getPath(a));for(var c=GLANCE.Lib.GElement.nativeGetProperty("children",a),d=0;c&&d<c.length;d++)this.assignGIDs(c[d]);(a=this._getElemHtml(a))?(this.differences.push({diff:"REPLACE",path:b,data:a}),"html"!==
b||GLANCE.Lib.GElement.USE_CHILDORDER||this._addReplaceNodeDiff(document.head),diffdetlog(this.differences.length+" differences")):diffslog("Ingoring filtered replace diff for ",b)}};
GLANCE.Lib.DomDiff.prototype._addChildListDiff=function(a){var b=a.target,c=a._addedNodes,d=a._removedNodes,e=a.nextSibling;e&&1===e.nodeType&&(GLANCE.Lib.toElem(e).isDescendantOf(document.documentElement)&&GLANCE.Lib.GElement.nativeGetProperty("parentElement",e)===b?e.getAttribute(GLANCE.Lib.Const.GID)||diffslog("No data-gid for nextSibling. removedgid:",e.removedgid):(diffdetlog("nextSibling not in dom or in different parent, not sending:",e),e=null));diffdetlog("CHILDLIST diff for element: "+this.getPath(b),
b);var g=this.getPath(b);if(null!==g){var k={diff:"CHILDLIST",path:g,nsib:e&&c?this.getPath(e):null,added:[],removed:[]};if(c)for(g=0;g<c.length;g++)if(!(0<=a.ignoreAdded.indexOf(g))){var n=GLANCE.Lib.GElement.nativeGetProperty("parentNode",c[g]);if(n!==b)diffdetlog("==> Ignoring add element no longer in same parent. gid=",c[g].gid),n||(diffdetlog("==> Ignored add element no longer in dom, removing gid"),delete c[g].gid,1===c[g].nodeType&&c[g].removeAttribute(GLANCE.Lib.Const.GID));else{if(1===c[g].nodeType){this.assignGIDs(c[g]);
var m=this._getElemHtml(c[g]);if(!m){diffdetlog("==> Not adding filtered element:",c[g]);continue}diffdetlog("==> Added element node gid="+c[g].getAttribute(GLANCE.Lib.Const.GID)+" before "+k.nsib,c[g],"htmllength",m.length,"html:",m.substr(0,100))}else if(3===c[g].nodeType)m=this.contentfilter(b)?c[g].nodeValue:"",diffdetlog("==> added text node ","'"+m+"'");else if(8===c[g].nodeType)m=c[g].nodeValue,diffdetlog("==> added comment node ","'"+m+"'");else{diffdetlog("==> ignoring added node type ",
c[g].nodeType);continue}k.added.push({nodeType:c[g].nodeType,tagName:c[g].tagName,value:m})}}if(d)for(g=0;g<d.length;g++)if(!(0<=a.ignoreRemoved.indexOf(g))){switch(d[g].nodeType){case 1:diffdetlog("==> Removed node gid=",d[g].removedgid);m=d[g].removedgid;if(!m){diffdetlog("==> Ignoring remove Element with no gid");continue}break;case 3:diffdetlog("==> removed text node with value "+d[g].nodeValue);m=d[g].nodeValue;break;default:GLANCE.Lib.log("==> Ignoring remove node type "+d[g].nodeType)}k.removed.push({nodeType:d[g].nodeType,
value:m})}if(0===k.removed.length&&0===k.added.length)return!1;this.differences.push(k);e&&8===e.nodeType&&(diffdetlog("Found comment node as nextSibling, adding childorder diff",b),this._addChildOrderDiff(b));return!0}};
GLANCE.Lib.DomDiff.prototype._mergeMutations=function(a){function b(f){a.push({target:f,type:"replacedNode"})}function c(f){if(f instanceof HTMLHtmlElement)diffslog("No order fixing mutation needed for HTML element");else if(!f.getAttribute(GLANCE.Lib.Const.GID)||!GLANCE.Lib.GElement.USE_CHILDORDER&&GLANCE.Lib.toElem(f).hasGIDlessDescendants())b(f);else a:{for(var h=0;h<x.length;h++)if(x[h].target===f)break a;x.push({target:f,type:"childOrder"})}}function d(f){f=GLANCE.Lib.GElement.nativeGetProperty("childNodes",
f);for(var h=1;h<f.length;h++)if(f[h].nodeType===f[h-1].nodeType&&(3===f[h].nodeType||8===f[h].nodeType))return!0;return!1}function e(f){for(var h=0;h<a.length;h++)if(a[h]!==f&&"attributes"===f.type&&"attributes"===a[h].type&&f.target===a[h].target&&f.attributeName===a[h].attributeName)return f.target;return!1}function g(f){var h,p,u=GLANCE.Lib.toElem(f.target);for(h=0;h<a.length;h++)if(a[h]!==f&&"childList"===a[h].type)for(p=0;a[h]._addedNodes&&p<a[h]._addedNodes.length;p++)if(f.target===a[h]._addedNodes[p]||
u.isDescendantOf(a[h]._addedNodes[p]))return a[h]._addedNodes[p];return!1}function k(f){var h;for(h=0;h<a.length;h++)if(a[h]!==f&&"replacedNode"===a[h].type&&(f.target===a[h].target||GLANCE.Lib.toElem(f.target).isDescendantOf(a[h].target)))return a[h].target;return!1}var n=this,m=new GLANCE.Lib.Timer;m.set();var x=[];diffslog("Merging "+a.length+" mutations");if(500<a.length){GLANCE.Lib.log("Mutation overflow");m=!1;for(var l=0;l<a.length&&!m;l++)if(a[l].target===document.head||GLANCE.Lib.GElement.nativeGetProperty("parentElement",
a[l].target)===document.head)m=!0;a.length=0;m&&this._addReplaceNodeDiff(document.head);this._addReplaceNodeDiff(document.body)}else{a.forEach(function(f){"attributes"===f.type&&"id"===f.attributeName&&f.target.id&&(f.target._idchanged=!0);"childList"===f.type&&(f.ignoreAdded=[],f.ignoreRemoved=[])});for(l=0;l<a.length;l++){var q=g(a[l]),t=GLANCE.Lib.GElement.nativeGetProperty("parentElement",a[l].target);q?(diffdetlog("Ignoring redundant mutation "+a[l].type+" to target ",a[l].target.tagName," descendant of added node ",
q.tagName),a.splice(l,1),l--):"characterData"===a[l].type&&t&&d(t)&&(diffslog("Using child order diff instead of content diff for",this.getPath(a[l].target),"due to consecutive text elements in parent",this.getPath(t)),c(t),a.splice(l,1),l--)}a.forEach(function(f){if("childList"===f.type){var h;a:{for(h=0;h<a.length;h++)if(a[h].target===f.target&&"replacedNode"===a[h].type){h=!0;break a}h=!1}if(!h){if(0<f._addedNodes.length)for(h=0;h<a.length;h++)if("childList"===a[h].type&&a[h].target===f.target&&
0<a[h]._removedNodes.length){diffslog("Creating order-fixing mutation for "+n.getPath(f.target)+" due to adds and removes in child list");c(f.target);return}if(f.nextSibling&&3===f.nextSibling.nodeType)GLANCE.Lib.GElement.USE_CHILDORDER?(diffslog("Creating order fixing mutation for "+n.getPath(f.target)+" due to add before text node"),c(f.target)):(diffslog("Creating replaceNode mutation for "+n.getPath(f.target)+" due to add before text node"),b(f.target));else for(h=0;h<f._removedNodes.length;h++)if(3===
f._removedNodes[h].nodeType){diffslog("Creating replaceNode mutation for "+n.getPath(f.target)+" due to remove text node");b(f.target);break}}}});for(l=0;l<a.length;l++)GLANCE.Lib.toElem(a[l].target).isDescendantOf(document.documentElement)||(diffdetlog("Ignoring mutation type=",a[l].type," to target ",a[l].target," no longer in dom"),a.splice(l,1),l--);for(l=0;l<a.length;l++)if("childList"===a[l].type&&0!==a[l]._addedNodes.length)for(q=0;q<a[l]._addedNodes.length;q++){t=a[l]._addedNodes[q];for(var z=
!1,v=l+1;!z&&v<a.length;v++)if("childList"===a[v].type)for(var w=0;w<a[v]._removedNodes.length;w++)if(t===a[v]._removedNodes[w]){diffdetlog("Ignoring add and remove for same node: (",l,q,") and (",v,w,") node:",t.tagName);a[l].ignoreAdded.push(q);a[v].ignoreRemoved.push(w);z=!0;break}}Array.prototype.push.apply(a,x);for(l=0;l<a.length;l++)if(q=k(a[l]))diffdetlog("Ignoring redundant mutation "+a[l].type+" to target ",a[l].target.tagName,a[l].target.gid," descendant of replaced node ",q.tagName,q.gid),
a.splice(l,1),l--;for(l=0;l<a.length;l++)if(q=e(a[l]))diffdetlog("Ignoring redundant attribute mutation "+a[l].attributeName+" to target "+this.getPath(q)),a.splice(l,1),l--;diffslog("Merged mutations to:"+a.length+" in "+m.elapsed()+" ms")}};
GLANCE.Lib.DomDiff.prototype._addDiffsFromMutationObserver=function(a){var b=this;a.forEach(function(c){if("childList"===c.type)for(var d=0;d<c._removedNodes.length;d++)1===c._removedNodes[d].nodeType&&(c._removedNodes[d].gid&&delete c._removedNodes[d].removedgid,c._removedNodes[d].gid&&(c._removedNodes[d].removedgid=c._removedNodes[d].gid,delete c._removedNodes[d].gid,c._removedNodes[d].removeAttribute(GLANCE.Lib.Const.GID)))});this._mergeMutations(a);a.forEach(function(c){switch(c.type){case "attributes":b._addAttrDiffFromMutation(c.target,
c.attributeName);break;case "characterData":b._addContentDiffFromMutation(c.target);break;case "childList":b._addChildListDiff(c);break;case "replacedNode":b._addReplaceNodeDiff(c.target);break;case "childOrder":b._addChildOrderDiff(c.target);break;default:GLANCE.Lib.log("Unrecognized mutation record type "+c.type)}})};GLANCE.Lib.DomDiff.prototype.setHtmlFilter=function(a){this.htmlfilter=a};GLANCE.Lib.DomDiff.prototype.setRenderedHtmlFilter=function(a){this.renderedhtmlfilter=a};
GLANCE.Lib.DomDiff.prototype.setAttrFilter=function(a){this.attrfilter=a};GLANCE.Lib.DomDiff.prototype.setContentFilter=function(a){this.contentfilter=a};GLANCE.Lib.DomDiff.prototype.diffsFromMutations=function(a){if(0!==a.length)return-1!==a[0].toString().indexOf("MutationRecord")&&this._addDiffsFromMutationObserver(a),diffslog("Got "+this.differences.length+" differences"),this._returnMyDiffs()};GLANCE.Lib.DomDiff.prototype._returnMyDiffs=function(){var a=this.differences;this.differences=[];return a};
GLANCE.Lib.DomDiffApplier=function(){};GLANCE.Lib.DomDiffApplier.prototype._applyAttrDiff=function(a,b){var c=a.data,d=[];for(a=0;a<b.attributes.length;a++)d.push(b.attributes[a].name);for(a=0;a<d.length;a++)void 0===c[d[a]]&&(diffslog("   -"+d[a]),b.removeAttribute(d[a]));for(var e in c)c.hasOwnProperty(e)&&(diffslog("   +"+e+"="+c[e]),b.setAttribute(e,c[e]))};
GLANCE.Lib.DomDiffApplier.prototype._hashHrefsToAbsolute=function(a){a=(a.parentElement||document.body).querySelectorAll("svg [*|href^='#']");for(var b=window.location.href.replace(/#.*/,""),c=0;c<a.length;c++){var d=a[c].attributes.getNamedItem("href")||a[c].attributes.getNamedItem("xlink:href");if(d){var e=d.value;diffslog("Page-relative href to absolute. Element:",a[c],"namespace:",d.namespaceURI,"href:",b+e);a[c].attributes.removeNamedItem(d.name);a[c].setAttributeNS(d.namespaceURI||"http://www.w3.org/1999/xlink",
"href",b+e)}else GLANCE.Lib.log("ERR_HREFNOTFOUND")}};GLANCE.Lib.DomDiffApplier.prototype._removeObjectUrlImages=function(a){if(!GLANCE.Lib.Browser.ie){a=(a.parentElement||document.body).querySelectorAll("svg image[*|href^='blob']");for(var b=0;b<a.length;b++){var c=a[b];c.href&&c.href.baseVal&&(c.href.baseVal="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAFCAIAAAD38zoCAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAQSURBVBhXYziMA9Be4vBhAFKrW2mB3kkXAAAAAElFTkSuQmCC")}}};
GLANCE.Lib.DomDiffApplier.prototype.processAddedElem=function(a){this._hashHrefsToAbsolute(a);null!==document.getElementById("glance-pdf")&&this._removeObjectUrlImages(a)};
GLANCE.Lib.DomDiffApplier.prototype._processAddedHeadElem=function(a){var b=GLANCE.Lib.GElement.nativeGetProperty("childNodes",document.head);for(let c=0;c<b.length;)document.head.removeChild(b[c]);b=document.implementation.createHTMLDocument("");b.head.outerHTML=a;a=document.head.getElementsByTagName("BASE");for(a=(a=a.length?a[0]:null)?a.nextSibling:null;0<b.head.childNodes.length;)document.head.insertBefore(b.head.firstChild,a)};
GLANCE.Lib.DomDiffApplier.prototype._setOuterHTML=function(a,b){b=b.replace(/<script\s/gi,"<template ").replace(/<script>/gi,"<template>").replace(/\/script>/gi,"/template>");b=b.replace(/http-equiv\s*=\s*['"]?refresh['"]?/gi,"");try{a.outerHTML=b}catch(c){GLANCE.Lib.errlog("Exception setting outer HTML:"+c.toString()+" for element:"+a.toString()+" to "+b.substr(0,200))}};
GLANCE.Lib.DomDiffApplier.prototype._applyChildOrderDiff=function(a,b,c){var d=GLANCE.Lib.GElement.nativeGetProperty("childNodes",b),e;if(/^(head|body)$/i.test(b.tagName))for(e=0;e<d.length;)1!==d[e].nodeType||d[e].getAttribute(GLANCE.Lib.Const.GID)||"BASE"===d[e].tagName||"glance_open_sel"===d[e].id?e++:(diffslog("ChildOrder: Removing gidless "+d[e].tagName+" id:"+d[e].id+" index:"+e+" in "+a),b.removeChild(d[e]));for(a=e=0;e<c.length;e++,a++)if(diffslog("ChildOrder: Entry "+e+"="+JSON.stringify(c[e])),
c[e])if(a>=d.length)diffslog("ChildOrder: Append empty text node"),b.appendChild(document.createTextNode(""));else if(1!==d[a].nodeType||d[a].getAttribute(GLANCE.Lib.Const.GID))if(void 0!==c[e].text)3!==d[a].nodeType?(diffslog("ChildOrder: Inserting text node "+JSON.stringify(c[e].text)+" at "+a),b.insertBefore(document.createTextNode(c[e].text),d[a])):d[a].textContent!==c[e].text?(diffslog("ChildOrder: Fixing up text "+JSON.stringify(c[e].text)+" in node "+a),d[a].textContent=c[e].text):diffslog("ChildOrder: Text "+
JSON.stringify(d[a].textContent)+" correct in node "+a);else if(void 0!==c[e].comment)8!==d[a].nodeType&&(diffslog("ChildOrder: Adding comment node at "+a),b.insertBefore(document.createComment(c[e].comment),d[a]));else if(1===d[a].nodeType&&d[a].getAttribute(GLANCE.Lib.Const.GID)===c[e].gid)diffslog("ChildOrder: Found "+c[e].gid+" in correct location at "+a);else{diffslog("ChildOrder: Moving "+c[e].gid+" to correct location at "+a);var g=b.querySelector("[data-gid='"+c[e].gid+"']");g?b.insertBefore(g,
d[a]):(diffslog("ChildOrder: Element missing gid:"+c[e].gid),a--)}else"BASE"!==d[a].tagName&&errorlog("ERR_MISSING_GID",b.tagName,b.id,b.className),e--;for(;a<d.length;)3===d[a].nodeType?b.removeChild(d[a]):a++};
GLANCE.Lib.DomDiffApplier.prototype.applyDiffs=function(a){var b,c=GLANCE.Lib.toElem(document.documentElement),d={};if(!a)return d;diffslog("=== Applying Diffs ===");for(b=0;b<a.length;b++){var e=c.getUniqueElement(a[b].path,!1);if(null===e)GLANCE.Lib.log("Element not found applying diff: "+a[b].diff+" to "+a[b].path);else switch(diffslog("Applying diff "+a[b].diff+" to "+e.tagName+" "+a[b].path),a[b].diff){case "ATTR":this._applyAttrDiff(a[b],e);break;case "SETATTR":diffslog("SETATTR attr on: "+
a[b].path+" attr:"+a[b].attr+" value:"+a[b].value);GLANCE.Lib.Browser.firefox&&"disabled"===a[b].attr&&e.tagName.match(/link/i)&&(e.disabled=!0);"style"===a[b].attr&&window.PrefixFree&&(a[b].value+=";"+PrefixFree.prefixCSS(a[b].value.replace(/-webkit-/,"")));"class"===a[b].attr?e.setAttribute("class",a[b].value):e.setAttribute(a[b].attr,a[b].value);"CANVAS"===e.tagName&&(d.canvas=!0);break;case "REMATTR":diffslog("REMATTR attr on: "+a[b].path+" attr:"+a[b].attr);GLANCE.Lib.Browser.firefox&&"disabled"===
a[b].attr&&e.tagName.match(/link/i)&&(e.disabled=!1);"class"===a[b].attr?e.setAttribute("class",""):e.removeAttribute(a[b].attr);break;case "CONTENT":0===a[b].node&&0===GLANCE.Lib.GElement.nativeGetProperty("childNodes",e).length&&(a[b].node=void 0);if(void 0!==a[b].node&&a[b].node>=GLANCE.Lib.GElement.nativeGetProperty("childNodes",e).length){GLANCE.Lib.log("Child node out of range applying CONTENT diff to "+a[b].path);break}void 0!==a[b].node?GLANCE.Lib.GElement.nativeGetProperty("childNodes",e)[a[b].node].textContent=
a[b].data:e.textContent=a[b].data;break;case "REPLACE":diffslog("REPLACE "+a[b].path+" with "+a[b].data.substr(0,100));if(e instanceof HTMLHtmlElement){var g=(new DOMParser).parseFromString(a[b].data,"text/html");e.querySelector("body").innerHTML=g.querySelector("body").innerHTML}else this._setOuterHTML(e,a[b].data);this.processAddedElem(e);/^(head|body|canvas)$/i.test(e.tagName)&&(d[e.tagName.toLowerCase()]=!0);0<e.getElementsByTagName("canvas").length&&(d.canvas=!0);/^head$/i.test(e.tagName)&&(g=
document.getElementsByTagName("body"),1<g.length&&0==GLANCE.Lib.GElement.nativeGetProperty("children",g[0]).length&&document.documentElement.removeChild(g[0]));/^body$/i.test(e.tagName)&&(g=document.getElementsByTagName("head"),1<g.length&&0==GLANCE.Lib.GElement.nativeGetProperty("children",g[1]).length&&document.documentElement.removeChild(g[1]));diffdetlog("==> replaced element with gid:",e.getAttribute(GLANCE.Lib.Const.GID));break;case "CHILDLIST":var k=a[b].nsib?GLANCE.Lib.toElem(e).getUniqueElement(a[b].nsib,
!1):null;for(g=0;g<a[b].added.length;g++)switch(diffslog("Adding node type: "+a[b].added[g].nodeType+" to "+GLANCE.Lib.toElem(e).getPath()),a[b].added[g].nodeType){case 1:if("HEAD"===a[b].added[g].tagName){diffdetlog("Added HEAD element");d.head=!0;this._processAddedHeadElem(a[b].added[g].value);break}var n=document.createElement("x");e.insertBefore(n,k);this._setOuterHTML(n,a[b].added[g].value);this.processAddedElem(n);diffdetlog("Added node gid:",n.getAttribute(GLANCE.Lib.Const.GID));break;case 3:n=
document.createTextNode(a[b].added[g].value);e.insertBefore(n,k);break;case 8:n=document.createComment(a[b].added[g].value);e.insertBefore(n,k);break;default:GLANCE.Lib.errlog("Unexpected node type "+a[b].added[g].nodeType+" added in applyDiffs")}for(g=0;g<a[b].removed.length;g++)switch(diffslog("Removing node type: "+a[b].removed[g].nodeType+" value "+a[b].removed[g].value),a[b].removed[g].nodeType){case 1:k=GLANCE.Lib.toElem(e).getElements("["+GLANCE.Lib.Const.GID+'="'+a[b].removed[g].value+'"]');
if(0===k.length||GLANCE.Lib.GElement.nativeGetProperty("parentElement",k[0])!==e&&k[0].parentNode!==e){diffslog("Ignoring removed Element gid "+a[b].removed[g].value+" not in parent");break}e.removeChild(k[0]);break;case 3:for(k=0;k<e.childNodes.length;k++)if(3===e.childNodes[k].nodeType&&e.childNodes[k].nodeValue===a[b].removed[g].value){e.removeChild(e.childNodes[k]);break}}break;case "CHILDORDER":/^(head|body)$/i.test(e.tagName)&&(d[e.tagName.toLowerCase()]=!0);this._applyChildOrderDiff(a[b].path,
e,a[b].data);break;case "HTML":e.innerHTML=a[b].data,this.processAddedElem(e)}}return d};document.domain=window.location.hostname.match(/[^\.]+\.([^\.]+)$/)[0];GLANCE=GLANCE||{};GLANCE.Cobrowse=GLANCE.Cobrowse||{};GLANCE.Cobrowse.ViewerFrame=function(){function a(f){q=document.id("pageframe");t=document.id("agentview");if(f){f=GLANCE_SESSIONINFO.state;var h=f.scroll;h=`.vscrollbardims
            {
                height: ${f.windims.y-4}px;
                display: ${f.scrollvisible.y?"inline-block":"none"};
            }
            .hscrollbardims
            {
                width:   ${f.windims.x-4}px; /* -4 for scrollbar border */
                display: ${f.scrollvisible.x?"block":"none"};
            }
            .vscrollpos
            {
                height: ${f.scrollinfo.y.tabsz}px;
                top:    ${Math.floor((h?"object"===typeof h.y?h.y.offset:f.scroll.y:0)*f.scrollinfo.y.ratio)}px;
            }
            .hscrollpos
            {
                width: ${f.scrollinfo.x.tabsz}px;
                left:${Math.floor((h?"object"===typeof h.x?h.x.offset:f.scroll.x:0)*f.scrollinfo.x.ratio)}px;
            }`;var p=document.createElement("style");p.type="text/css";p.appendChild(document.createTextNode(h));document.head.appendChild(p);t.setStyle("width",f.windims.x+24+"px");q.setStyle("width",f.windims.x+"px");q.setStyle("height",f.windims.y+"px");f=GLANCE_SESSIONINFO;q.set("src",`${f.server}/agent/Page?ssnid=${f.ssnid}&num=${f.num}#glance_scroll`)}document.addEvent("mouseleave",function(u){var r,y={},A=q.getPosition();for(r in u)"function"!==typeof u[r]&&"target"!==r&&"relatedTarget"!==
r&&"event"!==r&&(y[r]=u[r]);y.client.x-=A.x;y.client.y-=A.y;k()&&k().mouseLeave(y)});m();window.addEventListener("message",x,!1);window.addEvent("resize",m)}function b(f,h){f={mtype:f,data:h};f.num=GLANCE_SESSIONINFO.num;f.ssnid=GLANCE_SESSIONINFO.ssnid;fetch(`${GLANCE_SESSIONINFO.server}/agent/message`,{method:"POST",mode:"cors",cache:"no-cache",credentials:"include",keepalive:!0,headers:{"Content-Type":"application/json"},redirect:"error",referrerPolicy:"no-referrer",body:JSON.stringify(f)}).catch(p=>
{GLANCE.Lib.errlog("CobrowseConnection fetch failed")})}function c(){b("LeaveSession",{});w=!0}function d(f){fetch(GLANCE_SESSIONINFO.server+("agent"===f?"/agent/AgentConnectAPI?ssnid=":"/guest/GuestConnectAPI?ssnid=")+GLANCE_SESSIONINFO.ssnid,{credentials:"include"}).then(h=>{if(!h.ok)throw Error(h.statusText);h.json().then(p=>{debuglog("viewerConnect succeeded",p);delete GLANCE_SESSIONINFO["agent"===f?"agentconnect":"guestconnect"];Object.assign(p,window.GLANCE_SESSIONINFO);l.set("data-ssninfo",
JSON.stringify(p));GLANCE_SESSIONINFO=p;a(!0);GLANCE.Cobrowse.ViewerFrame.connected=!0;v.fire("connected")})}).catch(h=>{GLANCE.Lib.log("viewerConnect failed: "+JSON.stringify(h));window.location.href=`/cobrowse/Error.aspx?Error=AuthError&ssnid=${GLANCE_SESSIONINFO.ssnid}&role=${f}`})}async function e(){if(GLANCE_SESSIONINFO.universalcam){var f=`https://${GLANCE_SESSIONINFO.universalcam}/connect?groupid=${GLANCE_SESSIONINFO.groupid}`;debuglog("Connecting to CAM service at:",f);f=await fetch(f,{method:"POST",
cache:"no-cache",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({token:GLANCE_SESSIONINFO.camrestoken})});if(!f.ok)throw Error("CAM service connect failed: "+f.statusText);debuglog("Connected to CAM service")}}function g(f){var h=GLANCE_SESSIONINFO.server,p=GLANCE_SESSIONINFO.ssnid;let u=GLANCE_SESSIONINFO.ssnconnectinfo;u.ssnid=p;u.agentscriptver=GLANCE_SESSIONINFO.agentscriptver;fetch(h+("agent"===f?"/agent/AgentConnectPost?ssnid=":"/guest/GuestConnectPost?ssnid=")+
p,{method:"POST",cache:"no-cache",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(u)}).then(r=>{if(!r.ok)throw Error(r.statusText);return r.json()}).then(r=>{debuglog("viewerConnectPost succeeded",r);delete GLANCE_SESSIONINFO["agent"===f?"agentconnect":"guestconnect"];Object.assign(r,window.GLANCE_SESSIONINFO);l.set("data-ssninfo",JSON.stringify(r));GLANCE_SESSIONINFO=r;return e()}).then(()=>{a(!0);GLANCE.Cobrowse.ViewerFrame.connected=!0;v.fire("connected")}).catch(r=>
{GLANCE.Lib.log("viewerConnect failed: "+r.message);window.location.href=`/cobrowse/Error.aspx?Error=AuthError&ssnid=${GLANCE_SESSIONINFO.ssnid}&role=${f}`})}function k(){try{return q.contentWindow.GLANCE&&q.contentWindow.GLANCE.Cobrowse?q.contentWindow.GLANCE.Cobrowse.Viewer:null}catch(f){return null}}function n(){GLANCE_SESSIONINFO.scaledview=!1;document.body.removeClass("scaletofit");["transform","-webkit-transform","margin-left","width"].forEach(function(f){t.style.removeProperty(f)})}function m(){if(GLANCE_SESSIONINFO.scaledview){t.style.removeProperty("scroll");
var f=k()?k().getWinDims():void 0;f||(f=GLANCE_SESSIONINFO.state.windims);var h=f.x+document.id("vscrollbar").offsetWidth;f=f.y+document.id("hscrollbar").offsetHeight;var p=Window.getSize();p.y-=t.getPosition().y;document.body.addClass("scaletofit");var u=Math.min(Math.min(p.x/h,p.y/f),1);t.setStyle("margin-left",(p.x-u*h)/2+"px");["transform","-webkit-transform"].forEach(function(r){t.setStyle(r,"scale(sf, sf)".replace(/sf/g,u))});(h=k())&&h.notifyScaleFactor(u)}}function x(f){var h=GLANCE.Lib.getDomain(f.origin)===
GLANCE.Lib.getDomain(window.location.hostname);if(GLANCE.Lib.isAllowedOrigin(f.origin,GLANCE_SESSIONINFO.chatdomains)||h){if(h=k())if(f.data.GlanceMessage)h.sendAgentMsg({ssnmessage:f.data.GlanceMessage});else if(f.data.GlanceAgentInvoke)h[f.data.GlanceAgentInvoke.func](f.data.GlanceAgentInvoke.args)}else GLANCE.Lib.log("Message from untrusted domain "+f.origin)}var l=document.id("glance-ssninfo");window.GLANCE_SESSIONINFO=JSON.parse(l.get("data-ssninfo"));var q,t;let z={},v=new GLANCE.Lib.EventListeners,
w=!1;window.addEvent("domready",function(){window.addEventListener("beforeunload",c);GLANCE_SESSIONINFO||GLANCE.Lib.log("data-ssninfo missing");let f=GLANCE_SESSIONINFO.agentconnect?"agent":GLANCE_SESSIONINFO.guestconnect?"guest":null;f?GLANCE_SESSIONINFO.ssnconnectinfo?g(f):d(f):(a(!1),GLANCE.Cobrowse.ViewerFrame.connected=!0,v.fire("connected"))});return{Viewer:function(){return k()},waitConnected:function(){return new Promise((f,h)=>{this.connected?f():this.addEventListener("connected",f)})},setWinDims:function(f){q.setStyles({width:f.x,
height:f.y});m()},zoom:function(f){GLANCE_SESSIONINFO.scaledview=!f;f?n():m()},updateState:function(f){Object.assign(z,f);Object.keys(f).forEach(h=>{v.fire(h,f[h])})},getState:function(f){return z[f]},addEventListener:function(f,h){v.add(f,h)},agentLeft:function(){return w}}}();
