/*
 Copyright 2022 Glance Networks, Inc.
*/
function aa(a,...c){!window.console||!window.console[a]||window.GLANCE_COBROWSE&&window.GLANCE_COBROWSE.disableLogging||(c=c.map(b=>{if("object"===typeof b)try{b=JSON.stringify(b)}catch(f){console.error(f),b="unable to convert object to string"}return"string"===typeof b?b.replace(/[\r\n]/g," ").replace("<","&lt;"):b}),window.console[a](...c))}function n(...a){aa("log",...a)}function q(...a){aa("error",...a)}function v(...a){n("VID:",...a)};/*
 Copyright (c) 2022 Glance Networks, Inc.
*/
var ba=ba||{};window.GLANCE=window.GLANCE||{};window.GLANCE.VERSION="6.3.1.0";window.GLANCE.PATCH="";window.GLANCE.Lib=window.GLANCE.Lib||{};
var w=function(){var a=navigator.userAgent.toLowerCase(),c=navigator.platform.toLowerCase(),b=a.match(/(edge)[\s\/:]([\w\d\.]+)?/)||a.match(/(opera|ie|firefox|chrome|crios|version)[\s\/:]([\w\d\.]+)?.*?(safari|version[\s\/:]([\w\d\.]+)|$)/)||a.match(/(rv):([\w\d\.]+)/)||[null,"unknown",0];"crios"===b[1]?b[1]="chrome":"rv"===b[1]&&(b[1]="ie");a={extend:Function.prototype.extend,name:"version"==b[1]?b[3]:b[1],version:"ie"==b[1]&&document.documentMode||parseFloat("opera"==b[1]&&b[4]?b[4]:b[2]),B:{name:a.match(/ip(?:ad|od|hone)/)||
c.match(/mac/)&&"undefined"!==typeof navigator.g?"ios":(a.match(/(?:webos|android)/)||c.match(/mac|win|linux/)||["other"])[0]},K:{V:!!document.evaluate,N:!!window.T,query:!!document.querySelector,json:!!window.JSON},L:{},R:function(){return"ios"==this.B.name||"android"==this.B.name}};document.documentMode&&window.XDomainRequest?(a.name="ie",a.version=document.documentMode):window.navigator&&navigator.appVersion&&-1!=navigator.appVersion.indexOf("MSIE 7.")&&(a.name="ie",a.version="7");a[a.name]=!0;
a[a.name+parseInt(a.version,10)]=!0;a.B[a.B.name]=!0;return a}();if(void 0===ea)var ea=function(a){return y.h&&y.g?y.g.window.JSON.stringify(a):JSON.stringify(a)};function fa(a,c){A(window,"setTimeout",function(){fa(a,c)},100)}
function C(a){var c=String(window.GLANCE_SESSIONINFO.ver).split("."),b=String(a).split(".");c.push([0,0,0,0]);b.push([0,0,0,0]);for(a=0;4>a;a++){isNaN(c[a])&&(c[a]=0);isNaN(b[a])&&(b[a]=0);if(Number(c[a])<Number(b[a]))return-1;if(Number(c[a])>Number(b[a]))return 1}return 0}function D(){ba.U?this.j=new E(void 0):this.g=new window.XMLHttpRequest;this.response=null;this.type=void 0}D.prototype.abort=function(){this.j?this.j.abort():this.g.abort()};
D.prototype.onreadystatechange=function(){if(4==this.g.readyState){A(window,"clearTimeout",this.u);delete this.u;var a="error";if(0==this.g.status)n(this.method+" to "+this.url+" failed: network"),this.l(!0,"connection",this.g.status);else if(200!==this.g.status){q(this.method+" to "+this.url+" failed with status: "+this.g.status);"text"===this.g.responseType&&null!==this.g.responseText&&n(this.g.responseText);if(401===this.g.status||403===this.g.status)a="authorization",this.h&&this.h.O();this.l(!1,
a,this.g.status)}else{if(""!==this.g.response){if("XML"===this.accept)this.response=this.g.responseXML&&this.g.responseXML.documentElement,null===this.response&&q("Invalid XML response: "+this.g.responseText);else if(this.F){for(var c=new Uint8Array(this.g.responseText.length),b=0;b<this.g.responseText.length;b++)c[b]=this.g.responseText.charCodeAt(b)&255;this.response=new Blob([c],{type:this.g.getResponseHeader("Content-Type")})}else if("blob"===this.g.responseType)this.response=this.g.response;
else if(this.g.responseXML)this.response=ha(this.g.responseXML.childNodes[0].childNodes[0].nodeValue);else if("HTML"===this.accept||"TEXT"===this.accept)this.response=this.g.responseText;else if(this.response=ha(this.g.responseText),null===this.response){n(this.method+" to "+this.url+" failed - can't parse response "+this.g.responseText);this.l(!1,a);return}if(void 0!==this.response.err&&void 0!==this.response.msg){n(this.method+" to "+this.url+" failed with error:"+this.response.err+" "+this.response.msg);
this.l(!1,a);return}}this.onsuccess(this.response)}}};function ha(a){var c=null;try{c=JSON.parse(a)}catch(b){return n("JSON parse failed with error: "+b.toString()+" parsing: "+a),null}return c}D.prototype.getResponseHeader=function(a){return this.g.getResponseHeader(a)};function ia(a){a.accept="HTML";a.o="text/html"}D.prototype.get=function(a,c,b,f,g){this.method="GET";ja(this,a,c,b,f,g)};
function ja(a,c,b,f,g,m){a.url=c;a.onsuccess=void 0!==g?g:function(){};a.l=void 0!==m?m:function(){};a.method=a.method||"POST";if(a.j)ka(a.j,c,b,f,g,m);else{g=a.G||("JSON"===a.type?"application/json; charset=utf-8":"application/x-www-form-urlencoded; charset=utf-8");w.safari&&a.C&&(a.u=A(window,"setTimeout",function(){n(this.method+" to "+this.url+" failed - timedout (Safari)");this.l(!1,"timedout")}.bind(a),a.C));a.g.onreadystatechange=function(){a.onreadystatechange()};try{a.g.open(a.method,c,b),
void 0!==a.o&&a.g.setRequestHeader("Accept",a.o),void 0!==a.g.setRequestHeader&&"GET"!==a.method&&a.g.setRequestHeader("Content-type",g),a.h&&a.h.I()?a.g.setRequestHeader("Authorization","Bearer "+a.h.I()):a.v&&a.g.setRequestHeader("Authorization","Bearer "+a.v),a.g.withCredentials=f,a.g.send(void 0)}catch(t){n(a.method+" to "+c+" failed with: "+t.toString()),a.l(!1,t.toString())}}}function E(a){this.type=a}
function ka(a,c,b,f,g,m){a.onsuccess=g;a.l=m;fa({from:"IFrameProxyRequest",type:a.type,url:c,obj:null,async:b,withcred:f})}E.prototype.abort=function(){E.postMessage({from:"IFrameProxyRequest",abort:!0})};function la(a){var c={};["url","name","visitorselected","agentselected"].forEach(b=>{a.hasOwnProperty(b)&&(c[b]=a[b])});return c}
function F(a){this.g=a.document;this.A=a;var c=[["hidden","visibilitychange"],["mozHidden","mozvisibilitychange"],["webkitHidden","webkitvisibilitychange"],["msHidden","msvisibilitychange"],["oHidden","ovisibilitychange"]];for(a=0;a<c.length&&!(c[a][0]in document);a++);}
function ma(a){var c=new RegExp(/^(?:[a-z]{1,5}:\/\/|)([^:\?\/]*)/),b=a.match(/^\d+\.\d+.\d+.\d+$/);c=c.exec(a);if(b)return a;if(null===c||2!==c.length)return"about:"!==a&&n("ERR_DOMAINPARSE: "+a),null;b=c[1].split(".");return 1===b.length?(n("ERR_DOMAINPARSE: "+a),null):2===b.length?b.join("."):3===b.length?b.slice(1).join("."):4>=b[b.length-2].length?b.slice(b.length-3).join("."):b.slice(b.length-2).join(".")}
function na(a,c){for(var b=new ArrayBuffer(a.length),f=new Uint8Array(b),g=0,m=a.length;g<m;g++)f[g]=a.charCodeAt(g);return new Blob([b],{type:c})}F.prototype.getElementsByTagName=function(a){return A(this.g,"getElementsByTagName",a)};async function G(a,c){return new Promise((b,f)=>{var g=a.g.createElement("script");g.onload=b;g.onerror=f;for(const m in c)g.setAttribute(m,c[m]);g.setAttribute("charset","UTF-8");a.g.head.appendChild(g)})}function K(a){return A(a.g,"getElementById","viewer-css")}
F.prototype.head=function(){return void 0!==this.g.head?this.g.head:this.getElementsByTagName("head")[0]};function oa(a,c){a.A.addEventListener&&(document.readyState.match(/complete/)?c():(a.A.addEventListener("load",c),a.g.addEventListener("DOMContentLoaded",c,!1)))}
function pa(a){if(void 0!==window.pageXOffset)return{x:Math.round(a.A.pageXOffset),y:Math.round(a.A.pageYOffset)};if(void 0!==document.documentElement.scrollTop)return{x:a.g.documentElement.scrollLeft,y:a.g.documentElement.scrollTop};if(void 0!==document.body.scrollLeft)return{x:a.g.body.scrollLeft,y:a.g.body.scrollTop};throw Error("Can't get page scroll");}
F.prototype.scrollTo=function(a,c,b){var f=pa(this);f[a]=c;a={left:f.x,top:f.y,behavior:b?"smooth":"auto"};w.ie11||w.edge?window.scrollTo(f.x,f.y):window.scrollTo(a);pa(this)};F.prototype.addEventListener=function(a,c,b){A(this.g,"addEventListener",a,c,b)};F.prototype.removeEventListener=function(a,c,b){A(this.g,"removeEventListener",a,c,b)};function y(a){this.g=a}y.prototype.addEventListener=function(a,c,b){A(this.g,"addEventListener",c,b)};
y.prototype.removeEventListener=function(a,c,b){A(this.g,"removeEventListener",c,b)};function A(a,c,...b){return y.h&&y.g&&a.nodeType?"#document"===a.nodeName?y.g.document[c].apply(a,b):"#document-fragment"===a.nodeName?y.g.DocumentFragment.prototype[c].apply(a,b):y.g.document.body[c].apply(a,b):y.h&&y.g&&"[object Window]"===a.toString()?y.g.window[c].apply(a,b):a[c].apply(a,b)}y.prototype.remove=function(){this.g.parentNode&&this.g.parentNode.removeChild(this.g)};
function qa(a,c,b){a.g.style.left=c+"px";a.g.style.top=b+"px"}y.prototype.moveTo=function(a,c){function b(){10>t++?(g+=l,m+=B,qa(f,Math.floor(g),Math.floor(m)),f.h=A(window,"setTimeout",b,20)):qa(f,a,c)}void 0!==this.h&&A(window,"clearTimeout",this.h);var f=this,g=parseInt(this.g.style.left),m=parseInt(this.g.style.top);isNaN(g)&&(g=-999);isNaN(m)&&(m=-999);var t=0,l=(a-g)/10,B=(c-m)/10;0===l&&0===B||b()};function ra(){this.g={}}
function sa(a,c){var b=c.messageName;delete c.messageName;Object.keys(a.g).forEach(function(f){if((new RegExp(f)).test(b))a.g[f](b,c)})}function L(){this.listeners=this.g={}}L.prototype.add=function(a,c){this.g[a]=this.g[a]||[];this.g[a].push(c)};L.prototype.remove=function(a,c){a=this.g[a];void 0!==a&&(c=a.indexOf(c),0<=c&&a.splice(c,1))};function M(a,c){if(void 0!==a){var b=b||Object.keys(a);b.forEach(function(f){void 0!==a[f]&&(c[f]=a[f])})}}function ta(a){var c={};if(!a)return c;var b=0;for(a=a.attributes;b<a.length;b++){var f=a[b].nodeName.match(/data-(.*)/);f&&2===f.length&&(c[f[1]]=a[b].nodeValue)}return c}function ua(){var a=window.GLANCE_COBROWSE?window.GLANCE_COBROWSE:{},c=document.getElementById("cobrowsescript"),b=document.getElementById("glance-cobrowse");c=ta(c);b=ta(b);M(c,a);M(b,a);return a};function S(a,c,b,f){this.h=a;this.D=c;this.u=b;this.j=f;this.v=!!f}function U(a){var c;(null==(c=a.i)?0:c.contentWindow)&&(c=a.i.contentWindow.GPDF)&&c.Close();a.g&&a.i.remove();a.g=null}function Da(a,c){a.url=c.url;a.data=c.data;U(a);Ea(a,"XLS",c,()=>{let b=f=>{new a.g.A.XLSViewer({data:f,downloadURL:a.url,options:c.options})};a.url?Fa(a,a.url).then(f=>{b(f)}).catch(f=>{b({error:f})}):a.data&&b(a.data)})}
function Ga(a,c){U(a);Ea(a,"PDF",c,function(){var b=Object.assign(c,{mode:w.ie?"canvas":this.D.info.pdfmode||"canvas"});const f=this.i.contentWindow.GPDF;f.waitready.then(function(){f.View(b)})})}
function Ea(a,c,b,f){a.C=f;a.o=b.preview;a.j||(a.j=document.createElement("div"),document.body.appendChild(a.j));a.i=a.j.querySelector("#glance_"+c.toLowerCase()+"viewer");a.i||(a.i=document.createElement("iframe"),a.i.id="glance_"+c.toLowerCase()+"viewer",a.i.title="Glance "+c+" Viewer",a.j.appendChild(a.i));a.i.removeAttribute("data-agentinteractive");a.o&&(a.i.style.width="100%",a.i.style.height="99%");var g="PDF"===c?a.F:a.G;Ha(a,c,async m=>{a.i.contentDocument.documentElement.innerHTML=m;a.g=
new F(a.i.contentWindow);oa(a.g,async()=>{if(b.showdl&&b.data&&a.D.info.docsharevisitordl&&"true"===b.download){let l=a.i.contentDocument.getElementById("glance_dl");var t=na(b.data,b.showdl);l.href=window.URL.createObjectURL(t);l.download=b.name;l.style.display="inline-block";l.onclick=()=>{a.u.fireEvent("visitordownload",la(b))}}b.agentselected&&"closedoc nextTab prevtab pageselect zoomselect zoomout zoomin floating-button-next floating-button-previous pdf-find-button pdf-find-previous pdf-find-next pdf-find-close pdf-find-input".split(" ").forEach(l=>
{(l=a.i.contentDocument.getElementById(l))&&l.setAttribute("data-agentinteractive","remote")});if(!a.o&&!a.v){a.u.fireEvent("documentviewed",la(b));a.i.contentDocument.querySelector(".firstcontrol").addEventListener("keydown",function(l){"Tab"===l.key&&l.shiftKey&&l.preventDefault()});a.i.contentDocument.querySelector(".lastcontrol").addEventListener("keydown",function(l){"Tab"!==l.key||l.shiftKey||l.preventDefault()});if("large"===a.u.P()){window.GLANCE.Cobrowse.Visitor.smallVideo();let l=B=>{"docviewerclosed"===
B.data&&(window.GLANCE.Cobrowse.Visitor.largeVideo(),window.removeEventListener("message",l))};window.addEventListener("message",l)}window.addEventListener("message",l=>{"docviewerclosed"===l.data&&(U(a),a.v||a.u.M({docshare:{enabled:!1}}))})}a.v||await G(a.g,{id:"glance-cobrowse","data-groupid":a.D.groupId(),"data-ws":a.h.H,src:a.h.s.getAttribute("src")});g.bind(a)()})},a.l.bind(a))}
async function Fa(a,c){var b=await A(window,"fetch",c),f=await b.blob();return new Promise((g,m)=>{b.ok||m(b);var t=new FileReader;t.addEventListener("load",function(){g(t.result)},!1);t.onerror=()=>{m(a)};t.readAsBinaryString(f)})}function Ha(a,c,b,f){a=V(a.h,"styles/"+c+"Viewer_"+W+".html");c=new D;ia(c);c.get(a,!0,!1,function(g){b&&b(g)},f)}
S.prototype.G=async function(){if(this.o){var a=this.i.contentDocument;a.getElementById("closedoc").style.display="none";a.getElementById("xlslink").style.display="none";a.getElementById("tabname").style.display="none";a.getElementById("the-page").classList+="glance_masked"}K(this.g).href=V(this.h,"styles/XLSViewer_"+W+".css");await G(this.g,{src:V(this.h,"js/xlsx.full.min.js"),type:"text/javascript"});await G(this.g,{src:V(this.h,"js/XLSViewer_"+Ia+".js"),type:"text/javascript"});this.C()};
S.prototype.F=async function(){if(this.o){var a=this.i.contentDocument;a.getElementById("closedoc").style.display="none";a.getElementById("the-page").classList+="glance_masked"}K(this.g);K(this.g).href=V(this.h,"styles/PDFViewer_"+W+".css");await G(this.g,{src:V(this.h,"js/jquery-3.6.0.min.js"),type:"text/javascript"});await G(this.g,{src:V(this.h,"js/pdfjs2.16/pdf.js"),type:"text/javascript"});await G(this.g,{src:V(this.h,"js/pdfjs2.16/pdf.worker.js"),type:"text/javascript"});await G(this.g,{src:V(this.h,
"js/PDFViewer_"+Ia+".js"),type:"text/javascript"});this.C()};S.prototype.l=function(){};window.GLANCE.DocumentViewer=S;var W=["6","3","1","0"].slice(0,3).join("."),Ia=W+"M";
function Ja(){this.s=document.getElementById("cobrowsescript")||document.getElementById("glance-cobrowse");document.getElementById("glance-cobrowse");if(null!==this.s){var a=ua();M(a,this);var c=RegExp("//(.*)/").exec("string"===typeof this.s.src?this.s.src:a.scriptserver+"/");this.g=c&&2===c.length?c[1]:"www.glancecdn.net/cobrowse";this.g=this.g.replace("/js","");a.cbexperiment&&(this.g=this.g.replace("cobrowse","cbexperiment"));this.l=a.groupid||this.s.getAttribute("groupid");this.H=a.ws||this.s.getAttribute("ws")||
"www.glance.net";this.H.match("\\.glance\\.net$");this.uri=a.uri;this.o=a.site||this.s.getAttribute("site")||"production";JSON.parse(a.inputevents||"{}");if(!this.l)throw Error("data-groupid missing");a=a.additionalgroupids||"";this.j=[this.l].concat(a?a.split(","):[]);this.j=this.j.map(function(b){if(!parseInt(b))throw Error("data-groupid invalid: "+b);return parseInt(b)});if(!/staging|production/i.test(this.o))throw Error("data-site invalid");}}Ja.prototype.ready=function(){return null!==this.s};
function V(a,c){if(URL.toString().includes("[native code]"))a=(new URL(`https://${a.g}/${c}`)).href;else{c=[`https://${a.g}/${c}`];if(!a.h){let b=document.createElement("iframe");b.style.display="none";b.setAttribute("data-no-cobrowse-content",1);document.body.appendChild(b);a.h=b.contentWindow}a=a.h.URL;a=(new (Function.bind.apply(a,[a,...c]))).href}return a}function Ka(a,c){return"original"!==(c||"original")?`glance_video_${a}`:"glance_agentvideo"};function X(a,c,b){c={mtype:c,data:b};c.num=a.h;c.ssnid=a.j;fetch(`${a.l}/agent/message`,{method:"POST",mode:"cors",cache:"no-cache",credentials:"include",headers:{"Content-Type":"application/json"},redirect:"error",referrerPolicy:"no-referrer",body:JSON.stringify(c)}).catch(()=>{q("CobrowseConnection fetch failed")})}class La{constructor(a,c,b){this.j=c;this.h=b;this.l=a}}function Y(a,c){let b={};b["ssagent-"+a.g]=c;v("Cobrowse Agent sending video state:",b);X(a,"AgentData",b)}
function Ma(a,c){var b;if(b=c.offerurl){b=c.offerurl;var f=c.playerscaling;f=f||"clip";if(URL.toString().includes("[native code]"))var g=(new URL(b)).hostname;else g=y.g.window.URL,g=(new (Function.bind.apply(g,[g,b]))).hostname;b=`https://${g}/viv/VideoPlayer.html?offer=${b}&scaling=${f}&noendpage=1&guestid={guestid}&conntype={role}`}b&&0>C("5.1.1")&&(b=b.replace("{guestid}",0),b=b.replace("{role}",""));v("addVideoSession",c,"joinurl",b);a.m={view:a.g,agentnum:a.h,ssnid:c.offerurl,joinurl:b,params:{type:"forward"},
paused:c.paused,error:c.error,browserbased:!0};Y(a,a.m)}function Na(a){v("closeAgentVideo");Y(a,{ssnid:null,joinurl:null})}function Oa(a){v("agentVideoError");a.m.error=!0;0<=C("5.0.0")&&Y(a,a.m)}function Z(a){return a.m.paused}function Pa(a,c){Z(a)||(a.m.paused=!0,v("pauseAgentVideo:",a.g),c||Y(a,a.m))}class Qa extends La{constructor(a,c,b,f){super(a,c,b);this.g=f;this.m={}}};window.GLANCE=window.GLANCE||{};window.GLANCE.Cobrowse=window.GLANCE.Cobrowse||{};
window.GLANCE.Cobrowse.Agent=function(){function a(){function d(h){e++;let p=x.Viewer();p&&p.ready()?(n("DEBUG:",...["getCobrowseViewer: viewer ready"]),h(p)):(1===e%10&&n("DEBUG:",...["getCobrowseViewer: viewer not ready"]),window.setTimeout(()=>d(h),200))}let e=0;return new Promise(h=>{d(h)})}function c(d,e){null===H?a().then(h=>{h[d](e)}):H.postMessage({GlanceAgentInvoke:{func:d,args:e}},"*")}function b(d,e){va[d]=e;a().then(h=>{h.setStateAttribute(d,e)})}function f(d){var e=d.origin,h=e;e=e.split("?");
1<e.length&&(h=e[0]);h=(new RegExp(/(?:.*?:\/\/){0,1}([^\/:]+)/)).exec(h);ma(null===h||2>h.length||0>h[1].indexOf(".")?null:h[1]).match(new RegExp("^("+wa+"|glance.net|myglance.net)$","i"))&&(d.data.GlanceMessage?sa(N,d.data.GlanceMessage):d.data.GlanceEvent&&g(d.data.GlanceEvent.name,d.data.GlanceEvent.event))}function g(d,e){try{var h=ca;e&&JSON.stringify(e);var p,I=h.g[d];if(void 0!==I)for(p=0;p<I.length;p++)I[p](e)}catch(O){q("Exception ")}P[d]=e}function m(){k.pause();Pa(u.g);b("data-videostate",
"paused")}function t(){if(k){var d=!k.getBackgroundSettings().active;d&&xa?v("Cannot turn on background filtering due to filter performance failure"):(k.setBgFilterActive(d),b("data-videobgblur",d?"true":"false"))}}async function l(d){var e=d.options||{};e.sessionkey=e.sessionkey||d.key||d.sessionKey;e.maincallid=e.maincallid||window.GLANCE_SESSIONINFO.maincid;e.guestid=e.guestid||window.GLANCE_SESSIONINFO.guestid;e.role=e.role||window.GLANCE_SESSIONINFO.role;e.vserver=e.vserver||d.vserver||window.GLANCE_SESSIONINFO.videoserver||
"https://video.glance.net/";e.vserver.startsWith("https://")||(e.vserver="https://"+e.vserver);e.vserver.endsWith("/")||(e.vserver+="/");e.groupid=window.GLANCE_SESSIONINFO.groupid;e.personid=window.GLANCE_SESSIONINFO.personid;d.bgfilter=!!d.bgfilter;var h=d.source||null;v("Initializing agent video with options:",e);k=new ya(e);let p=window.GLANCE_SESSIONINFO;await x.waitConnected();u=new za("video",k,Ka(p.num,p.widget));return new Promise(function(I,O){k.addEventListener("error",function(r,Q){console.error("video error: "+
(r.statusText||r.toString())+" ("+(r.status||r.code)+") on "+Q.vserver,r,Q);O?O(r):g("video",{state:"error",error:r});b("data-videostate","error");Oa(u.g)});k.addEventListener("bgFilterPerformanceFail",()=>{g("videobgfilterfailed",{failuremode:d.bgfailuremode,performancefail:!0});b("data-videobgblurtoggle","false");xa=!0;switch(d.bgfailuremode){case "abortvideo":b("data-videostate","blocked");Oa(u.g);Aa();break;case "abortbgfilter":m(),t()}});k.addEventListener("initialized",function(){v("video initialized");
g("video",{state:"initialized"});J=!0;b("data-videobgblurtoggle","agent"!==window.GLANCE_SESSIONINFO.role&&window.GLANCE_SESSIONINFO.videobgblurtoggle&&k.getBackgroundSettings().capable);if(e.bgFilterEnabled&&!k.getBackgroundSettings().capable)switch(g("videobgfilterfailed",{failuremode:d.bgfailuremode}),d.bgfailuremode){case "abortvideo":b("data-videostate","error");Oa(u.g);return;case "abortbgfilter":b("data-videostate","paused"),d.bgfilter=!1,d.bgfilteron=!1}v("Starting video session, paused:",
d.paused,"background filter:",d.bgfilteron);k.startSession(d.paused,d.bgfilteron);b("data-videobgblur",d.bgfilter);let r=x.Viewer();r&&r.setVideoPreviewElement()});k.addEventListener("previewStarted",function(){v("video preview started");g("video",{state:"previewStarted"})});k.addEventListener("sessionStarted",function(r){v("Agent video started "+e.sessionkey,r);g("video",{state:"sessionStarted",options:e});O=void 0;I({key:e.sessionkey,ssnParams:d.ssnParams,agentparams:d.agentparams,offerurl:r.descriptor.url});
k.setAccepterCount(x.getState("agents").count);x.addEventListener("agents",Q=>{k&&k.setAccepterCount(Q.count)})});k.addEventListener("guestCountChanged",function(r){v("video guest connected");g("video",{state:"guestCountChanged",count:r})});k.addEventListener("sessionEnded",function(){v("video ended");u&&Na(u.g);g("video",{state:"sessionEnded"})});k.initialize(h,null,d.paused)})}function B(d){R=d=d||R;v("agentVideoStart",d);["nocamera","notsupported"].includes(d.camerastatus)?b("data-videostate",
"blocked"):(ya?window.GLANCE.Video.GlanceVideoSource.isAgentVideoCapable():Promise.reject("GLANCE.Video.GlanceVideoSource not defined")).catch(function(e){g("video",{state:"notEnabled",reason:e})}).then(()=>l(d)).then(function(e){v("Video started, adding to session");Ma(u.g,{offerurl:e.offerurl,playerscaling:"clip",paused:d.paused,error:!1});b("data-videostate",d.paused?"paused":"on")}).catch(function(e){Ma(u.g,{offerurl:null,paused:d.paused,error:!0});g("video",{state:"error",error:e});b("data-videostate",
"error")})}function Aa(){k&&(k.endSession(),k=null,Na(u.g),u=null,J=!1)}async function Ra(d,e){v("Adding browser based screenshare to session",d);await x.waitConnected();z=new za("screenshare",e,"glance_screenshare");Ma(z.g,{offerurl:d,playerscaling:"box",paused:!1,error:!1});b("data-screenshare","on");c("addScreenshare",{screenshareView:"glance_screenshare",browserbased:!0})}var H=null,N=new ra,wa,ca=new L,P={},x=window.GLANCE.Cobrowse.ViewerFrame,da,ya=window.GLANCE.Video&&window.GLANCE.Video.GlanceVideoSource,
k=null,J=!1,xa=!1,R=null,Ba=null,u=null,z=null;let va={};class za{constructor(d,e,h){this.o=e;this.j=h;this.h=null;d=window.GLANCE_SESSIONINFO;this.g=new Qa(d.server,d.ssnid,d.num,this.j)}l(d){this.h!==d&&(this.h=d,this.h.srcObject||(v(`Starting ${this.j} preview at:`,this.h),this.o.startPreview(this.h,Z(this.g))))}}var Ca={_dispatch:function(d){sa(N,d)},_fire:function(d,e){g(d,e)},init:function(d,e){x||(wa=e||"glance.net",H=d.contentWindow,window.addEventListener("message",f))},visitorVerAtLeast:function(d){return 0<=
C(d)},agentVideoStart:function(d){B(d)},agentVideoEnd:function(){Aa()},toggleAgentVideo:function(){let d=u.g;d.m.error?B():(Z(d)?k.unPause():k.pause(),d.m.paused=!d.m.paused,v("toggleAgentVideo",d.m.paused?"off":"on"),Y(d,d.m),g("videopaused",{paused:Z(d)}),b("data-videostate",Z(d)?"paused":"on"))},pauseAgentVideo:m,toggleAgentVideoBackgroundFilter:t,setAgentVideoSource:function(d){k.setSource(d)},updateAgentVideoOptions:function(d){v("Updating agent video options",d);J&&k.updateVideoOptions(d);R&&
(R.options=d)},addAgentScreenshare:function(d,e){Ra(d,e)},getScreensharePreviewElem:function(){return Ba},pauseAgentScreenshare:function(d){z&&(Pa(z.g,d),b("data-screenshare","paused"))},unPauseAgentScreenshare:function(){if(z){var d=z.g;Z(d)&&(d.m.paused=!1,v("unPauseAgentVideo:",d.g),Y(d,d.m));b("data-screenshare","on");c("addScreenshare",{screenshareView:"glance_screenshare",browserbased:!0})}},sendSessionMessage:function(d,e){let h=Ka(window.GLANCE_SESSIONINFO.num,window.GLANCE_SESSIONINFO.widget);
switch(d){case "agentVideoStart":this.addScreenshare({screenshareView:h,key:e.key,ssnParams:{type:"forward",video:"1"}});break;case "agentVideoEnd":this.closeScreenshare({screenshareView:h});break;case "agentVideoPause":this.pauseScreenshare({screenshareView:h});break;case "agentVideoResume":this.resumeScreenshare({screenshareView:h})}e.messageName=d;null===H?(d=x.Viewer())?d.sendAgentMsg({ssnmessage:e}):console.warn("no viewer in sendSessionMessage",e):H.postMessage({GlanceMessage:e},"*")},addSessionMessageHandler:function(d,
e){N.g["^"+d+"$"]=e},addSessionMessageListener:function(d,e){N.g["^"+d+"$"]=e},addEventListener:function(d,e){ca.add(d,e)},removeEventListener:function(d,e){ca.remove(d,e)},getSessionState:function(d){return P[d]},getUserState:function(d){return P.J?P.J[d]:void 0},leaveSession:function(d){c("leaveSession",{url:d})},agentVideoRunning:function(){return J},setVideoPreviewElement:function(d){u&&J?u.l(d):console.error("agent video should be initialized before this is called")},setScreensharePreviewElement:function(d){Ba=
d;z&&z.l(d)},requestVisitorVideo:function(d){v("Requesting visitor video, on:",d);let e={};e.requestvisitorvideo=d;X(da,"AgentMsg",e)},getViewerStateAttributes:function(){return va},setVideoSize:function(d){X(da,"AgentMsg",{videosize:{size:d}})},showDocumentPreview:(d,e,h)=>{if(!document.querySelector("meta#glance-cobrowse")){var p=document.createElement("meta");p.id="glance-cobrowse";p.setAttribute("data-scriptserver","https://"+window.GLANCE_SESSIONINFO.scriptserver+"/cobrowse");p.setAttribute("data-groupid",
window.GLANCE_SESSIONINFO.groupid);document.getElementsByTagName("head")[0].appendChild(p)}p=new Ja;h=new S(p,{groupId:()=>window.GLANCE_SESSIONINFO.groupid,info:{S:"canvas"}},null,h);switch(d){case "PDF":Ga(h,{data:e,preview:!0});break;case "XLS":Da(h,{data:e,preview:!0})}}};"addScreenshare closeScreenshare pauseScreenshare resumeScreenshare requestScreenshare stopVisitorsScreenshare requestRC requestCE requestDocShare navigationAssist agentDownloaded enableAccessibility accessibilityEnabled enableAgentAccessibility navigate".split(" ").forEach(function(d){Ca[d]=
function(e){c(d,e)}});x&&x.waitConnected().then(()=>{let d=window.GLANCE_SESSIONINFO;da=new La(d.server,d.ssnid,d.num)});return Ca}();
