(function() {/*
 Copyright 2022 Glance Networks, Inc.
*/
function h(a,...c){!window.console||!window.console[a]||window.GLANCE_COBROWSE&&window.GLANCE_COBROWSE.disableLogging||(c=c.map(b=>{if("object"===typeof b)try{b=JSON.stringify(b)}catch(f){console.error(f),b="unable to convert object to string"}return"string"===typeof b?b.replace(/[\r\n]/g," ").replace("<","&lt;"):b}),window.console[a](...c))}function n(...a){h("log",...a)}function v(...a){n("DEBUG:",...a)};/*
 Copyright (c) 2022 Glance Networks, Inc.
*/
window.GLANCE=window.GLANCE||{};window.GLANCE.VERSION="6.3.0.21";window.GLANCE.PATCH="";window.GLANCE.Lib=window.GLANCE.Lib||{};
var w=function(){var a=navigator.userAgent.toLowerCase(),c=navigator.platform.toLowerCase(),b=a.match(/(edge)[\s\/:]([\w\d\.]+)?/)||a.match(/(opera|ie|firefox|chrome|crios|version)[\s\/:]([\w\d\.]+)?.*?(safari|version[\s\/:]([\w\d\.]+)|$)/)||a.match(/(rv):([\w\d\.]+)/)||[null,"unknown",0];"crios"===b[1]?b[1]="chrome":"rv"===b[1]&&(b[1]="ie");a={extend:Function.prototype.extend,name:"version"==b[1]?b[3]:b[1],version:"ie"==b[1]&&document.documentMode||parseFloat("opera"==b[1]&&b[4]?b[4]:b[2]),l:{name:a.match(/ip(?:ad|od|hone)/)||
c.match(/mac/)&&"undefined"!==typeof navigator.g?"ios":(a.match(/(?:webos|android)/)||c.match(/mac|win|linux/)||["other"])[0]},H:{M:!!document.evaluate,J:!!window.L,query:!!document.querySelector,json:!!window.JSON},I:{},K:function(){return"ios"==this.l.name||"android"==this.l.name}};document.documentMode&&window.XDomainRequest?(a.name="ie",a.version=document.documentMode):window.navigator&&navigator.appVersion&&-1!=navigator.appVersion.indexOf("MSIE 7.")&&(a.name="ie",a.version="7");a[a.name]=!0;
a[a.name+parseInt(a.version,10)]=!0;a.l[a.l.name]=!0;return a}();if(void 0===ba)var ba=function(a){return y.h&&y.g?y.g.window.JSON.stringify(a):JSON.stringify(a)};function D(a,c,b){E(window,"addEventListener",a,c,b)}function F(a,c,b){var f={};f[c]=b;a.postMessage(f,"*")}function G(a,c){E(window,"addEventListener","message",function(b){if("string"===typeof b.data)try{var f=JSON.parse(b.data)}catch(g){return!1}else f=b.data;void 0!==f[a]&&c(b.source,f[a])})}
function H(){this.name="glance_ssn_info";var a=new J,c=a.h.location.hostname;for(a=a.h;""===c&&a.parent!==a;)c=a.parent.location.hostname,a=a.parent;this.domain=ca(c)}H.prototype.get=function(){return this.i()?unescape(document.cookie.replace(new RegExp("(?:^|.*;\\s*)"+escape(this.name).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=\\s*((?:[^;](?!;))*[^;]?).*"),"$1")):null};
H.prototype.j=function(){var a=new Date;a.setDate(a.getDate()-1);document.cookie=escape(this.name)+"=; expires="+a.toGMTString()+"; domain="+this.domain+"; path=/"};H.prototype.i=function(){return(new RegExp("(?:^|;\\s*)"+escape(this.name).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=")).test(document.cookie)};function K(){this.name="glance_ssn_info"}K.prototype.get=function(){return this.i()?localStorage.getItem(this.name):null};
K.prototype.j=function(){localStorage.removeItem(this.name);localStorage.removeItem(this.name+"_exp")};K.prototype.i=function(){var a=localStorage.getItem(this.name+"_exp");if(!a)return!1;a=new Date(a);return a<new Date?(this.j(),!1):!0};function O(){this.g=[new H,new K]}O.prototype.get=function(){return this.g[0].get()||this.g[1].get()};O.prototype.j=function(){this.g[0].j();this.g[1].j()};O.prototype.i=function(){return this.g[0].i()||this.g[1].i()};
function J(){var a=window;this.g=a.document;this.h=a;var c=[["hidden","visibilitychange"],["mozHidden","mozvisibilitychange"],["webkitHidden","webkitvisibilitychange"],["msHidden","msvisibilitychange"],["oHidden","ovisibilitychange"]];for(a=0;a<c.length&&!(c[a][0]in document);a++);}
function ca(a){var c=new RegExp(/^(?:[a-z]{1,5}:\/\/|)([^:\?\/]*)/),b=a.match(/^\d+\.\d+.\d+.\d+$/);c=c.exec(a);if(b)return a;if(null===c||2!==c.length)return"about:"!==a&&n("ERR_DOMAINPARSE: "+a),null;b=c[1].split(".");return 1===b.length?(n("ERR_DOMAINPARSE: "+a),null):2===b.length?b.join("."):3===b.length?b.slice(1).join("."):4>=b[b.length-2].length?b.slice(b.length-3).join("."):b.slice(b.length-2).join(".")}J.prototype.getElementsByTagName=function(a){return E(this.g,"getElementsByTagName",a)};
function P(a,c,b,f){var g=a.g.createElement("script");b&&g.addEventListener("load",b);f&&g.addEventListener("error",f);g.setAttribute("type","text/javascript");g.setAttribute("charset","UTF-8");for(b=0;b<c.length;b++)g.setAttribute(c[b][0],c[b][1]);a.g.head.appendChild(g)}J.prototype.head=function(){return void 0!==this.g.head?this.g.head:this.getElementsByTagName("head")[0]};
function Q(a,c){a.h.addEventListener&&(document.readyState.match(/complete/)?c():(a.h.addEventListener("load",c),a.g.addEventListener("DOMContentLoaded",c,!1)))}
function R(a){if(void 0!==window.pageXOffset)return{x:Math.round(a.h.pageXOffset),y:Math.round(a.h.pageYOffset)};if(void 0!==document.documentElement.scrollTop)return{x:a.g.documentElement.scrollLeft,y:a.g.documentElement.scrollTop};if(void 0!==document.body.scrollLeft)return{x:a.g.body.scrollLeft,y:a.g.body.scrollTop};throw Error("Can't get page scroll");}
J.prototype.scrollTo=function(a,c,b){var f=R(this);f[a]=c;a={left:f.x,top:f.y,behavior:b?"smooth":"auto"};w.ie11||w.edge?window.scrollTo(f.x,f.y):window.scrollTo(a);R(this)};J.prototype.addEventListener=function(a,c,b){E(this.g,"addEventListener",a,c,b)};J.prototype.removeEventListener=function(a,c,b){E(this.g,"removeEventListener",a,c,b)};function y(a){this.g=a}y.prototype.addEventListener=function(a,c,b){E(this.g,"addEventListener",c,b)};
y.prototype.removeEventListener=function(a,c,b){E(this.g,"removeEventListener",c,b)};function E(a,c,...b){return y.h&&y.g&&a.nodeType?"#document"===a.nodeName?y.g.document[c].apply(a,b):"#document-fragment"===a.nodeName?y.g.DocumentFragment.prototype[c].apply(a,b):y.g.document.body[c].apply(a,b):y.h&&y.g&&"[object Window]"===a.toString()?y.g.window[c].apply(a,b):a[c].apply(a,b)}function S(a,c,b){a.g.style.left=c+"px";a.g.style.top=b+"px"}
y.prototype.moveTo=function(a,c){function b(){10>t++?(g+=p,k+=z,S(f,Math.floor(g),Math.floor(k)),f.h=E(window,"setTimeout",b,20)):S(f,a,c)}void 0!==this.h&&E(window,"clearTimeout",this.h);var f=this,g=parseInt(this.g.style.left),k=parseInt(this.g.style.top);isNaN(g)&&(g=-999);isNaN(k)&&(k=-999);var t=0,p=(a-g)/10,z=(c-k)/10;0===p&&0===z||b()};function T(){this.listeners=this.g={}}T.prototype.add=function(a,c){this.g[a]=this.g[a]||[];this.g[a].push(c)};
function U(a,c){c&&JSON.stringify(c);var b=a.g.error;if(void 0!==b)for(a=0;a<b.length;a++)b[a](c)};function V(a,c){if(void 0!==a){var b=b||Object.keys(a);b.forEach(function(f){void 0!==a[f]&&(c[f]=a[f])})}}function W(a){var c={};if(!a)return c;var b=0;for(a=a.attributes;b<a.length;b++){var f=a[b].nodeName.match(/data-(.*)/);f&&2===f.length&&(c[f[1]]=a[b].nodeValue)}return c}function da(){var a=window.GLANCE_COBROWSE?window.GLANCE_COBROWSE:{},c=document.getElementById("cobrowsescript"),b=document.getElementById("glance-cobrowse");c=W(c);b=W(b);V(c,a);V(b,a);return a};var ea=["6","3","0","21"].slice(0,3).join(".")+"M";
function fa(){this.h=document.getElementById("cobrowsescript")||document.getElementById("glance-cobrowse");document.getElementById("glance-cobrowse");if(null!==this.h){var a=da();V(a,this);var c=RegExp("//(.*)/").exec("string"===typeof this.h.src?this.h.src:a.scriptserver+"/");this.g=c&&2===c.length?c[1]:"www.glancecdn.net/cobrowse";this.g=this.g.replace("/js","");a.cbexperiment&&(this.g=this.g.replace("cobrowse","cbexperiment"));this.m=a.groupid||this.h.getAttribute("groupid");this.G=a.ws||this.h.getAttribute("ws")||
"www.glance.net";this.G.match("\\.glance\\.net$");this.F=a.ui;this.uri=a.uri;this.C=a.site||this.h.getAttribute("site")||"production";this.v=JSON.parse(a.inputevents||"{}");this.A=a.presence;if(!this.m)throw Error("data-groupid missing");a=a.additionalgroupids||"";this.o=[this.m].concat(a?a.split(","):[]);this.o=this.o.map(function(b){if(!parseInt(b))throw Error("data-groupid invalid: "+b);return parseInt(b)});if(!/staging|production/i.test(this.C))throw Error("data-site invalid");}};function X(){return 0<window.location.href.indexOf("GlanceSession=1")};window.GLANCE=window.GLANCE||{};window.GLANCE.Cobrowse=window.GLANCE.Cobrowse||{};
function Y(){function a(d){function e(r,A,I){return function(B){B.keyCode===A&&B[r+"Key"]&&(B=I.match(/showButton|toggleButton|showTerms/)?"VisitorUI":"Visitor",g(B,I)||(v("inputevent:",I),window.GLANCE.Cobrowse[B][I]()))}}for(var l in d)if(d.hasOwnProperty(l)){var m=l.match(/(ctrl|alt|shift)-(\d*)/);!m||3>m.length||D("keydown",e(m[1],parseInt(m[2]),d[l]),!0)}}function c(d){function e(l){return function(m){var r=l.match(/showButton|toggleButton|showTerms/)?"VisitorUI":"Visitor";m.stopPropagation();
m.preventDefault();g(r,l)||(v("button click",r,l),u[r][l]())}}["glance_button","data-glancebutton"].forEach(function(l){for(var m=d.querySelectorAll("["+l+"]"),r=0;m&&r<m.length;r++){var A=m[r].getAttribute(l);"start"===A&&(A="startSession");m[r].addEventListener("click",e(A))}})}function b(){return u.Visitor}function f(d,e){u[e][d]=function(l){d.match(/showButton|toggleButton|showTerms/)&&"Visitor"==e&&(e="VisitorUI");k(function(){u[e][d](l)},e)}}function g(d,e){if(!t)return!1;v("forward event:",
d,e);F(window.top,"forwardevent",{namespace:d,funcname:e});return!0}function k(d,e){e=e||"Visitor";if(E(p.g,"getElementById",("glance_"+e).toLowerCase()))u[e].loaded?d&&d():d&&(n("SCRIPT_NOT_LOADED:"+e),U(C,{B:"SCRIPT_NOT_LOADED:"+e,code:"scriptloadfailed",D:{script:e}}));else if(d&&(Z._onload[e]=d),t||"Visitor"!==e||x.F||k(null,"VisitorUI"),P(p,[["id",("glance_"+e).toLowerCase()],["src",M+"/GlanceCobrowse"+e+"_"+N+".js"]]),"Visitor"===e)for(e=document.getElementsByTagName("iframe"),d=0;d<e.length;d++)e[d].contentWindow&&
F(e[d].contentWindow,"glance_load",{s:!0})}window.GLANCE.runTroubleshooter=function(){P(p,[["src","https://"+x.g+"/js/Troubleshooter.js"]])};window.GLANCE.checkHTML=function(){P(p,[["src","https://"+x.g+"/js/HTMLChecker.js"]])};if(window.localStorage&&window.XMLHttpRequest&&window.atob){var t=window.parent!==window,p=new J,z=!1,x=new fa,N=ea,u=window.GLANCE.Cobrowse,M="//"+x.g+"/js";if(!x.g)if(window.console&&window.console.error)h("error",...["ASSERT"]);else throw Error("ASSERT");var C=new T,q=x.h;
if(u.Loader&&q&&q.getAttribute("data-loaded"))n("ERR_DUP_SCRIPTS");else{q&&q.setAttribute("data-loaded",!0);var aa=null;q=new Promise(d=>{aa=()=>{d()}});var Z={load:function(d){k(d)},loadScript:function(d,e){P(p,[["src",M+"/"+d+"_"+N+".js"]],e,()=>{U(C,{B:"SCRIPT_NOT_LOADED:"+d,code:"scriptloadfailed",D:{script:d}})})},setUIReady:aa,_uiready:q,_eventListeners:C,_onload:{},_origpath:window.location.pathname};G("glance_load",function(d,e){d&&(d!==window.parent&&d.parent!==window?n("UNTRUSTED_LOAD_MSG"):
(e.s&&k(),e.u&&null!==E(p.g,"getElementById","glance_visitor")&&F(d,"glance_load",{s:!0})))});t&&F(window.parent,"glance_load",{u:!0});window.addEventListener("message",function(d){if("string"!==typeof d.data){if(b().loaded)return!0;d.data.glance_invoke&&(d.data.origin=d.origin,k(function(){window.postMessage(d.data,window.location.href)}))}});D("focus",function(){if(b().loaded)return!0;b().inSession()&&k()});u.Visitor={loaded:!1,inSession:function(){return(new O).i()},addEventListener:function(d,
e){C.add(d,e)},removeEventListener:function(d,e){d=C.g[d];void 0!==d&&(e=d.indexOf(e),0<=e&&d.splice(e,1))}};q=["showButton","toggleButton","showTerms","setStyle"];t||(u.VisitorUI={},q.forEach(function(d){f(d,"VisitorUI")}));q=q.concat(["startSession","setStartParams"]);q.forEach(function(d){f(d,"Visitor")});u.Loader=Z;t||X()||!b().inSession()||k();!t&&X()&&k(null,"XDOM");Q(p,function(){document.body&&!z&&(z=!0,c(document.body),a(x.v),x.A&&!t&&P(p,[["src",M+"/GlancePresenceVisitor_"+N+".js"]]))});
G("forwardevent",function(d,e){v("received forwarded event:",e);if(d.top!==window)n("UNTRUSTED_KEYEVT");else window.GLANCE.Cobrowse[e.namespace][e.funcname]()})}}else h("error",...["ERR_COBROWSE_NOT_SUPP"])}document.getElementById("cobrowsescript")||document.getElementById("glance-cobrowse")?Y():(n("LOADER_PAGE_NOT_READY"),Q(new J,Y));}).call(window);
//# sourceMappingURL=map.js.map
