/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var aa=this||self;/*
 Copyright 2022 Glance Networks, Inc.
*/
var g=["6","3","0","21"].slice(0,3).join(".");Uint8Array.prototype.slice||(Uint8Array.prototype.slice=function(a,b){return new Uint8Array(this.subarray(a,b))});
ArrayBuffer.prototype.slice||(ArrayBuffer.prototype.slice=function(a,b){void 0===a&&(a=0);void 0===b&&(b=this.byteLength);a=Math.floor(a);b=Math.floor(b);0>a&&(a+=this.byteLength);0>b&&(b+=this.byteLength);a=Math.min(Math.max(0,a),this.byteLength);b=Math.min(Math.max(0,b),this.byteLength);if(0>=b-a)return new ArrayBuffer(0);var c=new ArrayBuffer(b-a),d=new Uint8Array(c);a=new Uint8Array(this,a,b-a);d.set(a);return c});
var k=navigator.userAgent.toLowerCase(),ba=k.match(/(edge)[\s\/:]([\w\d\.]+)?/)||k.match(/(opera|ie|firefox|chrome|version)[\s\/:]([\w\d\.]+)?.*?(safari|version[\s\/:]([\w\d\.]+)|$)/)||k.match(/(rv):([\w\d\.]+)/)||[null,"unknown",0];"rv"===ba[1]&&(ba[1]="ie");function ca(a){for(var b="",c=0;c<a.length;c++)b+=("object"===typeof a[c]?JSON.stringify(a[c]):a[c])+" ";return b.replace(/[\r\n]/g," ").replace("<","&lt;").replace(">","&gt;")}function m(a){window.console&&window.console.log&&(window.GLANCE_COBROWSE?!window.GLANCE_COBROWSE.disableLogging:1)&&window.console.log(ca(arguments))}function da(a){window.console&&window.console.error&&window.console.error(ca(arguments))};function ea(a,...b){!window.console||!window.console[a]||window.GLANCE_COBROWSE&&window.GLANCE_COBROWSE.disableLogging||(b=b.map(c=>{if("object"===typeof c)try{c=JSON.stringify(c)}catch(d){console.error(d),c="unable to convert object to string"}return"string"===typeof c?c.replace(/[\r\n]/g," ").replace("<","&lt;"):c}),window.console[a](...b))}function n(...a){ea("log",...a)}function p(...a){ea("error",...a)}function q(...a){n("PRES:",...a)};/*
 Copyright (c) 2022 Glance Networks, Inc.
*/
var u=u||{};window.GLANCE=window.GLANCE||{};window.GLANCE.VERSION="6.3.0.21";window.GLANCE.PATCH="";window.GLANCE.Lib=window.GLANCE.Lib||{};
var v=function(){var a=navigator.userAgent.toLowerCase(),b=navigator.platform.toLowerCase(),c=a.match(/(edge)[\s\/:]([\w\d\.]+)?/)||a.match(/(opera|ie|firefox|chrome|crios|version)[\s\/:]([\w\d\.]+)?.*?(safari|version[\s\/:]([\w\d\.]+)|$)/)||a.match(/(rv):([\w\d\.]+)/)||[null,"unknown",0];"crios"===c[1]?c[1]="chrome":"rv"===c[1]&&(c[1]="ie");a={extend:Function.prototype.extend,name:"version"==c[1]?c[3]:c[1],version:"ie"==c[1]&&document.documentMode||parseFloat("opera"==c[1]&&c[4]?c[4]:c[2]),u:{name:a.match(/ip(?:ad|od|hone)/)||
b.match(/mac/)&&"undefined"!==typeof navigator.g?"ios":(a.match(/(?:webos|android)/)||b.match(/mac|win|linux/)||["other"])[0]},ea:{ka:!!document.evaluate,ga:!!window.ja,query:!!document.querySelector,json:!!window.JSON},fa:{},ia:function(){return"ios"==this.u.name||"android"==this.u.name}};document.documentMode&&window.XDomainRequest?(a.name="ie",a.version=document.documentMode):window.navigator&&navigator.appVersion&&-1!=navigator.appVersion.indexOf("MSIE 7.")&&(a.name="ie",a.version="7");a[a.name]=
!0;a[a.name+parseInt(a.version,10)]=!0;a.u[a.u.name]=!0;return a}();if(void 0===x)var x=function(a){return y.h&&y.g?y.g.window.JSON.stringify(a):JSON.stringify(a)};function fa(a){a.onmessage=function(b){b=JSON.parse(b.data);a.P&&a.P(b)};a.B=function(b){b=x(b);a.send(b)};a.Y=function(b){return b&&b.code||0};a.Z=function(b){return b&&b.reason||""}}
function ha(a){var b={};if(u.da)var c=new z(a);else v.ie9&&"http:"===window.location.protocol&&(b.protocols_whitelist=["iframe-eventsource","iframe-htmlfile"]),c=new SockJS(a,"",b);c.v=0;c.U=function(){c.N();c.transport&&!c.transport.match(/^iframe-/)&&(c.O=A(window,"setInterval",function(){c.v++;c.ca&&c.ca({v:c.v})},15E3))};c.N=function(){c.O&&A(window,"clearInterval",c.O)};fa(c);c.onclose=function(d){c.N();c.aa&&c.aa(d)};c.onheartbeat=function(){c.v=0;c.U();c.ba&&c.ba()};return c}
function B(a,b){A(window,"setTimeout",function(){B(a,b)},100)}function z(a){this.readyState=SockJS.CONNECTING;this.g=Math.round(1E6*Math.random());B({from:"GSockJSProxy",sockid:this.g,cmd:"open",url:a})}z.prototype.send=function(a){B({from:"GSockJSProxy",sockid:this.g,cmd:"send",data:a})};z.prototype.close=function(){this.readyState=SockJS.CLOSING;B({from:"GSockJSProxy",sockid:this.g,cmd:"close"})};
function C(a,b,c){void 0!==a&&(c=c||Object.keys(a),c.forEach(function(d){void 0!==a[d]&&(b[d]=a[d])}))}function ia(a){var b=a.func.split(".");if(2>b.length)p("ERR_BADINVOKE:");else if("GLANCE"===b[0]||"GLANCE_COBROWSE"===b[0]&&"Custom"===b[1]){for(var c=window[b[0]],d=1;d<b.length;d++)if(c=c[b[d]],!c){p("ERR_UNDEFINVOKE:"+b[d]);return}a.args=a.args||{};a.args.remote=!0;c(a.args)}else p("ERR_BADINVOKE:"+b[0])}
function D(){u.da?this.j=new F("JSON"):this.g=new window.XMLHttpRequest;this.response=null;this.type="JSON"}D.prototype.abort=function(){this.j?this.j.abort():this.g.abort()};
D.prototype.onreadystatechange=function(){if(4==this.g.readyState){A(window,"clearTimeout",this.l);delete this.l;var a="error";if(0==this.g.status)n(this.method+" to "+this.url+" failed: network"),this.h(!0,"connection",this.g.status);else if(200!==this.g.status){p(this.method+" to "+this.url+" failed with status: "+this.g.status);"text"===this.g.responseType&&null!==this.g.responseText&&n(this.g.responseText);if(401===this.g.status||403===this.g.status)a="authorization",this.i&&this.i.ha();this.h(!1,
a,this.g.status)}else{if(""!==this.g.response){if("XML"===this.accept)this.response=this.g.responseXML&&this.g.responseXML.documentElement,null===this.response&&p("Invalid XML response: "+this.g.responseText);else if(this.C){for(var b=new Uint8Array(this.g.responseText.length),c=0;c<this.g.responseText.length;c++)b[c]=this.g.responseText.charCodeAt(c)&255;this.response=new Blob([b],{type:this.g.getResponseHeader("Content-Type")})}else if("blob"===this.g.responseType)this.response=this.g.response;
else if(this.g.responseXML)this.response=ka(this.g.responseXML.childNodes[0].childNodes[0].nodeValue);else if("HTML"===this.accept||"TEXT"===this.accept)this.response=this.g.responseText;else if(this.response=ka(this.g.responseText),null===this.response){n(this.method+" to "+this.url+" failed - can't parse response "+this.g.responseText);this.h(!1,a);return}if(void 0!==this.response.err&&void 0!==this.response.msg){n(this.method+" to "+this.url+" failed with error:"+this.response.err+" "+this.response.msg);
this.h(!1,a);return}}this.onsuccess(this.response)}}};function ka(a){var b=null;try{b=JSON.parse(a)}catch(c){return n("JSON parse failed with error: "+c.toString()+" parsing: "+a),null}return b}D.prototype.getResponseHeader=function(a){return this.g.getResponseHeader(a)};D.prototype.get=function(a,b,c,d,f){this.method="GET";G(this,a,null,b,c,d,f)};
function G(a,b,c,d,f,h,e){a.url=b;a.onsuccess=void 0!==h?h:function(){};a.h=void 0!==e?e:function(){};a.method=a.method||"POST";if(a.j)la(a.j,b,c,d,f,h,e);else{h=a.D||("JSON"===a.type?"application/json; charset=utf-8":"application/x-www-form-urlencoded; charset=utf-8");if("string"===typeof c)var t=c;else c instanceof Blob?(h=c.type,t=c):c&&(t="JSON"===a.type?x(c):"data="+x(c));v.safari&&a.s&&(a.l=A(window,"setTimeout",function(){n(this.method+" to "+this.url+" failed - timedout (Safari)");this.h(!1,
"timedout")}.bind(a),a.s));a.g.onreadystatechange=function(){a.onreadystatechange()};try{a.g.open(a.method,b,d),void 0!==a.m&&a.g.setRequestHeader("Accept",a.m),void 0!==a.g.setRequestHeader&&"GET"!==a.method&&a.g.setRequestHeader("Content-type",h),a.i&&a.i.$()?a.g.setRequestHeader("Authorization","Bearer "+a.i.$()):a.o&&a.g.setRequestHeader("Authorization","Bearer "+a.o),a.g.withCredentials=f,a.g.send(t)}catch(l){n(a.method+" to "+b+" failed with: "+l.toString()),a.h(!1,l.toString())}}}
function F(a){this.type=a}function la(a,b,c,d,f,h,e){a.onsuccess=h;a.h=e;B({from:"IFrameProxyRequest",type:a.type,url:b,obj:c,async:d,withcred:f})}F.prototype.abort=function(){F.postMessage({from:"IFrameProxyRequest",abort:!0})};function H(a){this.name=a}function ma(a,b){var c=new Date;c.setUTCHours(c.getUTCHours()+8);localStorage.setItem(a.name,x(b));localStorage.setItem(a.name+"_exp",c.toGMTString())}function na(a){if(!oa(a))return null;a=localStorage.getItem(a.name);return JSON.parse(a)}
function pa(a,b){"string"===typeof b&&(b=parseInt(b));var c=new Date;c.setUTCMinutes(c.getUTCMinutes()+b);localStorage.setItem(a.name+"_exp",c.toGMTString())}H.prototype.get=function(){return oa(this)?localStorage.getItem(this.name):null};function qa(a){localStorage.removeItem(a.name);localStorage.removeItem(a.name+"_exp")}function oa(a){var b=localStorage.getItem(a.name+"_exp");if(!b)return!1;b=new Date(b);return b<new Date?(qa(a),!1):!0}
function I(){var a=window;this.g=a.document;this.h=a;var b=[["hidden","visibilitychange"],["mozHidden","mozvisibilitychange"],["webkitHidden","webkitvisibilitychange"],["msHidden","msvisibilitychange"],["oHidden","ovisibilitychange"]];for(a=0;a<b.length;a++)if(b[a][0]in document){this.i=b[a][0];this.j=b[a][1];break}}
function ra(a,b){var c=[["src","//www.glancecdn.net/cobrowse/js/sockjs1.0.2.min.js"]],d=a.g.createElement("script");b&&d.addEventListener("load",b);d.setAttribute("type","text/javascript");d.setAttribute("charset","UTF-8");for(b=0;b<c.length;b++)d.setAttribute(c[b][0],c[b][1]);a.g.head.appendChild(d)}function J(a){return void 0===a.i?!1:a.g[a.i]}function sa(a,b){a.g.addEventListener(a.j,b)}I.prototype.head=function(){return void 0!==this.g.head?this.g.head:A(this.g,"getElementsByTagName","head")[0]};
function ta(a){if(void 0!==window.pageXOffset)return{x:Math.round(a.h.pageXOffset),y:Math.round(a.h.pageYOffset)};if(void 0!==document.documentElement.scrollTop)return{x:a.g.documentElement.scrollLeft,y:a.g.documentElement.scrollTop};if(void 0!==document.body.scrollLeft)return{x:a.g.body.scrollLeft,y:a.g.body.scrollTop};throw Error("Can't get page scroll");}
I.prototype.scrollTo=function(a,b,c){var d=ta(this);d[a]=b;a={left:d.x,top:d.y,behavior:c?"smooth":"auto"};v.ie11||v.edge?window.scrollTo(d.x,d.y):window.scrollTo(a);ta(this)};I.prototype.addEventListener=function(a,b,c){A(this.g,"addEventListener",a,b,c)};I.prototype.removeEventListener=function(a,b,c){A(this.g,"removeEventListener",a,b,c)};function y(a){this.g=a}y.prototype.addEventListener=function(a,b,c){A(this.g,"addEventListener",b,c)};
y.prototype.removeEventListener=function(a,b,c){A(this.g,"removeEventListener",b,c)};function A(a,b,...c){return y.h&&y.g&&a.nodeType?"#document"===a.nodeName?y.g.document[b].apply(a,c):"#document-fragment"===a.nodeName?y.g.DocumentFragment.prototype[b].apply(a,c):y.g.document.body[b].apply(a,c):y.h&&y.g&&"[object Window]"===a.toString()?y.g.window[b].apply(a,c):a[b].apply(a,c)}function ua(a,b,c){a.g.style.left=b+"px";a.g.style.top=c+"px"}
y.prototype.moveTo=function(a,b){function c(){10>e++?(f+=t,h+=l,ua(d,Math.floor(f),Math.floor(h)),d.h=A(window,"setTimeout",c,20)):ua(d,a,b)}void 0!==this.h&&A(window,"clearTimeout",this.h);var d=this,f=parseInt(this.g.style.left),h=parseInt(this.g.style.top);isNaN(f)&&(f=-999);isNaN(h)&&(h=-999);var e=0,t=(a-f)/10,l=(b-h)/10;0===t&&0===l||c()};function va(a,b){if(void 0!==a){var c=c||Object.keys(a);c.forEach(function(d){void 0!==a[d]&&(b[d]=a[d])})}}function wa(a){var b={};if(!a)return b;var c=0;for(a=a.attributes;c<a.length;c++){var d=a[c].nodeName.match(/data-(.*)/);d&&2===d.length&&(b[d[1]]=a[c].nodeValue)}return b}function xa(){var a=window.GLANCE_COBROWSE?window.GLANCE_COBROWSE:{},b=document.getElementById("cobrowsescript"),c=document.getElementById("glance-cobrowse");b=wa(b);c=wa(c);va(b,a);va(c,a);return a};function K(){}function ya(a,b){a.G="undefined"===typeof WebSocket;a.g={};a.g.ws="www.glance.net";a.g.site="production";a.l=new I;C(xa(),a.g);C(b,a.g);delete a.g.presenceserver;a.D=[];a.j=L;a.m=new H("glance_presence");var c=na(a.m);c&&(0===["visitorid","ws","groupid"].filter(d=>c[d]!==a.g[d]).length?a.i=c.directserver:q("Ignoring glance_presence entry for different visitor",c.groupid,c.visitorid));q("direct server from local storage:",a.i)}var L=1;K.prototype.H=function(){};
function M(a,b,c,d,f){if(b&&!a.i)m("ERR_NODIRECTSERVER");else{var h=(f||"https")+"://"+(b?a.i:a.g.presenceserver)+"/"+c;d&&(h+="?",["groupid","visitorid"].forEach(function(e){h+=e+"="+a.g[e]+"&"}),h+=`&ver=${g}`);return h}}K.prototype.J=function(a){N(this,"findvisitor","GET",a)};
function O(a){m("connecting to "+a.i);var b=!1;a.G&&!window.SockJS?ra(a.l,function(){b||(q("sockjs script added"),b=!0,window.SockJS?O(a):m("ERR_NOSOCKJS"))}):(a.h&&a.h.close(),a.h=za(a),a.h.R=a.i,a.h.onopen=function(){q("sock onopen, sending connect");a.h.B({type:"connect",authorization:void 0,groupid:a.g.groupid,visitorid:a.g.visitorid,guesttoken:a.g.guesttoken,version:g});q("sending message queue");a.D.forEach(function(c){a.h.B(c)});a.D=[];a.j=3},a.h.P=function(c){m("received:"+x(c));if(a.h){var d=
c.mtype||c.type,f=c.data;switch(d){case "connected":if(a.g.nokeepalive)break;q("Keepalive interval: "+c.keepalive);a.o||(a.o=window.setInterval(function(){a.h.B({type:"k"})},1E3*c.keepalive));break;case "invoke":"visitor"===a.T&&ia(f);break;case "redirect":case "serverclose":f||(f=c);default:if(a["on"+d])a["on"+d](f)}}else q("Ignoring message received after socket close")},a.h.onclose=function(c){a.h===this&&(m(`presence connection closed ${this.Y(c)} ${this.Z(c)}`),Aa(a),P(a))},a.h.onerror=function(c){a.h===
this&&(q("socket error"),a.G=!0,a.h.onclose(c))})}
function N(a,b,c,d){function f(l){var r=l&&(l.directserver||l.direct);r&&(e.i=r,l.httpsport&&(e.i+=":"+l.httpsport),e.H());e.h&&e.i!=e.h.R&&(q("switching connection from "+e.h.R+" to "+e.i),O(e));if(d&&d.onsuccess)d.onsuccess(l)}function h(l,r,w){m(`Presence request: ${b} failed reason: ${r} http status: ${w||0}`);503===w&&(da("Presence service unavailable"),e.M=!0,r="serviceunavailable");if(d.onfail)d.onfail(r);else Q(e,{error:"connfail",detail:r})}if(!a.M){var e=a,t=new D;t.i=void 0;t.method=c;
m(b,JSON.stringify(d));(function(l){if(e.g.presenceserver)return l();var r=new H("glance_visitor_settings_"+e.g.groupid+"_"+e.g.site),w=na(r);if(w)return e.g.presenceserver=w.presenceserver,e.g.presenceserver||m("PRES_DISABLED (from cache)"),l();w=new D;var Da="https://"+e.g.ws+"/services/authorizationservice/GetVisitorSettings3?groupid="+e.g.groupid+"&site="+e.g.site+"&service=presence";w.method="GET";G(w,Da,null,!0,!1,function(U){e.g.presenceserver=U.presenceUrl;q("presence service: "+e.g.presenceserver);
e.g.presenceserver||m("PRES_DISABLED");var E={};E.presenceserver=e.g.presenceserver;E.presencesettings=U;ma(r,E);pa(r,1440);return l()},function(U,E){m("PRES_UNAVAILABLE "+E);l()})})(function(){e.g.presenceserver&&G(t,M(e,!1,b,!0),d.data?d.data:{},!0,!1,f,h)})}}function R(a){q("closewebsocket");a.h&&a.h.close();Aa(a)}function Aa(a){a.o&&(window.clearInterval(a.o),delete a.o);a.j=L;delete a.h;delete a.i}
function S(a,b){m("sending",b.type,a.j);3===a.j?(q("sending message: "+JSON.stringify(b)),a.h.B(b)):(q("queuing message: "+JSON.stringify(b)),a.D.push(b),a.connect())}K.prototype.S=function(a){let b=3===this.j;b&&this.disconnect();this.g.visitorid=a;(b||"api"!==this.g.presence)&&this.connect()};K.prototype.setVisitorId=K.prototype.S;
K.prototype.connect=function(){if(!this.M)if(this.g.visitorid)if(this.j!==L)q("connect() called when already connecting or connected");else{this.j=2;q("connect");var a=this;this.onscaledown=function(){a.disconnect();a.connect()};this.onredirect=function(b){q("Connected to wrong instance:",JSON.stringify(b),"current direct server:",this.i);this.m&&b.direct!==this.i&&(qa(this.m),this.m=new H("glance_presence"),this.disconnect(),P(this))};this.onserverclose=function(){a.disconnect();if(a.onclose)a.onclose()};
this.i?O(this):this.J({onsuccess:function(){m("found visitor, connect");O(a)},onfail:function(b){a.j=L;Q(a,{error:"connfail",detail:b})}})}else m("CONN_NOVISITORID")};K.prototype.connect=K.prototype.connect;K.prototype.disconnect=function(){R(this)};K.prototype.disconnect=K.prototype.disconnect;function P(a){q(`delayed reconnect.  count: ${a.s||0} connstate: ${a.j}`);a.I||(a.s=a.s||0,a.s++,a.I=window.setTimeout(()=>{delete a.I;a.connect()},3>=a.s?5E3:6E4))}
function Q(a,b){m("Error: ",JSON.stringify(b));a.K&&a.K(b);if(a.onerror)a.onerror(b)}K.prototype.X=function(a,b){S(this,{type:a,data:b})};K.prototype.fire=K.prototype.X;function T(a){ya(this,a);this.T="visitor";this.l=new I;this.F=!1;var b=this;A(window,"addEventListener","focus",function(){q("presence visitor got focus event");b.C=!1;b.L&&b.A()},void 0);sa(this.l,function(){if(!b.F&&(q("visibility:",J(b.l)?"hidden":"visible"),(b.L||3===b.j)&&!b.C)){var c={type:"visibility"};c.data={visibility:J(b.l)?"hidden":"visible"};S(b,c);J(b.l)&&R(b)}});T.instance=this}var Ba=T,V=["GLANCE","Presence","Visitor"],W=aa;
V[0]in W||"undefined"==typeof W.execScript||W.execScript("var "+V[0]);for(var X;V.length&&(X=V.shift());)V.length||void 0===Ba?W[X]&&W[X]!==Object.prototype[X]?W=W[X]:W=W[X]={}:W[X]=Ba;T.prototype=new K;T.prototype.H=function(){q("caching direct server:",this.i);var a={};a.directserver=this.i;a.groupid=this.g.groupid;a.visitorid=this.g.visitorid;a.ws=this.g.ws;ma(this.m,a);pa(this.m,20)};
T.prototype.A=function(a){q("presence");if(this.g.visitorid){var b={};C(this.g,b,["groupid","visitorid"]);var c={},d;for(d in this.g)0===d.indexOf("user-")&&(c[d.substring(5)]=this.g[d]);c.url=window.location.href;c.browser=v.name;c.browserver=v.version;c.platform=v.u.name;(a=a&&a.data)&&C(a,c);b.data=c;this.C||(c={type:"presence"},c.data=b.data,S(this,c),this.L=!0);this.K=function(f){"connfail"===f.error&&P(this)}}else m("PRES_NOVISITORID")};T.prototype.presence=T.prototype.A;
T.prototype.V=function(a){var b=this;this.F=!0;N(this,"uniquevisitor","GET",{onsuccess:function(c){m("got unique visitor id",c.visitorid);b.g.visitorid=c.visitorid;b.g.guesttoken=c.guesttoken;b.g.timeout=c.timeout||300;if(b.onuniqueid)b.onuniqueid(c.uniqueid,b.g.timeout);b.connect();a&&a.data&&b.A({data:a.data})},onfail:function(c){Q(b,{error:"connfail",detail:c})}})};T.prototype.connectUnique=T.prototype.V;
T.prototype.W=function(){this.F?3===this.j?(this.disconnect(),this.connect()):Q(this,{error:"connfail",detail:"extend"}):console.error("ERR_EXTEND_UNIQUE")};T.prototype.extendUnique=T.prototype.W;function za(a){a.G?a=ha(M(a,!0,"visitor")):(a=M(a,!0,"visitorws",!1,"wss"),a=new WebSocket(a),fa(a));return a}T.setVisitorId=function(a){T.instance&&T.instance.S(a)};T.prototype.J=function(a){a.data={};N(this,"presence","POST",a)};T.prototype.onblur=function(){m("BLURRED");this.C=!0;R(this)};var Ca=!1;
function Y(){if(!Ca){Ca=!0;var a=xa();a.presence&&"api"!==a.presence&&(new T).A()}}var Z=new I;Z.h.addEventListener&&(document.readyState.match(/complete/)?Y():(Z.h.addEventListener("load",Y),Z.g.addEventListener("DOMContentLoaded",Y,!1)));
