(function() {/*
 Copyright 2022 Glance Networks, Inc.
*/
function g(a,...c){!window.console||!window.console[a]||window.GLANCE_COBROWSE&&window.GLANCE_COBROWSE.disableLogging||(c=c.map(b=>{if("object"===typeof b)try{b=JSON.stringify(b)}catch(d){console.error(d),b="unable to convert object to string"}return"string"===typeof b?b.replace(/[\r\n]/g," ").replace("<","&lt;"):b}),window.console[a](...c))}function h(...a){g("log",...a)}function k(...a){g("error",...a)}function l(...a){h("XDOM:",...a)};/*
 Copyright (c) 2022 Glance Networks, Inc.
*/
var p=p||{};window.GLANCE=window.GLANCE||{};window.GLANCE.VERSION="6.3.0.21";window.GLANCE.PATCH="";window.GLANCE.Lib=window.GLANCE.Lib||{};
var q=function(){var a=navigator.userAgent.toLowerCase(),c=navigator.platform.toLowerCase(),b=a.match(/(edge)[\s\/:]([\w\d\.]+)?/)||a.match(/(opera|ie|firefox|chrome|crios|version)[\s\/:]([\w\d\.]+)?.*?(safari|version[\s\/:]([\w\d\.]+)|$)/)||a.match(/(rv):([\w\d\.]+)/)||[null,"unknown",0];"crios"===b[1]?b[1]="chrome":"rv"===b[1]&&(b[1]="ie");a={extend:Function.prototype.extend,name:"version"==b[1]?b[3]:b[1],version:"ie"==b[1]&&document.documentMode||parseFloat("opera"==b[1]&&b[4]?b[4]:b[2]),u:{name:a.match(/ip(?:ad|od|hone)/)||
c.match(/mac/)&&"undefined"!==typeof navigator.g?"ios":(a.match(/(?:webos|android)/)||c.match(/mac|win|linux/)||["other"])[0]},D:{O:!!document.evaluate,G:!!window.J,query:!!document.querySelector,json:!!window.JSON},F:{},I:function(){return"ios"==this.u.name||"android"==this.u.name}};document.documentMode&&window.XDomainRequest?(a.name="ie",a.version=document.documentMode):window.navigator&&navigator.appVersion&&-1!=navigator.appVersion.indexOf("MSIE 7.")&&(a.name="ie",a.version="7");a[a.name]=!0;
a[a.name+parseInt(a.version,10)]=!0;a.u[a.u.name]=!0;return a}();if(void 0===r)var r=function(a){return t.h&&t.g?t.g.window.JSON.stringify(a):JSON.stringify(a)};function u(a,c){w(window,"setTimeout",function(){u(a,c)},100)}function x(a){var c=window.opener,b={};b.glance_xdomain=a;c.postMessage(b,"*")}
function y(a,c){w(window,"addEventListener","message",function(b){if("string"===typeof b.data)try{var d=JSON.parse(b.data)}catch(f){return!1}else d=b.data;void 0!==d.glance_xdomain&&(c&&!z(b.origin,c)?k("UNTRUSTED_ORIGIN:"+b.origin+" "+JSON.stringify(d)):a(b.source,d.glance_xdomain))})}function A(){p.M?this.j=new B("JSON4"):this.g=new window.XMLHttpRequest;this.response=null;this.type="JSON4"}A.prototype.abort=function(){this.j?this.j.abort():this.g.abort()};
A.prototype.onreadystatechange=function(){if(4==this.g.readyState){w(window,"clearTimeout",this.o);delete this.o;var a="error";if(0==this.g.status)h(this.method+" to "+this.url+" failed: network"),this.h(!0,"connection",this.g.status);else if(200!==this.g.status){k(this.method+" to "+this.url+" failed with status: "+this.g.status);"text"===this.g.responseType&&null!==this.g.responseText&&h(this.g.responseText);if(401===this.g.status||403===this.g.status)a="authorization",this.i&&this.i.H();this.h(!1,
a,this.g.status)}else{if(""!==this.g.response){if("XML"===this.accept)this.response=this.g.responseXML&&this.g.responseXML.documentElement,null===this.response&&k("Invalid XML response: "+this.g.responseText);else if(this.L){for(var c=new Uint8Array(this.g.responseText.length),b=0;b<this.g.responseText.length;b++)c[b]=this.g.responseText.charCodeAt(b)&255;this.response=new Blob([c],{type:this.g.getResponseHeader("Content-Type")})}else if("blob"===this.g.responseType)this.response=this.g.response;
else if(this.g.responseXML)this.response=C(this.g.responseXML.childNodes[0].childNodes[0].nodeValue);else if("HTML"===this.accept||"TEXT"===this.accept)this.response=this.g.responseText;else if(this.response=C(this.g.responseText),null===this.response){h(this.method+" to "+this.url+" failed - can't parse response "+this.g.responseText);this.h(!1,a);return}if(void 0!==this.response.err&&void 0!==this.response.msg){h(this.method+" to "+this.url+" failed with error:"+this.response.err+" "+this.response.msg);
this.h(!1,a);return}}this.onsuccess(this.response)}}};function C(a){var c=null;try{c=JSON.parse(a)}catch(b){return h("JSON parse failed with error: "+b.toString()+" parsing: "+a),null}return c}A.prototype.getResponseHeader=function(a){return this.g.getResponseHeader(a)};A.prototype.get=function(a,c,b,d,f){this.method="GET";D(this,a,null,c,b,d,f)};
function D(a,c,b,d,f,e,m){a.url=c;a.onsuccess=void 0!==e?e:function(){};a.h=void 0!==m?m:function(){};a.method=a.method||"POST";if(a.j)E(a.j,c,b,d,f,e,m);else{e=a.N||("JSON"===a.type?"application/json; charset=utf-8":"application/x-www-form-urlencoded; charset=utf-8");if("string"===typeof b)var n=b;else b instanceof Blob?(e=b.type,n=b):b&&(n="JSON"===a.type?r(b):"data="+r(b));q.safari&&a.B&&(a.o=w(window,"setTimeout",function(){h(this.method+" to "+this.url+" failed - timedout (Safari)");this.h(!1,
"timedout")}.bind(a),a.B));a.g.onreadystatechange=function(){a.onreadystatechange()};try{a.g.open(a.method,c,d),void 0!==a.v&&a.g.setRequestHeader("Accept",a.v),void 0!==a.g.setRequestHeader&&"GET"!==a.method&&a.g.setRequestHeader("Content-type",e),a.i&&a.i.C()?a.g.setRequestHeader("Authorization","Bearer "+a.i.C()):a.A&&a.g.setRequestHeader("Authorization","Bearer "+a.A),a.g.withCredentials=f,a.g.send(n)}catch(v){h(a.method+" to "+c+" failed with: "+v.toString()),a.h(!1,v.toString())}}}
function B(a){this.type=a}function E(a,c,b,d,f,e,m){a.onsuccess=e;a.h=m;u({from:"IFrameProxyRequest",type:a.type,url:c,obj:b,async:d,withcred:f})}B.prototype.abort=function(){B.postMessage({from:"IFrameProxyRequest",abort:!0})};function F(a,c){this.name=a;if(!(a=c)){c=new G;a=c.h.location.hostname;for(c=c.h;""===a&&c.parent!==c;)a=c.parent.location.hostname,c=c.parent;a=H(a)}this.domain=a}
F.prototype.s=function(a,c){var b=new Date;b.setUTCHours(b.getUTCHours()+8);document.cookie=this.name+"="+escape(r(a))+"; expires="+b.toGMTString()+"; domain="+this.domain+"; path=/"+(c||a.K?";secure":"")};F.prototype.get=function(){return this.l()?unescape(document.cookie.replace(new RegExp("(?:^|.*;\\s*)"+escape(this.name).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=\\s*((?:[^;](?!;))*[^;]?).*"),"$1")):null};
F.prototype.m=function(){var a=new Date;a.setDate(a.getDate()-1);document.cookie=escape(this.name)+"=; expires="+a.toGMTString()+"; domain="+this.domain+"; path=/"};F.prototype.l=function(){return(new RegExp("(?:^|;\\s*)"+escape(this.name).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=")).test(document.cookie)};function I(a){this.name=a}I.prototype.s=function(a){var c=new Date;c.setUTCHours(c.getUTCHours()+8);localStorage.setItem(this.name,r(a));localStorage.setItem(this.name+"_exp",c.toGMTString())};
I.prototype.get=function(){return this.l()?localStorage.getItem(this.name):null};I.prototype.m=function(){localStorage.removeItem(this.name);localStorage.removeItem(this.name+"_exp")};I.prototype.l=function(){var a=localStorage.getItem(this.name+"_exp");if(!a)return!1;a=new Date(a);return a<new Date?(this.m(),!1):!0};function K(a,c){this.g=[new F(a,c),new I(a)]}K.prototype.s=function(a,c){this.g[0].s(a,c);this.g[1].s(a,c)};K.prototype.get=function(){return this.g[0].get()||this.g[1].get()};
K.prototype.m=function(){this.g[0].m();this.g[1].m()};K.prototype.l=function(){return this.g[0].l()||this.g[1].l()};function G(){var a=window;this.g=a.document;this.h=a;var c=[["hidden","visibilitychange"],["mozHidden","mozvisibilitychange"],["webkitHidden","webkitvisibilitychange"],["msHidden","msvisibilitychange"],["oHidden","ovisibilitychange"]];for(a=0;a<c.length&&!(c[a][0]in document);a++);}
function L(a){var c=a;a=a.split("?");1<a.length&&(c=a[0]);c=(new RegExp(/(?:.*?:\/\/){0,1}([^\/:]+)/)).exec(c);return null===c||2>c.length||0>c[1].indexOf(".")?null:c[1]}
function H(a){var c=new RegExp(/^(?:[a-z]{1,5}:\/\/|)([^:\?\/]*)/),b=a.match(/^\d+\.\d+.\d+.\d+$/);c=c.exec(a);if(b)return a;if(null===c||2!==c.length)return"about:"!==a&&h("ERR_DOMAINPARSE: "+a),null;b=c[1].split(".");return 1===b.length?(h("ERR_DOMAINPARSE: "+a),null):2===b.length?b.join("."):3===b.length?b.slice(1).join("."):4>=b[b.length-2].length?b.slice(b.length-3).join("."):b.slice(b.length-2).join(".")}
function z(a,c){var b=!1;a=L(a);if(null===a||!c)return!1;c.forEach(function(d,f){"object"===typeof d&&(d=d.domain);if(a.match(new RegExp("\\."+d+"$","i"))||a===d)b={index:f,domain:d}});return b}G.prototype.head=function(){return void 0!==this.g.head?this.g.head:w(this.g,"getElementsByTagName","head")[0]};
function M(a){if(void 0!==window.pageXOffset)return{x:Math.round(a.h.pageXOffset),y:Math.round(a.h.pageYOffset)};if(void 0!==document.documentElement.scrollTop)return{x:a.g.documentElement.scrollLeft,y:a.g.documentElement.scrollTop};if(void 0!==document.body.scrollLeft)return{x:a.g.body.scrollLeft,y:a.g.body.scrollTop};throw Error("Can't get page scroll");}
G.prototype.scrollTo=function(a,c,b){var d=M(this);d[a]=c;a={left:d.x,top:d.y,behavior:b?"smooth":"auto"};q.ie11||q.edge?window.scrollTo(d.x,d.y):window.scrollTo(a);M(this)};G.prototype.addEventListener=function(a,c,b){w(this.g,"addEventListener",a,c,b)};G.prototype.removeEventListener=function(a,c,b){w(this.g,"removeEventListener",a,c,b)};function t(a){this.g=a}t.prototype.addEventListener=function(a,c,b){w(this.g,"addEventListener",c,b)};
t.prototype.removeEventListener=function(a,c,b){w(this.g,"removeEventListener",c,b)};function w(a,c,...b){return t.h&&t.g&&a.nodeType?"#document"===a.nodeName?t.g.document[c].apply(a,b):"#document-fragment"===a.nodeName?t.g.DocumentFragment.prototype[c].apply(a,b):t.g.document.body[c].apply(a,b):t.h&&t.g&&"[object Window]"===a.toString()?t.g.window[c].apply(a,b):a[c].apply(a,b)}function N(a,c,b){a.g.style.left=c+"px";a.g.style.top=b+"px"}
t.prototype.moveTo=function(a,c){function b(){10>m++?(f+=n,e+=v,N(d,Math.floor(f),Math.floor(e)),d.h=w(window,"setTimeout",b,20)):N(d,a,c)}void 0!==this.h&&w(window,"clearTimeout",this.h);var d=this,f=parseInt(this.g.style.left),e=parseInt(this.g.style.top);isNaN(f)&&(f=-999);isNaN(e)&&(e=-999);var m=0,n=(a-f)/10,v=(c-e)/10;0===n&&0===v||b()};function O(a,c){if(void 0!==a){var b=b||Object.keys(a);b.forEach(function(d){void 0!==a[d]&&(c[d]=a[d])})}}function P(a){var c={};if(!a)return c;var b=0;for(a=a.attributes;b<a.length;b++){var d=a[b].nodeName.match(/data-(.*)/);d&&2===d.length&&(c[d[1]]=a[b].nodeValue)}return c}function Q(){var a=window.GLANCE_COBROWSE?window.GLANCE_COBROWSE:{},c=document.getElementById("cobrowsescript"),b=document.getElementById("glance-cobrowse");c=P(c);b=P(b);O(c,a);O(b,a);return a};function R(a){if(URL.toString().includes("[native code]"))var c=(new URL(`https://${a.j}/${"cobrowse/CobrowseSettings.asmx/GetGroupSettings"}`)).href;else{c=[`https://${a.j}/${"cobrowse/CobrowseSettings.asmx/GetGroupSettings"}`];if(!a.o){let b=document.createElement("iframe");b.style.display="none";b.setAttribute("data-no-cobrowse-content",1);document.body.appendChild(b);a.o=b.contentWindow}a=a.o.URL;c=(new (Function.bind.apply(a,[a,...c]))).href}return c};function S(){this.g=T}S.prototype.start=function(){if(window.opener)if(window.opener===window)l("self is opener, refreshed?");else{var a=new A,c=R(this.g),b=this;D(a,c,{groupid:this.g.h},!0,!1,function(d){U(b,d.trustedDomains)},function(){k("GetGroupSettings failed")})}else l("No window.opener")};
function U(a,c){l("Listen for messages from",c);y(function(b,d){window.clearTimeout(a.h);l("Received message",d);if(2!==d.type)k("Received unexpected xdom message type:"+d.type);else if(a.g.h.includes(parseInt(d.cookieinfo.ssnid.split(".")[0],10))){d.cookieinfo.xdomdone=!0;b=a.g;var f=d.cookieinfo;switch(b.v){case "ls":var e=I;break;case "dual":e=K;break;default:e=F}(new e("glance_ssn_info",b.A)).s(f,"secure"===b.v);d.nexthelper?window.location.replace(d.nexthelper):(x({type:3}),d.desturl&&window.location.replace(d.desturl))}else k("XDOM SSNID group not in script tag.  ssnid:"+
d.cookieinfo.ssnid+" groups:"+a.g.i)},c);l("Post ready_to_continue");x({type:1});a.h=window.setTimeout(function(){k("No message received from opener")},3E3)};var T=new function(){this.g=document.getElementById("cobrowsescript")||document.getElementById("glance-cobrowse");document.getElementById("glance-cobrowse");if(null!==this.g){var a=Q();O(a,this);RegExp("//(.*)/").exec("string"===typeof this.g.src?this.g.src:a.scriptserver+"/");this.h=a.groupid||this.g.getAttribute("groupid");this.j=a.ws||this.g.getAttribute("ws")||"www.glance.net";this.j.match("\\.glance\\.net$");this.A=a.cookiedomain;this.v=a.cookietype;this.uri=a.uri;this.B=a.site||this.g.getAttribute("site")||
"production";JSON.parse(a.inputevents||"{}");if(!this.h)throw Error("data-groupid missing");a=a.additionalgroupids||"";this.i=[this.h].concat(a?a.split(","):[]);this.i=this.i.map(function(c){if(!parseInt(c))throw Error("data-groupid invalid: "+c);return parseInt(c)});if(!/staging|production/i.test(this.B))throw Error("data-site invalid");}};(new S).start();}).call(window);
//# sourceMappingURL=map.js.map
