(function() {/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var aa=this||self;/*
 Copyright 2022 Glance Networks, Inc.
*/
var k=["6","33","0","1480702263"].slice(0,3).join(".");Uint8Array.prototype.slice||(Uint8Array.prototype.slice=function(a,b){return new Uint8Array(this.subarray(a,b))});
ArrayBuffer.prototype.slice||(ArrayBuffer.prototype.slice=function(a,b){void 0===a&&(a=0);void 0===b&&(b=this.byteLength);a=Math.floor(a);b=Math.floor(b);0>a&&(a+=this.byteLength);0>b&&(b+=this.byteLength);a=Math.min(Math.max(0,a),this.byteLength);b=Math.min(Math.max(0,b),this.byteLength);if(0>=b-a)return new ArrayBuffer(0);var c=new ArrayBuffer(b-a),d=new Uint8Array(c);a=new Uint8Array(this,a,b-a);d.set(a);return c});
var l=navigator.userAgent.toLowerCase(),m=l.match(/(edge)[\s\/:]([\w\d\.]+)?/)||l.match(/(opera|ie|firefox|chrome|version)[\s\/:]([\w\d\.]+)?.*?(safari|version[\s\/:]([\w\d\.]+)|$)/)||l.match(/(rv):([\w\d\.]+)/)||[null,"unknown",0];"rv"===m[1]&&(m[1]="ie");function n(a){for(var b="",c=0;c<a.length;c++)b+=("object"===typeof a[c]?JSON.stringify(a[c]):a[c])+" ";return b.replace(/[\r\n]/g," ").replace("<","&lt;").replace(">","&gt;")}function p(a){window.console&&window.console.log&&(window.GLANCE_COBROWSE?!window.GLANCE_COBROWSE.disableLogging:1)&&window.console.log(n(arguments))}function ba(a){window.console&&window.console.error&&window.console.error(n(arguments))};function r(a,...b){!window.console||!window.console[a]||window.GLANCE_COBROWSE&&window.GLANCE_COBROWSE.disableLogging||(b=b.map(c=>{if("object"===typeof c)try{c=JSON.stringify(c)}catch(d){console.error(d),c="unable to convert object to string"}return"string"===typeof c?c.replace(/[\r\n]/g," ").replace("<","&lt;"):c}),window.console[a](...b))}function t(...a){r("log",...a)}function u(...a){r("error",...a)}function x(...a){t("PRES:",...a)};/*
 Copyright (c) 2022 Glance Networks, Inc.
*/
var ca=ca||{};window.GLANCE=window.GLANCE||{};window.GLANCE.VERSION="6.33.0.1480702263";window.GLANCE.PATCH="";window.GLANCE.Lib=window.GLANCE.Lib||{};
var y=function(){var a=navigator.userAgent.toLowerCase(),b=navigator.platform.toLowerCase(),c=a.match(/(edge|edg)[\s\/:]([\w\d\.]+)?/)||a.match(/(opera|ie|firefox|chrome|crios|version)[\s\/:]([\w\d\.]+)?.*?(safari|version[\s\/:]([\w\d\.]+)|$)/)||a.match(/(rv):([\w\d\.]+)/)||[null,"unknown",0];"edg"===c[1]&&(c[1]="edge");"crios"===c[1]?c[1]="chrome":"rv"===c[1]&&(c[1]="ie");a={extend:Function.prototype.extend,name:"version"==c[1]?c[3]:c[1],version:"ie"==c[1]&&document.documentMode||parseFloat("opera"==
c[1]&&c[4]?c[4]:c[2]),u:{name:a.match(/ip(?:ad|od|hone)/)||b.match(/mac/)&&0<typeof navigator.maxTouchPoints?"ios":(a.match(/(?:webos|android)/)||b.match(/mac|win|linux/)||["other"])[0]},da:{ka:!!document.evaluate,fa:!!window.g,query:!!document.querySelector,json:!!window.JSON},ea:{},ha:function(){return"ios"==this.u.name||"android"==this.u.name}};document.documentMode&&window.XDomainRequest?(a.name="ie",a.version=document.documentMode):window.navigator&&navigator.appVersion&&-1!=navigator.appVersion.indexOf("MSIE 7.")&&
(a.name="ie",a.version="7");a[a.name]=!0;a[a.name+parseInt(a.version,10)]=!0;a.u[a.u.name]=!0;return a}();function z(){}z.prototype.set=function(a,b){A("clearTimeout",this.g);var c=this;this.g=A("setTimeout",function(){delete c.g;b&&b()},a)};z.prototype.clear=function(){A("clearTimeout",this.g);delete this.g};function B(a,b){if(Array.isArray(a))return(new b.Array(...a)).map(c=>B(c,b));if(null!==a&&"object"===typeof a){const c={};Object.entries(a).forEach(([d,e])=>c[d]=B(e,b));return c}return a}
if(void 0===C)var C=function(a){return D.g?(Array.prototype.toJSON&&(a=B(a,D.g.window)),D.g.window.JSON.stringify(a)):JSON.stringify(a)};B=function(a,b){if(Array.isArray(a))return(new b.Array(...a)).map(c=>B(c,b));if(null!==a&&"object"===typeof a){const c={};Object.entries(a).forEach(([d,e])=>c[d]=B(e,b));return c}return a};
function da(a){a.H=0;a.I=0;a.T=new z;a.S=new z;a.onclose=function(b){a.T.clear();a.S.clear();a.ca&&a.ca(b)};a.onmessage=function(b){b=JSON.parse(b.data);a.R&&a.R(b);a.ping()};a.A=function(b){b=C(b);a.readyState!==WebSocket.OPEN?u(`Tried to send message on closed websocket: ${b}`):a.send(b)};a.$=function(b){return b&&b.code||0};a.aa=function(b){return b&&b.reason||""};a.ia=function(b,c){this.H=b;this.I=c;this.ping()};a.ping=function(){0<a.H&&a.T.set(1E3*a.H,()=>a.A({mtype:"Ping"}));0<a.I&&a.S.set(1E3*
a.I,()=>a.onerror(new Event("WS_PING_TIMEOUT")))}}function ea(a){a=new WebSocket(a);da(a);return a}function fa(a,b){A("setTimeout",function(){fa(a,b)},100)}function E(a,b){if(void 0!==a){var c=c||Object.keys(a);c.forEach(function(d){void 0!==a[d]&&(b[d]=a[d])})}}
function ha(a){var b=a.func.split(".");if(2>b.length)u("ERR_BADINVOKE:");else if("GLANCE"===b[0]||"GLANCE_COBROWSE"===b[0]&&"Custom"===b[1]){for(var c=window[b[0]],d=1;d<b.length;d++)if(c=c[b[d]],!c){u("ERR_UNDEFINVOKE:"+b[d]);return}a.args=a.args||{};a.args.remote=!0;c(a.args)}else u("ERR_BADINVOKE:"+b[0])}function F(){ca.ja?this.j=new G("JSON"):this.g=new window.XMLHttpRequest;this.response=null;this.type="JSON"}F.prototype.abort=function(){this.j?this.j.abort():this.g.abort()};
F.prototype.onreadystatechange=function(){if(4==this.g.readyState){A("clearTimeout",this.l);delete this.l;var a="error";if(0==this.g.status)t(this.method+" to "+this.url+" failed: network"),this.h(!0,"connection",this.g.status);else if(200!==this.g.status){u(this.method+" to "+this.url+" failed with status: "+this.g.status);"text"===this.g.responseType&&null!==this.g.responseText&&t(this.g.responseText);if(401===this.g.status||403===this.g.status)a="authorization",this.i&&this.i.ga();this.h(!1,a,
this.g.status)}else{if(""!==this.g.response){if("XML"===this.accept)this.response=this.g.responseXML&&this.g.responseXML.documentElement,null===this.response&&u("Invalid XML response: "+this.g.responseText);else if(this.B){for(var b=new Uint8Array(this.g.responseText.length),c=0;c<this.g.responseText.length;c++)b[c]=this.g.responseText.charCodeAt(c)&255;this.response=new Blob([b],{type:this.g.getResponseHeader("Content-Type")})}else if("blob"===this.g.responseType)this.response=this.g.response;else if(this.g.responseXML)this.response=
ia(this.g.responseXML.childNodes[0].childNodes[0].nodeValue);else if("HTML"===this.accept||"TEXT"===this.accept)this.response=this.g.responseText;else if(this.response=ia(this.g.responseText),null===this.response){t(this.method+" to "+this.url+" failed - can't parse response "+this.g.responseText);this.h(!1,a);return}if(void 0!==this.response.err&&void 0!==this.response.msg){t(this.method+" to "+this.url+" failed with error:"+this.response.err+" "+this.response.msg);this.h(!1,a);return}}this.onsuccess(this.response)}}};
function ia(a){var b=null;try{b=JSON.parse(a)}catch(c){return t("JSON parse failed with error: "+c.toString()+" parsing: "+a),null}return b}F.prototype.getResponseHeader=function(a){return this.g.getResponseHeader(a)};F.prototype.get=function(a,b,c,d,e){this.method="GET";H(this,a,null,b,c,d,e)};
function H(a,b,c,d,e,h,f){a.url=b;a.onsuccess=void 0!==h?h:function(){};a.h=void 0!==f?f:function(){};a.method=a.method||"POST";if(a.j)ja(a.j,b,c,d,e,h,f);else{h=a.C||("JSON"===a.type?"application/json; charset=utf-8":"application/x-www-form-urlencoded; charset=utf-8");if("string"===typeof c)var v=c;else c instanceof Blob?(h=c.type,v=c):c&&(v="JSON"===a.type?C(c):"data="+C(c));y.safari&&a.s&&(a.l=A("setTimeout",function(){t(this.method+" to "+this.url+" failed - timedout (Safari)");this.h(!1,"timedout")}.bind(a),
a.s));a.g.onreadystatechange=function(){a.onreadystatechange()};try{a.g.open(a.method,b,d),void 0!==a.m&&a.g.setRequestHeader("Accept",a.m),void 0!==a.g.setRequestHeader&&"GET"!==a.method&&a.g.setRequestHeader("Content-type",h),a.i&&a.i.ba()?a.g.setRequestHeader("Authorization","Bearer "+a.i.ba()):a.o&&a.g.setRequestHeader("Authorization","Bearer "+a.o),a.g.withCredentials=e,a.g.send(v)}catch(q){t(a.method+" to "+b+" failed with: "+q.toString()),a.h(!1,q.toString())}}}function G(a){this.type=a}
function ja(a,b,c,d,e,h,f){a.onsuccess=h;a.h=f;fa({from:"IFrameProxyRequest",type:a.type,url:b,obj:c,async:d,withcred:e})}G.prototype.abort=function(){G.postMessage({from:"IFrameProxyRequest",abort:!0})};function I(a){this.name=a}function ka(a,b){var c=new Date;c.setUTCHours(c.getUTCHours()+8);try{window.localStorage.setItem(a.name,C(b)),window.localStorage.setItem(a.name+"_exp",c.toGMTString())}catch(d){t("Failed to write cookie: "+a.name)}}
function la(a){if(!ma(a))return null;var b=null;try{b=window.localStorage.getItem(a.name)}catch(c){return t("Failed to read cookie: "+a.name),null}return JSON.parse(b)}function oa(a,b){"string"===typeof b&&(b=parseInt(b));var c=new Date;c.setUTCMinutes(c.getUTCMinutes()+b);try{window.localStorage.setItem(a.name+"_exp",c.toGMTString())}catch(d){t("Failed to write cookie: "+a.name)}}
I.prototype.get=function(){if(!ma(this))return null;try{return window.localStorage.getItem(this.name)}catch(a){return t("Failed to read cookie: "+this.name),null}};function J(a){try{window.localStorage.removeItem(a.name),window.localStorage.removeItem(a.name+"_exp")}catch(b){t("Failed to delete cookie: "+a.name)}}
function ma(a){var b=null;try{b=window.localStorage.getItem(a.name+"_exp")}catch(c){return t("Failed to read cookie: "+a.name),!1}if(!b)return!1;b=new Date(b);return b<new Date?(J(a),!1):!0}
function K(){var a=window;this.g=a.document;this.i=a;var b=[["hidden","visibilitychange"],["mozHidden","mozvisibilitychange"],["webkitHidden","webkitvisibilitychange"],["msHidden","msvisibilitychange"],["oHidden","ovisibilitychange"]];for(a=0;a<b.length;a++)if(b[a][0]in document){this.h=b[a][0];this.j=b[a][1];break}}function L(a){return void 0===a.h?!1:a.g[a.h]}function pa(a,b){a.g.addEventListener(a.j,b)}function D(){}
function A(a,...b){var c=window;return D.g&&c.nodeType?"#document"===c.nodeName?D.g.document[a].apply(c,b):"#document-fragment"===c.nodeName?D.g.DocumentFragment.prototype[a].apply(c,b):D.g.document.body[a].apply(c,b):D.g&&"[object Window]"===c.toString()?D.g.window[a].apply(c,b):c[a].apply(c,b)};function qa(a,b){if(void 0!==a){var c=c||Object.keys(a);c.forEach(function(d){void 0!==a[d]&&(b[d]=a[d])})}}function ra(a){var b={};if(!a)return b;var c=0;for(a=a.attributes;c<a.length;c++){var d=a[c].nodeName.match(/data-(.*)/);d&&2===d.length&&(b[d[1]]=a[c].nodeValue)}return b}function sa(){var a=window.GLANCE_COBROWSE?window.GLANCE_COBROWSE:{},b=document.getElementById("cobrowsescript"),c=document.getElementById("glance-cobrowse");b=ra(b);c=ra(c);qa(b,a);qa(c,a);return a};function M(){}function ta(a,b){a.g={};a.g.ws="www.glance.net";a.g.site="production";a.o=new K;E(sa(),a.g);E(b,a.g);delete a.g.presenceserver;a.B=!1;a.P=new z;a.F=[];a.j=N;a.m=new I("glance_presence");var c=la(a.m);c&&(0===["visitorid","ws","groupid"].filter(d=>c[d]!==a.g[d]).length?a.i=c.directserver:x("Ignoring glance_presence entry for different webserver, group, or visitor",c.ws,c.groupid,c.visitorid));x("direct server from local storage:",a.i)}var N=1;M.prototype.J=function(){};
function ua(a,b,c,d,e){if(b&&!a.i)p("ERR_NODIRECTSERVER");else{var h=(e||"https")+"://"+(b?a.i:a.g.presenceserver)+"/"+c;d&&(h+="?",["groupid","visitorid"].forEach(function(f){h+=f+"="+a.g[f]+"&"}),h+=`&ver=${k}`);return h}}M.prototype.L=function(a){O(this,"findvisitor","GET",a)};
function P(a){p("connecting to "+a.i);a.h&&a.h.close();a.h=ea(ua(a,!0,"visitorws",!1,"wss"));a.h.U=a.i;a.h.onopen=function(){x("sock onopen, sending connect");a.h.A({type:"connect",authorization:void 0,groupid:a.g.groupid,visitorid:a.g.visitorid,guesttoken:a.g.guesttoken,version:k});a.s=0;x("sending message queue");a.F.forEach(function(b){a.h.A(b)});a.F=[];a.j=3};a.h.R=function(b){p("received:"+C(b));if(a.h){var c=h=>{a.P.clear();if(!a.B&&(a.B=!0,a.onvisitorconn))a.onvisitorconn(h)},d=b.mtype||b.type,
e=b.data;switch(d){case "connected":if(a.g.nokeepalive)break;x("Keepalive interval: "+b.keepalive);a.C||(a.C=window.setInterval(function(){a.h.A({type:"k"})},1E3*b.keepalive));if(a.onconnected)a.onconnected(e);break;case "invoke":"visitor"===a.W&&ha(e);break;case "redirect":case "serverclose":e||(e=b);a["on"+d](e);break;case "visitorsock":e.connected?c(e):!e.connected&&a.B&&a.P.set(5E3,()=>{a.B=!1;if(a.onvisitorconn)a.onvisitorconn(e)});break;case "visitorconn":e.connected&&c(e);break;default:if(a["on"+
d])a["on"+d](e)}}else x("Ignoring message received after socket close")};a.h.onclose=function(b){a.h===this&&(p(`presence connection closed ${this.$(b)} ${this.aa(b)}`),va(a),Q(a))};a.h.onerror=function(b){a.h===this&&(x("socket error"),a.h.onclose(b))}}
function O(a,b,c,d){function e(q){var w=q&&(q.directserver||q.direct);w&&(f.i=w,q.httpsport&&(f.i+=":"+q.httpsport),f.J());f.h&&f.i!=f.h.U&&(x("switching connection from "+f.h.U+" to "+f.i),P(f));if(d&&d.onsuccess)d.onsuccess(q)}function h(q,w,na){p(`Presence request: ${b} failed reason: ${w} http status: ${na||0}`);503===na&&(ba("Presence service unavailable"),f.O=!0,w="serviceunavailable");if(d.onfail)d.onfail(w);else R(f,{error:"connfail",detail:w})}if(!a.O){var f=a,v=new F;v.i=void 0;v.method=
c;p(b,JSON.stringify(d));wa(a,function(){f.g.presenceserver&&H(v,ua(f,!1,b,!0),d.data?d.data:{},!0,!1,e,h)})}}
function wa(a,b){if(a.g.presenceserver)b();else{var c=new I("glance_visitor_settings_"+a.g.groupid+"_"+a.g.site),d=la(c);if(d)a.g.presenceserver=d.presenceserver,a.g.isLoadBalanced=d.presencesettings.isPresenceLoadBalanced,a.g.isLoadBalanced&&(a.i=a.g.presenceserver),a.g.presenceserver||p("PRES_DISABLED (from cache)"),b();else{d=new F;var e="https://"+a.g.ws+"/services/authorizationservice/GetVisitorSettings3?groupid="+a.g.groupid+"&site="+a.g.site+"&service=presence";d.method="GET";H(d,e,null,!0,
!1,h=>{a.g.presenceserver=h.presenceUrl;h.isPresenceLoadBalanced&&(a.g.isLoadBalanced=h.isPresenceLoadBalanced,a.i=h.presenceUrl);x("presence service: "+a.g.presenceserver);a.g.presenceserver||p("PRES_DISABLED");var f={};f.presenceserver=a.g.presenceserver;f.presencesettings=h;ka(c,f);oa(c,1440);return b()},(h,f)=>{p("PRES_UNAVAILABLE "+f);b()})}}}function S(a){x("closewebsocket");a.h&&a.h.close();va(a)}
function va(a){a.C&&(window.clearInterval(a.C),delete a.C);a.j=N;a.g.isLoadBalanced||(delete a.h,delete a.i)}function T(a,b){p("sending",b.type,a.j);3===a.j?(x("sending message: "+JSON.stringify(b)),a.h.A(b)):(x("queuing message: "+JSON.stringify(b)),a.F.push(b),a.connect())}M.prototype.V=function(a){let b=3===this.j;b&&this.disconnect();this.g.visitorid=a;(b||"api"!==this.g.presence)&&this.connect()};M.prototype.setVisitorId=M.prototype.V;
M.prototype.connect=function(){if(!this.O)if(this.g.visitorid)if(this.j!==N)x("connect() called when already connecting or connected");else{this.j=2;x("connect");var a=this;this.onscaledown=function(){a.disconnect();a.connect()};this.onredirect=function(b){x("Connected to wrong instance:",JSON.stringify(b),"current direct server:",this.i);this.m&&b.direct!==this.i&&(J(this.m),this.m=new I("glance_presence"),this.disconnect(),Q(this))};this.onserverclose=function(){a.disconnect();if(a.onclose)a.onclose()};
wa(this,()=>{p("visitor settings loaded");this.i?P(this):this.L({onsuccess:function(){p("found visitor, connect");P(a)},onfail:function(b){a.j=N;R(a,{error:"connfail",detail:b})}})})}else p("CONN_NOVISITORID")};M.prototype.connect=M.prototype.connect;M.prototype.disconnect=function(){S(this);this.m&&J(this.m)};M.prototype.disconnect=M.prototype.disconnect;
function Q(a){x(`delayed reconnect.  count: ${a.s||0} connstate: ${a.j}`);a.K||(a.s=a.s||0,a.s++,a.K=window.setTimeout(()=>{delete a.K;a.connect()},3>=a.s?5E3:6E4))}function R(a,b){p("Error: ",JSON.stringify(b));a.M&&a.M(b);if(a.onerror)a.onerror(b)}M.prototype.Z=function(a,b){T(this,{type:a,data:b})};M.prototype.fire=M.prototype.Z;function U(a){ta(this,a);this.W="visitor";this.o=new K;this.G=!1;var b=this;A("addEventListener","focus",function(){x("presence visitor got focus event");b.D=!1;b.N&&b.v()},void 0);pa(this.o,function(){if(!b.G&&(x("visibility:",L(b.o)?"hidden":"visible"),(b.N||3===b.j)&&!b.D)){var c={type:"visibility"};c.data={visibility:L(b.o)?"hidden":"visible"};T(b,c);L(b.o)&&S(b)}});U.instance=this}var xa=U,V=["GLANCE","Presence","Visitor"],W=aa;
V[0]in W||"undefined"==typeof W.execScript||W.execScript("var "+V[0]);for(var X;V.length&&(X=V.shift());)V.length||void 0===xa?W[X]&&W[X]!==Object.prototype[X]?W=W[X]:W=W[X]={}:W[X]=xa;U.prototype=new M;U.prototype.J=function(){x("caching direct server:",this.i);var a={};a.directserver=this.i;a.groupid=this.g.groupid;a.visitorid=this.g.visitorid;a.ws=this.g.ws;ka(this.m,a);oa(this.m,20)};
U.prototype.v=function(a){x("presence");if(this.g.visitorid){this.l=this.l||{};for(var b in this.g)0===b.indexOf("user-")&&(this.l[b.substring(5)]=this.g[b]);this.l.url=window.location.href;this.l.browser=y.name;this.l.browserver=y.version;this.l.platform=y.u.name;(a=a&&a.data)&&E(a,this.l);this.D||(a={type:"presence"},a.data=this.l,T(this,a),this.N=!0);this.M=function(c){"connfail"===c.error&&Q(this)}}else p("PRES_NOVISITORID")};U.prototype.presence=U.prototype.v;
U.prototype.X=function(a){var b=this;this.G=!0;O(this,"uniquevisitor","GET",{onsuccess:function(c){p("got unique visitor id",c.visitorid);b.g.visitorid=c.visitorid;b.g.guesttoken=c.guesttoken;b.g.timeout=c.timeout||300;if(b.onuniqueid)b.onuniqueid(c.uniqueid,b.g.timeout);b.connect();a&&a.data&&b.v({data:a.data})},onfail:function(c){R(b,{error:"connfail",detail:c})}})};U.prototype.connectUnique=U.prototype.X;
U.prototype.Y=function(){this.G?3===this.j?(this.disconnect(),this.v()):R(this,{error:"connfail",detail:"extend"}):console.error("ERR_EXTEND_UNIQUE")};U.prototype.extendUnique=U.prototype.Y;U.setVisitorId=function(a){U.instance&&U.instance.V(a)};U.prototype.L=function(a){this.g.isLoadBalanced||(a.data={},O(this,"presence","POST",a))};U.prototype.onblur=function(){p("BLURRED");this.D=!0;S(this)};var ya=!1;function Y(){if(!ya){ya=!0;var a=sa();a.presence&&"api"!==a.presence&&(new U).v()}}var Z=new K;
Z.i.addEventListener&&(document.readyState.match(/complete/)?Y():(Z.i.addEventListener("load",Y),Z.g.addEventListener("DOMContentLoaded",Y,!1)));}).call(window);
//# sourceMappingURL=map.js.map
