(function() {/*
 Copyright 2022 Glance Networks, Inc.
*/
function m(a,...c){!window.console||!window.console[a]||window.GLANCE_COBROWSE&&window.GLANCE_COBROWSE.disableLogging||(c=c.map(b=>{if("object"===typeof b)try{b=JSON.stringify(b)}catch(f){console.error(f),b="unable to convert object to string"}return"string"===typeof b?b.replace(/[\r\n]/g," ").replace("<","&lt;"):b}),window.console[a](...c))}function p(...a){m("log",...a)}function x(...a){m("error",...a)}function y(...a){p("DEBUG:",...a)};/*
 Copyright (c) 2022 Glance Networks, Inc.
*/
window.GLANCE=window.GLANCE||{};window.GLANCE.VERSION="6.33.0.1480702263";window.GLANCE.PATCH="";window.GLANCE.Lib=window.GLANCE.Lib||{};
(function(){var a=navigator.userAgent.toLowerCase(),c=navigator.platform.toLowerCase(),b=a.match(/(edge|edg)[\s\/:]([\w\d\.]+)?/)||a.match(/(opera|ie|firefox|chrome|crios|version)[\s\/:]([\w\d\.]+)?.*?(safari|version[\s\/:]([\w\d\.]+)|$)/)||a.match(/(rv):([\w\d\.]+)/)||[null,"unknown",0];"edg"===b[1]&&(b[1]="edge");"crios"===b[1]?b[1]="chrome":"rv"===b[1]&&(b[1]="ie");a={extend:Function.prototype.extend,name:"version"==b[1]?b[3]:b[1],version:"ie"==b[1]&&document.documentMode||parseFloat("opera"==
b[1]&&b[4]?b[4]:b[2]),l:{name:a.match(/ip(?:ad|od|hone)/)||c.match(/mac/)&&0<typeof navigator.maxTouchPoints?"ios":(a.match(/(?:webos|android)/)||c.match(/mac|win|linux/)||["other"])[0]},F:{J:!!document.evaluate,H:!!window.g,query:!!document.querySelector,json:!!window.JSON},G:{},I:function(){return"ios"==this.l.name||"android"==this.l.name}};document.documentMode&&window.XDomainRequest?(a.name="ie",a.version=document.documentMode):window.navigator&&navigator.appVersion&&-1!=navigator.appVersion.indexOf("MSIE 7.")&&
(a.name="ie",a.version="7");a[a.name]=!0;a[a.name+parseInt(a.version,10)]=!0;a.l[a.l.name]=!0;return a})();function z(a,c){if(Array.isArray(a))return(new c.Array(...a)).map(b=>z(b,c));if(null!==a&&"object"===typeof a){const b={};Object.entries(a).forEach(([f,k])=>b[f]=z(k,c));return b}return a}if(void 0===aa)var aa=function(a){return A.g?(Array.prototype.toJSON&&(a=z(a,A.g.window)),A.g.window.JSON.stringify(a)):JSON.stringify(a)};
z=function(a,c){if(Array.isArray(a))return(new c.Array(...a)).map(b=>z(b,c));if(null!==a&&"object"===typeof a){const b={};Object.entries(a).forEach(([f,k])=>b[f]=z(k,c));return b}return a};function B(a,c,b){E(window,"addEventListener",a,c,b)}function F(a,c,b){var f={};f[c]=b;a.postMessage(f,"*")}function G(a,c){E(window,"addEventListener","message",function(b){if("string"===typeof b.data)try{var f=JSON.parse(b.data)}catch(k){return!1}else f=b.data;void 0!==f[a]&&c(b.source,f[a])})}
function H(){this.name="glance_ssn_info";var a=new M,c=a.h.location.hostname;for(a=a.h;""===c&&a.parent!==a;)c=a.parent.location.hostname,a=a.parent;this.domain=ba(c)}H.prototype.get=function(){return this.i()?decodeURIComponent(document.cookie.replace(new RegExp("(?:^|.*;\\s*)"+encodeURIComponent(this.name).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=\\s*((?:[^;](?!;))*[^;]?).*"),"$1")):null};
H.prototype.j=function(){var a=new Date;a.setDate(a.getDate()-1);document.cookie=encodeURIComponent(this.name)+"=; expires="+a.toGMTString()+"; domain="+this.domain+"; path=/"};H.prototype.i=function(){return(new RegExp("(?:^|;\\s*)"+encodeURIComponent(this.name).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=")).test(document.cookie)};function N(){this.name="glance_ssn_info"}
N.prototype.get=function(){if(!this.i())return null;try{return window.localStorage.getItem(this.name)}catch(a){return p("Failed to read cookie: "+this.name),null}};N.prototype.j=function(){try{window.localStorage.removeItem(this.name),window.localStorage.removeItem(this.name+"_exp")}catch(a){p("Failed to delete cookie: "+this.name)}};
N.prototype.i=function(){var a=null;try{a=window.localStorage.getItem(this.name+"_exp")}catch(c){return p("Failed to read cookie: "+this.name),!1}if(!a)return!1;a=new Date(a);return a<new Date?(this.j(),!1):!0};function P(){this.g=[new H,new N]}P.prototype.get=function(){return this.g[0].get()||this.g[1].get()};P.prototype.j=function(){this.g[0].j();this.g[1].j()};P.prototype.i=function(){return this.g[0].i()||this.g[1].i()};
function M(){var a=window;this.g=a.document;this.h=a;var c=[["hidden","visibilitychange"],["mozHidden","mozvisibilitychange"],["webkitHidden","webkitvisibilitychange"],["msHidden","msvisibilitychange"],["oHidden","ovisibilitychange"]];for(a=0;a<c.length&&!(c[a][0]in document);a++);}
function ba(a){var c=new RegExp(/^(?:[a-z]{1,5}:\/\/|)([^:\?\/]*)/),b=a.match(/^\d+\.\d+.\d+.\d+$/);c=c.exec(a);if(b)return a;if(null===c||2!==c.length)return"about:"!==a&&p("ERR_DOMAINPARSE: "+a),null;b=c[1].split(".");return 1===b.length?(p("ERR_DOMAINPARSE: "+a),null):2===b.length?b.join("."):3===b.length?b.slice(1).join("."):4>=b[b.length-2].length?b.slice(b.length-3).join("."):b.slice(b.length-2).join(".")}M.prototype.getElementsByTagName=function(a){return E(this.g,"getElementsByTagName",a)};
function Q(a,c,b,f){var k=a.g.createElement("script");b&&k.addEventListener("load",b);f&&k.addEventListener("error",f);k.setAttribute("type","text/javascript");k.setAttribute("charset","UTF-8");for(b=0;b<c.length;b++)k.setAttribute(c[b][0],c[b][1]);a.g.head.appendChild(k)}M.prototype.head=function(){return void 0!==this.g.head?this.g.head:this.getElementsByTagName("head")[0]};
function R(a,c){a.h.addEventListener&&(document.readyState.match(/complete/)?c():(a.h.addEventListener("load",c),a.g.addEventListener("DOMContentLoaded",c,!1)))}M.prototype.addEventListener=function(a,c,b){E(this.g,"addEventListener",a,c,b)};function A(a){this.g=a}A.prototype.addEventListener=function(a,c,b){E(this.g,"addEventListener",c,b)};
function E(a,c,...b){return A.g&&a.nodeType?"#document"===a.nodeName?A.g.document[c].apply(a,b):"#document-fragment"===a.nodeName?A.g.DocumentFragment.prototype[c].apply(a,b):A.g.document.body[c].apply(a,b):A.g&&"[object Window]"===a.toString()?A.g.window[c].apply(a,b):a[c].apply(a,b)}function S(){this.listeners=this.g={}}S.prototype.add=function(a,c){this.g[a]=this.g[a]||[];this.g[a].push(c)};function T(a,c){if(void 0!==a){var b=b||Object.keys(a);b.forEach(function(f){void 0!==a[f]&&(c[f]=a[f])})}}function U(a){var c={};if(!a)return c;var b=0;for(a=a.attributes;b<a.length;b++){var f=a[b].nodeName.match(/data-(.*)/);f&&2===f.length&&(c[f[1]]=a[b].nodeValue)}return c}function ca(){var a=window.GLANCE_COBROWSE?window.GLANCE_COBROWSE:{},c=document.getElementById("cobrowsescript"),b=document.getElementById("glance-cobrowse");c=U(c);b=U(b);T(c,a);T(b,a);return a};var da=["6","33","0","1480702263"].slice(0,3).join(".")+"M";
function ea(){this.h=document.getElementById("cobrowsescript")||document.getElementById("glance-cobrowse");document.getElementById("glance-cobrowse");if(null!==this.h){var a=ca();T(a,this);var c=RegExp("//(.*)/").exec("string"===typeof this.h.src?this.h.src:a.scriptserver+"/");this.g=c&&2===c.length?c[1]:"www.glancecdn.net/cobrowse";this.g=this.g.replace("/js","");a.cbexperiment&&(this.g=this.g.replace("cobrowse","cbexperiment"));this.m=a.groupid||this.h.getAttribute("groupid");this.D=a.ws||this.h.getAttribute("ws")||
"www.glance.net";this.D.match("\\.glance\\.net$");this.C=a.ui;this.uri=a.uri;this.B=a.site||this.h.getAttribute("site")||"production";this.v=JSON.parse(a.inputevents||"{}");this.A=a.presence;if(!this.m)throw Error("data-groupid missing");a=a.additionalgroupids||"";this.o=[this.m].concat(a?a.split(","):[]);this.o=this.o.map(function(b){if(!parseInt(b))throw Error("data-groupid invalid: "+b);return parseInt(b)});if(!/staging|production/i.test(this.B))throw Error("data-site invalid");}};function V(){return 0<window.location.href.indexOf("GlanceSession=1")};window.GLANCE=window.GLANCE||{};window.GLANCE.Cobrowse=window.GLANCE.Cobrowse||{};
function W(){function a(d){function e(q,C,I){return function(D){D.keyCode===C&&D[q+"Key"]&&(D=I.match(/showButton|toggleButton|showTerms/)?"VisitorUI":"Visitor",k(D,I)||(y("inputevent:",I),window.GLANCE.Cobrowse[D][I]()))}}for(var h in d)if(d.hasOwnProperty(h)){var l=h.match(/(ctrl|alt|shift)-(\d*)/);!l||3>l.length||B("keydown",e(l[1],parseInt(l[2]),d[h]),!0)}}function c(d){function e(h){return function(l){var q=h.match(/showButton|toggleButton|showTerms/)?"VisitorUI":"Visitor";l.stopPropagation();
l.preventDefault();k(q,h)||(y("button click",q,h),r[q][h]())}}["glance_button","data-glancebutton"].forEach(function(h){for(var l=d.querySelectorAll("["+h+"]"),q=0;l&&q<l.length;q++){var C=l[q].getAttribute(h);"start"===C&&(C="startSession");l[q].addEventListener("click",e(C))}})}function b(){return r.Visitor}function f(d,e){r[e][d]=function(h){d.match(/showButton|toggleButton|showTerms/)&&"Visitor"==e&&(e="VisitorUI");h&&h.groupid&&(r.Loader.groupid=h.groupid);v(function(){r[e][d](h)},e)}}function k(d,
e){if(!w)return!1;y("forward event:",d,e);F(window.top,"forwardevent",{namespace:d,funcname:e});return!0}function O(d){p("SCRIPT_NOT_LOADED:"+d);const e={};e.msg="SCRIPT_NOT_LOADED:"+d;e.code="scriptloadfailed";e.params={script:d};d=J;e&&JSON.stringify(e);var h=d.g.error;if(void 0!==h)for(d=0;d<h.length;d++)try{h[d](e)}catch(l){x("Exception in : GLANCE.Lib.EventListeners.fire. Event : error, error : "+l.toString())}}function v(d,e){e=e||"Visitor";if(E(t.g,"getElementById",("glance_"+e).toLowerCase()))r[e].loaded?
d&&d():d&&O(e);else if(d&&(X._onload[e]=d),w||"Visitor"!==e||u.C||v(null,"VisitorUI"),Q(t,[["id",("glance_"+e).toLowerCase()],["src",K+"/GlanceCobrowse"+e+"_"+L+".js"]],null,()=>O(e)),"Visitor"===e){var h=document.getElementsByTagName("iframe");for(d=0;d<h.length;d++)h[d].contentWindow&&F(h[d].contentWindow,"glance_load",{s:!0})}}window.GLANCE.runTroubleshooter=function(){Q(t,[["src","https://"+u.g+"/js/Troubleshooter.js"]])};window.GLANCE.checkHTML=function(){Q(t,[["src","https://"+u.g+"/js/HTMLChecker.js"]])};
if(window.localStorage&&window.XMLHttpRequest&&window.atob){var w=window.parent!==window,t=new M,Y=!1,u=new ea,L=da,r=window.GLANCE.Cobrowse,K="//"+u.g+"/js";if(!u.g)if(window.console&&window.console.error)x("ASSERT");else throw Error("ASSERT");var J=new S,n=u.h;if(r.Loader&&n&&n.getAttribute("data-loaded"))p("ERR_DUP_SCRIPTS");else{n&&n.setAttribute("data-loaded",!0);var Z=null;n=new Promise(d=>{Z=()=>{d()}});var X={load:function(d){v(d)},loadScript:function(d,e){Q(t,[["src",K+"/"+d+"_"+L+".js"]],
e,()=>{O(d)})},setUIReady:Z,_uiready:n,_eventListeners:J,_onload:{},_origpath:document.baseURI,groupid:function(){var d=(new P).get();if(!d)return null;let e;return null==(e=JSON.parse(d).ssnid)?void 0:e.split(".")[0]}()};G("glance_load",function(d,e){d&&(d!==window.parent&&d.parent!==window?p("UNTRUSTED_LOAD_MSG"):(e.s&&v(),e.u&&null!==E(t.g,"getElementById","glance_visitor")&&F(d,"glance_load",{s:!0})))});w&&F(window.parent,"glance_load",{u:!0});window.addEventListener("message",function(d){if("string"!==
typeof d.data){if(b().loaded)return!0;d.data.glance_invoke&&v(()=>{b()._handleInvokeMessage(d)})}});B("focus",function(){if(b().loaded)return!0;b().inSession()&&v()});r.Visitor={loaded:!1,inSession:function(){return(new P).i()},addEventListener:function(d,e){J.add(d,e)},removeEventListener:function(d,e){d=J.g[d];void 0!==d&&(e=d.indexOf(e),0<=e&&d.splice(e,1))}};n=["showButton","toggleButton","showTerms","setStyle"];w||(r.VisitorUI={},n.forEach(function(d){f(d,"VisitorUI")}));n=n.concat(["startSession",
"setStartParams"]);n.forEach(function(d){f(d,"Visitor")});r.Loader=X;w||V()||!b().inSession()||v();!w&&V()&&v(null,"XDOM");R(t,function(){document.body&&!Y&&(Y=!0,c(document.body),a(u.v),u.A&&!w&&Q(t,[["src",K+"/GlancePresenceVisitor_"+L+".js"]]),u.collection&&!w&&Q(t,[["src",K+"/GlanceSessionMetrics_"+L+".js"]],()=>{let d=document.getElementById("glance-cobrowse");(new window.GLANCE.VisitorSessionMetrics({group_id:d.dataset.groupid,web_server:d.dataset.ws,site:d.dataset.site})).run()}))});G("forwardevent",
function(d,e){y("received forwarded event:",e);if(d.top!==window)p("UNTRUSTED_KEYEVT");else window.GLANCE.Cobrowse[e.namespace][e.funcname]()})}}else x("ERR_COBROWSE_NOT_SUPP")}document.getElementById("cobrowsescript")||document.getElementById("glance-cobrowse")?W():(p("LOADER_PAGE_NOT_READY"),R(new M,W));}).call(window);
//# sourceMappingURL=map.js.map
