(function() {/*
 Copyright 2022 Glance Networks, Inc.
*/
function f(a,...c){!window.console||!window.console[a]||window.GLANCE_COBROWSE&&window.GLANCE_COBROWSE.disableLogging||(c=c.map(b=>{if("object"===typeof b)try{b=JSON.stringify(b)}catch(d){console.error(d),b="unable to convert object to string"}return"string"===typeof b?b.replace(/[\r\n]/g," ").replace("<","&lt;"):b}),window.console[a](...c))}function k(...a){f("log",...a)}function l(...a){f("error",...a)}function m(...a){k("XDOM:",...a)};/*
 Copyright (c) 2022 Glance Networks, Inc.
*/
var n=n||{};window.GLANCE=window.GLANCE||{};window.GLANCE.VERSION="6.33.0.1480702263";window.GLANCE.PATCH="";window.GLANCE.Lib=window.GLANCE.Lib||{};
var p=function(){var a=navigator.userAgent.toLowerCase(),c=navigator.platform.toLowerCase(),b=a.match(/(edge|edg)[\s\/:]([\w\d\.]+)?/)||a.match(/(opera|ie|firefox|chrome|crios|version)[\s\/:]([\w\d\.]+)?.*?(safari|version[\s\/:]([\w\d\.]+)|$)/)||a.match(/(rv):([\w\d\.]+)/)||[null,"unknown",0];"edg"===b[1]&&(b[1]="edge");"crios"===b[1]?b[1]="chrome":"rv"===b[1]&&(b[1]="ie");a={extend:Function.prototype.extend,name:"version"==b[1]?b[3]:b[1],version:"ie"==b[1]&&document.documentMode||parseFloat("opera"==
b[1]&&b[4]?b[4]:b[2]),u:{name:a.match(/ip(?:ad|od|hone)/)||c.match(/mac/)&&0<typeof navigator.maxTouchPoints?"ios":(a.match(/(?:webos|android)/)||c.match(/mac|win|linux/)||["other"])[0]},D:{N:!!document.evaluate,G:!!window.g,query:!!document.querySelector,json:!!window.JSON},F:{},I:function(){return"ios"==this.u.name||"android"==this.u.name}};document.documentMode&&window.XDomainRequest?(a.name="ie",a.version=document.documentMode):window.navigator&&navigator.appVersion&&-1!=navigator.appVersion.indexOf("MSIE 7.")&&
(a.name="ie",a.version="7");a[a.name]=!0;a[a.name+parseInt(a.version,10)]=!0;a.u[a.u.name]=!0;return a}();function q(a,c){if(Array.isArray(a))return(new c.Array(...a)).map(b=>q(b,c));if(null!==a&&"object"===typeof a){const b={};Object.entries(a).forEach(([d,e])=>b[d]=q(e,c));return b}return a}if(void 0===r)var r=function(a){return t.g?(Array.prototype.toJSON&&(a=q(a,t.g.window)),t.g.window.JSON.stringify(a)):JSON.stringify(a)};
q=function(a,c){if(Array.isArray(a))return(new c.Array(...a)).map(b=>q(b,c));if(null!==a&&"object"===typeof a){const b={};Object.entries(a).forEach(([d,e])=>b[d]=q(e,c));return b}return a};function u(a,c){w(window,"setTimeout",function(){u(a,c)},100)}function x(a){var c=window.opener,b={};b.glance_xdomain=a;c.postMessage(b,"*")}
function z(a,c){w(window,"addEventListener","message",function(b){if("string"===typeof b.data)try{var d=JSON.parse(b.data)}catch(e){return!1}else d=b.data;void 0!==d.glance_xdomain&&(c&&!A(b.origin,c)?l("UNTRUSTED_ORIGIN:"+b.origin+" "+JSON.stringify(d)):a(b.source,d.glance_xdomain))})}function B(){n.L?this.j=new C("JSON4"):this.g=new window.XMLHttpRequest;this.response=null;this.type="JSON4"}B.prototype.abort=function(){this.j?this.j.abort():this.g.abort()};
B.prototype.onreadystatechange=function(){if(4==this.g.readyState){w(window,"clearTimeout",this.o);delete this.o;var a="error";if(0==this.g.status)k(this.method+" to "+this.url+" failed: network"),this.h(!0,"connection",this.g.status);else if(200!==this.g.status){l(this.method+" to "+this.url+" failed with status: "+this.g.status);"text"===this.g.responseType&&null!==this.g.responseText&&k(this.g.responseText);if(401===this.g.status||403===this.g.status)a="authorization",this.i&&this.i.H();this.h(!1,
a,this.g.status)}else{if(""!==this.g.response){if("XML"===this.accept)this.response=this.g.responseXML&&this.g.responseXML.documentElement,null===this.response&&l("Invalid XML response: "+this.g.responseText);else if(this.K){for(var c=new Uint8Array(this.g.responseText.length),b=0;b<this.g.responseText.length;b++)c[b]=this.g.responseText.charCodeAt(b)&255;this.response=new Blob([c],{type:this.g.getResponseHeader("Content-Type")})}else if("blob"===this.g.responseType)this.response=this.g.response;
else if(this.g.responseXML)this.response=D(this.g.responseXML.childNodes[0].childNodes[0].nodeValue);else if("HTML"===this.accept||"TEXT"===this.accept)this.response=this.g.responseText;else if(this.response=D(this.g.responseText),null===this.response){k(this.method+" to "+this.url+" failed - can't parse response "+this.g.responseText);this.h(!1,a);return}if(void 0!==this.response.err&&void 0!==this.response.msg){k(this.method+" to "+this.url+" failed with error:"+this.response.err+" "+this.response.msg);
this.h(!1,a);return}}this.onsuccess(this.response)}}};function D(a){var c=null;try{c=JSON.parse(a)}catch(b){return k("JSON parse failed with error: "+b.toString()+" parsing: "+a),null}return c}B.prototype.getResponseHeader=function(a){return this.g.getResponseHeader(a)};B.prototype.get=function(a,c,b,d,e){this.method="GET";E(this,a,null,c,b,d,e)};
function E(a,c,b,d,e,h,v){a.url=c;a.onsuccess=void 0!==h?h:function(){};a.h=void 0!==v?v:function(){};a.method=a.method||"POST";if(a.j)F(a.j,c,b,d,e,h,v);else{h=a.M||("JSON"===a.type?"application/json; charset=utf-8":"application/x-www-form-urlencoded; charset=utf-8");if("string"===typeof b)var y=b;else b instanceof Blob?(h=b.type,y=b):b&&(y="JSON"===a.type?r(b):"data="+r(b));p.safari&&a.B&&(a.o=w(window,"setTimeout",function(){k(this.method+" to "+this.url+" failed - timedout (Safari)");this.h(!1,
"timedout")}.bind(a),a.B));a.g.onreadystatechange=function(){a.onreadystatechange()};try{a.g.open(a.method,c,d),void 0!==a.v&&a.g.setRequestHeader("Accept",a.v),void 0!==a.g.setRequestHeader&&"GET"!==a.method&&a.g.setRequestHeader("Content-type",h),a.i&&a.i.C()?a.g.setRequestHeader("Authorization","Bearer "+a.i.C()):a.A&&a.g.setRequestHeader("Authorization","Bearer "+a.A),a.g.withCredentials=e,a.g.send(y)}catch(H){k(a.method+" to "+c+" failed with: "+H.toString()),a.h(!1,H.toString())}}}
function C(a){this.type=a}function F(a,c,b,d,e,h,v){a.onsuccess=h;a.h=v;u({from:"IFrameProxyRequest",type:a.type,url:c,obj:b,async:d,withcred:e})}C.prototype.abort=function(){C.postMessage({from:"IFrameProxyRequest",abort:!0})};function G(a,c){this.name=a;if(!(a=c)){c=new I;a=c.h.location.hostname;for(c=c.h;""===a&&c.parent!==c;)a=c.parent.location.hostname,c=c.parent;a=J(a)}this.domain=a}
G.prototype.s=function(a,c){var b=new Date;b.setUTCHours(b.getUTCHours()+8);document.cookie=this.name+"="+encodeURIComponent(r(a))+"; expires="+b.toGMTString()+"; domain="+this.domain+"; path=/"+(c||a.J?";secure":"")};G.prototype.get=function(){return this.l()?decodeURIComponent(document.cookie.replace(new RegExp("(?:^|.*;\\s*)"+encodeURIComponent(this.name).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=\\s*((?:[^;](?!;))*[^;]?).*"),"$1")):null};
G.prototype.m=function(){var a=new Date;a.setDate(a.getDate()-1);document.cookie=encodeURIComponent(this.name)+"=; expires="+a.toGMTString()+"; domain="+this.domain+"; path=/"};G.prototype.l=function(){return(new RegExp("(?:^|;\\s*)"+encodeURIComponent(this.name).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=")).test(document.cookie)};function K(a){this.name=a}
K.prototype.s=function(a){var c=new Date;c.setUTCHours(c.getUTCHours()+8);try{window.localStorage.setItem(this.name,r(a)),window.localStorage.setItem(this.name+"_exp",c.toGMTString())}catch(b){k("Failed to write cookie: "+this.name)}};K.prototype.get=function(){if(!this.l())return null;try{return window.localStorage.getItem(this.name)}catch(a){return k("Failed to read cookie: "+this.name),null}};
K.prototype.m=function(){try{window.localStorage.removeItem(this.name),window.localStorage.removeItem(this.name+"_exp")}catch(a){k("Failed to delete cookie: "+this.name)}};K.prototype.l=function(){var a=null;try{a=window.localStorage.getItem(this.name+"_exp")}catch(c){return k("Failed to read cookie: "+this.name),!1}if(!a)return!1;a=new Date(a);return a<new Date?(this.m(),!1):!0};function L(a,c){this.g=[new G(a,c),new K(a)]}L.prototype.s=function(a,c){this.g[0].s(a,c);this.g[1].s(a,c)};
L.prototype.get=function(){return this.g[0].get()||this.g[1].get()};L.prototype.m=function(){this.g[0].m();this.g[1].m()};L.prototype.l=function(){return this.g[0].l()||this.g[1].l()};function I(){var a=window;this.g=a.document;this.h=a;var c=[["hidden","visibilitychange"],["mozHidden","mozvisibilitychange"],["webkitHidden","webkitvisibilitychange"],["msHidden","msvisibilitychange"],["oHidden","ovisibilitychange"]];for(a=0;a<c.length&&!(c[a][0]in document);a++);}
function M(a){var c=a;a=a.split("?");1<a.length&&(c=a[0]);c=(new RegExp(/(?:.*?:\/\/){0,1}([^\/:]+)/)).exec(c);return null===c||2>c.length||0>c[1].indexOf(".")?null:c[1]}
function J(a){var c=new RegExp(/^(?:[a-z]{1,5}:\/\/|)([^:\?\/]*)/),b=a.match(/^\d+\.\d+.\d+.\d+$/);c=c.exec(a);if(b)return a;if(null===c||2!==c.length)return"about:"!==a&&k("ERR_DOMAINPARSE: "+a),null;b=c[1].split(".");return 1===b.length?(k("ERR_DOMAINPARSE: "+a),null):2===b.length?b.join("."):3===b.length?b.slice(1).join("."):4>=b[b.length-2].length?b.slice(b.length-3).join("."):b.slice(b.length-2).join(".")}
function A(a,c){var b=!1;a=M(a);if(null===a||!c)return!1;c.forEach(function(d,e){"object"===typeof d&&(d=d.domain);if(a.match(new RegExp("\\."+d+"$","i"))||a===d)b={index:e,domain:d}});return b}I.prototype.getElementsByTagName=function(a){return w(this.g,"getElementsByTagName",a)};I.prototype.head=function(){return void 0!==this.g.head?this.g.head:this.getElementsByTagName("head")[0]};function t(){}
function w(a,c,...b){return t.g&&a.nodeType?"#document"===a.nodeName?t.g.document[c].apply(a,b):"#document-fragment"===a.nodeName?t.g.DocumentFragment.prototype[c].apply(a,b):t.g.document.body[c].apply(a,b):t.g&&"[object Window]"===a.toString()?t.g.window[c].apply(a,b):a[c].apply(a,b)};function N(a,c){if(void 0!==a){var b=b||Object.keys(a);b.forEach(function(d){void 0!==a[d]&&(c[d]=a[d])})}}function O(a){var c={};if(!a)return c;var b=0;for(a=a.attributes;b<a.length;b++){var d=a[b].nodeName.match(/data-(.*)/);d&&2===d.length&&(c[d[1]]=a[b].nodeValue)}return c}function P(){var a=window.GLANCE_COBROWSE?window.GLANCE_COBROWSE:{},c=document.getElementById("cobrowsescript"),b=document.getElementById("glance-cobrowse");c=O(c);b=O(b);N(c,a);N(b,a);return a};function Q(a){if(URL.toString().includes("[native code]"))var c=(new URL(`https://${a.j}/${"cobrowse/CobrowseSettings.asmx/GetGroupSettings"}`)).href;else{c=[`https://${a.j}/${"cobrowse/CobrowseSettings.asmx/GetGroupSettings"}`];if(!a.o){let b=document.createElement("iframe");b.style.display="none";b.setAttribute("data-no-cobrowse-content",1);document.body.appendChild(b);a.o=b.contentWindow}a=a.o.URL;c=(new (t.g.Function.bind.apply(a,[a,...c]))).href}return c};function R(){this.g=S}R.prototype.start=function(){if(window.opener)if(window.opener===window)m("self is opener, refreshed?");else{var a=new B,c=Q(this.g),b=this;E(a,c,{groupid:this.g.h},!0,!1,function(d){T(b,d.trustedDomains)},function(){l("GetGroupSettings failed")})}else m("No window.opener")};
function T(a,c){m("Listen for messages from",c);z(function(b,d){window.clearTimeout(a.h);m("Received message",d);if(2!==d.type)l("Received unexpected xdom message type:"+d.type);else if(a.g.h.includes(parseInt(d.cookieinfo.ssnid.split(".")[0],10))){d.cookieinfo.xdomdone=!0;b=a.g;var e=d.cookieinfo;switch(b.v){case "ls":var h=K;break;case "dual":h=L;break;default:h=G}(new h("glance_ssn_info",b.A)).s(e,"secure"===b.v);d.nexthelper?window.location.replace(d.nexthelper):(x({type:3}),d.desturl&&window.location.replace(d.desturl))}else l("XDOM SSNID group not in script tag.  ssnid:"+
d.cookieinfo.ssnid+" groups:"+a.g.i)},c);m("Post ready_to_continue");x({type:1});a.h=window.setTimeout(function(){l("No message received from opener")},3E3)};var S=new function(){this.g=document.getElementById("cobrowsescript")||document.getElementById("glance-cobrowse");document.getElementById("glance-cobrowse");if(null!==this.g){var a=P();N(a,this);RegExp("//(.*)/").exec("string"===typeof this.g.src?this.g.src:a.scriptserver+"/");this.h=a.groupid||this.g.getAttribute("groupid");this.j=a.ws||this.g.getAttribute("ws")||"www.glance.net";this.j.match("\\.glance\\.net$");this.A=a.cookiedomain;this.v=a.cookietype;this.uri=a.uri;this.B=a.site||this.g.getAttribute("site")||
"production";JSON.parse(a.inputevents||"{}");if(!this.h)throw Error("data-groupid missing");a=a.additionalgroupids||"";this.i=[this.h].concat(a?a.split(","):[]);this.i=this.i.map(function(c){if(!parseInt(c))throw Error("data-groupid invalid: "+c);return parseInt(c)});if(!/staging|production/i.test(this.B))throw Error("data-site invalid");}};(new R).start();}).call(window);
//# sourceMappingURL=map.js.map
