(function() {/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';/*
 Copyright (c) 2022 Glance Networks, Inc.
 Copyright 2022 Glance Networks, Inc.
*/
var g=g||{};window.GLANCE=window.GLANCE||{};window.GLANCE.VERSION="5.8.5.0";window.GLANCE.PATCH="";window.GLANCE.Lib=window.GLANCE.Lib||{};
var h=function(){var a=navigator.userAgent.toLowerCase(),b=navigator.platform.toLowerCase(),c=a.match(/(edge)[\s\/:]([\w\d\.]+)?/)||a.match(/(opera|ie|firefox|chrome|crios|version)[\s\/:]([\w\d\.]+)?.*?(safari|version[\s\/:]([\w\d\.]+)|$)/)||a.match(/(rv):([\w\d\.]+)/)||[null,"unknown",0];"crios"===c[1]?c[1]="chrome":"rv"===c[1]&&(c[1]="ie");a={extend:Function.prototype.extend,name:"version"==c[1]?c[3]:c[1],version:"ie"==c[1]&&document.documentMode||parseFloat("opera"==c[1]&&c[4]?c[4]:c[2]),l:{name:a.match(/ip(?:ad|od|hone)/)||
b.match(/mac/)&&"undefined"!==typeof navigator.a?"ios":(a.match(/(?:webos|android)/)||b.match(/mac|win|linux/)||["other"])[0]},v:{K:!!document.evaluate,B:!!window.H,query:!!document.querySelector,json:!!window.JSON},A:{},D:function(){return"ios"==this.l.name||"android"==this.l.name}};document.documentMode&&window.XDomainRequest?(a.name="ie",a.version=document.documentMode):window.navigator&&navigator.appVersion&&-1!=navigator.appVersion.indexOf("MSIE 7.")&&(a.name="ie",a.version="7");a[a.name]=!0;
a[a.name+parseInt(a.version,10)]=!0;a.l[a.l.name]=!0;return a}();if(void 0===k)var k=function(a){return JSON.stringify(a)};function l(a,b){p(window,"setTimeout",function(){l(a,b)},100)}function q(a){var b=window.opener,c={};c.glance_xdomain=a;b.postMessage(c,"*")}
function r(a,b){p(window,"addEventListener","message",function(c){if("string"===typeof c.data)try{var d=JSON.parse(c.data)}catch(f){return!1}else d=c.data;void 0!==d.glance_xdomain&&(b&&!t(c.origin,b)?v("UNTRUSTED_ORIGIN:"+c.origin+" "+JSON.stringify(d)):a(c.source,d.glance_xdomain))})}function w(){g.J?this.f=new x("JSON4"):this.a=new window.XMLHttpRequest;this.response=null;this.type="JSON4"}w.prototype.abort=function(){this.f?this.f.abort():this.a.abort()};
w.prototype.onreadystatechange=function(){if(4==this.a.readyState){p(window,"clearTimeout",this.i);delete this.i;var a="error";if(0==this.a.status)y(this.method+" to "+this.url+" failed: network"),this.b(!0,"connection",this.a.status);else if(200!==this.a.status){v(this.method+" to "+this.url+" failed with status: "+this.a.status);"text"===this.a.responseType&&null!==this.a.responseText&&y(this.a.responseText);if(401===this.a.status||403===this.a.status)a="authorization",this.c&&this.c.C();this.b(!1,
a,this.a.status)}else{if(""!==this.a.response){if("XML"===this.accept)this.response=this.a.responseXML&&this.a.responseXML.documentElement,null===this.response&&v("Invalid XML response: "+this.a.responseText);else if(this.F){for(var b=new Uint8Array(this.a.responseText.length),c=0;c<this.a.responseText.length;c++)b[c]=this.a.responseText.charCodeAt(c)&255;this.response=new Blob([b],{type:this.a.getResponseHeader("Content-Type")})}else if("blob"===this.a.responseType)this.response=this.a.response;
else if(this.a.responseXML)this.response=z(this.a.responseXML.childNodes[0].childNodes[0].nodeValue);else if("HTML"===this.accept||"TEXT"===this.accept)this.response=this.a.responseText;else if(this.response=z(this.a.responseText),null===this.response){y(this.method+" to "+this.url+" failed - can't parse response "+this.a.responseText);this.b(!1,a);return}if(void 0!==this.response.err&&void 0!==this.response.msg){y(this.method+" to "+this.url+" failed with error:"+this.response.err+" "+this.response.msg);
this.b(!1,a);return}}this.onsuccess(this.response)}}};function z(a){var b=null;try{b=JSON.parse(a)}catch(c){return y("JSON parse failed with error: "+c.toString()+" parsing: "+a),null}return b}w.prototype.getResponseHeader=function(a){return this.a.getResponseHeader(a)};w.prototype.get=function(a,b,c,d,f){this.method="GET";A(this,a,null,b,c,d,f)};
function A(a,b,c,d,f,e,m){a.url=b;a.onsuccess=void 0!==e?e:function(){};a.b=void 0!==m?m:function(){};a.method=a.method||"POST";if(a.f)B(a.f,b,c,d,f,e,m);else{e=a.G||("JSON"===a.type?"application/json; charset=utf-8":"application/x-www-form-urlencoded; charset=utf-8");if("string"===typeof c)var n=c;else c instanceof Blob?(e=c.type,n=c):c&&(n="JSON"===a.type?k(c):"data="+k(c));h.safari&&a.s&&(a.i=p(window,"setTimeout",function(){y(this.method+" to "+this.url+" failed - timedout (Safari)");this.b(!1,
"timedout")}.bind(a),a.s));a.a.onreadystatechange=function(){a.onreadystatechange()};try{a.a.open(a.method,b,d),void 0!==a.m&&a.a.setRequestHeader("Accept",a.m),void 0!==a.a.setRequestHeader&&"GET"!==a.method&&a.a.setRequestHeader("Content-type",e),a.c&&a.c.u()?a.a.setRequestHeader("Authorization","Bearer "+a.c.u()):a.o&&a.a.setRequestHeader("Authorization","Bearer "+a.o),a.a.withCredentials=f,a.a.send(n)}catch(u){y(a.method+" to "+b+" failed with: "+u.toString()),a.b(!1,u.toString())}}}
function x(a){this.type=a}function B(a,b,c,d,f,e,m){a.onsuccess=e;a.b=m;l({from:"IFrameProxyRequest",type:a.type,url:b,obj:c,async:d,withcred:f})}x.prototype.abort=function(){x.postMessage({from:"IFrameProxyRequest",abort:!0})};function C(a,b){this.name=a;if(!(a=b)){b=new D;a=b.b.location.hostname;for(b=b.b;""===a&&b.parent!==b;)a=b.parent.location.hostname,b=b.parent;a=E(a)}this.domain=a}
C.prototype.j=function(a,b){var c=new Date;c.setUTCHours(c.getUTCHours()+8);document.cookie=this.name+"="+escape(k(a))+"; expires="+c.toGMTString()+"; domain="+this.domain+"; path=/"+(b||a.I?";secure":"")};C.prototype.get=function(){return this.g()?unescape(document.cookie.replace(new RegExp("(?:^|.*;\\s*)"+escape(this.name).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=\\s*((?:[^;](?!;))*[^;]?).*"),"$1")):null};
C.prototype.h=function(){var a=new Date;a.setDate(a.getDate()-1);document.cookie=escape(this.name)+"=; expires="+a.toGMTString()+"; domain="+this.domain+"; path=/"};C.prototype.g=function(){return(new RegExp("(?:^|;\\s*)"+escape(this.name).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=")).test(document.cookie)};function F(a){this.name=a}F.prototype.j=function(a){var b=new Date;b.setUTCHours(b.getUTCHours()+8);localStorage.setItem(this.name,k(a));localStorage.setItem(this.name+"_exp",b.toGMTString())};
F.prototype.get=function(){return this.g()?localStorage.getItem(this.name):null};F.prototype.h=function(){localStorage.removeItem(this.name);localStorage.removeItem(this.name+"_exp")};F.prototype.g=function(){var a=localStorage.getItem(this.name+"_exp");if(!a)return!1;a=new Date(a);return a<new Date?(this.h(),!1):!0};function G(a,b){this.a=[new C(a,b),new F(a)]}G.prototype.j=function(a,b){this.a[0].j(a,b);this.a[1].j(a,b)};G.prototype.get=function(){return this.a[0].get()||this.a[1].get()};
G.prototype.h=function(){this.a[0].h();this.a[1].h()};G.prototype.g=function(){return this.a[0].g()||this.a[1].g()};function D(){var a=window;this.a=a.document;this.b=a;var b=[["hidden","visibilitychange"],["mozHidden","mozvisibilitychange"],["webkitHidden","webkitvisibilitychange"],["msHidden","msvisibilitychange"],["oHidden","ovisibilitychange"]];for(a=0;a<b.length&&!(b[a][0]in document);a++);}
function I(a){var b=a;a=a.split("?");1<a.length&&(b=a[0]);b=(new RegExp(/(?:.*?:\/\/){0,1}([^\/:]+)/)).exec(b);return null===b||2>b.length||0>b[1].indexOf(".")?null:b[1]}
function E(a){var b=new RegExp(/^(?:[a-z]{1,5}:\/\/|)([^:\?\/]*)/),c=a.match(/^\d+\.\d+.\d+.\d+$/);b=b.exec(a);if(c)return a;if(null===b||2!==b.length)return"about:"!==a&&y("ERR_DOMAINPARSE: "+a),null;c=b[1].split(".");return 1===c.length?(y("ERR_DOMAINPARSE: "+a),null):2===c.length?c.join("."):3===c.length?c.slice(1).join("."):4>=c[c.length-2].length?c.slice(c.length-3).join("."):c.slice(c.length-2).join(".")}
function t(a,b){var c=!1;a=I(a);if(null===a||!b)return!1;b.forEach(function(d,f){"object"===typeof d&&(d=d.domain);if(a.match(new RegExp("\\."+d+"$","i"))||a===d)c={index:f,domain:d}});return c}D.prototype.head=function(){return void 0!==this.a.head?this.a.head:p(this.a,"getElementsByTagName","head")[0]};
function J(a){if(void 0!==window.pageXOffset)return{x:Math.round(a.b.pageXOffset),y:Math.round(a.b.pageYOffset)};if(void 0!==document.documentElement.scrollTop)return{x:a.a.documentElement.scrollLeft,y:a.a.documentElement.scrollTop};if(void 0!==document.body.scrollLeft)return{x:a.a.body.scrollLeft,y:a.a.body.scrollTop};throw Error("Can't get page scroll");}
D.prototype.scrollTo=function(a,b,c){var d=J(this);d[a]=b;a={left:d.x,top:d.y,behavior:c?"smooth":"auto"};h.ie11||h.edge?window.scrollTo(d.x,d.y):window.scrollTo(a);J(this)};D.prototype.addEventListener=function(a,b,c){p(this.a,"addEventListener",a,b,c)};D.prototype.removeEventListener=function(a,b,c){p(this.a,"removeEventListener",a,b,c)};function K(a){this.a=a}K.prototype.addEventListener=function(a,b,c){p(this.a,"addEventListener",b,c)};
K.prototype.removeEventListener=function(a,b,c){p(this.a,"removeEventListener",b,c)};function p(a,b,...c){return K.b&&K.a&&a.nodeType?"#document"===a.nodeName?K.a.document[b].apply(a,c):"#document-fragment"===a.nodeName?K.a.DocumentFragment.prototype[b].apply(a,c):K.a.document.body[b].apply(a,c):K.b&&K.a&&"[object Window]"===a.toString()?K.a.window[b].apply(a,c):a[b].apply(a,c)}function L(a,b,c){a.a.style.left=b+"px";a.a.style.top=c+"px"}
K.prototype.moveTo=function(a,b){function c(){10>m++?(f+=n,e+=u,L(d,Math.floor(f),Math.floor(e)),d.b=p(window,"setTimeout",c,20)):L(d,a,b)}void 0!==this.b&&p(window,"clearTimeout",this.b);var d=this,f=parseInt(this.a.style.left),e=parseInt(this.a.style.top);isNaN(f)&&(f=-999);isNaN(e)&&(e=-999);var m=0,n=(a-f)/10,u=(b-e)/10;0===n&&0===u||c()};
function M(a,...b){!window.console||!window.console[a]||window.GLANCE_COBROWSE&&window.GLANCE_COBROWSE.disableLogging||(b=b.map(c=>{if("object"===typeof c)try{c=JSON.stringify(c)}catch(d){console.error(d),c="unable to convert object to string"}return"string"===typeof c?c.replace(/[\r\n]/g," ").replace("<","&lt;"):c}),window.console[a](...b))}function y(...a){M("log",...a)}function v(...a){M("error",...a)}function N(...a){y("XDOM:",...a)};function O(a,b){if(void 0!==a){var c=c||Object.keys(a);c.forEach(function(d){void 0!==a[d]&&(b[d]=a[d])})}}function P(a){var b={};if(!a)return b;var c=0;for(a=a.attributes;c<a.length;c++){var d=a[c].nodeName.match(/data-(.*)/);d&&2===d.length&&(b[d[1]]=a[c].nodeValue)}return b}function Q(){var a=window.GLANCE_COBROWSE?window.GLANCE_COBROWSE:{},b=document.getElementById("glance-cobrowse"),c=P(document.getElementById("cobrowsescript"));b=P(b);O(c,a);O(b,a);return a};function R(a){if(URL.toString().includes("[native code]"))var b=(new URL(`https://${a.f}/${"cobrowse/CobrowseSettings.asmx/GetGroupSettings"}`)).href;else{b=[`https://${a.f}/${"cobrowse/CobrowseSettings.asmx/GetGroupSettings"}`];if(!a.i){let c=document.createElement("iframe");c.style.display="none";c.setAttribute("data-no-cobrowse-content",1);document.body.appendChild(c);a.i=c.contentWindow}a=a.i.URL;b=new (Function.bind.apply(a,[a,...b]));b=b.href}return b};function S(){this.a=T}S.prototype.start=function(){if(window.opener)if(window.opener===window)N("self is opener, refreshed?");else{var a=new w,b=R(this.a),c=this;A(a,b,{groupid:this.a.a},!0,!1,function(d){U(c,d.trustedDomains)},function(){v("GetGroupSettings failed")})}else N("No window.opener")};
function U(a,b){N("Listen for messages from",b);r(function(c,d){window.clearTimeout(a.b);N("Received message",d);if(2!==d.type)v("Received unexpected xdom message type:"+d.type);else if(a.a.a.includes(parseInt(d.cookieinfo.ssnid.split(".")[0],10))){d.cookieinfo.xdomdone=!0;c=a.a;var f=d.cookieinfo;switch(c.m){case "ls":var e=F;break;case "dual":e=G;break;default:e=C}(new e("glance_ssn_info",c.o)).j(f,"secure"===c.m);d.nexthelper?window.location.replace(d.nexthelper):(q({type:3}),d.desturl&&window.location.replace(d.desturl))}else v("XDOM SSNID group not in script tag.  ssnid:"+
d.cookieinfo.ssnid+" groups:"+a.a.c)},b);N("Post ready_to_continue");q({type:1});a.b=window.setTimeout(function(){v("No message received from opener")},3E3)};var T=new function(){this.b=document.getElementById("cobrowsescript")||document.getElementById("glance-cobrowse");if(null!==this.b){var a=Q();O(a,this);this.a=a.groupid||this.b.getAttribute("groupid");this.f=a.ws||this.b.getAttribute("ws")||"www.glance.net";this.f.match("\\.glance\\.net$");this.o=a.cookiedomain;this.m=a.cookietype;this.s=a.site||this.b.getAttribute("site")||"production";JSON.parse(a.inputevents||"{}");if(!this.a)throw Error("data-groupid missing");a=a.additionalgroupids||"";this.c=
[this.a].concat(a?a.split(","):[]);this.c=this.c.map(function(b){if(!parseInt(b))throw Error("data-groupid invalid: "+b);return parseInt(b)});if(!/staging|production/i.test(this.s))throw Error("data-site invalid");}};(new S).start();}).call(window);
