(function() {/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var aa=this||self;/*
 Copyright 2022 Glance Networks, Inc.
*/
var h=["5","8","5","0"].slice(0,3).join(".");Uint8Array.prototype.slice||(Uint8Array.prototype.slice=function(a,b){return new Uint8Array(this.subarray(a,b))});
ArrayBuffer.prototype.slice||(ArrayBuffer.prototype.slice=function(a,b){void 0===a&&(a=0);void 0===b&&(b=this.byteLength);a=Math.floor(a);b=Math.floor(b);0>a&&(a+=this.byteLength);0>b&&(b+=this.byteLength);a=Math.min(Math.max(0,a),this.byteLength);b=Math.min(Math.max(0,b),this.byteLength);if(0>=b-a)return new ArrayBuffer(0);var c=new ArrayBuffer(b-a),d=new Uint8Array(c);a=new Uint8Array(this,a,b-a);d.set(a);return c});
var k=navigator.userAgent.toLowerCase(),ba=k.match(/(edge)[\s\/:]([\w\d\.]+)?/)||k.match(/(opera|ie|firefox|chrome|version)[\s\/:]([\w\d\.]+)?.*?(safari|version[\s\/:]([\w\d\.]+)|$)/)||k.match(/(rv):([\w\d\.]+)/)||[null,"unknown",0];"rv"===ba[1]&&(ba[1]="ie");function ca(a){for(var b="",c=0;c<a.length;c++)b+=("object"===typeof a[c]?JSON.stringify(a[c]):a[c])+" ";return b.replace(/[\r\n]/g," ").replace("<","&lt;").replace(">","&gt;")}function m(a){window.console&&window.console.log&&(window.GLANCE_COBROWSE?!window.GLANCE_COBROWSE.disableLogging:1)&&window.console.log(ca(arguments))}function da(a){window.console&&window.console.error&&window.console.error(ca(arguments))};/*
 Copyright (c) 2022 Glance Networks, Inc.
 Copyright 2022 Glance Networks, Inc.
*/
var n=n||{};window.GLANCE=window.GLANCE||{};window.GLANCE.VERSION="5.8.5.0";window.GLANCE.PATCH="";window.GLANCE.Lib=window.GLANCE.Lib||{};
var p=function(){var a=navigator.userAgent.toLowerCase(),b=navigator.platform.toLowerCase(),c=a.match(/(edge)[\s\/:]([\w\d\.]+)?/)||a.match(/(opera|ie|firefox|chrome|crios|version)[\s\/:]([\w\d\.]+)?.*?(safari|version[\s\/:]([\w\d\.]+)|$)/)||a.match(/(rv):([\w\d\.]+)/)||[null,"unknown",0];"crios"===c[1]?c[1]="chrome":"rv"===c[1]&&(c[1]="ie");a={extend:Function.prototype.extend,name:"version"==c[1]?c[3]:c[1],version:"ie"==c[1]&&document.documentMode||parseFloat("opera"==c[1]&&c[4]?c[4]:c[2]),l:{name:a.match(/ip(?:ad|od|hone)/)||
b.match(/mac/)&&"undefined"!==typeof navigator.a?"ios":(a.match(/(?:webos|android)/)||b.match(/mac|win|linux/)||["other"])[0]},aa:{ga:!!document.evaluate,ca:!!window.fa,query:!!document.querySelector,json:!!window.JSON},ba:{},ea:function(){return"ios"==this.l.name||"android"==this.l.name}};document.documentMode&&window.XDomainRequest?(a.name="ie",a.version=document.documentMode):window.navigator&&navigator.appVersion&&-1!=navigator.appVersion.indexOf("MSIE 7.")&&(a.name="ie",a.version="7");a[a.name]=
!0;a[a.name+parseInt(a.version,10)]=!0;a.l[a.l.name]=!0;return a}();if(void 0===q)var q=function(a){return JSON.stringify(a)};function ea(a){a.onmessage=function(b){b=JSON.parse(b.data);a.I&&a.I(b)};a.v=function(b){b=q(b);a.send(b)};a.U=function(b){return b&&b.code||0};a.V=function(b){return b&&b.reason||""}}
function ha(a){var b={};if(n.$)var c=new u(a);else p.ie9&&"http:"===window.location.protocol&&(b.protocols_whitelist=["iframe-eventsource","iframe-htmlfile"]),c=new SockJS(a,"",b);c.m=0;c.P=function(){c.G();c.transport&&!c.transport.match(/^iframe-/)&&(c.H=v(window,"setInterval",function(){c.m++;c.Z&&c.Z({m:c.m})},15E3))};c.G=function(){c.H&&v(window,"clearInterval",c.H)};ea(c);c.onclose=function(d){c.G();c.X&&c.X(d)};c.onheartbeat=function(){c.m=0;c.P();c.Y&&c.Y()};return c}
function x(a,b){v(window,"setTimeout",function(){x(a,b)},100)}function u(a){this.readyState=SockJS.CONNECTING;this.a=Math.round(1E6*Math.random());x({from:"GSockJSProxy",sockid:this.a,cmd:"open",url:a})}u.prototype.send=function(a){x({from:"GSockJSProxy",sockid:this.a,cmd:"send",data:a})};u.prototype.close=function(){this.readyState=SockJS.CLOSING;x({from:"GSockJSProxy",sockid:this.a,cmd:"close"})};
function y(a,b,c){void 0!==a&&(c=c||Object.keys(a),c.forEach(function(d){void 0!==a[d]&&(b[d]=a[d])}))}function ia(a){var b=a.func.split(".");if(2>b.length)z("ERR_BADINVOKE:");else if("GLANCE"===b[0]||"GLANCE_COBROWSE"===b[0]&&"Custom"===b[1]){for(var c=window[b[0]],d=1;d<b.length;d++)if(c=c[b[d]],!c){z("ERR_UNDEFINVOKE:"+b[d]);return}a.args=a.args||{};a.args.remote=!0;c(a.args)}else z("ERR_BADINVOKE:"+b[0])}
function A(){n.$?this.f=new B("JSON"):this.a=new window.XMLHttpRequest;this.response=null;this.type="JSON"}A.prototype.abort=function(){this.f?this.f.abort():this.a.abort()};
A.prototype.onreadystatechange=function(){if(4==this.a.readyState){v(window,"clearTimeout",this.g);delete this.g;var a="error";if(0==this.a.status)C(this.method+" to "+this.url+" failed: network"),this.b(!0,"connection",this.a.status);else if(200!==this.a.status){z(this.method+" to "+this.url+" failed with status: "+this.a.status);"text"===this.a.responseType&&null!==this.a.responseText&&C(this.a.responseText);if(401===this.a.status||403===this.a.status)a="authorization",this.c&&this.c.da();this.b(!1,
a,this.a.status)}else{if(""!==this.a.response){if("XML"===this.accept)this.response=this.a.responseXML&&this.a.responseXML.documentElement,null===this.response&&z("Invalid XML response: "+this.a.responseText);else if(this.o){for(var b=new Uint8Array(this.a.responseText.length),c=0;c<this.a.responseText.length;c++)b[c]=this.a.responseText.charCodeAt(c)&255;this.response=new Blob([b],{type:this.a.getResponseHeader("Content-Type")})}else if("blob"===this.a.responseType)this.response=this.a.response;
else if(this.a.responseXML)this.response=ja(this.a.responseXML.childNodes[0].childNodes[0].nodeValue);else if("HTML"===this.accept||"TEXT"===this.accept)this.response=this.a.responseText;else if(this.response=ja(this.a.responseText),null===this.response){C(this.method+" to "+this.url+" failed - can't parse response "+this.a.responseText);this.b(!1,a);return}if(void 0!==this.response.err&&void 0!==this.response.msg){C(this.method+" to "+this.url+" failed with error:"+this.response.err+" "+this.response.msg);
this.b(!1,a);return}}this.onsuccess(this.response)}}};function ja(a){var b=null;try{b=JSON.parse(a)}catch(c){return C("JSON parse failed with error: "+c.toString()+" parsing: "+a),null}return b}A.prototype.getResponseHeader=function(a){return this.a.getResponseHeader(a)};A.prototype.get=function(a,b,c,d,f){this.method="GET";D(this,a,null,b,c,d,f)};
function D(a,b,c,d,f,g,e){a.url=b;a.onsuccess=void 0!==g?g:function(){};a.b=void 0!==e?e:function(){};a.method=a.method||"POST";if(a.f)ka(a.f,b,c,d,f,g,e);else{g=a.s||("JSON"===a.type?"application/json; charset=utf-8":"application/x-www-form-urlencoded; charset=utf-8");if("string"===typeof c)var t=c;else c instanceof Blob?(g=c.type,t=c):c&&(t="JSON"===a.type?q(c):"data="+q(c));p.safari&&a.j&&(a.g=v(window,"setTimeout",function(){C(this.method+" to "+this.url+" failed - timedout (Safari)");this.b(!1,
"timedout")}.bind(a),a.j));a.a.onreadystatechange=function(){a.onreadystatechange()};try{a.a.open(a.method,b,d),void 0!==a.h&&a.a.setRequestHeader("Accept",a.h),void 0!==a.a.setRequestHeader&&"GET"!==a.method&&a.a.setRequestHeader("Content-type",g),a.c&&a.c.W()?a.a.setRequestHeader("Authorization","Bearer "+a.c.W()):a.i&&a.a.setRequestHeader("Authorization","Bearer "+a.i),a.a.withCredentials=f,a.a.send(t)}catch(l){C(a.method+" to "+b+" failed with: "+l.toString()),a.b(!1,l.toString())}}}
function B(a){this.type=a}function ka(a,b,c,d,f,g,e){a.onsuccess=g;a.b=e;x({from:"IFrameProxyRequest",type:a.type,url:b,obj:c,async:d,withcred:f})}B.prototype.abort=function(){B.postMessage({from:"IFrameProxyRequest",abort:!0})};function F(a){this.name=a}function la(a,b){var c=new Date;c.setUTCHours(c.getUTCHours()+8);localStorage.setItem(a.name,q(b));localStorage.setItem(a.name+"_exp",c.toGMTString())}function ma(a){if(!na(a))return null;a=localStorage.getItem(a.name);return JSON.parse(a)}
function oa(a,b){"string"===typeof b&&(b=parseInt(b));var c=new Date;c.setUTCMinutes(c.getUTCMinutes()+b);localStorage.setItem(a.name+"_exp",c.toGMTString())}F.prototype.get=function(){return na(this)?localStorage.getItem(this.name):null};function pa(a){localStorage.removeItem(a.name);localStorage.removeItem(a.name+"_exp")}function na(a){var b=localStorage.getItem(a.name+"_exp");if(!b)return!1;b=new Date(b);return b<new Date?(pa(a),!1):!0}
function G(){var a=window;this.a=a.document;this.b=a;var b=[["hidden","visibilitychange"],["mozHidden","mozvisibilitychange"],["webkitHidden","webkitvisibilitychange"],["msHidden","msvisibilitychange"],["oHidden","ovisibilitychange"]];for(a=0;a<b.length;a++)if(b[a][0]in document){this.c=b[a][0];this.f=b[a][1];break}}
function qa(a,b){var c=[["src","//www.glancecdn.net/cobrowse/js/sockjs1.0.2.min.js"]],d=a.a.createElement("script");b&&d.addEventListener("load",b);d.setAttribute("type","text/javascript");d.setAttribute("charset","UTF-8");for(b=0;b<c.length;b++)d.setAttribute(c[b][0],c[b][1]);a.a.head.appendChild(d)}function H(a){return void 0===a.c?!1:a.a[a.c]}function ra(a,b){a.addEventListener(a.f,b)}G.prototype.head=function(){return void 0!==this.a.head?this.a.head:v(this.a,"getElementsByTagName","head")[0]};
function sa(a){if(void 0!==window.pageXOffset)return{x:Math.round(a.b.pageXOffset),y:Math.round(a.b.pageYOffset)};if(void 0!==document.documentElement.scrollTop)return{x:a.a.documentElement.scrollLeft,y:a.a.documentElement.scrollTop};if(void 0!==document.body.scrollLeft)return{x:a.a.body.scrollLeft,y:a.a.body.scrollTop};throw Error("Can't get page scroll");}
G.prototype.scrollTo=function(a,b,c){var d=sa(this);d[a]=b;a={left:d.x,top:d.y,behavior:c?"smooth":"auto"};p.ie11||p.edge?window.scrollTo(d.x,d.y):window.scrollTo(a);sa(this)};G.prototype.addEventListener=function(a,b,c){v(this.a,"addEventListener",a,b,c)};G.prototype.removeEventListener=function(a,b,c){v(this.a,"removeEventListener",a,b,c)};function I(a){this.a=a}I.prototype.addEventListener=function(a,b,c){v(this.a,"addEventListener",b,c)};
I.prototype.removeEventListener=function(a,b,c){v(this.a,"removeEventListener",b,c)};function v(a,b,...c){return I.b&&I.a&&a.nodeType?"#document"===a.nodeName?I.a.document[b].apply(a,c):"#document-fragment"===a.nodeName?I.a.DocumentFragment.prototype[b].apply(a,c):I.a.document.body[b].apply(a,c):I.b&&I.a&&"[object Window]"===a.toString()?I.a.window[b].apply(a,c):a[b].apply(a,c)}function ta(a,b,c){a.a.style.left=b+"px";a.a.style.top=c+"px"}
I.prototype.moveTo=function(a,b){function c(){10>e++?(f+=t,g+=l,ta(d,Math.floor(f),Math.floor(g)),d.b=v(window,"setTimeout",c,20)):ta(d,a,b)}void 0!==this.b&&v(window,"clearTimeout",this.b);var d=this,f=parseInt(this.a.style.left),g=parseInt(this.a.style.top);isNaN(f)&&(f=-999);isNaN(g)&&(g=-999);var e=0,t=(a-f)/10,l=(b-g)/10;0===t&&0===l||c()};
function ua(a,...b){!window.console||!window.console[a]||window.GLANCE_COBROWSE&&window.GLANCE_COBROWSE.disableLogging||(b=b.map(c=>{if("object"===typeof c)try{c=JSON.stringify(c)}catch(d){console.error(d),c="unable to convert object to string"}return"string"===typeof c?c.replace(/[\r\n]/g," ").replace("<","&lt;"):c}),window.console[a](...b))}function C(...a){ua("log",...a)}function z(...a){ua("error",...a)}function J(...a){C("PRES:",...a)};function va(a,b){if(void 0!==a){var c=c||Object.keys(a);c.forEach(function(d){void 0!==a[d]&&(b[d]=a[d])})}}function wa(a){var b={};if(!a)return b;var c=0;for(a=a.attributes;c<a.length;c++){var d=a[c].nodeName.match(/data-(.*)/);d&&2===d.length&&(b[d[1]]=a[c].nodeValue)}return b}function xa(){var a=window.GLANCE_COBROWSE?window.GLANCE_COBROWSE:{},b=document.getElementById("glance-cobrowse"),c=wa(document.getElementById("cobrowsescript"));b=wa(b);va(c,a);va(b,a);return a};function K(){}function ya(a,b){a.B="undefined"===typeof WebSocket;a.a={};a.a.ws="www.glance.net";a.a.site="production";a.g=new G;y(xa(),a.a);y(b,a.a);delete a.a.presenceserver;a.s=[];a.f=L;a.h=new F("glance_presence");var c=ma(a.h);c&&(0===["visitorid","ws","groupid"].filter(d=>c[d]!==a.a[d]).length?a.c=c.directserver:J("Ignoring glance_presence entry for different visitor",c.groupid,c.visitorid));J("direct server from local storage:",a.c)}var L=1;K.prototype.L=function(){};
function M(a,b,c,d,f){if(b&&!a.c)m("ERR_NODIRECTSERVER");else{var g=(f||"https")+"://"+(b?a.c:a.a.presenceserver)+"/"+c;d&&(g+="?",["groupid","visitorid"].forEach(function(e){g+=e+"="+a.a[e]+"&"}),g+=`&ver=${h}`);return g}}K.prototype.C=function(a){N(this,"findvisitor","GET",a)};
function O(a){m("connecting to "+a.c);var b=!1;a.B&&!window.SockJS?qa(a.g,function(){b||(J("sockjs script added"),b=!0,window.SockJS?O(a):m("ERR_NOSOCKJS"))}):(a.b&&a.b.close(),a.b=za(a),a.b.J=a.c,a.b.onopen=function(){J("sock onopen, sending connect");a.b.v({type:"connect",authorization:void 0,groupid:a.a.groupid,visitorid:a.a.visitorid,guesttoken:a.a.guesttoken,version:h});J("sending message queue");a.s.forEach(function(c){a.b.v(c)});a.s=[];a.f=3},a.b.I=function(c){m("received:"+q(c));if(a.b){var d=
c.mtype||c.type,f=c.data;switch(d){case "connected":if(a.a.nokeepalive)break;J("Keepalive interval: "+c.keepalive);a.i||(a.i=window.setInterval(function(){a.b.v({type:"k"})},1E3*c.keepalive));break;case "invoke":"visitor"===a.O&&ia(f);break;case "redirect":case "serverclose":f||(f=c);default:if(a["on"+d])a["on"+d](f)}}else J("Ignoring message received after socket close")},a.b.onclose=function(c){a.b===this&&(m(`presence connection closed ${this.U(c)} ${this.V(c)}`),Aa(a),P(a))},a.b.onerror=function(c){a.b===
this&&(J("socket error"),a.B=!0,a.b.onclose(c))})}
function N(a,b,c,d){function f(l){var r=l&&(l.directserver||l.direct);r&&(e.c=r,l.httpsport&&(e.c+=":"+l.httpsport),e.L());e.b&&e.c!=e.b.J&&(J("switching connection from "+e.b.J+" to "+e.c),O(e));if(d&&d.onsuccess)d.onsuccess(l)}function g(l,r,w){m(`Presence request: ${b} failed reason: ${r} http status: ${w||0}`);503===w&&(da("Presence service unavailable"),e.F=!0,r="serviceunavailable");if(d.onfail)d.onfail(r);else Q(e,{error:"connfail",detail:r})}if(!a.F){var e=a,t=new A;t.c=void 0;t.method=c;
m(b,JSON.stringify(d));(function(l){if(e.a.presenceserver)return l();var r=new F("glance_visitor_settings_"+e.a.groupid+"_"+e.a.site),w=ma(r);if(w)return e.a.presenceserver=w.presenceserver,e.a.presenceserver||m("PRES_DISABLED (from cache)"),l();w=new A;var Da="https://"+e.a.ws+"/services/authorizationservice/GetVisitorSettings3?groupid="+e.a.groupid+"&site="+e.a.site+"&service=presence";w.method="GET";D(w,Da,null,!0,!1,function(U){e.a.presenceserver=U.presenceUrl;J("presence service: "+e.a.presenceserver);
e.a.presenceserver||m("PRES_DISABLED");var E={};E.presenceserver=e.a.presenceserver;E.presencesettings=U;la(r,E);oa(r,1440);return l()},function(U,E){m("PRES_UNAVAILABLE "+E);l()})})(function(){e.a.presenceserver&&D(t,M(e,!1,b,!0),d.data?d.data:{},!0,!1,f,g)})}}function R(a){J("closewebsocket");a.b&&a.b.close();Aa(a)}function Aa(a){a.i&&(window.clearInterval(a.i),delete a.i);a.f=L;delete a.b;delete a.c}
function S(a,b){m("sending",b.type,a.f);3===a.f?(J("sending message: "+JSON.stringify(b)),a.b.v(b)):(J("queuing message: "+JSON.stringify(b)),a.s.push(b),a.connect())}K.prototype.K=function(a){let b=3===this.f;b&&this.disconnect();this.a.visitorid=a;(b||"api"!==this.a.presence)&&this.connect()};K.prototype.setVisitorId=K.prototype.K;
K.prototype.connect=function(){if(!this.F)if(this.a.visitorid)if(this.f!==L)J("connect() called when already connecting or connected");else{this.f=2;J("connect");var a=this;this.onscaledown=function(){a.disconnect();a.connect()};this.onredirect=function(b){J("Connected to wrong instance:",JSON.stringify(b),"current direct server:",this.c);this.h&&b.direct!==this.c&&(pa(this.h),this.h=new F("glance_presence"),this.disconnect(),P(this))};this.onserverclose=function(){a.disconnect();if(a.onclose)a.onclose()};
this.c?O(this):this.C({onsuccess:function(){m("found visitor, connect");O(a)},onfail:function(b){a.f=L;Q(a,{error:"connfail",detail:b})}})}else m("CONN_NOVISITORID")};K.prototype.connect=K.prototype.connect;K.prototype.disconnect=function(){R(this)};K.prototype.disconnect=K.prototype.disconnect;function P(a){J(`delayed reconnect.  count: ${a.j||0} connstate: ${a.f}`);a.M||(a.j=a.j||0,a.j++,a.M=window.setTimeout(()=>{delete a.M;a.connect()},3>=a.j?5E3:6E4))}
function Q(a,b){m("Error: ",JSON.stringify(b));a.D&&a.D(b);if(a.onerror)a.onerror(b)}K.prototype.T=function(a,b){S(this,{type:a,data:b})};K.prototype.fire=K.prototype.T;function T(a){ya(this,a);this.O="visitor";this.g=new G;this.A=!1;var b=this;v(window,"addEventListener","focus",function(){J("presence visitor got focus event");b.o=!1;b.N&&b.u()},void 0);ra(this.g,function(){if(!b.A&&(J("visibility:",H(b.g)?"hidden":"visible"),3===b.f&&!b.o)){var c={type:"visibility"};c.data={visibility:H(b.g)?"hidden":"visible"};S(b,c);H(b.g)&&R(b)}});T.instance=this}var Ba=T,V=["GLANCE","Presence","Visitor"],W=aa;
V[0]in W||"undefined"==typeof W.execScript||W.execScript("var "+V[0]);for(var X;V.length&&(X=V.shift());)V.length||void 0===Ba?W[X]&&W[X]!==Object.prototype[X]?W=W[X]:W=W[X]={}:W[X]=Ba;T.prototype=new K;T.prototype.L=function(){J("caching direct server:",this.c);var a={};a.directserver=this.c;a.groupid=this.a.groupid;a.visitorid=this.a.visitorid;a.ws=this.a.ws;la(this.h,a);oa(this.h,20)};
T.prototype.u=function(a){J("presence");if(this.a.visitorid){var b={};y(this.a,b,["groupid","visitorid"]);var c={},d;for(d in this.a)0===d.indexOf("user-")&&(c[d.substring(5)]=this.a[d]);c.url=window.location.href;c.browser=p.name;c.browserver=p.version;c.platform=p.l.name;(a=a&&a.data)&&y(a,c);b.data=c;this.o||(c={type:"presence"},c.data=b.data,S(this,c),this.N=!0);this.D=function(f){"connfail"===f.error&&P(this)}}else m("PRES_NOVISITORID")};T.prototype.presence=T.prototype.u;
T.prototype.R=function(a){var b=this;this.A=!0;N(this,"uniquevisitor","GET",{onsuccess:function(c){m("got unique visitor id",c.visitorid);b.a.visitorid=c.visitorid;b.a.guesttoken=c.guesttoken;b.a.timeout=c.timeout||300;if(b.onuniqueid)b.onuniqueid(c.uniqueid,b.a.timeout);b.connect();a&&a.data&&b.u({data:a.data})},onfail:function(c){Q(b,{error:"connfail",detail:c})}})};T.prototype.connectUnique=T.prototype.R;
T.prototype.S=function(){this.A?3===this.f?(this.disconnect(),this.connect()):Q(this,{error:"connfail",detail:"extend"}):console.error("ERR_EXTEND_UNIQUE")};T.prototype.extendUnique=T.prototype.S;function za(a){a.B?a=ha(M(a,!0,"visitor")):(a=M(a,!0,"visitorws",!1,"wss"),a=new WebSocket(a),ea(a));return a}T.setVisitorId=function(a){T.instance&&T.instance.K(a)};T.prototype.C=function(a){a.data={};N(this,"presence","POST",a)};T.prototype.onblur=function(){m("BLURRED");this.o=!0;R(this)};var Ca=!1;
function Y(){if(!Ca){Ca=!0;var a=xa();a.presence&&"api"!==a.presence&&(new T).u()}}var Z=new G;Z.b.addEventListener&&(document.readyState.match(/complete/)?Y():(Z.b.addEventListener("load",Y),Z.a.addEventListener("DOMContentLoaded",Y,!1)));}).call(window);
