(function() {/*
 this.options.screenshare && */
window.GLANCE||(window.GLANCE={});var GLANCE=window.GLANCE;GLANCE.Video||(GLANCE.Video={},GLANCE.Video.BGEffectsLoaded=!1,GLANCE.Video.BGEffectsLoading=!1);GLANCE.Video.VideoDebug=!1;GLANCE.Video.LogVideoTelemetry=!1;GLANCE.Video.VideoDebugEntryPoints=!1;GLANCE.Video.GlanceVideoSourceScriptElement=document.currentScript;GLANCE.Video.AgentBlurEnabled=!0;GLANCE.Video.polyfilledMediaRecorder=!1;GLANCE.Video.VideoSources=void 0;
GLANCE.Video.GlanceVideoSource=class{constructor(a){this.videoTypes=['video/webm; codecs="avc1.42E01E"',"image/jpeg"];this.defaultVideoType='video/webm; codecs="avc1.42E01E"';this.defaults={width:352,height:288,framerate:24,sessionkey:"",bandwidth:"250kbps",vserver:"https://"+window.location.host+"/",mime:null,modelID:"browser",deviceName:null,maincallid:null,maincid:null,stopPreviewsOnSessionEnd:!0,groupid:null,partnerid:null,username:null,isAnonymous:null,password:null,videoBackEnabled:!1,bgBlur:!1,
bgType:"blur",bgColor:"#2E9CDD",bgImageURL:null,bgFilterEnabled:null,screenshare:!1,screenshareSurfaces:null,segmentationModel:"tflite"};this.authTags="username password partnerid groupid partneruserid loginkey authToken isAnonymous".split(" ");this.commandQueue=new GLANCE.Queue;this.history=new GLANCE.Queue;this.thisGVS=Math.random();this.options=a||this.defaults;for(var b in this.defaults)this.defaults.hasOwnProperty(b)&&(this.options.hasOwnProperty(b)||(this.options[b]=this.defaults[b]));this.options.bitspersecond||
(this.options.bitspersecond=GLANCE.Video.GlanceVideoSource.expandBandwidth(this.options.bandwidth));this.options.requestedbitspersecond=this.options.bitspersecond;this.systemDefaultSource=this.source=this.mime=null;this.torchState=!1;this.activePreviews=new Set;this.requestedPreviews=new Set;this.frameMilliseconds=10;this.isClosing=!1;this.guestCount=0;this.transmitStarted=!1;this.mediaRecorderCount=0;this.paused=!1;this.blurDenied=this.keepAliveTimerID=null;this.websocketBufferLimitInSeconds=1E3;
this.Workaround_14731=60;this.historyTime=3E4;this.historyLookback=3E3;this.lastSpeedChangeTime=null;this.speedChangeTimeout=3E4;this.segmentationModel=this.options.segmentationModel;this.BGEffectInitializedPromise=this.BGEffectsPromise=null;this.bufferReconnect=!1;this.reconnectRetries=0;this.awaitingReconnect=this.giveUpReconnect=!1;this.measuredFramesPerSecond=0;this.orientationChangedRestartTimeoutInMilliseconds=250;this.events={};this.browserCapabilities=JSON.parse(JSON.stringify(GLANCE.browserCapabilities));
this.browserCapabilities.width=screen.width;this.browserCapabilities.height=screen.height;this.browserCapabilities.role="offer";this.browserCapabilities.self=!0;b=Math.floor(Math.random()*Number.MAX_SAFE_INTEGER).toString(16);this.clientKey=this.browserCapabilities.browserId+"|"+b;this.clients=new Map;this.clients.set(this.clientKey,{browserCapabilities:this.browserCapabilities});this.telemetryRollcall=!1;this.currentOrientationPortrait=this.BGEffects=this.rollcallCallback=null;GLANCE.Video.GlanceVideoSource.isIOS()&&
(window.onpageshow=function(c){c.persisted&&!this.paused&&window.location.reload()});if(this.bgBlurEnabled=(this.bgBlurEnabled=null!=this.options.bgFilterEnabled?this.options.bgFilterEnabled:null!==this.options.bgBlur?this.options.bgBlur:GLANCE.Video.AgentBlurEnabled)&&!this.options.screenshare)(this.bgBlurEnabled=this.webgl_support())||console.log(this.videoLogFormatter("NOTICE Background Blurring is disabled "+this.blurDenied));this.profileManager=new GLANCE.Video.GlanceVideoProfileManager(a,this.bgBlurEnabled,
this);this.GVSVersion=null;a=GLANCE.Video.GlanceVideoSourceScriptElement.getAttribute("src");b=a.lastIndexOf("/")+1;this.GVSbaseURL=a.slice(0,b);b=a.lastIndexOf("_");this.GVSVersion=0<=b?a.slice(b):".js";this.bgBlurEnabled&&!GLANCE.Video.BGEffectsLoading&&(GLANCE.Video.BGEffectsLoaded?this.BGEffectsPromise=Promise.resolve():(GLANCE.Video.BGEffectsLoading=!0,a=null,"selfiesegmentation"==this.segmentationModel?a="GlanceVideoBGEffects":"tflite"==this.segmentationModel&&(a="tflite/GlanceVideoBGEffects"),
null!==a?(GLANCE.Video.VideoDebugEntryPoints&&console.log(this.videoLogFormatter("LOADING segmentation Model "+a)),this.BGEffectsPromise=GLANCE.Video.dynamicallyLoadScript(this.GVSbaseURL+a+this.GVSVersion)):console.warn(this.videoLogFormatter("Attempting to load unknown Segmentation model "+this.segmentationModel+" BG Effects disabled"))),this.BGEffectsPromise&&this.BGEffectsPromise.then(()=>{GLANCE.Video.BGEffectsLoaded=!0;GLANCE.Video.BGEffectsLoading=!1;this.BGEffects=new GLANCE.Video.GlanceVideoBGEffects(this);
this.BGEffectInitializedPromise=this.BGEffects.initialize();this.BGEffectInitializedPromise.then(()=>{this.BGEffects.setBackgroundSettings(this.options.bgType,this.options.bgColor,this.options.bgImageURL)})}));this.mediaRecorderAvailablePromise=null;"Safari"!==GLANCE.Video.GlanceVideoSource.getBrowser()&&"Firefox"!==GLANCE.Video.GlanceVideoSource.getBrowser()&&"Chrome"!==GLANCE.Video.GlanceVideoSource.getBrowser()||window.MediaRecorder&&"function"===typeof window.MediaRecorder&&"function"===typeof window.MediaRecorder.isTypeSupported&&
window.MediaRecorder.isTypeSupported('video/webm; codecs="avc1.42E01E"')?this.mediaRecorderAvailablePromise=Promise.resolve():this.mediaRecorderAvailablePromise=new Promise((c,d)=>{GLANCE.Video.polyfilledMediaRecorder?c():(GLANCE.Video.polyfilledMediaRecorder=!0,GLANCE.Video.dynamicallyLoadScript(this.GVSbaseURL+"WebMMediaRecorder"+this.GVSVersion).then(()=>MediaRecorder.load(this.GVSbaseURL,this.GVSVersion)).then(()=>c()))});this.setupOrientationChangeHandlerIfNeeded();this.commandQueue.setOptions({handler:this.handleCommand,
that:this});GLANCE.Send||(GLANCE.Send=this.send.bind(this))}static reportOutOfMemory(){this.bgBlurEnabled&&this.fireEvent("bgFilterPerformanceFail")}webgl_support(){if(this.browserCapabilities.hasWebGL)return!0;this.blurDenied=this.browserCapabilities.WebGLError||"WebGL capability unknown";return!1}async setBackgroundSettings(a,b,c){this.BGEffects&&(await this.BGEffects.setBackgroundSettings(a,b,c),this.options.bgType=a)}setAccepterCount(a){GLANCE.Video.VideoDebug&&console.log(this.videoLogFormatter("SETACCEPTERCOUNT",
a))}getOptions(){return this.options}setOptions(a){for(let b in a)this.defaults.hasOwnProperty(b)&&null!==a[b]&&""!==a[b]&&(this.options[b]=a[b]);this.profileManager.setOptions(this.options)}getSources(a){!GLANCE.Video.GlanceVideoSource.isBrowserCapable()||this.options.screenshare?a(null):this.getSystemDefaultSource().then(b=>{this.enumerateSources().then(c=>{b&&c.forEach(d=>{d.isDefault=d.deviceId===b.deviceId});a(c)})}).catch(b=>{console.error(this.videoLogFormatter(" "),b);a(b)})}getSourcesAsync(){return new Promise((a,
b)=>{try{this.getSources(c=>{a(c)})}catch(c){b(c)}})}async initialize(a,b,c){GLANCE.Video.VideoDebugEntryPoints&&console.log(this.videoLogFormatter("=======INITIALIZE"));this.paused=c;if(b){this.requestedPreviews.add(b);const d=this.getVideoSourceStatus(b);d&&d.requestedPreviews.add(b)}this.bgBlurEnabled&&(await this.BGEffectsPromise,await this.BGEffectInitializedPromise,this.BGEffects.setupBGEffectElements(b));await this.mediaRecorderAvailablePromise;return new Promise((d,e)=>{if(navigator&&navigator.mediaDevices&&
"function"===typeof navigator.mediaDevices.getUserMedia)if(window.MediaRecorder&&"function"===typeof window.MediaRecorder&&"function"===typeof window.MediaRecorder.isTypeSupported){var f;MediaRecorder.isTypeSupported(this.defaultVideoType)?f=this.defaultVideoType:this.videoTypes.forEach(g=>{MediaRecorder.isTypeSupported(g)&&(f=g)});f&&"string"===typeof f||(console.log(this.videoLogFormatter("Mediarecorder.isTypeSupported did not accept",this.videoTypes," we use",this.videoTypes[0])),f=this.videoTypes[0]);
this.mime=f;this.commandQueue.enqueue({name:"initialize",method:async function(g){this.restartVideoStreamInProgress=!0;g||(g={});let h=!1;if(!this.options.screenshare){try{await this.enumerateSources(),g=await this.getSource(g)}catch(k){h=!0,g.message=k}if(!g.source||h){this.restartVideoStreamInProgress=!1;this.fireEvent("error",g.message||"no camera",this.options);e(g);return}}try{g=this.setSourceFromParams(g),g=await this.getConstraints(g),c?g.videoElement=b:(g=await this.getMediaStream(g),g=this.startVideoStream(g),
g=await this.startVideoPreviews(g)),this.saveParams(g),this.restartVideoStreamInProgress=!1,this.fireEvent("initialized",this.options),this.addEventListener("sourceStarted",()=>{this.sendTorchEvent()}),this.fireEvent("sourceStarted",this.source,this.options),b&&!c&&(this.fireEvent("previewStarted",b,this.options),a&&this.alignPreview(a.label,b)),d(g)}catch(k){this.restartVideoStreamInProgress=!1,console.error(this.videoLogFormatter("initialize failure"),k),this.fireEvent("error",k,this.options),e(g)}},
params:{source:a}})}else console.error(this.videoLogFormatter("MediaRecorder is not supported by your browser.")),this.fireEvent("error","MediaRecorder is not supported by your browser.",this.options),e("MediaRecorder not supported by your browser.");else console.error(this.videoLogFormatter("getUserMedia not supported by your browser.")),this.fireEvent("error","getUserMedia not supported by your browser.",this.options),e("getUserMedia not supported by your browser.")})}startSession(a,b){GLANCE.Video.VideoDebugEntryPoints&&
console.log(this.videoLogFormatter("---------------------STARTSESSION"));this.paused=a;void 0!==b&&null!==b&&this.setBgFilterActive(b);null!=this.blurDenied&&(this.fireEvent("info",this.blurDenied,this.options),this.blurDenied=null);a=this.makeOfferQueryString(this.options);this.requestOffer(this.options.vserver,a).then(c=>this.openWebSocket(c)).then(()=>{this.fireEvent("sessionStarted",this.relay);this.blurDenied?this.send("Metrics set Offer.BGAllowed "+this.blurDenied):this.send("Metrics set Offer.BGAllowed true");
if(this.stream){let c=this.getStreamConstraints(this.stream);this.send("Metrics timed Offer.stream.resolution "+c.settings.width+"/"+c.settings.height);this.send("Metrics timed Offer.stream.orientation "+(this.currentOrientationPortrait?"Portrait":"Landscape"))}}).then(()=>{this.paused?this.keepAliveTimer(this):this.commandQueue.enqueue({name:"restartVideoStream",method:this.restartVideoStream,params:{sessionStarting:!0}})}).catch(c=>{console.error(this.videoLogFormatter("startSession "),c);this.fireEvent("error",
c,this.options)})}endSession(){GLANCE.Video.VideoDebugEntryPoints&&console.log(this.videoLogFormatter("endSessionendSessionendSessionendSessionendSession"));this.commandQueue.enqueue({name:"closeVideoStream",method:this.closeVideoStream,params:{},callback:()=>{this.ws&&!this.isClosing&&(this.ws.transmitter("Stopping "+this.clientKey),this.ws.transmitter("Closing "+this.clientKey),this.ws.close(1E3,"endSession"))}})}resumeSession(a,b){GLANCE.Video.VideoDebugEntryPoints&&console.log(this.videoLogFormatter("resumeSessionresumeSessionresumeSessionresumeSession"));
a=JSON.parse(a);this.openWebSocket(a).then(()=>{this.fireEvent("sessionStarted",this.relay)}).then(()=>{this.guestCount=b?b:1;this.transmitStarted=!0;this.commandQueue.enqueue({name:"restartVideoStream",method:this.restartVideoStream,params:{}})}).catch(c=>{console.error(this.videoLogFormatter("startSession "),c);this.fireEvent("error",c,this.options)})}isTorchAvailable(){try{if(this.stream){const a=this.stream.getVideoTracks()[0];if(a&&"function"===typeof a.getCapabilities)return!!a.getCapabilities().torch}return!1}catch(a){return!1}}sendTorchEvent(){this.fireEvent("torch",
!1);setTimeout(()=>{this.isTorchAvailable()&&this.fireEvent("torch",!0)},500)}setTorch(a){if(this.stream){const b=this.stream.getVideoTracks()[0];b&&"function"===typeof b.getCapabilities&&b.getCapabilities().torch&&b.applyConstraints({torch:a,advanced:[{torch:a}]}).then(()=>{this.torchState=a;GLANCE.VideoDebug&&console.log("setTorch",a?"on":"off")}).catch(c=>{console.log("setTorch",a?"on":"off","error",c)})}}getTorch(){return!!this.torchState}async setSource(a){if(a&&!this.options.screenshare&&(a=
"object"===typeof a&&a.deviceId&&"string"===typeof a.deviceId?a.deviceId:a,"string"===typeof a)){var b=await this.enumerateSources();b=this.findSource(b,a);b||(b=await this.enumerateSources(!0),b=this.findSource(b,a));this.source&&this.source.deviceId===b.deviceId||(a=this.setSourceFromParams({source:b}),await this.restartVideoStream(a),GLANCE.Video.VideoDebug&&console.log(this.videoLogFormatter("setSource"),b),this.fireEvent("sourceStarted",b,this.options))}}findSource(a,b){return a.find(c=>c.name===
b||c.label===b?!0:c.deviceId===b)}setSourceFromParams(a){let b=a.source;this.source=b;this.options.device=b&&b.name||b&&b.label||this.options.deviceName||"";return a}keepAliveTimer(a){a.send("KeepAlive");a.keepAliveTimerID||(a.keepAliveTimerID=setInterval(a.keepAliveTimer,3E4,a))}async pause(){if(!this.paused){GLANCE.Video.VideoDebugEntryPoints&&console.log(this.videoLogFormatter("PAUSEPAUSE"));var a=GLANCE.Video.GlanceVideoSource.loadParams(this);this.transmitStarted=!1;a=await this.stopVideoStream(a);
a=await this.releaseUserMedia(a);a.videoElement=this.activePreviews.values().next().value;this.stopAllPreviews();a.stream=null;this.saveParams(a);this.paused=!0;this.fireEvent("sessionPaused");this.options.frameProcessor&&this.options.frameProcessor.pause();this.keepAliveTimer(this);this.lastRequestedMediaStreamConstraints=null}}async unPause(){if(this.paused){GLANCE.Video.VideoDebugEntryPoints&&console.log(this.videoLogFormatter("UNPAUSEUNPAUSEUNPAUSEUNPAUSE"));this.paused=!1;this.options.frameProcessor&&
this.options.frameProcessor.unPause();this.keepAliveTimerID&&clearTimeout(this.keepAliveTimerID);this.keepAliveTimerID=null;var a=GLANCE.Video.GlanceVideoSource.loadParams(this);a.videoElement||(a.videoElement=this.requestedPreviews.values().next().value);a.stream&&(a.stream.mediaStreamStopping=!0);a.stream=null;this.transmitStarted=!0;try{await this.startPreview(a.videoElement),this.fireEvent("sessionUnpaused")}catch(b){this.pause()}}}setBgFilterActive(a){this.BGEffects&&this.BGEffects.setBgFilterActive(a)}getBackgroundSettings(){if(this.BGEffects)return this.BGEffects.bGEffectSettings;
console.warn(this.videoLogFormatter("Warning - getBackgroundSettings called before/without initializing GlanceVideoSource - returning capable false"));return{capable:!1,active:!1,type:""}}getCameraFacingMode(){let a="";this.streamConstraints&&this.streamConstraints.capabilities&&this.streamConstraints.capabilities.facingMode&&0<this.streamConstraints.capabilities.facingMode.length&&(a=this.streamConstraints.capabilities.facingMode[0]);return a.toLowerCase()}alignPreview(a,b){"environment"==this.getCameraFacingMode()||
a&&0<=a.indexOf("back")?b.setAttribute("data-camera","back"):b.removeAttribute("data-camera")}reconnectSession(){this.reconnectWebSocket()}async startPreview(a,b){GLANCE.Video.VideoDebugEntryPoints&&console.log(this.videoLogFormatter("STARTPREVIEWSTARTPREVIEW"));this.paused=b;if(a&&!a.previewActive&&!a.previewIsStarting){this.requestedPreviews.has(a)||this.requestedPreviews.add(a);var c=this.getVideoSourceStatus(a);if(!c)return GLANCE.Video.VideoDebug&&console.log(this.videoLogFormatter("videoSourceStatus is null - invalid element")),
null;c.requestedPreviews.has(a)||c.requestedPreviews.add(a);a.stopPreview=function(){this.stopPreview(this)};this.BGEffects&&this.BGEffects.setupBGEffectElements(a);if(!b){a.previewIsStarting=!0;delete a.previewIsStopping;b=GLANCE.Video.GlanceVideoSource.loadParams(this,{videoElement:a});c="";b&&b.source&&(c=b.source.label);this.alignPreview(c,a);if(this.areStreamsValid())try{await this.startVideoElementPreview(b);this.fireEvent("previewStarted",a,this.options);return}catch(d){console.error(this.videoLogFormatter("couldn't start video element preview because of failure. "),
d)}try{await this.restartVideoStream(b),delete a.previewIsStarting,this.fireEvent("previewStarted",a,this.options)}catch(d){throw GLANCE.Video.VideoDebug&&console.log(this.videoLogFormatter("startPreview aborted with error")),delete a.previewIsStarting,Error(d);}}}}stopPreview(a,b){GLANCE.Video.VideoDebugEntryPoints&&console.log(this.videoLogFormatter("===============stopPreview"));a.previewIsStopping||(a.previewIsStopping=!0,b&&1==b&&(a.preserveStream=!0),delete a.previewIsStarting,a&&this.commandQueue.enqueue({name:"stopOnePreview",
method:this.stopOnePreview,params:a}))}stopAllPreviews(){this.activePreviews.forEach(a=>this.stopPreview(a));this.activePreviews.clear()}quickStopOnePreview(a){var b=this.stream;a&&(a.previewActive&&(b&&b.mostRecentlyActivatedPreview===a&&(b.mostRecentlyActivatedPreview=null),a.srcObject=null),delete a.previewIsStarting,delete a.previewIsStopping,delete a.previewActive,delete a.preserveStream,a.stopPreview=function(){},(b=this.lookupVideoSourceStatus(a.ownerDocument.defaultView))&&b.activePreviews&&
b.activePreviews.delete(a),this.activePreviews.delete(a),GLANCE.Video.VideoDebug&&console.log(this.videoLogFormatter("stopped preview on",a)),this.fireEvent("previewStopped",a,this.options))}stopOnePreview(a){return new Promise((b,c)=>{var d=!1;a?(a.preserveStream&&(d=a.preserveStream),this.quickStopOnePreview(a),0===this.activePreviews.size?this.ws&&this.ws.transmitter&&"function"===typeof this.ws.transmitter?b({element:a}):d?b({element:a}):this.releaseUserMedia({}).then(e=>b(e)):b({element:a})):
c("invalid element")})}setupOrientationChangeHandlerIfNeeded(){GLANCE.Video.GlanceVideoSource.isSafariIOS()?(this.currentOrientationPortrait=window.innerWidth<window.innerHeight,void 0!==window.orientation&&(this.currentOrientationPortrait=0===window.orientation%180),"onorientationchange"in window&&"orientation"in window?(this.onOrientationChange=a=>{this.restartAfterOrientationChange(!0)},window.addEventListener("orientationchange",this.onOrientationChange)):(this.onOrientationChange=a=>{this.mediaRecorder&&
GLANCE.Video.polyfilledMediaRecorder&&(a=window.innerWidth<window.innerHeight,void 0!==window.orientation&&(a=0===window.orientation%180),this.currentOrientationPortrait!==a&&this.restartAfterOrientationChange())},window.addEventListener("resize",this.onOrientationChange))):"Chrome"===GLANCE.Video.GlanceVideoSource.getBrowser()&&(this.onOrientationChange=a=>{let b;void 0!==screen.orientation&&(b=-1!==screen.orientation.type.indexOf("portrait"));this.currentOrientationPortrait!==b&&(this.orientationMustReset=
!0,this.restartAfterOrientationChange())},this.currentOrientationPortrait=window.innerWidth<window.innerHeight,void 0!==screen.orientation?this.currentOrientationPortrait=-1!==screen.orientation.type.indexOf("portrait"):void 0!==window.orientation&&(this.currentOrientationPortrait=0===window.orientation%180),this.orientationMustReset=!1,"orientation"in screen&&"onchange"in screen.orientation?screen.orientation.addEventListener("change",this.onOrientationChange):window.addEventListener("resize",this.onOrientationChange))}orientationChanged(a){return new window.Promise(function(b){const c=
(d,e)=>{window.innerHeight!=e||120<=d?b():window.requestAnimationFrame(()=>c(d+1,e))};c(0,a)})}async restartAfterOrientationChange(a){let b=window.innerHeight;this.restartAfterOrientationChangeTimeout&&(clearInterval(this.restartAfterOrientationChangeTimeout),this.restartAfterOrientationChangeTimeout=void 0);let c=GLANCE.Video.GlanceVideoSource.loadParams(this);c.restarting=!0;await this.stopVideoStream(c);a&&await this.orientationChanged(b);this.restartAfterOrientationChangeTimeout=setTimeout(this.restartAfterOrientationChangeDelay.bind(this),
this.orientationChangedRestartTimeoutInMilliseconds)}restartAfterOrientationChangeDelay(){var a=window.innerWidth<window.innerHeight;void 0!==screen.orientation?a=-1!==screen.orientation.type.indexOf("portrait"):void 0!==window.orientation&&(a=0===window.orientation%180);this.currentOrientationPortrait=a;GLANCE.Video.VideoDebug&&console.log(this.videoLogFormatter("Device orientation has changed to - portrait="+a));this.restartAfterOrientationChangeTimeout=void 0;a=GLANCE.Video.GlanceVideoSource.loadParams(this);
a.restarting=!0;a.discard=!0;this.restartVideoStream(a)}async restartVideoStream(a){if(this.paused)return a;if(this.restartVideoStreamInProgress)return this.abortRestartVideoStream=!0,this.commandQueue.enqueue({name:"restartVideoStream",method:this.restartVideoStream,params:a}),a;this.abortRestartVideoStream=!1;this.restartVideoStreamInProgress=!0;GLANCE.Video.VideoDebug&&console.log(this.videoLogFormatter("enter restartVideoStream"),a);this.pendingRestartTimeout&&(window.clearTimeout(this.pendingRestartTimeout),
this.pendingRestartTimeout=0);try{a=await this.stopVideoStream(a);if(this.abortRestartVideoStream)return this.restartVideoStreamInProgress=!1,GLANCE.Video.VideoDebug&&console.log(this.videoLogFormatter("restartVideoStream aborted after stopVideoStream"),a),a;a=await this.getConstraints(a);if(this.abortRestartVideoStream)return this.restartVideoStreamInProgress=!1,GLANCE.Video.VideoDebug&&console.log(this.videoLogFormatter("restartVideoStream aborted after _getConstraints"),a),a;a=await this.getMediaStream(a);
if(this.abortRestartVideoStream)return this.restartVideoStreamInProgress=!1,GLANCE.Video.VideoDebug&&console.log(this.videoLogFormatter("restartVideoStream aborted after _getMediaStream"),a),a;a=await this.getMediaRecorder(a);if(this.abortRestartVideoStream)return this.restartVideoStreamInProgress=!1,GLANCE.Video.VideoDebug&&console.log(this.videoLogFormatter("restartVideoStream aborted after _getMediaRecorder"),a),a;a=await this.startVideoStream(a);if(this.abortRestartVideoStream)return this.restartVideoStreamInProgress=
!1,GLANCE.Video.VideoDebug&&console.log(this.videoLogFormatter("restartVideoStream aborted after _startVideoStream"),a),a;a=await this.startVideoPreviews(a);if(this.abortRestartVideoStream)return this.restartVideoStreamInProgress=!1,GLANCE.Video.VideoDebug&&console.log(this.videoLogFormatter("restartVideoStream aborted after _startVideoPreviews"),a),a;GLANCE.Video.VideoDebug&&console.log(this.videoLogFormatter("startVideoPreviews done"),a);this.saveParams(a);GLANCE.Video.VideoDebug&&console.log(this.videoLogFormatter("saveParams done"),
a)}catch(b){throw console.error(this.videoLogFormatter("error in restartVideoStream"),b,a),this.fireEvent("error",b,this.options),GLANCE.Video.VideoDebug&&console.log(this.videoLogFormatter("leave restartVideoStream with Reject()"),a),this.restartVideoStreamInProgress=!1,Error(a);}GLANCE.Video.VideoDebug&&console.log(this.videoLogFormatter("leave restartVideoStream"),a);this.restartVideoStreamInProgress=!1;return a}closeVideoStream(a){this.pendingRestartTimeout&&(window.clearTimeout(this.pendingRestartTimeout),
this.pendingRestartTimeout=0);return new Promise(b=>{this.options.stopPreviewsOnSessionEnd&&this.activePreviews.forEach(c=>this.quickStopOnePreview(c));this.transmitStarted=!1;this.guestCount=0;this.stopVideoStream(a).then(c=>this.releaseUserMedia(c)).then(c=>{this.profileManager.onClose();return c}).then(c=>b(c))})}getVideoSourceStatus(a){if(a=a.ownerDocument.defaultView){a.GLANCE||(a.GLANCE={});a.GLANCE.Video||(a.GLANCE.Video={});a.GLANCE.Video.GlanceVideoSourceStatuses||(a.GLANCE.Video.GlanceVideoSourceStatuses=
new Map);let b=a.GLANCE.Video.GlanceVideoSourceStatuses.get(this);b||(b={sender:this,activePreviews:new Set,requestedPreviews:new Set},a.GLANCE.Video.GlanceVideoSourceStatuses.set(this,b));a.addEventListener("unload",this.onPreviewDocumentUnload.bind(this));return b}return null}lookupVideoSourceStatus(a){if(a&&a.GLANCE&&a.GLANCE.Video&&a.GLANCE.Video.GlanceVideoSourceStatuses)return a.GLANCE.Video.GlanceVideoSourceStatuses.get(this)}onPreviewDocumentUnload(a){a=a.currentTarget;let b=this.lookupVideoSourceStatus(a);
if(b&&b.sender){const c=b.sender;b.requestedPreviews.forEach(e=>{this.requestedPreviews.delete(e)});b.requestedPreviews.clear();let d=0;b.activePreviews.forEach(e=>{c.stopPreview(e);d++});GLANCE.Video.VideoDebug&&0<d&&console.log(this.videoLogFormatter("document unload: stopped previews"))}b&&(b.activePreviews.clear(),a.GLANCE.Video.GlanceVideoSourceStatuses.delete(this));a.removeEventListener("unload",this.onPreviewDocumentUnload);this.videoElement=null}async getSource(a){try{const c=a.source;if(c&&
"object"===typeof c&&c.deviceId)return a;if("string"===typeof c){var b=await this.enumerateSources();a.source=this.findSource(b,c);a.source||(b=await this.enumerateSources(!0),a.source=this.findSource(b,c));return a}this.systemDefaultSource||(this.systemDefaultSource=await this.getSystemDefaultSource());a.source=this.systemDefaultSource;return a}catch(c){throw this.systemDefaultSource=a.source=null,a.message=c.message,c;}}async getSystemDefaultSource(){let a;if(this.options.screenshare)return a;if(this.systemDefaultSource&&
this.systemDefaultSource.deviceId&&"string"===typeof this.systemDefaultSource.deviceId)GLANCE.Video.VideoDebug&&console.info(this.videoLogFormatter("default video source",this.systemDefaultSource.label,"refetched")),a=this.systemDefaultSource;else try{delete this.systemDefaultSource;const b=await this.enumerateSources();if(1<b.length)for(let c of b)c.name.startsWith("front")&&(a=c);a||(a=1<=b.length?b[0]:null);this.systemDefaultSource=a;if(!a)throw Error("No camera");}catch(b){throw console.error(this.videoLogFormatter("getSystemDefaultSource"),
b),delete this.systemDefaultSource,b;}return this.systemDefaultSource=a}async enumerateSources(a){let b;try{b=window.sessionStorage}catch(f){b=null}if(!a){if(b&&!GLANCE.Video.VideoSources)try{var c=b.getItem('GLANCE["Video"].VideoSources');if(c){var d=JSON.parse(c);d&&0<d.length&&(GLANCE.Video.VideoSources=d)}}catch(f){}if(GLANCE.Video.VideoSources)return GLANCE.Video.VideoSources}if(navigator&&navigator.mediaDevices&&"function"===typeof navigator.mediaDevices.enumerateDevices){a=null;d=await navigator.mediaDevices.enumerateDevices();
function f(h){return h.filter(k=>"videoinput"===k.kind?(k.label&&0<k.label.length?0<=k.label.toLowerCase().indexOf("back")?(k.ordinal=-2,k.name="back"):0<=k.label.toLowerCase().indexOf("front")?(k.ordinal=-1,k.name="front"):(k.name=k.label.replace(/\s*\([0-9a-fA-f:]{9,}\)\s*$/,""),k.ordinal=g++):(k.ordinal=g,k.name="cam"+g,g++),!0):!1)}let g=0;c=f(d);var e=!1;0==c.length?e=!0:1==c.length&&"cam0"==c[0].name&&""==c[0].deviceId&&(e=!0);if(e||GLANCE.Video.GlanceVideoSource.isMobileDevice()){GLANCE.Video.VideoDebug&&
console.log(this.videoLogFormatter("enumerateSources: getUserMedia"));try{a=await navigator.mediaDevices.getUserMedia({video:!0,audio:!1}),d=await navigator.mediaDevices.enumerateDevices(),g=0,c=f(d)}catch(h){throw GLANCE.Video.VideoDebug&&console.log(this.videoLogFormatter("enumerateDevices getUserMedia exception error - "+h.name)),h.name;}}d=[];if(0<c.length){c.sort((h,k)=>h.ordinal-k.ordinal);try{for(e=0;e<c.length;e++){let h=c[e];d.push({deviceId:h.deviceId,groupId:h.groupId,kind:h.kind,label:h.label?
h.label:h.name,name:h.name})}b&&b.setItem('GLANCE["Video"].VideoSources',JSON.stringify(d))}catch(h){}}a&&this.releaseUserMediaStream(a);return GLANCE.Video.VideoSources=d}throw"navigator.mediaDevices.enumerateDevices() function not available";}async getConstraints(a){a||(a={});var b=await this.getSystemDefaultSource();if(b&&"object"===typeof b&&b.deviceId)this.systemDefaultSource=b;else if(!this.options.screenshare)return a.message=b,a;b=a.source||this.source||this.systemDefaultSource;a.source=b;
let c=this.profileManager.getProfile();if(c){var d={video:{width:c.width,height:c.height,frameRate:c.framerate},audio:!1};d.bitspersecond=c.bitsPerSecond;b&&b.deviceId&&(d.deviceId={exact:b.deviceId},d.video.deviceId={exact:b.deviceId},GLANCE.Video.VideoDebug&&console.info(this.videoLogFormatter(" chosen video source"),b.label,"constraints",d));a.constraints=d}return a}releaseUserMedia(a){a||(a={});return new Promise(b=>{const c=()=>{this.BGEffects&&this.BGEffects.StopRenderingStream();const f=a.stream||
this.stream;f&&(f.mediaStreamStopping=!0,f.getTracks().forEach(g=>{g.stop()}));null!=this.mediaRecorder&&--this.mediaRecorderCount;this.mediaRecorder=null;this.stream=a.stream=null;a.paramSetChanging=!1;this.activePreviews.forEach(g=>delete g.previewActive);b(a)};var d=this.requestedPreviews&&0<this.requestedPreviews.size||this.activePreviews&&0<this.activePreviews.size;const e=this.ws&&this.ws.transmitter&&"function"===typeof this.ws.transmitter&&this.transmitStarted&&0<this.guestCount;"Safari"!==
GLANCE.Video.GlanceVideoSource.getBrowser()||a.paramSetChanging||!d&&!e?(d=this.mediaRecorder)&&"inactive"!==d.state?(d.addEventListener("stop",c),d.stop()):c():b(a)})}getMediaStream(a){let b=a.stream||this.stream;if(b&&!this.options.screenshare){var c=!0;const d=this.lastRequestedMediaStreamConstraints;b.active&&d&&a.constraints&&a.constraints.video&&d.video.width>=a.constraints.video.width&&d.video.height>=a.constraints.video.height&&d.video.frameRate>=a.constraints.video.frameRate&&(d.deviceId&&
d.deviceId.exact&&a.constraints.video.deviceId&&a.constraints.video.deviceId.exact?d.deviceId.exact==a.constraints.video.deviceId.exact&&(c=!1):c=!1);this.options.screenshare&&(c=!1);a.discard&&(c=a.discard,a.discard=void 0);c?(GLANCE.Video.VideoDebug&&console.log(this.videoLogFormatter("_getMediaStream: Discarding mediaStream")),b.mediaStreamStopping=!0,b.getTracks().forEach(e=>{e.stop()}),b=null,this.lastRequestedMediaStreamConstraints=this.stream=a.stream=null):GLANCE.Video.VideoDebug&&console.log(this.videoLogFormatter("_getMediaStream: Keeping mediaStream"))}c=
this.ws&&this.ws.transmitter&&"function"===typeof this.ws.transmitter&&this.transmitStarted&&0<this.guestCount||a.sessionStarting;a.inactive=!(this.requestedPreviews&&0<this.requestedPreviews.size||this.activePreviews&&0<this.activePreviews.size)&&!c;return new Promise((d,e)=>{(a.source||this.options.screenshare)&&a.constraints||e(Error("no webcam"));if(a.inactive)this.releaseUserMedia(a).then(f=>d(f)).catch(f=>e(f));else if(b){a.stream=b;if(this.orientationMustReset){let f=this.getStreamConstraints(b);
f&&f.settings&&this.BGEffects&&this.BGEffects.resetPipelineSize(a.constraints.video.width,a.constraints.video.height,f.settings.width,f.settings.height,this.currentOrientationPortrait)}d(a)}else{const f=a.constraints;if(!this.lastRequestedMediaStreamConstraints||this.lastRequestedMediaStreamConstraints.video.width<f.video.width||this.lastRequestedMediaStreamConstraints.video.height<f.video.height)this.lastRequestedMediaStreamConstraints=f;this.options.screenshare?this.getDisplayMediaStream(f).then(async g=>
{a.stream=g;if(this.options.screenshareSurfaces){const h=g.getVideoTracks()[0];if(!this.options.screenshareSurfaces.includes(h.getSettings().displaySurface))throw this.stream=g,this.fireEvent("invalidsurface"),this.pause(),Error("invalidsurface");}g.getVideoTracks()[0].onended=()=>{this.paused||this.pause()};g.addEventListener("inactive",h=>{this.paused||this.pause()});this.options.frameProcessor?this.options.frameProcessor.getStream(g).then(h=>{a.stream=h;this.stream=a.stream;d(a)}):d(a)}).catch(g=>
{console.error(this.videoLogFormatter("_getMediaStream"),g);e(g)}):this.getUserMediaStream(f).then(async g=>{a.stream=g;let h=20;f.video&&f.video.framerate&&(h=f.video.framerate);this.BGEffects&&await this.BGEffects.startVideoCapture(g,h);d(a)}).catch(g=>{console.error(this.videoLogFormatter("_getMediaStream"),g);e(g)})}})}async getDisplayMediaStream(a){return navigator.mediaDevices.getDisplayMedia({video:!0})}async getUserMediaStream(a,b){b=b||0;var c;if(navigator&&navigator.mediaDevices&&"function"===
typeof navigator.mediaDevices.getUserMedia){let d;try{return GLANCE.Video.VideoDebug&&console.log(this.videoLogFormatter("_getUserMediaStream: getUserMedia")),this.stream=c=await navigator.mediaDevices.getUserMedia(a),d=this.getStreamConstraints(c),c.deviceId=d.settings.deviceId,c.addEventListener("inactive",e=>{e.target.mediaStreamStopping||(console.log(this.videoLogFormatter("MediaStream INACTIVE due to camera error")),this.fireEvent("error","Camera stream ended unexpectedly",e),this.endSession())},
{once:!0}),d&&d.settings&&this.BGEffects&&this.BGEffects.resetPipelineSize(a.video.width,a.video.height,d.settings.width,d.settings.height,this.currentOrientationPortrait),this.send("Metrics timed Offer.stream.resolution "+d.settings.width+"/"+d.settings.height),this.send("Metrics timed Offer.stream.orientation "+(this.currentOrientationPortrait?"Portrait":"Landscape")),GLANCE.Video.VideoDebug&&console.info(this.videoLogFormatter(" chosen video source"),d.track.label,!0===a.video?"probed":"opened"),
c}catch(e){if(d&&d.track)console.error(this.videoLogFormatter(" chosen video source"),d.track.label,!0===a.video?"probe failure":"open failure",e.name);else{if(5>b)return console.log(this.videoLogFormatter("error retrieving stream constraints:"),e,"retrying:",b),e&&e.constraint&&"deviceId"==e.constraint&&(c=await this.enumerateSources(!0),a.video.deviceId=c[0]),this.getUserMediaStream(a,++b);console.error(this.videoLogFormatter("cannot retrieve stream constraints"),a)}throw e.name;}}else throw Error("Browser MediaRecorder unavailable. Use Google Chrome.");
}releaseUserMediaStream(a){try{if(a){const b=a.getTracks();if(b)for(a=0;a<b.length;a++)b[a].stop()}}catch(b){console.error(this.videoLogFormatter("releaseUserMediaStream"),b)}}async getMediaRecorder(a){if(a.inactive||!this.transmitStarted)return a;this.BGEffects&&(this.BGEffects.skipEffectRendering=!0);await this.mediaRecorderAvailablePromise;var b=a.constraints,c=this.profileManager.getProfile(),d=c?c.bitsPerSecond:b.bitspersecond;const e=c?c.framerate:b.video.frameRate;GLANCE.Video.polyfilledMediaRecorder?
this.frameMilliseconds=1E3/e:this.mime.startsWith("video/webm")&&0<this.Workaround_14731&&480>Math.min(b.video.height,b.video.width)&&(d=d*this.Workaround_14731/e);this.options.screenshare&&(this.frameMilliseconds=1E3/e);b=null;this.BGEffects&&this.BGEffects.effectRenderedStream?(b=c?c.width:a.constraints.video.width,c=c?c.height:a.constraints.video.height,this.BGEffects.resetPipelineSize(b,c,b,c,this.currentOrientationPortrait),b=this.BGEffects.effectRenderedStream):b=a.stream;c={mimeType:this.mime};
c.videoBitsPerSecond=d;c.bitsPerSecond=d;c.audioBitsPerSecond=0;this.mediaRecorder&&console.error(this.videoLogFormatter("about to create a new MediaRecorder when one already exists"));c.qualityParameter="number"===typeof a.qualityParameter?.01*a.qualityParameter:.75;d=new MediaRecorder(b,c);d.addEventListener("resize",()=>{this.restartAfterOrientationChange(!0)});GLANCE.Video.VideoDebug&&console.log(this.videoLogFormatter("NEW MEDIARECORDER"));this.mediaRecorderCount+=1;this.mediaRecorder=d;a.streamConstraints=
this.getStreamConstraints(a.stream);this.options.sourceDevice=a.streamConstraints.track.label;this.BGEffects&&(this.BGEffects.skipEffectRendering=!1);return a}startVideoStream(a){if(a.inactive)return a;const b=a.stream,c=this.mediaRecorder;let d=null;this.ws&&this.ws.transmitter&&"function"===typeof this.ws.transmitter&&this.transmitStarted&&0<this.guestCount&&(d=this.ws.transmitter);if(d&&"function"===typeof d){d("T "+JSON.stringify({client:this.clientKey,browserCapabilities:this.browserCapabilities}));
const e=this.makeInfoQueryString();d(`Info set ${e}`);d(`Starting ${this.mime}`)}this.requestedPreviews&&0<this.requestedPreviews.size||this.activePreviews&&0<this.activePreviews.size||d||this.BGEffects&&this.BGEffects.effectVideoCaptureElement?(GLANCE.Video.VideoDebug&&console.debug(this.videoLogFormatter(d?"start preview and transmit stream":"start preview only stream")),c&&d&&(this.relay.frameindex=0,c.ondataavailable=d,c.start(this.frameMilliseconds)),this.BGEffects&&this.BGEffects.startupRendering(a.constraints.video.frameRate)):
GLANCE.Video.VideoDebug&&console.debug(this.videoLogFormatter("no transmitter, no preview, do not start capture stream"));a.streamConstraints=this.getStreamConstraints(b);return a}areStreamsValid(){if(this.stream&&this.stream.active)if(this.bgBlurEnabled){if(this.BGEffects&&this.BGEffects.effectRenderedStream)return!0}else{const a=this.profileManager.getProfile();if(a){let b=a.width,c=a.height,d=this.getStreamConstraints(this.stream);if(d.settings&&d.settings.width!=b&&d.settings.height!=c||this.constraints&&
a.framerate&&this.constraints.video.frameRate&&this.constraints.video.frameRate!=a.framerate)return!1}return!0}return!1}saveParams(a,b){b=b||this;b.stream=a.stream;b.videoElement=a.videoElement;b.streamConstraints=a.streamConstraints;b.source=a.source;b.constraints=a.constraints;b.indexDelta=a.indexDelta;b.qualityParameter=a.qualityParameter}static getScreenshareSurfaces(){return{application:"application",window:"window",browser:"browser",monitor:"monitor"}}static loadParams(a,b){a={stream:a.stream,
streamConstraints:a.streamConstraints,source:a.source,videoElement:a.videoElement,constraints:a.constraints,indexDelta:a.indexDelta,qualityParameter:a.qualityParameter};if(b)for(const c in b)b.hasOwnProperty(c)&&(a[c]=b[c]);return a}async startVideoPreviews(a){if(a.inactive)return a;const b=new Set(this.activePreviews);this.requestedPreviews.forEach(d=>b.add(d));const c=[];b.forEach(d=>{d&&(d.tagName&&"string"===typeof d.tagName&&"VIDEO"===d.tagName.toUpperCase()?c.push(d):console.error(this.videoLogFormatter("unexpected video preview element:",
d,"Possible MooTools corruption of Array.forEach()")))});for(let d=0;d<c.length;d++)this.commandQueue.enqueue({name:"startVideoElementPreview",method:this.startVideoElementPreview,params:{stream:a.stream,videoElement:c[d]}});return a}startVideoElementPreview(a){let b=a.stream;const c=a.videoElement;return new Promise((d,e)=>{let f;const g=k=>{delete c.isPlayRequestInProgress;c.removeEventListener("playing",f);c.removeEventListener("abort",g);c.removeEventListener("error",g);console.error(this.videoLogFormatter("preview play failed: abort or error occurred. "),
k,c.readyState,b.active);e("preview play failed: abort or error occurred. ")};f=k=>{GLANCE.Video.VideoDebug&&console.log(this.videoLogFormatter("playRequestComplete entered"),!!c.isPlayRequestInProgress,k||"event",c,c.readyState,b.active);c.removeEventListener("playing",f);c.removeEventListener("abort",g);c.removeEventListener("error",g);c.isPlayRequestInProgress?(GLANCE.Video.VideoDebug&&console.log(this.videoLogFormatter("playRequestComplete activity"),k||"event",c,c.readyState,b.active),delete c.isPlayRequestInProgress,
c.previewActive=!0,this.requestedPreviews.delete(c),this.activePreviews.add(c),c.ownerDocument&&c.ownerDocument.defaultView&&(k=this.lookupVideoSourceStatus(c.ownerDocument.defaultView))&&(k.requestedPreviews.delete(c),k.activePreviews.add(c)),b.mostRecentlyActivatedPreview=c,b.activePreviews=this.activePreviews,"Safari"===GLANCE.Video.GlanceVideoSource.getBrowser()&&this.BGEffects&&this.BGEffects.effectRenderedCanvas&&(b.canvas=this.BGEffects.effectRenderedCanvas),GLANCE.Video.VideoDebug&&console.log(this.videoLogFormatter("started preview on"),
c,c.readyState,b.active)):GLANCE.Video.VideoDebug&&console.log(this.videoLogFormatter("playRequestComplete BUT NO isPlayRequestInProgress - resolving anyway"),k||"event",c,c.readyState,b.active);d()};if(c)if(c&&"VIDEO"!==c.tagName.toUpperCase())e("not a video element");else if(c&&b!==c.srcObject)if(c.isPlayRequestInProgress)GLANCE.Video.VideoDebug&&console.log(this.videoLogFormatter("play request already in progress"),c.readyState,b.active),d();else{this.BGEffects&&this.BGEffects.effectRenderedStream&&
(b=this.BGEffects.effectRenderedStream);c.setAttribute("playsinline",!0);c.setAttribute("muted",!0);c.srcObject=b;c.isPlayRequestInProgress=!0;c.addEventListener("playing",f);c.addEventListener("abort",g);c.addEventListener("error",g);GLANCE.Video.VideoDebug&&console.log(this.videoLogFormatter("about to call element.play on "),c,c.readyState,b.active);c.load();"Safari"===GLANCE.Video.GlanceVideoSource.getBrowser()&&(c.style.backgroundColor="black");var h=c.play();h&&"undefined"!==typeof h?h.then(()=>
{f()}).catch(k=>{g(k)}):d()}else c&&b===c.srcObject?d():e("no video element to play");else e("no video element provided")})}stopVideoStream(a){a||(a={});return new Promise(b=>{const c=this.mediaRecorder;if(c){if(c.ondataavailable){var d="Stopping";a.restarting&&(d+=" restarting=true");a.restarting=null;c.ondataavailable(d)}c.ondataavailable=null;c.stop();GLANCE.Video.VideoDebug&&1!==this.mediaRecorderCount&&console.error(this.videoLogFormatter(this.mediaRecorderCount,"MediaRecorder instances right before deletion"));
delete this.mediaRecorder;this.mediaRecorder=null;--this.mediaRecorderCount}b(a)})}getStreamConstraints(a){a=a.getVideoTracks();if(!a||1<=!a.length||!a[0])return null;a=a[0];const b=a.getSettings?a.getSettings():null,c=a.getConstraints?a.getConstraints():null,d=a.getCapabilities?a.getCapabilities():null;return{settings:b,constraints:c,capabilities:d,track:a}}makeInfoQueryString(){var a=this.profileManager.getProfile();if(a){var b=a.width,c=a.height;if(!(this.BGEffects&&this.BGEffects.effectRenderedStream||
this.options.screenshare)&&this.stream){var d=this.stream.getVideoTracks();if(d&&1<=d.length){d=d[0];const e=d.getSettings?d.getSettings():null;e&&(b=e.width,c=e.height,GLANCE.Video.GlanceVideoSource.isSafariIOS()&&(d=window.innerWidth<window.innerHeight,void 0!==window.orientation&&(d=0==window.orientation%180),d&&b>c&&(b=e.height,c=e.width)))}}a={videowidth:Number(b).toFixed(0),videoheight:Number(c).toFixed(0),downsample:Number(a.downsample||1).toFixed(1),framerate:Number(a.framerate).toFixed(2),
bitrate:Number(a.bitsPerSecond).toFixed(0),paramset:Number(a.paramIndex||0),pframes:Number(a.pframes||100)};(b=this.profileManager.getRealFramerate())&&(a.realFramerate=Number(b).toFixed(2));b=[];for(let e in a)a.hasOwnProperty(e)&&b.push(`${e}=${a[e]}`);return b.join("&")}return""}makeOfferQueryString(a){const b=[];b.push("videowidth="+a.width);b.push("videoheight="+a.height);b.push("bandwidth="+a.bitspersecond);b.push("framerate="+a.framerate);b.push("passcode="+encodeURIComponent(a.sessionkey));
a.videoBackEnabled&&b.push("videoBackEnabled="+a.videoBackEnabled);b.push("modelID="+encodeURIComponent(a.screenshare?"screenshare/"+this.mime:a.modelID+"/"+this.mime));b.push("localizedName="+encodeURIComponent(a.deviceName||a.device||"webcam"));b.push("MIME="+encodeURIComponent(this.mime));a.conntype?b.push("conntype="+a.conntype):a.role&&b.push("conntype="+a.role);a.maincallid?b.push("maincallid="+a.maincallid):a.maincid&&b.push("maincallid="+a.maincid);b.push("uniqueID="+encodeURIComponent(navigator.userAgent));
a.personid&&b.push("personid="+a.personid);a.screenshare&&b.push("isScreenshare=true");for(let c=0;c<this.authTags.length;c++){const d=this.authTags[c];a.hasOwnProperty(d)&&a[d]&&b.push(d+"="+encodeURIComponent(a[d]))}return b}requestOffer(a,b,c="PUT",d="offer"){return new Promise((e,f)=>{const g={method:c,cache:"no-cache",credentials:"include",cors:"cors",body:b.join("&"),headers:new Headers({Accept:"application/json","Content-type":"application/x-www-form-urlencoded"})};fetch(a+d,g).then(h=>{h.ok&&
h.json||f(h);return h.json()}).then(h=>{this.currentOfferDescriptor=h;e(h)}).catch(h=>{console.error(this.videoLogFormatter(a),h);f({ok:!1,status:408,statusText:"no response from server: "+h})})})}openWebSocket(a){return new Promise(async(b,c)=>{this.isClosing=!1;const d=a.offerer,e=a.streamid,f={};f.descriptor=a;f.streamId=e;f.connection=this.ws;f.request=d;f.role="offer";f.octetcount=0;f.packetcount=0;f.frameindex=0;f.username=a.username||"";this.relay=f;this.profileManager.setDescriptor(a);try{await this.makeAWebSocket(d),
b()}catch(g){this.shutdownNow(g,"error"),c()}})}static GetExponentialBackoffTime(a){4<a&&(a=4);return 1E3*(2**a+1*Math.random())}async reconnectWebSocket(){if(this.awaitingReconnect)GLANCE.Video.VideoDebug&&console.log(this.videoLogFormatter("reconnectWebSocket - already waiting"));else{var a=GLANCE.Video.GlanceVideoSource.GetExponentialBackoffTime(0);setTimeout(this.retryWebSocketConnect.bind(this),a);GLANCE.Video.VideoDebug&&console.log(this.videoLogFormatter("Websocket reconnect attempt",0," in ",
a," ms"))}}async retryWebSocketConnect(){this.reconnectRetries++;try{this.awaitingReconnect=!0,GLANCE.Video.VideoDebug&&console.log(this.videoLogFormatter("Awaiting makeAWebSocket")),await this.makeAWebSocket(this.relay.request),this.bufferReconnect&&this.stepDownPerformanceProfile(-2),this.reconnectRetries=0,this.awaitingReconnect=!1,this.bufferReconnect?this.bufferReconnect=!1:(GLANCE.Video.VideoDebug&&console.log(this.videoLogFormatter("Reconnect successful - going to _restartVideoStream")),await this.restartVideoStream())}catch(b){if(6>
this.reconnectRetries){var a=GLANCE.Video.GlanceVideoSource.GetExponentialBackoffTime(this.reconnectRetries);setTimeout(this.retryWebSocketConnect.bind(this),a);GLANCE.Video.VideoDebug&&console.log(this.videoLogFormatter("got error from makeAWebSocket: reconnect attempt",this.reconnectRetries," in ",a," ms"))}else this.bufferReconnect=!1,this.reconnectRetries=0,this.awaitingReconnect=!1,this.giveUpReconnect=!0,console.log(this.videoLogFormatter("Too many retries in Reconnect"))}}shutdownNow(a,b="sessionEnded"){GLANCE.Video.VideoDebugEntryPoints&&
console.log(this.videoLogFormatter("shutdownNowshutdownNow "+b));this.isClosing||(this.reportHistoryInterval&&clearInterval(this.reportHistoryInterval),this.reportHistoryInterval=null,this.history.clear(),this.closeVideoStream({}).then(()=>{this.fireEvent(b,this.options,a);this.ws&&this.ws.intervalPing&&(clearTimeout(this.ws.intervalPing),this.ws.intervalPing=null);this.ws=null}),this.isClosing=!0)}send(a){if(a&&"string"===typeof a&&0<a.length&&this.ws&&this.ws.transmitter)return this.ws.transmitter(a),
a}async makeAWebSocket(a){return new Promise((b,c)=>{let d=new WebSocket(a);this.ws=d;d.binaryType="blob";!this.reportHistoryInterval&&0<this.historyLookback&&0<this.historyTime&&this.history&&(this.reportHistoryInterval=setInterval(this.reportHistory.bind(this),this.historyTime,this));d.onopen=()=>{this.awaitingReconnect=!1;b()};d.onclose=f=>{GLANCE.Video.VideoDebug&&console.debug(this.videoLogFormatter("Websocket close "),f);if(!f.wasClean||this.bufferReconnect){this.bufferReconnect?GLANCE.Video.VideoDebug&&
console.log(this.videoLogFormatter("websocket CLOSE - buffer reconnect")):f.wasClean||GLANCE.Video.VideoDebug&&console.log(this.videoLogFormatter("websocket CLOSE - clean flag is "+f.wasClean));try{this.giveUpReconnect?(this.giveUpReconnect=!1,this.shutdownNow(f,"error")):this.reconnectWebSocket()}catch(g){this.shutdownNow(g,"error")}}else this.shutdownNow(f,"sessionEnded")};d.onerror=f=>{console.error(this.videoLogFormatter("websocket error "),f);f.statusMessage||(f.statusMessage="websocket error");
c(f)};let e;d.transmitter=f=>{const g=Date.now();e=e||g;let h;var k=f.data||null;k&&k instanceof Blob&&0!==k.size?(g>e&&(e=g),this.relay.octetcount+=k.size,this.relay.packetcount+=1,this.relay.frameindex+=1,h=this.transmitStarted?k:null,this.history.enqueue({timestamp:g,size:k.size}),h&&(f=100,GLANCE.Video.polyfilledMediaRecorder&&(f=2*this.profileManager.getProfile().framerate),this.profileManager.frame(this.relay.frameindex,f))):"string"===typeof f&&0<f.length&&(h=f,GLANCE.Video.VideoDebug&&(GLANCE.Video.LogVideoTelemetry||
!h.startsWith('T {"client'))&&console.log(this.videoLogFormatter("send command: ",h)));if(this.ws&&d&&1===d.readyState&&h){if(0<d.bufferedAmount&&(f=1E5,this.constraints.bitspersecond&&(f=this.constraints.bitspersecond/8),f*=this.websocketBufferLimitInSeconds/1E3,k=1E3>.25*f?1E3:.25*f,d.bufferedAmount>k)){GLANCE.Video.VideoDebug&&console.log(this.videoLogFormatter("ws.bufferedAmount exceeds limit of "+k+" enough to downgrade"));(!this.profileManager.shouldDowngrade&&!this.profileManager.lastDowngradeTime||
g-this.profileManager.lastDowngradeTime>this.profileManager.minDowngradeInterval)&&this.profileManager.offererNetworkFailure();try{if(d.bufferedAmount>f){GLANCE.Video.VideoDebug&&console.log(this.videoLogFormatter("ws.bufferedAmount exceeds limit of "+f+" enough to drop the connection"));this.bufferReconnect=!0;d.close(3E3,"buffer reconnect");return}}catch(l){GLANCE.Video.VideoDebug&&console.error(this.videoLogFormatter(" "),l)}}d.send(h)}};d.onmessage=f=>{"Restart"==f.data?(this.restartAfterOrientationChangeDelay(),
this.commandQueue.clear()):(GLANCE.Video.VideoDebug&&!f.data.startsWith('T {"client')&&console.debug(this.videoLogFormatter("receiving",f.data)),this.commandQueue.enqueue(f))}})}reportHistory(){for(var a=Date.now(),b=this.history,c=b.peek();c&&"number"===typeof c.timestamp&&c.timestamp<=a-this.historyLookback;)b.dequeue(),c=b.peek();if(c&&"number"===typeof c.timestamp){var d=c.timestamp;let f=c.timestamp;a=-1;c=-c.size;for(var e of b)c+=e.size,a+=1,f=e.timestamp;b=f-d;0<b&&0<a&&(e=(d=this.profileManager.getProfile())?
d.bitsPerSecond/1E6:0,d=d?d.framerate:0,c=c/b*8,this.measuredFramesPerSecond=a/b*1E3,this.browserCapabilities.bitrate=Number((1E3*c).toFixed(0)),this.browserCapabilities.framerate=Number(d.toFixed(2)),this.ws.transmitter("T "+JSON.stringify({client:this.clientKey,browserCapabilities:this.browserCapabilities})),GLANCE.Video.VideoDebug&&console.log(this.videoLogFormatter(`actual: ${(c/1E3).toFixed(2)}mbps ${this.measuredFramesPerSecond.toFixed(1)}fps`+` requested: ${e.toFixed(2)}mbps  ${d.toFixed(1)}fps`)),
this.send("Metrics minmaxavg Offer.stream.framerate "+this.measuredFramesPerSecond.toFixed(1)),this.send("Metrics minmaxavg Offer.stream.bitrate "+(c/1E3).toFixed(2)))}}async dispatchCommand(a){GLANCE.Video.VideoDebug&&(GLANCE.Video.LogVideoTelemetry||!a.startsWith('T {"client'))&&console.debug(this.videoLogFormatter("processing",a));var b=a.split(/\s+/);if(1>b.length)throw Error("no command: "+a);const c=b.shift();var d=b.join(" "),e=1<=b.length?b.shift():null;const f=b.join(" ");var g=Number(f);
isNaN(g)&&(g=f);"string"===typeof g&&0===g.length&&(g=!1);var h=GLANCE.Video.GlanceVideoSource.loadParams(this);switch(c){case "Failure":case "Error":GLANCE.Video.VideoDebug&&console.info(this.videoLogFormatter(a));break;case "Info":h=!1;if(e)switch(e){case "viewers":this.fireEvent("guestCountChanged",g,this.options);this.guestCount=g;h=!0;break;case "debug":GLANCE.Video.VideoDebug=g,h=!0}h||this.fireEvent("info",d,this.options);break;case "Start":this.transmitStarted=!0;if(this.options.screenshare&&
this.restartVideoStreamInProgress)break;this.lastSpeedChangeTime=Date.now();"string"===typeof d&&(b=d.trim().split("#"),a=1<=b.length?b[0]:"",d=2<=b.length?b[1]:void 0,e=3<=b.length?Number(b[2]):void 0,g=4<=b.length?Number(b[3]):void 0,b=5<=b.length?b[4]:"open",GLANCE.Video.VideoDebug&&console.log(this.videoLogFormatter("Start",a,d,e,g,b)),d&&e&&g?this.profileManager.addAcceptor(d,e,g):this.profileManager.acceptors&&0!=Object.keys(this.profileManager.acceptors).length||this.profileManager.staticMode());
this.paused||!this.areStreamsValid()||this.restartVideoStreamInProgress?(GLANCE.Video.VideoDebugEntryPoints&&console.log(this.videoLogFormatter("STARTSTARTSTART   FULL RESTARTVIDEOSTREAM ")),await this.restartVideoStream(h)):(GLANCE.Video.VideoDebugEntryPoints&&console.log(this.videoLogFormatter("STARTSTARTSTART   ONLY RESTART MR ")),h.restarting=!0,h=await this.stopVideoStream(h),h=await this.getConstraints(h),h=await this.getMediaRecorder(h),h=await this.startVideoStream(h),this.saveParams(h));
break;case "Stop":GLANCE.Video.VideoDebugEntryPoints&&console.log(this.videoLogFormatter("!!!!!!!!!!!STOPSTOPSTOPSTOP"));this.transmitStarted=!1;h=await this.stopVideoStream(h);h=await this.releaseUserMedia(h);this.saveParams(h);this.pendingRestartTimeout||(this.pendingRestartTimeout=window.setTimeout(k=>{this.commandQueue.enqueue({name:"restartVideoStream",method:this.restartVideoStream,params:k});this.pendingRestartTimeout=0},200,h));break;case "Faster":GLANCE.Video.VideoDebugEntryPoints&&console.log(this.videoLogFormatter("Faster - Ignoring Faster command"));
break;case "Slower":"reason=device"==e?this.profileManager.acceptorRenderFailure(b[b.length-1]):"reason=network"==e?this.profileManager.acceptorNetworkFailure(b[b.length-1]):this.profileManager.legacySlower();break;case "Ping":this.ws.transmitter&&this.ws.transmitter("Pong "+d);break;case "Pong":try{const k=Date.now(),l=JSON.parse(d),p=(k-Number(l.time)).toFixed(0),m=this.relay.octetcount-Number(l.octetcount),n=this.relay.packetcount-Number(l.packetcount);(0<m||0<n)&&console.log(this.videoLogFormatter(`ping ${p}ms backlog octets:${m} packets:${n}`))}catch(k){console.error(this.videoLogFormatter("Pong "),
k)}break;case "Passthrough":if(e)switch(e){case "SessionInvitation":d=a.indexOf("username=");e=a.indexOf("&sessionkey=");h=a.indexOf("&sessiontype=");-1<d&&-1<e&&-1<h?(d=a.slice(d+9,e),e=a.slice(e+12,h),h=a.slice(h+13),GLANCE.Video.VideoDebug&&console.log(this.videoLogFormatter(`SessionInvitation message received GlanceAddress: ${d} Session Key:${e} Sesion Viewer:${h}`)),this.fireEvent("sessionInvitation",d,e,h)):GLANCE.Video.VideoDebug&&console.log(this.videoLogFormatter(` Malformed SessionInvitation message received: ${a}`));
break;case "sendpassthrough":this.fireEvent("passthrough",f)}break;case "updatedProfile":try{let k=JSON.parse(d);await this.switchProfile(k,h)}catch(k){console.error(this.videoLogFormatter("Invalid object returned for profile update "),k)}break;case "T":try{this.handleTelemetry(JSON.parse(d))}catch(k){console.error(this.videoLogFormatter("Cannot handle telemetry error - "),k," payload - ",d)}break;case "Closed":d&&(this.clients.has(d)&&this.clients.delete(d),this.profileManager.removeAcceptor(d));
break;default:GLANCE.Video.VideoDebug&&console.log(this.videoLogFormatter("Unexpected websocket metadata received:",a))}}startTelemetryRollcall(a){this.telemetryRollcall=!0;this.rollcallCallback=a;this.clients.forEach(b=>{b.rollCallPresent=!1})}checkRollcall(){let a=!0;this.clients.forEach((b,c)=>{c!=this.clientKey&&(a=a&&b.rollCallPresent)});a&&(this.telemetryRollcall=!1,this.rollcallCallback())}handleTelemetry(a){const b=a.client,c={};a.browserCapabilities&&(c.browserCapabilities=a.browserCapabilities);
a.client===this.clientKey?this.browserCapabilities=a.browserCapabilities:(c.browserCapabilities.self=!1,this.telemetryRollcall&&(c.rollCallPresent=!0));this.clients.set(b,c);(a=c.browserCapabilities)&&a.clientWidth&&a.clientHeight&&this.profileManager.addAcceptor(b,a.clientWidth,a.clientHeight,a.screenWidth,a.screenHeight,a.devicePixelRatio);this.telemetryRollcall&&this.checkRollcall()}onProfileChanged(a){GLANCE.Video.VideoDebug&&console.info(this.videoLogFormatter("Video profile changed to: "),a);
this.logToServer(this.videoLogFormatter("Video profile changed to:"),a);a=GLANCE.Video.GlanceVideoSource.loadParams(this);a.restarting=!0;this.commandQueue.enqueue({name:"restartVideoStream",method:this.restartVideoStream,params:a})}onProfileRealFramerate(a){GLANCE.Send("Info realFramerate "+a)}onProfileLog(a){this.logToServer(a)}logToServer(){var a=Array.prototype.slice.call(arguments);a.splice(0,0,"Log","notice");for(var b=0;b<a.length;b++)"object"===typeof a[b]&&(a[b]=JSON.stringify(a[b]));this.send(a.join(" "))}stepDownPerformanceProfile(a){this.profileManager.offererEncodingFailure()}updateVideoOptions(a){GLANCE.Video.VideoDebugEntryPoints&&
console.log(this.videoLogFormatter("updateVideoOptionsupdateVideoOptions"+a));a.width&&(this.options.width=a.width,this.options.width>this.profileManager.maximumWidth&&(this.profileManager.maximumWidth=this.options.width));a.height&&(this.options.height=a.height,this.options.height>this.profileManager.maximumHeight&&(this.profileManager.maximumHeight=this.options.height));a.bitspersecond&&(this.options.bitspersecond=a.bitspersecond);a.framerate&&(this.options.framerate=a.framerate);a.modelID&&(this.options.modelID=
a.modelID);this.profileManager.setOptions(this.options);this.profileManager.getMode()==GlanceVideoProfileManagerMode.STATIC&&this.send("requestNewProfile "+JSON.stringify(a))}doSwitchProfileRestart(a){this.telemetryRollcall=!1;this.pendingRestartTimeout&&(window.clearTimeout(this.pendingRestartTimeout),this.pendingRestartTimeout=0);this.restartVideoStream(a);this.profileManager.resume()}async switchProfile(a,b){GLANCE.Video.VideoDebugEntryPoints&&console.log(this.videoLogFormatter("switchProfileswitchProfile"));
this.descriptor&&this.relay?(this.descriptor.coderparams=a.params,this.paramset=this.descriptor.coderparams[0],this.relay.devicedescriptor=this.descriptor.devicedescriptor=a.devicedescriptor,this.paramIndex=0,b.indexDelta=0,b.restarting=!0,this.paused||(this.profileManager.pause(),this.profileManager.setDescriptor(this.descriptor),this.startTelemetryRollcall(()=>{this.doSwitchProfileRestart(b)}),this.pendingRestartTimeout||(this.pendingRestartTimeout=window.setTimeout(()=>{this.doSwitchProfileRestart(b)},
1E3))),this.fireEvent("profileUpdated",this.relay)):GLANCE.Video.VideoDebug&&console.log(this.videoLogFormatter("switchProfile called with null descriptor"))}async dispatchMethod(a,b,c){a=await a.call(this,b);c&&"function"===typeof c&&(a=c(a));return a}handleCommand(a,b){let c;if(a&&a.data&&"string"===typeof a.data){var d=a.data;let f=!0;for(var e of b)if(e&&e.data&&"string"===typeof e.data&&d===e.data){f=!1;break}f&&(c=b._options.that.dispatchCommand(a.data))}else if(a&&a.method&&"string"===typeof a.name){e=
!0;for(d of b)if(d&&d.name&&d.name===a.name){e=!1;break}e&&a.method&&"function"===typeof a.method&&(c=b._options.that.dispatchMethod(a.method,a.params,a.callback))}else console.error(a,"unrecognized queue element"),b.complete(a);c?c.then(()=>{b.complete(a)}).catch(f=>{console.error(a,f);b.complete(a)}):(GLANCE.Video.VideoDebug&&console.error("skipped","string"===typeof a.data?a.data:a.name,"string"===typeof a.data?"command":"method","queued:",b.getLength()),b.complete(a))}static expandBandwidth(a,
b=256E3){a=a.match(/^(\d+)([KMGkmg]?[A-Za-z]*)$/);return 3>a.length?b||128E3:"kbps"===a[2]?1E3*a[1]:"mbps"===a[2]?1E6*a[1]:"gbps"===a[2]?1E9*a[1]:"K"===a[2]?8192*a[1]:"M"===a[2]?8388608*a[1]:"G"===a[2]?8589934592*a[1]:b||128E3}addEventListener(a,b){this.events.hasOwnProperty(a)?this.events[a].push(b):this.events[a]=[b]}removeAllEventListeners(){for(var a in this.events)delete this.events[a]}removeEventListener(a,b){this.events.hasOwnProperty(a)&&(b=this.events[a].indexOf(b),-1!==b&&(this.events[a][b]=
null,this.events[a].splice(b,1),0===this.events[a].length&&delete this.events[a]))}fireEvent(a){if(this.events.hasOwnProperty(a)){var b=Array.prototype.slice.call(arguments,1),c=this.events[a];for(let d=0;d<c.length;d++){const e=c[d];e&&"function"===typeof e&&"function"===typeof e.apply&&e.apply(null,b)}}}sendSessionInvitation(a,b,c){this.send("Passthrough SessionInvitation username="+a+"&sessionkey="+b+"&sessiontype="+c)}videoLogFormatter(a){let b="(v) ";this.options.screenshare&&(b="(ss) ");arguments[0]=
b+arguments[0];return Array.from(arguments).join(" ")}static getBrowser(){return GLANCE.browserCapabilities.browser}static isBrowserCapable(){return GLANCE.browserCapabilities.isBrowserCapable}static isSafariIOS(){return GLANCE.browserCapabilities.isSafariIOS}static isIOS(){return GLANCE.browserCapabilities.isIOS}static isAndroid(){return GLANCE.browserCapabilities.isAndroid}static isMobileDevice(){return GLANCE.browserCapabilities.isIOS||GLANCE.browserCapabilities.isAndroid}static isAgentVideoCapable(){return new Promise(function(a,
b){const c=GLANCE.Video.GlanceVideoSource.getBrowser();"Chrome"!==c&&"Safari"!==c&&"Firefox"!==c?b(c+" does not support video"):navigator&&navigator.mediaDevices&&"function"===typeof navigator.mediaDevices.getUserMedia?"function"!==typeof navigator.mediaDevices.enumerateDevices?b(c+" does not support enumerateDevices"):navigator.mediaDevices.enumerateDevices().then(d=>{(d=d.some(e=>"videoinput"===e.kind))?a(d):b("No video input devices available")}):b(c+" does not support getUserMedia")})}};
GLANCE.Queue=class{constructor(a){this._queue=[];this._offset=0;this._current=null;this._options=a||{}}setOptions(a){for(let b in a)a.hasOwnProperty(b)&&(this._options[b]=a[b])}clear(){this._queue=[];this._offset=0;this._current=null}_dispatch(){this._options&&this._options.handler&&"function"===typeof this._options.handler&&!this._current&&!this.isEmpty()&&(this._current=this.dequeue(),this._options.handler(this._current,this))}complete(a){this._options&&this._options.handler&&"function"===typeof this._options.handler&&
(this._current!==a&&console.error(this.videoLogFormatter("returned item out of order"),a),this._current=void 0,this.isEmpty()||setTimeout(()=>{this._dispatch()},0))}getLength(){return this._queue.length-this._offset}isEmpty(){return 0===this.getLength()}enqueue(a){this._queue.push(a);this._dispatch()}dequeue(){if(0!==this._queue.length){var a=this._queue[this._offset];2*++this._offset>=this._queue.length&&(this._queue=this._queue.slice(this._offset),this._offset=0);return a}}peek(){return 0<this._queue.length?
this._queue[this._offset]:void 0}peekTail(){return 0<this._queue.length?this._queue[this._queue.length-1]:void 0}[Symbol.iterator](){let a=this._offset;return{next:()=>this._queue.length<=a?{value:void 0,done:!0}:{value:this._queue[a++],done:!1}}}};
const GlanceVideoProfileManagerState={UNINITIALIZED:"uninitialized",READY:"READY"},GlanceVideoProfileManagerMode={STATIC:"static",DYNAMIC:"dynamic"},GlanceVideoProfileManagerDowngradeReason={OFFERER_NETWORK:"OFFERER_NETWORK",OFFERER_DEVICE:"OFFERER_DEVICE",ACCEPTOR_NETWORK:"ACCEPTOR_NETWORK",ACCEPTOR_DEVICE:"ACCEPTOR_DEVICE"},GlanceVideoProfileManagerProfileStorageKey="GLANCE.Video.GlanceVideoProfileManager.Profile";
GLANCE.Video.GlanceVideoProfileManager=class{constructor(a,b,c){this.options=a;this.listener=c;this.minimumFramerate=5;this.minimumWidth=120;this.minimumHeight=90;a=24;b&&GLANCE.Video.GlanceVideoSource.isIOS()&&(c=navigator.userAgent.toLowerCase().split(" os "),c[1]?(c=c[1].substring(0,c[1].indexOf(" ")),15>parseFloat(c)&&(a=12)):a=12);this.maximumFramerate=a;this.maximumWidth=this.options.width||640;this.maximumHeight=this.options.height||360;this.goalFramerate=this.options.framerate?parseInt(this.options.framerate):
20;this.framerate=this.options.framerate?parseInt(this.options.framerate):this.goalFramerate;this.stabilityLevel=1;this.qualityNetworkDowngradeFramerateInPercentage=this.qualityNetworkDowngradeResolutionInPercentage=20;this.qualityDeviceDowngradeFramerateInPercentage=this.qualityDeviceDowngradeResolutionInPercentage=25;this.qualityUpgradeFramerateInPercentage=this.qualityUpgradeResolutionInPercentage=15;this.maximumResolutionDownscaleInPercentage=200;this.offererNetworkFailureRetries=3;this.h264Constant=
.13;this.frameTimestamps=[];this.upgradesInaRowCount=0;this.state=GlanceVideoProfileManagerState.UNINITIALIZED;this.mode=GlanceVideoProfileManagerMode.DYNAMIC;this.options.screenshare&&(this.mode=GlanceVideoProfileManagerMode.STATIC);this.acceptors={};this.paramIndex=0;this.descriptor=null;this.downgradeCount=0;this.paused=!1;this.bgBlurEnabled=b;this.realFramerate=void 0;this.minDowngradeInterval=1E3;this.shouldDowngrade=this.shouldUpgrade=!1;this.downgradeReason=void 0;this.newMinimumHeight=!1;
this.offererNetworkFailureCount=this.successfulKeyframeIntervals=0;this.keyframeInterval=100;this.frameIndexWithinKeyframe=0;this.requiredStabilityIntervals=3;this.frameTimestampsToSample=0;this.height=this.width=null;this.reset()}getMode(){return this.mode}pause(){GLANCE.Video.VideoDebug&&console.log("Video profile manager paused");this.paused=!0;this.clearFrameTimestamps()}resume(){GLANCE.Video.VideoDebug&&console.log("Video profile manager resumed");this.paused=!1;this.clearFrameTimestamps()}setOptions(a){this.options=
a;this.options.width&&this.options.height&&(this.maximumWidth&&this.maximumHeight&&this.bgBlurEnabled||(this.maximumWidth=this.options.width,this.maximumHeight=this.options.height),(a=this.options.framerate)&&!this.bgBlurEnabled&&(a=parseInt(a),this.framerate||(this.framerate=a),this.goalFramerate||(this.goalFramerate=a),this.maximumFramerate=a,this.framerate>this.maximumFramerate&&(this.framerate=this.maximumFramerate),this.goalFramerate>this.maximumFramerate&&(this.goalFramerate=this.maximumFramerate)),
this.updateProfile(this.options.width,this.options.height,a))}setDescriptor(a){this.descriptor=a;this.paramIndex=0;this.notifyListener()}onClose(){this.mode==GlanceVideoProfileManagerMode.STATIC&&(this.paramIndex=0,this.descriptor=null);this.stabilityLevel=1;this.clearSavedSessionProfile()}addAcceptor(a,b,c,d,e,f){"undefined"==typeof f&&this.acceptors[a].devicePixelRatio&&(f=this.acceptors[a].devicePixelRatio);if(f&&(b*=f,c*=f,d&&e)){d*=f;e*=f;var g=c/b;let h=b/c;d<b&&(b=d,c=b*g);e<c&&(c=e,b=c*h)}b=
Math.floor(b);c=Math.floor(c);0!=b%2&&b--;0!=c%2&&c--;if(this.state==GlanceVideoProfileManagerState.UNINITIALIZED)this.width||this.height||(e=c,e>this.maximumHeight&&(e=this.maximumHeight),g=Math.floor(this.maximumWidth/this.maximumHeight*e),this.setWidth(g),this.setHeight(e)),this.acceptors[a]={width:b,height:c,devicePixelRatio:f},this.state=GlanceVideoProfileManagerState.READY;else if(d=this.getAcceptorMinimumResolution(),this.acceptors[a]={width:b,height:c,devicePixelRatio:f},a=this.getAcceptorMinimumResolution(),
b=this.getAcceptorMaximumResolution(),b=b.height>this.maximumHeight?this.maximumHeight:b.height,e=a.height,e>b&&(e=b),g=Math.floor(this.maximumWidth/this.maximumHeight*e),!this.width||!this.height||a&&d&&10<Math.abs(d.height-a.height))return GLANCE.Video.VideoDebug&&console.log("Update Profile on Add Acceptor "+g+", "+e+"                       "+d.height+", "+a.height),this.reset(),a&&d&&a.height>d.height&&(this.newMinimumHeight=!0),this.updateProfile(g,e),!0;return!1}removeAcceptor(a){if(this.acceptors[a])if(delete this.acceptors[a],
a=this.getAcceptorMinimumResolution()){if(a.width<this.width||a.height<this.height)return this.updateProfile(a.width,a.height),!0}else this.reset(),this.height=this.width=void 0,this.downgradeCount=0,this.framerate=this.goalFramerate,this.notifyListener();return!1}staticMode(){this.mode=GlanceVideoProfileManagerMode.STATIC;this.notifyListener()}notifyListener(){if(this.listener)this.listener.onProfileChanged(this.getProfile())}notifyListenerRealFramerate(){if(this.listener&&this.realFramerate)this.listener.onProfileRealFramerate(this.realFramerate)}updateProfile(a,
b,c){if(!this.width&&!this.height&&(this.fetchSavedSessionProfile(),this.width&&this.height)){this.clearFrameTimestamps();this.notifyListener();return}const d=this.width,e=this.height,f=this.framerate;a&&this.setWidth(a);b&&this.setHeight(b);c&&this.setFramerate(c);if(this.width!=d||this.height!=e||this.framerate!=f)this.clearFrameTimestamps(),this.notifyListener(),this.height>e||this.framerate>f?GLANCE.Video.VideoDebug&&console.log("Upgrade : "+this.width+", "+this.height+", "+this.framerate):GLANCE.Video.VideoDebug&&
console.log("Downgrade : "+this.width+", "+this.height+", "+this.framerate);this.mode==GlanceVideoProfileManagerMode.DYNAMIC&&this.saveSessionProfile()}saveSessionProfile(){let a;try{a=window.sessionStorage}catch(c){a=null}if(a)try{var b=this.getProfile();b&&(b.stabilityLevel=this.stabilityLevel,a.setItem(GlanceVideoProfileManagerProfileStorageKey,JSON.stringify(b)))}catch(c){}}fetchSavedSessionProfile(){if(this.mode==GlanceVideoProfileManagerMode.DYNAMIC&&window.sessionStorage)try{const a=window.sessionStorage.getItem(GlanceVideoProfileManagerProfileStorageKey);
if(a){const b=JSON.parse(a);b.width&&b.height&&b.framerate&&(GLANCE.Video.VideoDebug&&console.log("Video profile manager: Fetched saved profile from session storage: "+a),this.width=b.width,this.height=b.height,this.framerate=b.framerate,this.stabilityLevel=b.stabilityLevel)}}catch(a){}}clearSavedSessionProfile(){window.sessionStorage&&window.sessionStorage.removeItem(GlanceVideoProfileManagerProfileStorageKey)}clearFrameTimestamps(){this.frameTimestamps.splice(0,this.frameTimestamps.length)}setWidth(a){a=
Math.floor(a);0!=a%2&&a--;a<this.minimumWidth?a=this.minimumWidth:a>this.maximumWidth&&(a=this.maximumWidth);this.width=a}setHeight(a){a=Math.floor(a);0!=a%2&&a--;a<this.minimumHeight?a=this.minimumHeight:a>this.maximumHeight&&(a=this.maximumHeight);this.height=a}setFramerate(a){this.framerate!=a&&(this.realFramerate=void 0);a<this.minimumFramerate?a=this.minimumFramerate:a>this.maximumFramerate&&(a=this.maximumFramerate);this.framerate=a}hasAcceptors(){for(var a in this.acceptors)return!0;return!1}getAcceptorMinimumResolution(){var a=
void 0,b=void 0,c;for(c in this.acceptors){var d=this.acceptors[c];let e=d.width;a=a?Math.min(a,e):e;d=d.height;b=b?Math.min(b,d):d}if(a&&b)return a=Math.floor(a),b=Math.floor(b),0!=a%2&&a++,0!=b%2&&b++,{width:a,height:b}}getAcceptorMaximumResolution(){var a=void 0,b=void 0,c;for(c in this.acceptors){var d=this.acceptors[c];let e=d.width;a=a?Math.max(a,e):e;d=d.height;b=b?Math.max(b,d):d}if(a&&b)return a=Math.floor(a),b=Math.floor(b),0!=a%2&&a++,0!=b%2&&b++,{width:a,height:b}}reset(){this.frameIndexWithinKeyframe=
this.successfulKeyframeIntervals=this.offererNetworkFailureCount=0;this.shouldDowngrade=this.shouldUpgrade=!1;this.downgradeReason=void 0;this.clearFrameTimestamps()}upgrade(){this.shouldDowngrade||(this.shouldUpgrade=!0)}log(a){GLANCE.Video.VideoDebug&&console.log(a);if(this.listener)this.listener.onProfileLog(a)}performUpgrade(){this.reset();this.mode==GlanceVideoProfileManagerMode.STATIC?this.performStaticUpgrade():this.mode==GlanceVideoProfileManagerMode.DYNAMIC&&this.performDynamicUpgrade();
1<this.stabilityLevel&&(this.stabilityLevel--,this.setRequiredStabilityIntervals(),GLANCE.Video.VideoDebug&&console.log("Video profile manager: Stability is now "+this.requiredStabilityInSeconds+" seconds ("+this.requiredStabilityIntervals+" successful keyframe intervals)."))}performStaticUpgrade(){let a=this.getCoderparamsDelta(this.descriptor,this.paramIndex,1);a!==this.paramIndex&&(this.paramIndex=a,this.notifyListener())}performDynamicUpgrade(){if(this.framerate&&this.width&&this.height){var a=
this.framerate,b=this.width,c=this.height;if(this.newMinimumHeight||b<this.maximumWidth)if(0<this.downgradeCount){var d=this.getAcceptorMinimumResolution();this.height<d.height&&(c=this.newMinimumHeight?d.height:Math.floor(this.height*(1+this.qualityUpgradeResolutionInPercentage/100)),c>d.height&&(c=d.height),b=this.getAcceptorMaximumResolution(),d=this.maximumHeight,b&&b.height<d&&(d=b.height),c>=d&&(a=Math.floor(a*(1+this.qualityUpgradeFramerateInPercentage/100)),c=d),b=Math.floor(this.maximumWidth/
this.maximumHeight*c))}else b=this.getAcceptorMinimumResolution(),c=c<b.height?b.height:Math.floor(c*(1+this.qualityUpgradeResolutionInPercentage/100)),b=this.getAcceptorMaximumResolution(),d=this.maximumHeight,b&&b.height<d&&(d=b.height),c>=d&&(a=Math.floor(a*(1+this.qualityUpgradeFramerateInPercentage/100)),c=d),b=Math.floor(this.maximumWidth/this.maximumHeight*c);else a=Math.ceil(a*(1+this.qualityUpgradeFramerateInPercentage/100)),a>this.goalFramerate&&(a=this.goalFramerate);a>this.maximumFramerate&&
(a=this.maximumFramerate);this.newMinimumHeight=!1;this.updateProfile(b,c,a)}}downgrade(a){this.shouldDowngrade=!0;this.shouldUpgrade=!1;this.downgradeReason=a;this.newMinimumHeight=!1;this.upgradesInaRowCount=this.successfulKeyframeIntervals=0}performDowngrade(){this.lastDowngradeTime=Date.now();const a=this.downgradeReason;this.downgradeCount++;this.reset();this.mode==GlanceVideoProfileManagerMode.STATIC?this.performStaticDowngrade(a):this.mode==GlanceVideoProfileManagerMode.DYNAMIC&&this.performDynamicDowngrade(a);
2>this.stabilityLevel&&(this.stabilityLevel++,this.setRequiredStabilityIntervals(),GLANCE.Video.VideoDebug&&console.log("Video profile manager: Stability is now "+this.requiredStabilityInSeconds+" seconds ("+this.requiredStabilityIntervals+" successful keyframe intervals)."))}performStaticDowngrade(a){a=this.getCoderparamsDelta(this.descriptor,this.paramIndex,-1);a!==this.paramIndex&&(this.paramIndex=a,this.notifyListener())}performDynamicDowngrade(a){if(this.framerate&&this.width&&this.height){var b=
this.framerate;if(this.framerate>this.goalFramerate)b=this.goalFramerate;else{var c=this.height;this.getAcceptorMinimumResolution();var d=a==GlanceVideoProfileManagerDowngradeReason.OFFERER_DEVICE||a==GlanceVideoProfileManagerDowngradeReason.ACCEPTOR_DEVICE?this.qualityDeviceDowngradeResolutionInPercentage:this.qualityNetworkDowngradeResolutionInPercentage;const e=a==GlanceVideoProfileManagerDowngradeReason.OFFERER_DEVICE||a==GlanceVideoProfileManagerDowngradeReason.ACCEPTOR_DEVICE?this.qualityDeviceDowngradeFramerateInPercentage:
this.qualityNetworkDowngradeFramerateInPercentage;"framerate"==this.getDowngradeAspect(a)?b=Math.floor(b*(1-e/100)):(c=Math.floor(this.height*(1-d/100)),c<this.minimumHeight&&(c=this.minimumHeight));d=Math.floor(this.maximumWidth/this.maximumHeight*c);b<this.minimumFramerate&&(b=this.minimumFramerate)}this.updateProfile(d,c,b)}}getDowngradeAspect(a){let b=100*this.height/this.maximumHeight,c=100*this.framerate/this.maximumFramerate,d=2;if(a&&a==GlanceVideoProfileManagerDowngradeReason.OFFERER_NETWORK||
a==GlanceVideoProfileManagerDowngradeReason.ACCEPTOR_NETWORK)d=.5;return b>c*d?"resolution":"framerate"}getProfile(){if(this.mode==GlanceVideoProfileManagerMode.STATIC)return this.getStaticProfile();if(this.mode==GlanceVideoProfileManagerMode.DYNAMIC)return this.getDynamicProfile()}getStaticProfile(){const a=this.getCoderparamSet(this.descriptor,this.paramIndex);if(a&&this.options&&this.options.width&&this.options.height){const d=a.framerate||5;var b=a.downsample||1,c=this.options.width/b;b=this.options.height/
b;0!=c%2&&c++;0!=b%2&&b++;return{framerate:d,width:c,height:b,bitsPerSecond:a.bitrate,paramIndex:this.paramIndex,pframes:a.pframes}}if(this.options.width&&this.options.height&&this.options.bitspersecond)return{framerate:this.options.framerate,width:this.options.width,height:this.options.height,bitsPerSecond:this.options.bitspersecond}}getDynamicProfile(){if(!this.hasAcceptors())return{framerate:this.maximumFramerate,width:this.maximumWidth,height:this.maximumHeight,bitsPerSecond:Math.floor(this.maximumFramerate*
this.maximumWidth*this.maximumHeight*this.h264Constant)};if(this.framerate&&this.width&&this.height)return{framerate:this.framerate,width:this.width,height:this.height,bitsPerSecond:Math.floor(this.framerate*this.width*this.height*this.h264Constant)}}getRealFramerate(){return this.realFramerate}isMobileBlurring(){return(GLANCE.browserCapabilities.isAndroid||GLANCE.browserCapabilities.isSafariIOS)&&this.bgBlurEnabled}frame(a,b){if(this.paused)return!1;this.keyframeInterval=b;this.frameTimestampsToSample||
(this.frameTimestampsToSample=b);var c=window.performance?window.performance.now():(new Date).getTime();1==a&&this.reset();this.frameTimestamps.push(c);this.frameTimestamps.length>this.frameTimestampsToSample&&this.frameTimestamps.shift();if(this.frameTimestamps.length>=this.frameTimestampsToSample){c=(this.frameTimestamps[this.frameTimestamps.length-1]-this.frameTimestamps[0])/(this.frameTimestamps.length-1);var d=!this.realFramerate,e=this.realFramerate;this.realFramerate=1E3/c;(d||a>this.frameTimestampsToSample&&
0==a%this.frameTimestampsToSample&&e&&.01<Math.abs(1-e/this.realFramerate))&&this.notifyListenerRealFramerate();if(this.bgBlurEnabled&&(d=this.framerate,this.mode==GlanceVideoProfileManagerMode.STATIC&&(e=this.getProfile())&&(d=e.framerate),c>1E3/d*1.1))return this.clearFrameTimestamps(),this.offererEncodingFailure(),this.performDowngrade(),!0}if(0==a%b){this.frameIndexWithinKeyframe=1;this.successfulKeyframeIntervals++;this.setRequiredStabilityIntervals();0<this.successfulKeyframeIntervals&&0==this.successfulKeyframeIntervals%
this.requiredStabilityIntervals&&(this.upgradesInaRowCount++,3<this.upgradesInaRowCount?(this.upgradesInaRowCount=0,this.resetToMax()):this.upgrade());if(this.shouldUpgrade)return this.performUpgrade(),!0;if(this.shouldDowngrade)return this.performDowngrade(),!0}else this.frameIndexWithinKeyframe++;return!1}resetToMax(){let a=this.getAcceptorMaximumResolution();a?this.updateProfile(a.width,a.height,this.maximumFramerate):this.updateProfile(this.maximumWidth,this.maximumHeight,this.maximumFramerate)}setRequiredStabilityIntervals(){if(this.keyframeInterval){let a=
this.keyframeInterval/this.framerate;this.requiredStabilityInSeconds=10*Math.pow(2,this.stabilityLevel-1);this.requiredStabilityIntervals=Math.ceil(this.requiredStabilityInSeconds/a)}else this.requiredStabilityIntervals=Math.pow(2,this.stabilityLevel)}offererNetworkFailure(){GLANCE.Video.VideoDebug&&console.log("Video profile manager: Couldn't offer stream because of network issues");this.offererNetworkFailureCount++;this.downgrade(GlanceVideoProfileManagerDowngradeReason.OFFERER_NETWORK)}offererEncodingFailure(){this.options.screenshare||
(GLANCE.Video.VideoDebug&&console.log("Video profile manager: Couldn't offer stream because frames could not be encoded at framerate"),this.downgrade(GlanceVideoProfileManagerDowngradeReason.OFFERER_DEVICE))}acceptorNetworkFailure(a){this.options.screenshare||(GLANCE.Video.VideoDebug&&console.log("Video profile manager: Acceptor player "+a+" couldn't render stream because of their network"),this.downgrade(GlanceVideoProfileManagerDowngradeReason.ACCEPTOR_NETWORK))}acceptorRenderFailure(a){GLANCE.Video.VideoDebug&&
console.log("Video profile manager: Acceptor player "+a+" couldn't render stream because of their device");this.downgrade(GlanceVideoProfileManagerDowngradeReason.ACCEPTOR_DEVICE)}legacySlower(){this.options.screenshare||(GLANCE.Video.VideoDebug&&console.log("Video profile manager: Slower requested without stated reason by vserver or acceptor."),this.downgrade(GlanceVideoProfileManagerDowngradeReason.ACCEPTOR_NETWORK))}getCoderparamsDelta(a,b,c){var d=b;if(a&&a.coderparams){d=a.coderparams;let e=
(b||0)+(c||0),f=!1;for(const g in d)if(d.hasOwnProperty(g)&&e===Number(g)){f=!0;break}if(!f&&1<Math.abs(c))return 1<c?--c:++c,this.getCoderparamsDelta(a,b,c);d=f?e:b}return d}getCoderparamSet(a,b){let c={};a&&a.coderparams&&(c=a.coderparams[(0<b?"+":"")+b.toString()]);return c}};
GLANCE.Video.dynamicallyLoadScript=function(a){return new Promise(function(b,c){let d=document.getElementsByTagName("head")[0],e=document.createElement("script");e.src=a;e.type="text/javascript";e.onload=b;e.onerror=()=>c(Error(`Error when loading ${a}!`));d.appendChild(e)})};GLANCE.Video.VideoSource=function(a){return new GLANCE.Video.GlanceVideoSource(a)};GLANCE.AgentVideo=function(a){return new GLANCE.Video.GlanceVideoSource(a)};/*
 Copyright (c) 2023 Glance Networks, Inc.
*/
GLANCE=GLANCE||{};GLANCE.Lib=GLANCE.Lib||{};GLANCE.Lib.CleanContext=GLANCE.Lib.CleanContext||{};GLANCE.Lib.CleanContext.nativeClass=function(a){let b=document.getElementById("glance-clean-context");b||(b=document.createElement("iframe"),b.id="glance-clean-context",b.class="glance_hide",b.setAttribute("data-no-cobrowse-content",1),document.body.appendChild(b));return b.contentWindow[a]};}).call(window);
//# sourceMappingURL=map.js.map
