(function() {window.GLANCE||(window.GLANCE={});GLANCE.VideoDebug=!1;GLANCE.Workaround_14731=60;GLANCE.ProbeTime=0;GLANCE.historyTime=3E4;GLANCE.historyLookback=3E3;GLANCE.ElementPlayTimeout=2E3;
GLANCE.AgentVideo=function AgentVideo(k){function r(b){4<b&&(b=4);return 1E3*(2**b+5*Math.random())}async function t(b){return new Promise(function(c,d){function e(h,l="sessionEnded"){a.isClosing||(f.reportHistoryInterval&&clearInterval(f.reportHistoryInterval),f.reportHistoryInterval=null,a._history.clear(),a._closeVideoStream({}).then(()=>{a.fireEvent(l,a.options,h);a.ws&&a.ws.intervalPing&&(clearTimeout(a.ws.intervalPing),a.ws.intervalPing=null);a.ws=null}),a.isClosing=!0)}var f=new WebSocket(b);
a.ws=f;f.binaryType="blob";0<GLANCE.ProbeTime&&(f.intervalPing=setInterval(()=>{f&&f.transmitter&&"function"===typeof f.transmitter&&f.transmitter("Ping "+JSON.stringify({time:Date.now(),octetcount:relay.octetcount||0,packetcount:relay.packetcount||0}))},GLANCE.ProbeTime));0<GLANCE.historyLookback&&0<GLANCE.historyTime&&a._history&&(f.reportHistoryInterval=setInterval(function(){const h=a._reportHistory(a);h&&console.log(h)},GLANCE.historyTime));f.onopen=function(){delete a.awaitingReconnect;c()};
f.onclose=function(h){GLANCE.VideoDebug&&console.debug("Websocket close",h);GLANCE.VideoDebug&&console.log("websocket CLOSE - clean flag is "+h.wasClean);if(h.wasClean)e(h,"sessionEnded");else try{a.giveUpReconnect?e(h,"error"):a._reconnectWebSocket()}catch(l){e(error,"error")}};f.onerror=function(h){console.error("websocket error",h);h.statusMessage||(h.statusMessage="websocket error");d(h)};let g;WebSocket.prototype.transmitter=function(h){const l=Date.now();g=g||l;let n;const p=h.data||null;p&&
p instanceof Blob&&0!==p.size?(l>g&&(g=l),a.relay.octetcount+=p.size,a.relay.packetcount+=1,n=a.transmitStarted&&0<a.guestCount?p:null,GLANCE.VideoDebug&&console.log("send payload size: ",p.size,n?"sent":"skipped, no guests"),a._history.enqueue({timestamp:l,size:p.size})):"string"===typeof h&&0<h.length&&(n=h,GLANCE.VideoDebug&&console.log("send command: ",n));a.ws&&f&&1===f.readyState&&n?f.send(n):a.ws&&f&&1!==f.readyState&&n&&GLANCE.VideoDebug&&console.log("Websocket not ready, cannot send payload")};
f.onmessage=function(h){GLANCE.VideoDebug&&console.debug("receiving",h.data);a._commandQueue.enqueue(h)}})}function y(b,c=256E3){b=b.match(/^(\d+)([KMGkmg]?[A-Za-z]*)$/);return 3>b.length?c||128E3:"kbps"===b[2]?1E3*b[1]:"mbps"===b[2]?1E6*b[1]:"gbps"===b[2]?1E9*b[1]:"K"===b[2]?8192*b[1]:"M"===b[2]?8388608*b[1]:"G"===b[2]?8589934592*b[1]:c||128E3}const a=this,u=['video/webm; codecs="avc1.42E01E"',"image/jpeg"],q={width:176,height:144,framerate:15,sessionkey:"",bandwidth:"250kbps",vserver:"https://"+
window.location.host+"/",mime:null,modelID:"browser",deviceName:null,maincallid:null,maincid:null,groupid:null,partnerid:null,username:null,isAnonymous:null,password:null,videoBackEnabled:!1};a.options=k||q;for(let b in q)q.hasOwnProperty(b)&&(a.options.hasOwnProperty(b)||(a.options[b]=q[b]));a.options.bitspersecond||(a.options.bitspersecond=y(a.options.bandwidth));a.options.requestedbitspersecond=a.options.bitspersecond;a.mime=null;a.source=null;a.sources=null;a.systemDefaultSource=null;a.preview=
null;a.isClosing=!1;a.guestCount=0;a.transmitStarted=!1;a._commandQueue=new GLANCE.Queue;a._history=new GLANCE.Queue;const v="username password partnerid groupid partneruserid loginkey isAnonymous".split(" ");AgentVideo.prototype.getOptions=function(){return a.options};AgentVideo.prototype.setOptions=function(b){for(let c in b)q.hasOwnProperty(c)&&b[c]&&(a.options[c]=b[c])};AgentVideo.prototype.getSources=function(b){if(!GLANCE.isBrowserCapable())return b(null);a._getSystemDefaultSource().then(c=>
{c?a._enumerateSources().then(d=>{c&&d.forEach(e=>{e.isDefault=e.deviceId===c.deviceId});b(d)}):b(null)}).catch(c=>{console.error(c);b(null)})};AgentVideo.prototype.getSourcesAsync=function(){return new Promise((b,c)=>{try{a.getSources(d=>{b(d)})}catch(d){c(d)}})};AgentVideo.prototype.initialize=function(b,c){if(!c)throw Error("preview element required when initializing");a.preview=c;return new Promise((d,e)=>{if(navigator&&navigator.mediaDevices&&"function"===typeof navigator.mediaDevices.getUserMedia)if(window.MediaRecorder&&
"function"===typeof window.MediaRecorder&&"function"===typeof window.MediaRecorder.isTypeSupported){var f;MediaRecorder.isTypeSupported("image/jpeg")?f="image/jpeg":u.forEach(g=>{MediaRecorder.isTypeSupported(g)&&(f=g)});f&&"string"===typeof f||(console.log("Mediarecorder.isTypeSupported did not accept",u," we use",u[0]),f=u[0]);q.mime=f;a.mime=f;a._getSource({source:b}).then(a._setSource).then(a._getConstraints).then(a._getMediaStream).then(a._getMediaRecorder).then(a._startVideoStream).then(a._startVideoPreview).then(a._saveParams).then(g=>
{a.addEventListener("sourceStarted",a._sendTorchEvent);a.fireEvent("initialized",a.options);a.fireEvent("sourceStarted",a.source,a.options);d(g)}).catch(g=>{g=g.message||"initialize failure";a.fireEvent("error",g,a.options);e(g)})}else console.error("MediaRecorder is not supported by your browser."),a.fireEvent("error","MediaRecorder is not supported by your browser.",a.options),e("MediaRecorder not supported by your browser.");else console.error("getUserMedia not supported by your browser."),a.fireEvent("error",
"getUserMedia not supported by your browser.",a.options),e("getUserMedia not supported by your browser.")})};AgentVideo.prototype.setSource=async function(b){if(b){var c="object"===typeof b&&b.deviceId&&"string"===typeof b.deviceId?b.deviceId:b;if("string"===typeof c&&(b=(await a._enumerateSources()).find(e=>e.name===c||e.label===c?!0:e.deviceId===c),!a.source||a.source.deviceId!==b.deviceId)){var d=a._setSource({source:b});await a._restartVideoStream(d);GLANCE.VideoDebug&&console.log("setSource",
b);a.fireEvent("sourceStarted",b,a.options)}}};AgentVideo.prototype.isTorchAvailable=function(){try{if(a&&a.stream){const b=a.stream.getVideoTracks()[0];if(b&&"function"===typeof b.getCapabilities)return!!b.getCapabilities().torch}return!1}catch(b){return!1}};AgentVideo.prototype._sendTorchEvent=function(){a.fireEvent("torch",!1);setTimeout(function(){a.isTorchAvailable()&&a.fireEvent("torch",!0)},500)};AgentVideo.prototype.setTorch=function(b){if(a&&a.stream){const c=a.stream.getVideoTracks()[0];
c&&"function"===typeof c.getCapabilities&&c.getCapabilities().torch&&c.applyConstraints({torch:b,advanced:[{torch:b}]}).then(()=>{a._torchState=b;GLANCE.VideoDebug&&console.log("setTorch",b?"on":"off")}).catch(d=>{console.log("setTorch",b?"on":"off","error",d)})}};AgentVideo.prototype.getTorch=function(){return!!a._torchState};AgentVideo.prototype.startSession=function(){const b=a._makeOfferQueryString(a.options);a._requestOffer(a.options.vserver,b).then(a._openWebSocket).then(()=>{a.fireEvent("sessionStarted",
a.relay)}).then(()=>{a._commandQueue.enqueue({name:"restartVideoStream",method:a._restartVideoStream,params:{sessionStarting:!0}})}).catch(c=>{console.error("startSession",c);a.fireEvent("error",c,a.options)})};AgentVideo.prototype.endSession=function(){a._closeVideoStream({}).then(function(b){a.isClosing||a.fireEvent("sessionEnded",a.options);a.ws&&!a.isClosing&&(a.isClosing=!0,a.ws.transmitter("Stopping"),a.ws.transmitter("Closing"),a.ws.close(1E3,"endSession"))})};AgentVideo.prototype.reconnectSession=
function(){a.reconnectWebSocket()};GLANCE.Send=function(b){if(b&&"string"===typeof b&&0<b.length&&a&&a.ws&&a.ws.transmitter&&"function"==typeof a.ws.transmitter)return a.ws.transmitter(b),b};AgentVideo.prototype._restartVideoStream=async function(b){GLANCE.VideoDebug&&console.log("enter restartVideoStream",b);b||(b={});a.pendingRestartTimeout&&(window.clearTimeout(a.pendingRestartTimeout),a.pendingRestartTimeout=0);try{b=await a._stopVideoStream(b),GLANCE.VideoDebug&&console.log("stopVideoStream done",
b),b=await a._getConstraints(b),GLANCE.VideoDebug&&console.log("getConstraints done",b),b=await a._getMediaStream(b),GLANCE.VideoDebug&&console.log("getMediaStream done",b),b=await a._getMediaRecorder(b),GLANCE.VideoDebug&&console.log("getMediaRecorder done",b),b=await a._startVideoStream(b),GLANCE.VideoDebug&&console.log("startVideoStream done",b),b=await a._startVideoPreview(b),GLANCE.VideoDebug&&console.log("startVideoPreviews done",b),b=await a._saveParams(b),GLANCE.VideoDebug&&console.log("saveParams done",
b)}catch(c){console.error("error in restartVideoStream",c,b),a.fireEvent("error",c,a.options)}GLANCE.VideoDebug&&console.log("leave restartVideoStream",b);return b};AgentVideo.prototype._closeVideoStream=function(b){return new Promise(c=>{a.transmitStarted=!1;a.guestCount=0;a.paramset=null;a.paramIndex=0;a._stopVideoStream(b).then(d=>{a.descriptor=null;a.paramIndex=0;a.paramset=null;d.indexDelta=0;return d}).then(a._getConstraints).then(a._getMediaStream).then(a._getMediaRecorder).then(a._startVideoStream).then(a._startVideoPreview).then(a._saveParams).then(d=>
c(d))})};AgentVideo.prototype._getAgentVideoStatus=function(b){b=b.ownerDocument.defaultView;b.agentVideoStatus||(b.agentVideoStatus={sender:this,activePreviews:new Set,requestedPreviews:new Set});b.addEventListener("unload",a._onPreviewDocumentUnload);return b.agentVideoStatus};AgentVideo.prototype._onPreviewDocumentUnload=function(b){b=b.currentTarget;if(b.agentVideoStatus&&b.agentVideoStatus.sender){const c=b.agentVideoStatus.sender;b.agentVideoStatus.requestedPreviews.forEach(e=>{a.requestedPreviews.delete(e)});
b.agentVideoStatus.requestedPreviews.clear();let d=0;b.agentVideoStatus.activePreviews.forEach(e=>{c.stopPreview(e);d++});GLANCE.VideoDebug&&0<d&&console.log("document unload: stopped previews")}b.agentVideoStatus.activePreviews.clear();b.agentVideoStatus=void 0;b.removeEventListener("unload",this._onPreviewDocumentUnload)};AgentVideo.prototype._getSource=async function(b){try{const c=b.source;if(c&&"object"===typeof c&&c.deviceId)return b;if("string"===typeof c){const d=await a._enumerateSources();
b.source=d.find(e=>e.name===c||e.label===c?!0:e.deviceId===c);return b}a.systemDefaultSource||(a.systemDefaultSource=await a._getSystemDefaultSource());b.source=a.systemDefaultSource;return b}catch(c){throw b.source=null,a.systemDefaultSource=null,b.message=c.message,c;}};AgentVideo.prototype._getSystemDefaultSource=async function(){let b;if(a.systemDefaultSource&&a.systemDefaultSource.deviceId&&"string"===typeof a.systemDefaultSource.deviceId)GLANCE.VideoDebug&&console.info("default video source",
a.systemDefaultSource.label,"refetched"),b=a.systemDefaultSource;else try{delete a.systemDefaultSource;const c=await a._enumerateSources();b=1<=c.length?c[0]:null;a.systemDefaultSource=b;if(!b)throw Error("No camera");}catch(c){throw console.error("_getSystemDefaultSource",c),delete a.systemDefaultSource,c;}return a.systemDefaultSource=b};AgentVideo.prototype._setSource=function(b){let c=b.source;a.source=c;a.options.device=c&&c.name||c&&c.label||a.options.deviceName||"";return b};AgentVideo.prototype._enumerateSources=
async function(){if(a.sources)return a.sources;if(navigator&&navigator.mediaDevices&&"function"===typeof navigator.mediaDevices.enumerateDevices){const b=await navigator.mediaDevices.getUserMedia({video:!0,audio:!1});let c=0;const d=(await navigator.mediaDevices.enumerateDevices()).filter(e=>"videoinput"===e.kind?(e.label&&0<e.label.length?0<=e.label.toLowerCase().indexOf("back")?(e.ordinal=-2,e.name="back"):0<=e.label.toLowerCase().indexOf("front")?(e.ordinal=-1,e.name="front"):(e.name=e.label.replace(/\s*\([0-9a-fA-f:]{9,}\)\s*$/,
""),e.ordinal=c++):(e.ordinal=c,e.name="cam"+c,c++),!0):!1);0<d.length?(d.sort((e,f)=>e.ordinal-f.ordinal),a.sources=d):delete a.sources;a._releaseUserMediaStream(b);return d}throw"navigator.mediaDevices.enumerateDevices() function not available";};AgentVideo.prototype._getConstraints=async function(b){b||(b={});var c=await a._getSystemDefaultSource();if(c&&"object"===typeof c&&c.deviceId)a.systemDefaultSource=c;else return b.message=c,b;b.source=b.source||a.source||a.systemDefaultSource;var d=b.indexDelta||
0;c=a.options.framerate;let e=a.options.width,f=a.options.height;var g=a.options.bitspersecond;a.descriptor&&(a.paramIndex=a._getCoderparamsDelta(a.descriptor,a.paramIndex,d),a.paramset=a._getCoderparamSet(a.descriptor,a.paramIndex));a.paramset&&(g=a.paramset,c=g.framerate||1,d=g.downsample||1,e/=d,f/=d,g=g.bitrate,b.qualityParameter=a.paramset.pframes/c||90);c={video:{width:{min:160,ideal:e,max:1280},height:{min:120,ideal:f,max:720},frameRate:c},audio:!1};c.bitspersecond=g;b.constraints=c;return b};
AgentVideo.prototype._getMediaStream=function(b){return new Promise((c,d)=>{let e=b.stream||a.stream;if(e){if(e.deviceId&&e.deviceId===b.source.deviceId)return b.stream=e,c(b);a.stream=null;b.stream=null}e&&e.closeBeforeReplacing&&(a._releaseUserMediaStream(e),e=null);a._getUserMediaStream(b.constraints,b.source).then(f=>{a._torchState=!1;e&&a._releaseUserMediaStream(e);b.stream=f;c(b)}).catch(f=>{console.error("_getMediaStream",f);d(f)})})};AgentVideo.prototype._getUserMediaStream=async function(b,
c){let d;var e=c?c.name||c.label||"default":"unknown";c&&c.deviceId&&(b.deviceId={exact:c.deviceId},b.video.deviceId={exact:c.deviceId},GLANCE.VideoDebug&&console.info(" chosen video source",e,"constraints",b));let f;try{return d=await navigator.mediaDevices.getUserMedia(b),f=a._getStreamConstraints(d),d.deviceId=f.settings.deviceId,d.closeBeforeReplacing=!0,GLANCE.VideoDebug&&console.info(" chosen video source",f.track.label,!0===b.video?"probed":"opened"),d}catch(g){throw c=g.message?g.message:
" Cannot start video source ",g.constraint&&(c+=" ("+g.constraint+")"),e=(g.name?g.name+":":"")+c+" Camera:"+e+(!0===b.video?" (probing)":""),console.error(e,g,b),Error(e);}};AgentVideo.prototype._releaseUserMediaStream=function(b){try{if(b){const c=b.getTracks();if(c)for(b=0;b<c.length;b++)c[b].stop()}}catch(c){console.error("releaseUserMediaStream",c)}};AgentVideo.prototype._getMediaRecorder=function(b){var c=b.constraints;const d=b.stream;let e=c.bitspersecond;a.mime.startsWith("video/webm")&&
0<GLANCE.Workaround_14731&&(e=e*(480>Math.min(c.video.height.ideal,c.video.width.ideal)?GLANCE.Workaround_14731:.5*GLANCE.Workaround_14731)/(a.paramset&&a.paramset.framerate?a.paramset.framerate:1));c={mimeType:a.mime};c.videoBitsPerSecond=e;c.bitsPerSecond=e;c.audioBitsPerSecond=0;a.mediaRecorder&&console.error("about to create a new MediaRecorder when one already exists");c.qualityParameter="number"===typeof b.qualityParameter?.01*b.qualityParameter:.75;a.mediaRecorder=new MediaRecorder(d,c);b.streamConstraints=
a._getStreamConstraints(d);a.options.sourceDevice=b.streamConstraints.track.label;return b};AgentVideo.prototype._startVideoStream=function(b){const c=b.stream,d=a.mediaRecorder;let e=null;a.ws&&a.ws.transmitter&&"function"===typeof a.ws.transmitter&&a.transmitStarted&&0<a.guestCount&&(e=a.ws.transmitter);if(e&&"function"===typeof e){const f=a._makeInfoQueryString(a);e(`Info set ${f}`);e(`Starting ${a.mime}`);e("Info user-agent "+window.navigator.userAgent)}a.preview||e?(GLANCE.VideoDebug&&console.debug(e?
"start preview and transmit stream":"start preview only stream"),d.ondataavailable=e,d.start(10)):GLANCE.VideoDebug&&console.debug("no transmitter, no preview, do not start capture stream");b.streamConstraints=a._getStreamConstraints(c);return b};AgentVideo.prototype._saveParams=function(b,c){c=c||a;c.stream=b.stream;c.videoElement=b.videoElement;c.streamConstraints=b.streamConstraints;c.source=b.source};AgentVideo.prototype._loadParams=function(b,c){b={stream:b.stream,streamConstraints:b.streamConstraints,
source:b.source};if(c)for(const d in c)c.hasOwnProperty(d)&&(b[d]=c[d]);return b};AgentVideo.prototype._startVideoPreview=async function(b){try{await a._startVideoElementPreview({stream:b.stream,videoElement:a.preview})}catch(c){console.error("error starting element preview",c)}return b};AgentVideo.prototype._startVideoElementPreview=function(b){const c=b.stream,d=b.videoElement;return new Promise((e,f)=>{let g;const h=l=>{GLANCE.VideoDebug&&console.log("playRequestComplete entered",!!d.isPlayRequestInProgress,
l||"event",d,d.readyState,c.active);d.removeEventListener("play",h);g&&clearTimeout(g);g=null;d.isPlayRequestInProgress&&(GLANCE.VideoDebug&&console.log("playRequestComplete activity",l||"event",d,d.readyState,c.active),delete d.isPlayRequestInProgress,d.previewActive=!0,c.mostRecentlyActivatedPreview=d,GLANCE.VideoDebug&&console.log("started preview on",d,d.readyState,c.active),a.fireEvent("previewStarted",d,a.options),e())};if(d)if(d&&"VIDEO"!==d.tagName.toUpperCase())f("not a video element");else if(d&&
c!==d.srcObject)if(d.isPlayRequestInProgress)GLANCE.VideoDebug&&console.log("play request already in progress",d.readyState,c.active),a.fireEvent("previewStarted",d,a.options),e();else{d.setAttribute("autoplay",!0);d.setAttribute("playsinline",!0);d.setAttribute("muted",!0);d.srcObject=c;d.isPlayRequestInProgress=!0;d.addEventListener("play",h);GLANCE.VideoDebug&&console.log("about to call element.play on ",d,d.readyState,c.active);const l=d.play();g=setTimeout(h,50,"timeout");l&&"function"===typeof l.then?
l.then(()=>{h("promise resolution")}).catch(n=>{console.log("preview play failed, resolving anyway",n,d.readyState,c.active);h(n)}):(console.error("preview play failed: play function returned no Promise."),f("preview play failed: play function returned no Promise."))}else d&&c===d.srcObject?e():f("no video element to play");else f("no video element provided")})};AgentVideo.prototype._stopVideoStream=function(b){let c=!1;b||(b={});return new Promise(d=>{const e=a.mediaRecorder;if(e){if(e.ondataavailable)e.ondataavailable("Stopping");
e.ondataavailable=null;"inactive"!==e.state&&"function"===typeof e.stop&&(e.addEventListener("stop",()=>{d(b)}),c=!0,e.stop(),delete a.mediaRecorder)}c||d(b)})};AgentVideo.prototype._getStreamConstraints=function(b){b=b.getVideoTracks();if(!b||1<=!b.length||!b[0])return null;b=b[0];const c=b.getSettings?b.getSettings():null,d=b.getConstraints?b.getConstraints():null,e=b.getCapabilities?b.getCapabilities():null;return{settings:c,constraints:d,capabilities:e,track:b}};AgentVideo.prototype._getCoderparamsDelta=
function(b,c,d){var e=c;if(b&&b.coderparams){b=b.coderparams;d=(c||0)+(d||0);e=!1;for(const f in b)if(b.hasOwnProperty(f)&&d===Number(f)){e=!0;break}e=e?d:c}return e};AgentVideo.prototype._getCoderparamSet=function(b,c){let d={};b&&b.coderparams&&(d=b.coderparams[(0<c?"+":"")+c.toString()]);return d};AgentVideo.prototype._makeInfoQueryString=function(b){if(b.paramset){b={videowidth:Number(b.options.width/(b.paramset.downsample||1)).toFixed(0),videoheight:Number(b.options.height/(b.paramset.downsample||
1).toFixed(0)),downsample:Number(b.paramset.downsample||1).toFixed(1),framerate:Number(b.paramset.framerate||b.options.framerate).toFixed(2),bitrate:Number(b.paramset.bitrate||b.options.bitspersecond).toFixed(0),paramset:Number(b.paramIndex),pframes:Number(b.paramset.pframes||100)};const c=[];for(let d in b)b.hasOwnProperty(d)&&c.push(`${d}=${b[d]}`);return c.join("&")}return""};AgentVideo.prototype._makeOfferQueryString=function(b){const c=[];c.push("videowidth="+b.width);c.push("videoheight="+b.height);
c.push("bandwidth="+b.bitspersecond);c.push("framerate="+b.framerate);c.push("passcode="+encodeURIComponent(b.sessionkey));c.push("modelID="+encodeURIComponent(b.modelID+"/"+a.mime));c.push("localizedName="+encodeURIComponent(b.deviceName||b.device||"webcam"));c.push("MIME="+encodeURIComponent(a.mime));b.hasOwnProperty("videoBackEnabled")&&b.videoBackEnabled&&c.push("videoBackEnabled="+b.videoBackEnabled);b.maincallid?c.push("maincallid="+b.maincallid):b.maincid&&c.push("maincallid="+b.maincid);c.push("uniqueID="+
encodeURIComponent(navigator.userAgent));for(let d=0;d<v.length;d++){const e=v[d];b.hasOwnProperty(e)&&b[e]&&c.push(e+"="+encodeURIComponent(b[e]))}return c};AgentVideo.prototype._requestOffer=function(b,c,d="PUT",e="offer"){return new Promise((f,g)=>{const h={method:d,cache:"no-cache",credentials:"include",cors:"cors",body:c.join("&"),headers:new Headers({Accept:"application/json","Content-type":"application/x-www-form-urlencoded"})};fetch(b+e,h).then(l=>{l.ok&&l.json||g(l);return l.json()}).then(l=>
{a.currentOfferDescriptor=l;f(l)}).catch(l=>{console.error(b,l);g({ok:!1,status:408,statusText:"no response from server: "+l})})})};AgentVideo.prototype._openWebSocket=function(b){return new Promise(function(c,d){a.isClosing=!1;const e=b.offerer,f=b.streamid,g={};g.descriptor=b;g.streamId=f;g.request=e;g.role="offer";g.octetcount=0;g.packetcount=0;g.username=b.username||"";a.paramIndex=0;a.relay=g;(a.descriptor=b)&&b.coderparams&&b.coderparams[0]&&(a.paramset=b.coderparams[0]);try{t(e).then(c())}catch(h){console.error("websocket exception",
h),ws&&ws.shutdownNow(h,"exception"),d(h)}})};AgentVideo.prototype._reconnectWebSocket=async function(){if(a.awaitingReconnect)GLANCE.VideoDebug&&console.log("reconnectWebSocket - already waiting");else{var b=r(0);setTimeout(a._retryWebSocketConnect,b);GLANCE.VideoDebug&&console.log("Websocket reconnect attempt",0," in ",b," ms")}};AgentVideo.prototype._retryWebSocketConnect=async function c(){"undefined"===typeof a.reconnectRetries?a.reconnectRetries=1:a.reconnectRetries++;try{a.awaitingReconnect=
!0,GLANCE.VideoDebug&&console.log("Awaiting makeAWebSocket"),await t(a.relay.request),delete a.reconnectRetries,delete a.awaitingReconnect,console.log("Reconnect successful - going to _restartVideoStream"),a._restartVideoStream()}catch(e){if(6>a.reconnectRetries){var d=r(a.reconnectRetries);setTimeout(c,d);GLANCE.VideoDebug&&console.log("got error from makeAWebSocket: reconnect attempt",a.reconnectRetries," in ",d," ms")}else throw delete a.reconnectRetries,delete a.awaitingReconnect,a.giveUpReconnect=
!0,console.log("Too many retries in Reconnect"),e;}};AgentVideo.prototype._reportHistory=function(c){for(var d=Date.now(),e=c._history,f=e.peek();f&&"number"===typeof f.timestamp&&f.timestamp<=d-GLANCE.historyLookback;)e.dequeue(),f=e.peek();if(f&&"number"===typeof f.timestamp){const h=f.timestamp;let l=f.timestamp;d=-1;f=-f.size;for(var g of e)f+=g.size,d+=1,l=g.timestamp;e=l-h;if(0<e&&0<d)return g=c.paramset&&c.paramset.bitrate?c.paramset.bitrate/1E6:0,c=c.paramset&&c.paramset.framerate?c.paramset.framerate:
0,d=d/e*1E3,`actual: ${(f/e*8/1E3).toFixed(2)}mbps ${d.toFixed(1)}fps`+` requested: ${g.toFixed(2)}mbps  ${c.toFixed(1)}fps`}};AgentVideo.prototype._dispatchCommand=async function(c){GLANCE.VideoDebug&&console.debug("processing",c);var d=c.split(/\s+/);if(1>d.length)throw Error("no command: "+c);var e=d.shift(),f=d.join(" "),g=1<=d.length?d.shift():null,h=d.join(" ");d=Number(h);isNaN(d)&&(d=h);"string"===typeof d&&0===d.length&&(d=!1);h=a._loadParams(a);switch(e){case "Failure":case "Error":GLANCE.VideoDebug&&
console.info(c);break;case "Info":c=!1;if(g)switch(g){case "viewers":a.fireEvent("guestCountChanged",d,a.options);a.guestCount=d;c=!0;break;case "debug":GLANCE.VideoDebug=d,c=!0}c||a.fireEvent("info",f,a.options);break;case "Start":a.transmitStarted=!0;await a._restartVideoStream(h);break;case "Stop":a.transmitStarted=!1;h=await a._stopVideoStream(h);h=await a._saveParams(h);await a._restartVideoStream(h);break;case "Faster":h.indexDelta=1;h.paramSetChanging=!0;c=a._getCoderparamsDelta(a.descriptor,
a.paramIndex,h.indexDelta);c!==a.paramIndex&&await a._restartVideoStream(h);break;case "Slower":h.indexDelta=-1;h.paramSetChanging=!0;c=a._getCoderparamsDelta(a.descriptor,a.paramIndex,h.indexDelta);c!==a.paramIndex&&await a._restartVideoStream(h);break;case "Ping":a.ws.transmitter&&a.ws.transmitter("Pong "+f);break;case "Pong":try{const l=Date.now(),n=JSON.parse(f),p=(l-Number(n.time)).toFixed(0),w=this.relay.octetcount-Number(n.octetcount),x=this.relay.packetcount-Number(n.packetcount);(0<w||0<
x)&&console.log(`ping ${p}ms backlog octets:${w} packets:${x}`)}catch(l){console.error("Pong",l)}break;case "Passthrough":if(g)switch(g){case "SessionInvitation":g=c.indexOf("username="),e=c.indexOf("&sessionkey="),f=c.indexOf("&sessiontype="),-1<g&&-1<e&&-1<f?(g=c.slice(g+9,e),e=c.slice(e+12,f),c=c.slice(f+13),console.log(`SessionInvitation message received GlanceAddress: ${g} Session Key:${e} Sesion Viewer:${c}`),a.fireEvent("sessionInvitation",g,e,c)):console.log(` Malformed SessionInvitation message received: ${c}`)}break;
default:console.log("Unexpected websocket metadata received:",c)}};AgentVideo.prototype._dispatchMethod=async function(c,d,e){c=await c(d);e&&"function"===typeof e&&(c=e(c));return c};AgentVideo.prototype._handleCommand=function(c,d){GLANCE.VideoDebug&&console.log("starting","string"===typeof c.data?c.data:c.name,"string"===typeof c.data?"command":"method","queued:",d.getLength());let e;c&&c.data&&"string"===typeof c.data?e=a._dispatchCommand(c.data):c&&c.method&&"string"===typeof c.name?c.method&&
"function"===typeof c.method&&(e=a._dispatchMethod(c.method,c.params,c.callback)):(console.error(c,"unrecognized queue element"),d.complete(c));e?e.then(()=>{GLANCE.VideoDebug&&console.log("completing","string"===typeof c.data?c.data:c.name,"string"===typeof c.data?"command":"method","queued:",d.getLength());d.complete(c)}).catch(f=>{console.error(c,f);d.complete(c)}):(GLANCE.VideoDebug&&console.error("skipped","string"===typeof c.data?c.data:c.name,"string"===typeof c.data?"command":"method","queued:",
d.getLength()),d.complete(c))};a._commandQueue.setOptions({handler:a._handleCommand});a.events={};AgentVideo.prototype.addEventListener=function(c,d){a.events.hasOwnProperty(c)?a.events[c].push(d):a.events[c]=[d]};AgentVideo.prototype.removeEventListener=function(c,d){a.events.hasOwnProperty(c)&&(d=a.events[c].indexOf(d),-1!==d&&(a.events[c][d]=null,a.events[c].splice(d,1),0===a.events[c].length&&delete a.events[c]))};AgentVideo.prototype.fireEvent=function(c){if(a.events.hasOwnProperty(c)){var d=
Array.prototype.slice.call(arguments,1),e=a.events[c];for(let f=0;f<e.length;f++){const g=e[f];g&&"function"===typeof g&&"function"===typeof g.apply&&g.apply(null,d)}}};AgentVideo.prototype.sendSessionInvitation=function(c,d,e){GLANCE.Send("Passthrough SessionInvitation username="+c+"&sessionkey="+d+"&sessiontype="+e)}};
GLANCE.Queue=class{constructor(k){this._queue=[];this._offset=0;this._current=null;this._options=k||{}}setOptions(k){for(let m in k)k.hasOwnProperty(m)&&(this._options[m]=k[m])}clear(){this._queue=[];this._offset=0;this._current=null}_dispatch(){this._options&&this._options.handler&&"function"===typeof this._options.handler&&!this._current&&!this.isEmpty()&&(this._current=this.dequeue(),this._options.handler(this._current,this))}complete(k){this._options&&this._options.handler&&"function"===typeof this._options.handler&&
(this._current!==k&&console.error("returned item out of order",k),this._current=void 0,this.isEmpty()||setTimeout(()=>{this._dispatch()},0))}getLength(){return this._queue.length-this._offset}isEmpty(){return 0===this.getLength()}enqueue(k){this._queue.push(k);this._dispatch()}dequeue(){if(0!==this._queue.length){var k=this._queue[this._offset];2*++this._offset>=this._queue.length&&(this._queue=this._queue.slice(this._offset),this._offset=0);return k}}peek(){return 0<this._queue.length?this._queue[this._offset]:
void 0}peekTail(){return 0<this._queue.length?this._queue[this._queue.length-1]:void 0}[Symbol.iterator](){let k=this._offset;return{next:()=>this._queue.length<=k?{value:void 0,done:!0}:{value:this._queue[k++],done:!1}}}};
GLANCE.getBrowser=function(){const k=navigator.userAgent;let m=navigator.appName,r,t;-1!==k.indexOf("Opera")?m="Opera":-1!==k.indexOf("MSIE")?m="Microsoft Internet Explorer":-1!==k.indexOf("Trident")?m="Microsoft Internet Explorer":-1!==k.indexOf("Edge/")?m="Edge":-1!==k.indexOf("Edg/")?m="Chrome":-1!==k.indexOf("Chrome")?m="Chrome":-1!==k.indexOf("Safari")?m="Safari":-1!==k.indexOf("Firefox")?m="Firefox":(r=k.lastIndexOf(" ")+1)<(t=k.lastIndexOf("/"))&&(m=k.substring(r,t),m.toLowerCase()===m.toUpperCase()&&
(m=navigator.appName));return m};GLANCE.isBrowserCapable=function(){return navigator&&navigator.mediaDevices&&"function"===typeof navigator.mediaDevices.getUserMedia&&"function"===typeof navigator.mediaDevices.enumerateDevices?window.MediaRecorder&&"function"===typeof window.MediaRecorder&&"function"===typeof window.MediaRecorder.isTypeSupported:!1};
GLANCE.isAgentVideoCapable=async function(){if(!navigator||!navigator.mediaDevices||"function"!==typeof navigator.mediaDevices.getUserMedia)throw"browser does not support getUserMedia";if("function"!==typeof navigator.mediaDevices.enumerateDevices)throw"browser does not support enumerateDevices";let k=await navigator.mediaDevices.enumerateDevices();k=k.filter(m=>"videoinput"===m.kind);GLANCE.VideoDebug&&console.log(k);if(k)return!0;throw"No video input devices available";};}).call(window);
//# sourceMappingURL=map.js.map
