(function() {window.MediaRecorder=window.MediaRecorder&&"function"===typeof window.MediaRecorder&&"function"===typeof window.MediaRecorder.isTypeSupported&&window.MediaRecorder.isTypeSupported('video/webm; codecs="avc1.42E01E"')&&0>navigator.userAgent.indexOf("Android")?window.MediaRecorder:function(){function k(a){const b=new Event("error");b.data=Error("Wrong state for "+a);return b}function q(a){a=a.getVideoTracks();if(!a||1<=!a.length||!a[0])return null;a=a[0];const b=a.getSettings?a.getSettings():null,g=
a.getConstraints?a.getConstraints():null,c=a.getCapabilities?a.getCapabilities():null;return{settings:b,constraints:g,capabilities:c,track:a}}function l(a,b){if(b&&"string"===typeof b.mimeType){if(!l.isTypeSupported(b.mimeType))throw Error("NotSupportedError: mimeType "+b.mimeType+" unknown");this.mimeType=b.mimeType}this._pruneConsecutiveEqualFrames=b&&b.pruneConsecutiveEqualFrames;this._qualityParameter=b&&"number"===typeof b.qualityParameter?b.qualityParameter:.75;this._lookbackTime=b&&"number"===
typeof b.lookbackTime?b.lookbackTime:1E3;this.stream=a;this.state="inactive";this._em=document.createDocumentFragment();this._eventListenerCounts=[];this._canvasElementContext=this._canvasElement=this._videoElement=null;this._imageQuality={current:this._qualityParameter,max:.9,min:.3,step:.02};this._history=new r;a=b&&"number"===typeof b.videoBitsPerSecond?b.videoBitsPerSecond:0;b=b&&"number"===typeof b.bitsPerSecond?b.bitsPerSecond:0;this._targetBitsPerSecond=b>a?b:a;0>=this._targetBitsPerSecond&&
(this._targetBitsPerSecond=25E4);this._imagePending=!1;this.ondataavailable=null}console.log("polyfilling MediaRecorder");l.prototype={mimeType:"image/jpeg",_getActivePreview:function(a){return a&&a.mostRecentlyActivatedPreview?a.mostRecentlyActivatedPreview:a&&a.activePreviews&&0<a.activePreviews.size?a.activePreviews.values().next().value:this._videoElement},_completeStart:function(a){this.state="recording";this._em.dispatchEvent(new Event("start"));a&&(this._actualTimeSlice=a=a>this.millisecondsPerFrame?
a:this.millisecondsPerFrame,this._slicing=setInterval(function(b){"recording"===b.state&&b.requestData()},a,this))},start:function(a){this._slicing&&(clearInterval(this._slicing),delete this._slicing,delete this._actualTimeSlice);if("inactive"!==this.state)return this._em.dispatchEvent(k("start"));this._imagePending=!1;this.constraints=q(this.stream);const b=this.constraints.settings.width,g=this.constraints.settings.height;this.millisecondsPerFrame=1E3/this.constraints.settings.frameRate;this.previousBlobSize=
-1;this._canvasElement=document.createElement("canvas");this._canvasElementContext=this._canvasElement.getContext("2d");(this._videoElement=this._getActivePreview(this.stream))?this._completeStart(a):(this._videoElement=document.createElement("video"),this._videoElement.playsInline=!0,this._videoElement.style.width=b+"px",this._videoElement.style.height=g+"px",this._videoElement.srcObject=this.stream,this.stream.mostRecentlyActivatedPreview=this._videoElement,this._videoElement.play().then(()=>{this._completeStart(a)}))},
stop:function(){if("inactive"===this.state)return this._em.dispatchEvent(k("stop"));this.requestData();this.state="inactive";this._slicing&&(clearInterval(this._slicing),delete this._slicing,delete this._actualTimeSlice);this._imagePending=!1;return this._em.dispatchEvent(new Event("stop"))},pause:function(){if("recording"!==this.state)return this._em.dispatchEvent(k("pause"));this.state="paused";return this._em.dispatchEvent(new Event("pause"))},resume:function(){if("paused"!==this.state)return this._em.dispatchEvent(k("resume"));
this.state="recording";return this._em.dispatchEvent(new Event("resume"))},requestData:function(){if("inactive"===this.state)return this._em.dispatchEvent(k("requestData"));if(!("function"!==typeof this.ondataavailable&&0>=(this._eventListenerCounts.dataavailable||0)||this._imagePending)){this._imagePending=!0;var a=this._getActivePreview(this.stream),b=a.videoWidth,g=a.videoHeight;this._canvasElement.width=b;this._canvasElement.height=g;try{this._canvasElementContext.drawImage(a,0,0,b,g)}catch(c){throw this._imagePending=
!1,console.error("drawImage() error",c),c;}try{const c=this,m=c._history;let n=!0;this._canvasElement.toBlob(function(e){var f=Date.now();if(e&&0<e.size){for(var d=m.peek();d&&"number"===typeof d.timestamp&&d.timestamp<=f-c._lookbackTime;)m.dequeue(),d=m.peek();if(d&&"number"===typeof d.timestamp&&(d=f-d.timestamp,0<d)){let p=e.size;for(h of m)p+=h.size;var h=8E3*p/d;h>c._targetBitsPerSecond&&(n=!1)}n&&c._pruneConsecutiveEqualFrames&&e.size===c.previousBlobSize&&(c.previousBlobUrl?(h=c._canvasElement.toDataURL(c.mimeType,
c._imageQuality.min),h===c.previousBlobUrl?n=!1:(n=!0,c.previousBlobUrl=h)):c.previousBlobUrl=c._canvasElement.toDataURL(c.mimeType,c._imageQuality.min));if(n){m.enqueue({timestamp:f,size:e.size});f=new Event("dataavailable");f.data=e;c._em.dispatchEvent(f);if("function"===typeof c.ondataavailable)c.ondataavailable(f);c.previousBlobSize=e.size}}"inactive"===c.state&&c._em.dispatchEvent(new Event("stop"));c._imagePending=!1},this.mimeType,this._imageQuality.current)}catch(c){throw console.error("toBlob() error",
c),c;}}},addEventListener:function(){const a=arguments[0];"string"===typeof a&&(this._eventListenerCounts[a]="number"===typeof this._eventListenerCounts[a]?this._eventListenerCounts[a]+1:1);this._em.addEventListener.apply(this._em,arguments)},removeEventListener:function(){const a=arguments[0];"string"===typeof a&&(this._eventListenerCounts[a]="number"===typeof this._eventListenerCounts[a]?this._eventListenerCounts[a]-1:0);return this._em.removeEventListener.apply(this._em,arguments)},dispatchEvent:function(){this._em.dispatchEvent.apply(this._em,
arguments)}};l.isTypeSupported=function(a){return/image\/jpeg?/.test(a)||/image\/webp?/.test(a)};l.notSupported=!navigator.mediaDevices;class r{constructor(){this._queue=[];this._offset=0}size(){return this._queue-this._offset}getLength(){return this._queue-this._offset}isEmpty(){return 0===this._queue.length}enqueue(a){this._queue.push(a)}dequeue(){if(0!==this._queue.length){var a=this._queue[this._offset];2*++this._offset>=this._queue.length&&(this._queue=this._queue.slice(this._offset),this._offset=
0);return a}}peek(){return 0<this._queue.length?this._queue[this._offset]:void 0}[Symbol.iterator](){let a=this._offset;return{next:()=>this._queue.length<=a?{value:void 0,done:!0}:{value:this._queue[a++],done:!1}}}}return l}();}).call(window);
//# sourceMappingURL=map.js.map
