(function() {window.GLANCE||(window.GLANCE={});GLANCE.DefaultEndPage="/ViewerEnd.asp";GLANCE.RedirectDelay=250;GLANCE.ResizeDebounce=250;function getField(b){let d=document.getElementById(b);d||(d=document.getElementById("data-"+b));let k;if(d){const m=d.matches('[type="checkbox"]');k=m?d.checked:d.value||d.content;if(!0===k||k&&0<k.length)return k;(k=getURLParameter(b))&&0<k.length&&(m?d.checked=!!k:d.value=k)}return getURLParameter(b)}
function setField(b,d){(b=document.getElementById(b))&&"checkbox"===b.tagName&&b&&(b.value=d)}const parameterAliases={bandwidth:"b",framerate:"f",resolution:"r",sessionkey:"k",username:"u",password:"pw",groupid:"g",partneruserid:"puid",loginkey:"l",maincid:"c",isAnonymous:"a",telephone:"t",scaling:"q",start:"s",camera:"w",videoBackEnabled:"vb"},urlParams=new URLSearchParams,videoParamsmeta=document.getElementById("data-videoparams");
if(videoParamsmeta){const b=new URLSearchParams(videoParamsmeta.content);for(const [d,k]of b)urlParams.set(d,k)}const urlp=(new URL(document.URL)).searchParams;for(const [b,d]of urlp)urlParams.set(b,d);function getURLParameter(b){if(urlParams.has(b))return urlParams.get(b);if(b in parameterAliases){b=parameterAliases[b];"string"===typeof b&&(b=[b]);for(let d=0;d<b.length;d++){const k=b[d];if(urlParams.has(k))return urlParams.get(k)}}return null}
function numericNonce(b){let d="";for(let k=b;0<k;--k){let m=Math.floor(1E3*Math.random()).toString();m=m.substr(m.length-1);d+=m}return d.substring(0,b)}function getResolution(b=null){let d=640,k=360;var m=getURLParameter("res");m?(m=m.split("x"),2===m.length&&(b=parseInt(m[0],10),m=parseInt(m[1],10),b&&160<=b&&m&&120<=m&&(d=b,k=m))):b&&(d=b.scrollWidth,k=b.scrollHeight);return{width:d,height:k}}const fieldNames="bandwidth framerate sessionkey username password groupid partneruserid loginkey maincid maincallid isAnonymous telephone poster scaling vserver errorpage endpage videoBackEnabled".split(" ");
function getOptions(b,d=fieldNames){b||(b={});b.vserver="https://"+window.location.host+("myvideo.myglance.org"===window.location.host?":3000/":"/");b.mime='video/webm; codecs="avc1.42E01E"';b.stopPreviewsOnSessionEnd=!0;const {width:k,height:m}=getResolution();b.width=k;b.height=m;b.modelID="visitor_sodium_large";b.start=getField("start");d.forEach(B=>{const C=getField(B);C&&(b[B]=C)});b.scaling||(b.scaling="clip");d=b.isAnonymous||"false";"string"===typeof d?(d=d.toLowerCase(),d=d.startsWith("1")||
d.startsWith("y")||d.startsWith("t")?"true":"false"):d=d?"true":"false";b.isAnonymous=d;return b}function encodeURIComponentWithPlus(b){return encodeURIComponent(b).replace(/%20/gi,"+")}
document.addEventListener("DOMContentLoaded",function(){function b(a){a?(a=n.getAttribute("data-offtext")||"Turn light off",n.firstElementChild.src=GLANCE.camIcons.torchOn):(a=n.getAttribute("data-ontext")||"Turn light on",n.firstElementChild.src=GLANCE.camIcons.torchOff);n.setAttribute("title",a);n.setAttribute("alt",a)}function d(a){h.setTorch(a);b(a)}function k(){n.local.enableTimeout||(d(!h.getTorch()),n.local.enableTimeout=window.setTimeout(function(){n.local.enableTimeout=null},500))}function m(a){n&&
(n.local||(n.local={}),n.local.enableTimeout&&window.clearTimeout(n.local.enableTimeout),n.local.enableTimeout=null,a?(n.classList.remove("invisible-icon"),d(h.getTorch()),n.addEventListener("click",k)):(n.classList.add("invisible-icon"),n.removeEventListener("click",k)))}function B(a){f.local.disabled||(f.local.camIndex+=1,f.local.camIndex>=f.local.cams.length&&(f.local.camIndex=0),a=f.local.cams[f.local.camIndex].deviceId,f.local.enableTimeout&&window.clearTimeout(f.local.enableTimeout),f.local.enableTimeout=
null,f.local.disabled=!0,f.disabled=!0,n.classList.add("invisible-icon"),b(!1),h.setSource(a).then().catch(c=>{console.error(c);f.disabled=!1;f.local.disabled=!1;f.local.enableTimeout&&window.clearTimeout(f.local.enableTimeout);f.local.enableTimeout=null}))}function C(a,c){f.local.enableTimeout||(f.local.enableTimeout=window.setTimeout(function(){f.local.disabled=!1;f.disabled=!1;f.local.enableTimeout=null},500));h.alignPreview(a.label,t)}function P(a,c){return GLANCE.browserCapabilities.isSafariIOS||
GLANCE.browserCapabilities.isAndroid?c.height>c.width?{width:a.height,height:a.width}:a:a}function Q(a,c){if(0>=c.height||0>=c.width)return a;const e=c.width/c.height;if(0>=a.width)return{width:a.height*e,height:a.height};if(0>=a.height)return{width:a.width,height:a.width/e};a=Math.sqrt(a.width*a.height/(c.width*c.height))/8;return{width:8*Math.round(c.width*a),height:8*Math.round(c.height*a)}}function R(a,c){const e=S.getBoundingClientRect();var g=a.videoWidth;const u=a.videoHeight;if(a.classList.contains("scaling-clip")){let q=
e.width,l=e.height;if(0>=u||0>=e.height){0>=--H&&(window.clearInterval(w),w=null);return}window.clearInterval(w);w=null;g/=u;g>e.width/e.height?(q=l*g,g=Math.round(.5*(e.width-q)),r.style.top="0px",r.style.left=g+"px",r.style.width=e.width-g+"px",r.style.height=e.height+"px",GLANCE.VideoDebug&&console.log("resize clip sides",e.width-g,e.height,q,l)):(l=q/g,g=Math.round(.5*(e.height-l)),r.style.left="0px",r.style.top=g+"px",r.style.width=e.width+"px",r.style.height=e.height-g+"px",GLANCE.VideoDebug&&
console.log("resize clip top/bottom",e.width,e.height-g,q,l));a.style.width=q+"px";a.style.height=l+"px"}else r.style.left="0px",r.style.top="0px",r.style.width=e.width+"px",r.style.height=e.height+"px",GLANCE.VideoDebug&&console.log("resize fill",e.width,e.height);"function"===typeof c&&c(a)}function I(a){w&&window.clearInterval(w);H=10;w=window.setInterval(R,GLANCE.ResizeDebounce||250,t,a)}function y(a,c){if(!E){f.local.enableTimeout&&window.clearTimeout(f.local.enableTimeout);f.local.enableTimeout=
null;n.local.enableTimeout&&window.clearTimeout(n.local.enableTimeout);n.local.enableTimeout=null;var e=a?getField("errorpage"):getField("endpage");e&&0!==e.length||(e=GLANCE.DefaultEndPage);if(!e.startsWith("https:")&&!e.startsWith("http:")){var g="www."+window.location.hostname.split(".").splice(1).join(".");e.startsWith("/")||(e="/"+e);e=window.location.protocol+"//"+g+e}g=[];var u=getField("groupid")||0;u&&g.push("groupid="+u);a&&g.push("err="+a);c&&(0<=c.toLowerCase().indexOf("permission denied")?
(g.push("Error=CamPermissionDenied"),g.push(`ErrorTitle=${encodeURIComponentWithPlus("Camera Blocked")}`),g.push(`ErrorMessage=${encodeURIComponentWithPlus("You blocked access to your camera")}`),g.push(`ErrorDetail=${encodeURIComponentWithPlus("Please Allow "+window.location.hostname+" to Use your camera")}`)):0<=c.toLowerCase().indexOf("constraint")||0<=c.indexOf("does not support getUserMedia")?(g.push("Error=CamSoftwareIncompatible"),g.push(`ErrorTitle=${encodeURIComponentWithPlus("Cannot Access Camera")}`),
g.push(`ErrorMessage=${encodeURIComponentWithPlus("No access to the camera on this device or web browser")}`),g.push(`ErrorDetail=${encodeURIComponentWithPlus("Your device's OS or web browser version allows no access to your camera. If possible please update your software or use another device.")}`),c="Camera incompatible: "+c):(g.push("Error=CamShareError"),g.push(`ErrorTitle=${encodeURIComponentWithPlus("Camera sharing error")}`),g.push(`ErrorMessage=${encodeURIComponentWithPlus("Video session did not start")}`)),
F&&G&&(c+=` (${F}x${G})`),g.push("msg="+encodeURIComponentWithPlus(c)));a=0<e.indexOf("?")?"&":"?";0<g.length&&(e=e+a+g.join("&"));E=window.setTimeout(function(){E=null;window.location.href=e},GLANCE.RedirectDelay)}}function J(){z&&(window.clearTimeout(z),z=null);p.removeAttribute("style");p.removeAttribute("class")}function K(a){p.style.transition=`opacity ${a}s, width 0s, height 0s`;p.style.opacity=0;window.setTimeout(J,1E3*a)}function T(a,c){p.style.left=Math.min(a.x,c.x)+"px";p.style.top=Math.min(a.y,
c.y)+"px";p.style.width=Math.abs(a.x-c.x)+"px";p.style.height=Math.abs(a.y-c.y)+"px";p.classList.add("rect");return window.setTimeout(function(){K("0.4")},1E3)}function U(a){p.style.display="block";p.style.left=a.x-5+"px";p.style.top=a.y-5+"px";p.classList.add("ripple");window.setTimeout(function(){p.style.transition="width 0.5s, height 0.5s, top 0.5s, left 0.5s";p.style.left=a.x-30+"px";p.style.top=a.y-30+"px";p.classList.add("fade")},10);return window.setTimeout(function(){K("0.1")},500)}function L(a,
c,e=null){J();switch(a){case "ripple":z=U(c);break;case "rect":z=T(c,e);break;default:console.log("unrecognized gesture")}}const t=document.getElementById("preview-element"),r=document.getElementById("preview-frame"),S=document.getElementById("preview-viewport"),x=document.getElementById("poster-element");document.getElementById("logo-element");const n=document.getElementById("torch-button"),f=document.getElementById("camera-button"),V=document.getElementById("end-session");let F,G,h,w,H=0,E;var p=
document.getElementById("glance_gesture");let z;if(x&&!x.src){const a=getField("poster")||GLANCE.defaultPoster;a?(x.src=a,x.classList.remove("invisible")):x.classList.add("invisible")}(async function(){try{await GLANCE.Video.GlanceVideoSource.isAgentVideoCapable();const c=getOptions();var a=t.getBoundingClientRect();const {width:e,height:g}=P(Q(c,a),a);c.width=e;c.height=g;F=e;G=g;t.classList.add("scaling-"+(c.scaling?c.scaling:"clip"));c.sessionkey||c.isAnonymous||(c.sessionkey=numericNonce(4),setField("sessionkey",
c.sessionkey));h=new GLANCE.Video.GlanceVideoSource(c);let u=getField("camera");u="f"===u?"front":"back";const q=await h.getSourcesAsync();if(q&&0!==q.length){f.local={};f.local.cams=q;f.local.camIndex=0;f.local.disabled=!1;f.local.enableTimeout=null;if(!q||1>=q.length)f.classList.add("invisible-icon"),f.disabled=!0,f.local.disabled=!0;else{for(a=0;a<q.length;a++)if(q[a].name.startsWith(u)){f.local.camIndex=a;break}f.classList.remove("invisible-icon");f.addEventListener("click",B)}m(!1);h.addEventListener("torch",
m);h.addEventListener("guestCountChanged",function(l,v){});h.addEventListener("error",function(l){console.error(l);y(1,l)});h.addEventListener("sessionEnded",function(l){h=null;y(0)});window.addEventListener("unload",function(l){h&&"function"===typeof h.endSession&&h.endSession();h=null});document.addEventListener("unload",function(l){h&&"function"===typeof h.endSession&&h.endSession();h=null});h.addEventListener("sourceStarted",C);h.addEventListener("previewStarted",l=>{I(v=>{x&&x.classList.add("invisible");
v&&v.classList.remove("behind")});window.addEventListener("resize",I)});h.addEventListener("sessionStarted",()=>{V.addEventListener("click",function(){h&&"function"===typeof h.endSession&&h.endSession()})});h.addEventListener("initialized",l=>{h.setOptions(c);h.startSession()});h.addEventListener("passthrough",l=>{console.log("mobile.js received passthrough",l.split(" "));l=l.split(" ");var v=l[1];switch(l[0]){case "gesture":{l=JSON.parse(v);var D=l.coordsDown;v=l.coordsUp;var A=document.getElementById("preview-element");
let [M,N]=[parseInt(A.style.width.split("px")[0]),parseInt(A.style.height.split("px")[0])];D={x:(1-D.x)*M,y:D.y*N};A=null;v&&(A={x:(1-v.x)*M,y:v.y*N});let [O,W]=[D,A];switch(l.gesture){case "ripple":L("ripple",O);break;case "rect":L("rect",O,W)}}}});t.setAttribute("autoplay","");t.setAttribute("muted","");t.setAttribute("playsinline","");await h.initialize(f.local.cams[f.local.camIndex].deviceId,t)}else y(1,"Camera permission denied, or no camera available")}catch(c){c&&console.error(c),y(1,c)}})(t).then().catch(a=>
{console.error(a);y(1,"Video session did not start")})});}).call(window);
//# sourceMappingURL=map.js.map
